### ISSUE TITLE
Movistar+ color logos

### ISSUE THREAD

**Issue by Jglez3** [picons/picons-source#100]
Hello.

Movistar+ is modifying their color logos to have all same category channels with the same color (movies are red, series are blue, sports are orange and football is green).

 If anyone can modify svg files to adapt it, I'll appreciate that.

The channels I listed below changed logo color from light green to orange.

```
canalplusdeporteshd-esp
canalplusdeportes-esp
canalplusdeportes2hd-esp
canalplusdeportes2-esp
canalplusgolfhd-esp
canalplusgolf-esp
```

Take this reference: http://www.plus.es/recorte/m-NEO/guianeo/CPDEP.png

Canal+ Xtra changed from orange to red: http://www1.plus.es/recorte/m-NEO/canal/CPXTRA

```
canalplusxtrahd-esp
canalplusxtra-esp
```

I think Canal+Series changed too, but I'm not pretty sure. I think before was dark blue and now is more like light blue (http://www1.plus.es/recorte/m-NEO/canal/CPSER).

```
canalplusserieshd-esp
canalplusseries-esp
```

Thank you so much!

**Comment by charlesduco** [comment]
Done. If everything is okay, you can close this issue.

**Comment by Jglez3** [comment]
Everything is okay, thank you so much @charlesduco.
