### ISSUE TITLE
TVHeadend Server API doesn't work -- Tvh version 4.1-2236

### ISSUE THREAD

**Issue by gurabli** [picons/picons-source#101]
Hi,
I just migrated to Tvh from VDR, and I wanted to build the picons. I tried the second option, created the tvheadend.serverconf with the required data. When I run ./1-build-servicelist.sh, select 1) Service reference, I have the following output:

```
Log file located at: /tmp/tmp.tK8Wd8Ds50.servicelist.log

Which style are you going to build?
1) Service Reference
2) Service Name
#? 1
Enigma2: /home/server/piconstvh2/picons-source/build-input/enigma2 not found
TvHeadend (file-mode): /home/server/piconstvh2/picons-source/build-input/tvheadend not found
TvHeadend (server-mode): Exported to /home/server/piconstvh2/picons-source/build-output/servicelist-tvheadend-servermode-srp
VDR: /home/server/piconstvh2/picons-source/build-input/channels.conf not found
```
However, the servicelist-tvheadend-servermode-srp file gets created in build-output, but it is empty. 

I'm using Ubuntu Server 16.04, I had to install the following at the start: sudo apt-get install jq since this was missing according to the log file, now the log file is empty.

I'm using Tvheadend 4.1-2236 (unstable).

Any suggestions?

**Comment by gurabli** [comment]
Sorry, it was a user error, as usual. I am new to Tvh.

**Comment by hissingshark** [comment]
@gurabli 
Could you please share your "user error"?
I have had an identical experience, including the need to install `jq`.
TVH is running and server-mode counts through all 111 of my channels so I assume it connected successfully.
But the output file is empty.

**Comment by gurabli** [comment]
If I remember correctly, it was about setting the picons in Tvheadend. You need to have the picons listed under Configuration -> Channel/EPG, and the tab user picon should be filled with the service reference code (it is generated by tvh). Once you have this, then you can run service reference build and it should catch all the channels from tvheadend. Hope this helps.

**Comment by hissingshark** [comment]
Ah yes, the TVH end! It was 18 months ago since I last did it. Had quite forgotten.
Took me a few hours but finally got it populating the picon column.
The script could then pick up the channels.
Thanks.
