### ISSUE TITLE
enigma2-plugin-picons-snp-full.400x240-400x240.light.on.transparent_2017-09-12--13-35-09_all.ipk

### ISSUE THREAD

**Issue by crapaola** [picons/picons-source#102]
the package does not want to be installed...
it is stuck at "progress of implementation" then the box is stuck and need a hard reboot

**Comment by AbuBaniaz** [comment]
Do you have enough free flash memory? You can issue the following command to find the free space
```
df -Th
```

**Comment by crapaola** [comment]
i have enough memory (free 732mb)

**Comment by AbuBaniaz** [comment]
No issue here.  It is a large package so takes a while to install. Unless you post your output, not much that can be done.

```
root@tmnanosem2:~# df -Th
Filesystem           Type            Size      Used Available Use% Mounted on
ubi0:rootfs          ubifs         208.0M     75.1M    132.9M  36% /
devtmpfs             devtmpfs      153.5M      4.0K    153.5M   0% /dev
tmpfs                tmpfs          64.0K         0     64.0K   0% /media
tmpfs                tmpfs         153.6M     28.6M    125.1M  19% /var/volatile
root@tmnanosem2:~# opkg install /tmp/*.ipk
Installing enigma2-plugin-picons-snp-full.400x240-400x240.light.on.transparent (2017-09-13--09-53) on root.
Configuring enigma2-plugin-picons-snp-full.400x240-400x240.light.on.transparent.
root@tmnanosem2:~#
```

**Comment by mocram** [comment]
What does this have to do with picons? Please fix your box or install a proper image. The picon packages are all identical except for content and they have not changed in a long time....

**Comment by crapaola** [comment]
@Mocram ok ill ask to openpli 6 forum if it is a good image , and ask my box if it is fix or not ....
idiot

**Comment by mocram** [comment]
@AbuBaniaz I'm dying to know what he wrote?

**Comment by mocram** [comment]
@crapaola Hey mister dumdum, this is not a support forum for your stupid slow hardware.
