### ISSUE TITLE
Serviceref not starting with 1_0_1_

### ISSUE THREAD

**Issue by gurabli** [picons/picons-source#102]
I just came over this issue, after I created all the picons for my providers, that there are some channels where the serviceref is not starting with 1_0_1_ but has a different number. These channels were not mapped correctly. For example:
S0.8W
`
1_0_19_1C2A_29_46_E080000_0_0_0      |  BBC Earth HD                 |  1C2A_29_46_E080000=bbcearth`

As you can see, it is 1_0_19_
I don't know why is it, but maybe you should check this. Until then, I mapped manually these channels. Maybe if I add the following to the srp would work:
19_1C2A_29_46_E080000

**Comment by mocram** [comment]
1_0_19 is perfectly normal for a HD channel, the script found the 19 in your channellist, so it should be mapped, because it found something, if not building against a channellist, 1_0_1 is used as default.

**Comment by gurabli** [comment]
Well, the picons got built, but Tvh doesn't see them. I needed to manually edit the 1_0_19 part in Tvh to have the picons loaded. Hm, actually it might be it is a Tvh problem them?

**Comment by mocram** [comment]
Sorry, but I can't help you with the limited amount of info that you gave.

` 1_0_19_1C2A_29_46_E080000_0_0_0 | BBC Earth HD | 1C2A_29_46_E080000=bbcearth`
This indicates to me that the script found a serviceref `1_0_19_1C2A_29_46_E080000_0_0_0` and succesfully linked it to the logo `bbcearth`, the channel name is `BBC Earth HD`.

For whatever reason it doesn't show up in TVH is for me to guess...
