### ISSUE TITLE
Movistar+ Vacaciones

### ISSUE THREAD

**Issue by Jglez3** [picons/picons-source#103]
Movistar+ launched a new channel to replace Movistar+ Star Wars, it's called 'Movistar+ Vacaciones'

```
78B4_3EC_1_C00000=tv/movistarvacaciones
757B_412_1_C00000=tv/movistarvacaciones
```

@charlesduco I think you can make a good one as you always do (thanks for that!).

Picon (white background): http://www1.plus.es/recorte/m-NEO/canal/MVCIVA

**Comment by charlesduco** [comment]
This time it was very difficult to find a good logo.
Luckily, I found something on http://www.comunicacion.canalplus.es/galeria/index?search=cine+de+vacaciones to compose an acceptable png logo.

I also updated DCine Espanol logos to vector format. FYI, I found the logos here: http://www.movistar.es/Microsites/revista-tienda/nav/LaTiendaCast/

**Comment by Jglez3** [comment]
Thank you again! Also to update DCine Español.
