### ISSUE TITLE
What's wrong with ESPNU and ESPN2 logos?

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#106]
In the source they are fine, but on my Enigma2 tuner they are not okay:

![image](https://user-images.githubusercontent.com/14023349/30499888-7e3f4f22-9a5c-11e7-91ae-8d6370e908b7.png)
![image](https://user-images.githubusercontent.com/14023349/30499909-953b07c0-9a5c-11e7-88ae-e1bd9ea4dda0.png)

**Comment by mocram** [comment]
Probably rsvg messing up, so we either update the svg so it is rsvg compatible or I should switch the building to inkscape, which would be alot slower....

**Comment by Lexzie** [comment]
I guess making it rsvg compatible is the first to try? (Although I don't know (yet) what that means).
The one for ESPN U I edited in Inkspace (switched white and black).
Should I have used another editor? Or was the svg already faulty at the source? Because I did not edit the EPSN 2 logo as far as I can remember and there was no need to.
Also any tips in finding svg-logos would be great.

**Comment by mocram** [comment]
You could try exporting as an optimized svg with inkscape, keep the svg as simple as possible, probably something that's not supported with rsvg that's tripping up. Only way to be sure is test it with rsvg before submitting.

Support for Inkscape is built-in into the scripts, but it will take a long time when running with inkscape on the VPS.

**Comment by charlesduco** [comment]
No problem with rsvg-convert version 2.40.13 here.
It seems the build server at picons.eu is using another version that has a problem with these logos.
I cleaned up the logos in Inkscape and saved them as `optimized svg` with the option `work around renderer bugs` checked as I always do.

**Comment by Lexzie** [comment]
Thanks guys for your work!

**Comment by mocram** [comment]
Server is running rsvg-convert version 2.40.2

**Comment by AbuBaniaz** [comment]
I removed some of the logos I added recently because they had black blocks on logo too . Is cause the same or something wrong with the logos?
https://github.com/picons/picons-source/commit/001d39d1036c573f5ab567035137c93a75ba78f5

**Comment by charlesduco** [comment]
Maybe. Build your commits first on your local machine before submitting them to the remote repository and you will notice most problems.

**Comment by charlesduco** [comment]
espn2 and espnu look all right in last build.

**Comment by Lexzie** [comment]
Yes, it's okay now. Thanks!
