### ISSUE TITLE
Unitymedia changes SRP

### ISSUE THREAD

**Issue by pommesfrites** [picons/picons-source#107]
```
5E3A_F1_270F_FFFF0000=atvavrupa
D743_23B_270F_FFFF0000=brhd
566F_DD_270F_FFFF0000=discovery
E2F5_245_270F_FFFF0000=discoveryhd
5E3B_F1_270F_FFFF0000=godtv
E2F6_245_270F_FFFF0000=historyhd
372D_8D_270F_FFFF0000=motorvisiontv
5275_D3_270F_FFFF0000=natgeowild
CF73_23B_270F_FFFF0000=ndrhd
566E_DD_270F_FFFF0000=weltderwunder
```

missing Picon:
QVC Beauty & Style HD
```
DF0E_23B_270F_FFFF0000=--------
```

Picon Change:
```
759C_1A5_270F_FFFF0000=classica
```
must be
```
759C_1A5_270F_FFFF0000=classicahd-phibruspel
```

**Comment by AbuBaniaz** [comment]
Added links apart or the missing picon https://github.com/picons/picons-source/commit/a9c57454b9be2d6863ed42beef2eb0614b7b7ef9

We have a non-HD version of `QVC Beauty and Style` if you want that added for time being. 

```https://github.com/picons/picons-source/blob/master/build-source/logos/qvcbeautyandstyle.default.png```

Maybe logo could do with an update, but colours are slightly different.
```
http://unternehmen.qvc.de/wp-content/uploads/2015/03/QVC_Logo_Beauty_und_Style.jpg
```

**Comment by pommesfrites** [comment]
i found a picon for that, is it usable?

´´´
http://www.schau-hd.tv/attachments/186/QVCbeauty.png
´´´

**Comment by charlesduco** [comment]
No, I added the logos already. All QVC variants use the Gotham Bold font, so it was easy the make svg logos in [Inkscape](https://inkscape.org/en/).
