### ISSUE TITLE
[WIP] Italian channels updates

### ISSUE THREAD

**Issue by secuflag** [picons/picons-source#11]
Edit: Attached an archive since it's not possible to direct link some logos: [logo.tar.gz](https://github.com/picons/picons-source/files/919110/logo.tar.gz)

Please, consider to update to SNP:

```cinemamaxplus1hd``` logo: https://goo.gl/k55BNU
```cinemamaxhd``` logo: https://goo.gl/mTMmh9
```cinemaclassicshd``` logo: https://goo.gl/3evVTI
```cinemaculthd``` logo: https://goo.gl/ehXUbl
```cinemapassionhd``` logo: https://goo.gl/k9GFVI
```alice``` logo: https://goo.gl/mYPmdH
```raiscuola``` logo: https://goo.gl/iJGcE0
```raistoria``` logo: https://goo.gl/XJFwEX
```supertennis``` logo: https://goo.gl/KAmWZt
```supertennishd``` logo: https://goo.gl/KAmWZt

Please, consider to add to SNP:

```skycinemaunohd``` logo: https://goo.gl/zsmujO
```skycinemaunoplus1hd``` logo: https://goo.gl/CKcIyJ
```skycinemaunoplus24``` logo: https://goo.gl/vyaCi5
```skycinemaunoplus24hd``` logo: https://goo.gl/iOVjcF
```skycinemafamilyplus1hd``` logo: https://goo.gl/AkSA1H
```donnaesposa``` logo: https://goo.gl/OfkTmr
```rai5hd``` logo: https://goo.gl/PpCt6E
```telelombardia``` logo: https://goo.gl/mLlzbu
```discoverychannelhd``` logo: https://goo.gl/mPbDty
```crimeinvestigationd``` logo: https://goo.gl/ua77Jb
```raiscuolahd``` logo: https://goo.gl/iJGcE0
```raistoriahd``` logo: https://goo.gl/XJFwEX
```fightnetwork``` logo: https://goo.gl/OJyIJI
```pescareecacciaretv``` logo: https://goo.gl/ZDycKg
```mediasetpremiumcinemaenergyhd``` logo: https://goo.gl/0VnEAk
```mediasetpremiumcinemaenergyplus24``` logo https://goo.gl/ybI6VA

thanks!

**Comment by secuflag** [comment]
Please, consider to update to SNP:

```raiyoyo``` logo: https://goo.gl/Ekk29G
```raigulp``` logo: https://goo.gl/XWiWIy

Please, consider to add to SNP:

```raiyoyohd``` logo: https://goo.gl/79rWn5
```raigulphd``` logo: https://goo.gl/o8LU8w

thanks!

**Comment by secuflag** [comment]
Please, consider to update to SNP:

```centopercentotv``` logo: https://goo.gl/W0Lw5O

thanks!

**Comment by AbuBaniaz** [comment]
These can be added, but you need to make it easy to do. At the moment, you are expecting others to do the work as well, when you have done it already.

When you say update to SNP, what you mean to say is to add the link. For example, 

We have an existing logo called centopercentotv.default.png, 
The SNP name for channel is centoxcentotv

We have existing logo crimeandinvestigation.default.svg
SNP name for channel is cicrimeplusinv 



So you want us to add following links
```
centoxcentotv=centopercentotv
cicrimeplusinv=crimeandinvestigation
```

Can you compose all the links you want in that layout please?

**Comment by secuflag** [comment]
Please, consider to add to SNP:

```venus=venus``` logo: https://goo.gl/ijV3mb
```raiyoyohd=raiyoyohd``` logo: https://goo.gl/79rWn5
```raigulphd=raigulphd``` logo: https://goo.gl/o8LU8w
```skycinemaunohd=skycinemaunohd``` logo: https://goo.gl/zsmujO
```skycinemaunoplus1hd=skycinemaunoplus1hd``` logo: https://goo.gl/CKcIyJ
```skycinemaunoplus24=skycinemaunoplus24``` logo: https://goo.gl/vyaCi5
```skycinemaunoplus24hd=skycinemaunoplus24hd``` logo: https://goo.gl/iOVjcF
```skycinemafamilyplus1hd=skycinemafamilyplus1hd``` logo: https://goo.gl/AkSA1H
```donnaesposa=donnaesposa``` logo: https://goo.gl/OfkTmr
```rai5hd=rai5hd``` logo: https://goo.gl/PpCt6E
```telelombardia=telelombardia``` logo: https://goo.gl/mLlzbu
```discoverychannelhd=discoverychannelhd``` logo: https://goo.gl/mPbDty
```crimeinvestigationhd=crimeinvestigationhd``` logo: https://goo.gl/ua77Jb
```raiscuolahd=raiscuolahd``` logo: https://goo.gl/iJGcE0
```raistoriahd=raistoriahd``` logo: https://goo.gl/XJFwEX
```fightnetwork=fightnetwork``` logo: https://goo.gl/OJyIJI
```pescareecacciaretv=pescareecacciaretv``` logo: https://goo.gl/ZDycKg
```mediasetpremiumcinemaenergyhd=mediasetpremiumcinemaenergyhd``` logo: https://goo.gl/0VnEAk
```mediasetpremiumcinemaenergyplus24=mediasetpremiumcinemaenergyplus24``` logo https://goo.gl/ybI6VA



Please, consider to update to SNP:

```cinemamaxplus1hd=skycinemamaxplus1hd-phibruspel``` logo: https://goo.gl/k55BNU
```cinemamaxhd=skycinemamaxhd-phibruspel``` logo: https://goo.gl/mTMmh9
```cinemaclassicshd=skycinemaclassicshd-phibruspel``` logo: https://goo.gl/3evVTI
```cinemaculthd=skycinemaculthd-phibruspel``` logo: https://goo.gl/ehXUbl
```cinemapassionhd=skycinemapassionhd-phibruspel``` logo: https://goo.gl/k9GFVI
```alice=alice``` logo: https://goo.gl/mYPmdH
```raiscuola=raiscuola``` logo: https://goo.gl/iJGcE0
```raistoria=raistoria``` logo: https://goo.gl/XJFwEX
```supertennis=supertennis``` logo: https://goo.gl/KAmWZt
```supertennishd=supertennishd``` https://goo.gl/KAmWZt
```raiyoyo=raiyoyo``` logo: https://goo.gl/Ekk29G
```raigulp=raigulp``` logo: https://goo.gl/XWiWIy
```centopercentotv=centopercentotv``` logo: https://goo.gl/W0Lw5O
```raimovie=raimovie``` logo: https://goo.gl/Zpavkj
```raimoviehd=raimoviehd``` logo: https://goo.gl/JStmXu

Logo package: [logo.tar.gz](https://github.com/picons/picons-source/files/921589/logo.tar.gz)

**Comment by charlesduco** [comment]
This issue doesn't meet our [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md). Please read, understand en follow these rules conscientiously.

I'll close this issue, you created 4 messages and it's still not clear which logos and references should be added to this repository.

Open a new issue when you have learned the rules and have decided what exactly should be added to this project.
