### ISSUE TITLE
Arena Sport logos

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#110]
Can these be tidied up and added please? Edges are a bit jagged.

SNP and SRP
```
1CF_B_1_186AB7F=arenasport1-drukahehip
1D0_B_1_186AB7F=arenasport2-drukahehip
1D1_B_1_186AB7F=arenasport3-drukahehip
1D2_B_1_186AB7F=arenasport4-drukahehip
1E2_B_1_186AB7F=arenasport5-drukahehip
```

`donkey monkey got issue`

Thanks in advance
[arena sport logos(2).zip](https://github.com/picons/picons-source/files/1325647/arena.sport.logos.2.zip)

**Comment by AbuBaniaz** [comment]
website is here
`http://www.tvarenasport.com/`

**Comment by mocram** [comment]
they look fine to me
