### ISSUE TITLE
New logos

### ISSUE THREAD

**Issue by secuflag** [picons/picons-source#111]
Add to snp-index:
```
radiofreccia=radiofreccia
radioitaliatvhd=radioitaliatvhd
radioitaliavision=radioitaliavision
radionumberone=radionumberone
```
Please can someone adjust the png.
[logos.tar.gz](https://github.com/picons/picons-source/files/1328771/logos.tar.gz)

Thanks.

`donkey monkey got issued`

**Comment by mocram** [comment]
only one logo is OK

**Comment by mcfly822** [comment]
Is there anybody who will make these logos? If not, I can do it.

**Comment by AbuBaniaz** [comment]
@mcfly822, if you can make the logos, that would be great.

**Comment by mcfly822** [comment]
Here are the logos.
@AbuBaniaz @mocram @charlesduco : are they acceptable?
[logos.zip](https://github.com/picons/picons-source/files/1352186/logos.zip)

**Comment by secuflag** [comment]
Thank you @mcfly822

**Comment by AbuBaniaz** [comment]
Does the radionumberone logo meet the transparency requirements?
`
https://github.com/AbuBaniaz/picons-source/blob/f11975b700322756bb3696974b82eb0c4f5b605d/build-source/logos/radionumberone.default.png
`

**Comment by AbuBaniaz** [comment]
I added the three logos here.
https://github.com/picons/picons-source/commit/4f523040becdac7e7d82facd1a63a2f9f23f5d29

I'll wait for comments from charlesduco/Ocram before adding the radionumberone one.

**Comment by mocram** [comment]
In the first archive, only radionumberone was OK
Last archive all are good.
