### ISSUE TITLE
PNG picons

### ISSUE THREAD

**Issue by Frep90** [picons/picons-source#111]
Hi. Is it possible to have picons in png format? I have to use them in Kodi.

**Comment by TheLegoBatman** [comment]
There are at https://picons.xyz/ on the downloads section.

**Comment by Frep90** [comment]
I mean a zip archive with picons inside. I only found ipk and xz archives.

**Comment by TheLegoBatman** [comment]
Extract the xz archives with 7zip or if using linux use the command line or archive manager. You can also extract the ipk archives.

**Comment by mocram** [comment]
The above replies from @TheLegoBatman sums it all up. Take the hardlink version if using Windows.
