### ISSUE TITLE
Missing SFR Sport hd 1 - 2  - 3 - 5  and  SFR Sport HD 4k , CNEWS (canalnews old iTélé) , LFM TV , One TV , TVM3HD , Elle girl HD , CanalAlpha , LaTéléHD , Léman bleuHD , Be curiousTV

### ISSUE THREAD

**Issue by crapaola** [picons/picons-source#113]
missing those picons entries and png in the list
thanks a lot :)

Here's the wiki related infos for each channels

https://fr.wikipedia.org/wiki/SFR_Sport_1
https://fr.wikipedia.org/wiki/SFR_Sport_2
https://fr.wikipedia.org/wiki/SFR_Sport_3
https://fr.wikipedia.org/wiki/SFR_Sport_5
https://fr.wikipedia.org/wiki/SFR_Sport_4K
https://fr.wikipedia.org/wiki/I-T%C3%A9l%C3%A9#/media/File:CNews_Logo.jpg
https://fr.wikipedia.org/wiki/LFM_TV
http://www.onetv.ch/
https://fr.wikipedia.org/wiki/TVM3
https://fr.wikipedia.org/wiki/ELLE_Girl
https://fr.wikipedia.org/wiki/Canal_Alpha
https://fr.wikipedia.org/wiki/La_T%C3%A9l%C3%A9
https://fr.wikipedia.org/wiki/L%C3%A9man_Bleu
https://fr.wikipedia.org/wiki/BeCuriousTV

**Comment by charlesduco** [comment]
I added the logos. You have to provide the service references or service names yourself, cause these are different for each tv provider.

**Comment by crapaola** [comment]
yea no prob , thanks for the logos , make my day :-)

**Comment by charlesduco** [comment]
Yes, the logos are included in all packages the next morning after the update.

**Comment by crapaola** [comment]
well i can not find them in the picons folder , let me check again

**Comment by charlesduco** [comment]
Okay, you're right, the logos are indeed not in the packages because you didn't provide service references or service names for these channels.

Services names should first be added to snp-index.

More info:
https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md#samples
https://github.com/picons/picons-source#snp---service-name-picons

**Comment by crapaola** [comment]
how can i provide service ref/name ?
thats how service name are in my channel list:
sfrsporthd1
sfrsporthd2
sfrsporthd3
sfrsporthd4k
canalalphahd
canalalphajurahd
canalnewshd
lemanbleuhd
lfmtv
onetv
tvm3hd
becurioustvhd

elle girl is ok

**Comment by charlesduco** [comment]
Should be like this, as set in the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md):
snpindex:
```
sfrsporthd1=sfrsport1
sfrsporthd2=sfrsport2
sfrsporthd3=sfrsport3
sfrsporthd4k=sfrsport4k
canalalphahd=canalalphahd
canalalphajurahd=canalalphahd
canalnewshd=cnews
lemanbleuhd=lemanbleu
lfmtv=lfmtv
onetv=onetv
tvm3hd=tvm3
becurioustvhd=becurioustv
latelehd=latelehd
```
and srp-index:
```
2570_3F_1_FFFF0000=sfrsport1
2379_3E_1_FFFF0000=sfrsport2
2488_A8_1_FFFF0000=canalalphahd
2489_B1_1_FFFF0000=canalalphahd
2526_3E_1_FFFF0000=cnews
255A_A2_1_FFFF0000=lemanbleu
2552_B5_1_FFFF0000=lfmtv
2554_B5_1_FFFF0000=onetv
2556_A2_1_FFFF0000=tvm3
2452_3F_1_FFFF0000=becurioustv
248A_A8_1_FFFF0000=latelehd
```

The service reference for `sfrsport3` and `sfrsport4k` is still missing, so you should only use the snp-packages to get the picons for these channels

**Comment by crapaola** [comment]
great thanks , ill know the methods for the next "maybe" missing picons channels :)
