### ISSUE TITLE
no logo for VICELAND (153)

### ISSUE THREAD

**Issue by chenks** [picons/picons-source#114]
this channel launched a few weeks ago.
could the logo be added for this?

**Comment by charlesduco** [comment]
I added the logo and service references.

**Comment by chenks** [comment]
Thanks, will I do an update or will it appear automatically?

**Comment by charlesduco** [comment]
You have to update it manually. This update will be available tomorrow morning in a freshly generated picon package at http://picons.xyz

**Comment by chenks** [comment]
which one is yours on the picons list within downloadable plugins?
i added picons.xyz in the feeds section already.

**Comment by charlesduco** [comment]
All packages on http://picons.xyz/ are updated. Which version you choose is up to you.

**Comment by chenks** [comment]
How do I make my box take the update?

**Comment by charlesduco** [comment]
I don't know which box or software you use. Please contact the support of your box vendor or software provider for help.
