### ISSUE TITLE
best place to get sky uk logos from

### ISSUE THREAD

**Issue by leec32** [picons/picons-source#114]
hi

where would be the best place to get the correct sky uk logos from

a few have changed and i would like to get them added but don't want to upload the wrong type

thanks

**Comment by mocram** [comment]
Wherever you can find them on the WWW, you can use Google image search, search for svg or png files of the logo. Sometimes they can also be extracted in SVG format from PDF files listed on the broadcaster's website.

**Comment by leec32** [comment]
![skychb4015](https://user-images.githubusercontent.com/30335438/31316627-e1668fba-ac28-11e7-9611-8dfaa2362c91.png)


would this be to small ?

thanks

**Comment by leec32** [comment]
![sky_cinema_greats_hd](https://user-images.githubusercontent.com/30335438/31316668-f2f3b4b4-ac29-11e7-91c9-6246fb4d89e2.png)

or would this one be allowed

**Comment by charlesduco** [comment]
Bitmap logos from the web:
http://tv.sky.com/tv-guide/
Then find the image url:
http://tv.sky.com/logo/80/35/skychb2075.png
and change it to http://tv.sky.com/logo/0/0/skychb2075.png to get full resolution

Vector logos from online pdf's:
https://business.sky.com/hotels/home/
https://www.freeview.co.uk/why-freeview/channels
http://www.sky.it/business/materiali/locandine-hotel.html

Vector logos from the web:
http://www.skysports.com/watch

You need[ Inkscape](https://inkscape.org) and [GIMP](https://www.gimp.org/) to edit the logos so they meet the [contributing rules.](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md)

**Comment by leec32** [comment]
great thanks

**Comment by leec32** [comment]
![test](https://user-images.githubusercontent.com/30335438/31318420-40e0c2f0-ac4a-11e7-8b1f-ae94f1603094.png)

would that be suitable, i am not 100% sure what i am doing here, still learning lol so any input is appriciated

thanks

**Comment by leec32** [comment]
![test2](https://user-images.githubusercontent.com/30335438/31318810-c2ccc2e6-ac4f-11e7-9753-ef21a4efb21f.png)


or is this one better, just trying to get to grips with the pixel thing ha

**Comment by mocram** [comment]
Your very first image is obviously too small, I can't even read the text...
There is nothing really hard about the pixel thing, the higher the resolution the better. Unless you find a 10000px version, in that case it would be good to try converting it to an svg, otherwise the file sizes would get too big in the repository.

But as has been said numerous times, try reading the guidelines. It's not very hard, just some english words smashed togheter.
