### ISSUE TITLE
updated logo 

### ISSUE THREAD

**Issue by leec32** [picons/picons-source#115]
not sure if i have done this correct, please let me know if not so i can correct
i have quite a few to do but doing just this one at the moment to make sure everything is correct 

this is to replace the picon sky sports the open hd for the now sky sports golf hd 

thanks 

`9_F56_7D5_2_11A0000=skysptgolfhd.default`

[skysptgolfhd.default.zip](https://github.com/picons/picons-source/files/1367077/skysptgolfhd.default.zip)

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
That picture is very rough round the edges.

This is what is on the sky website.
`http://tv.sky.com/logo/0/0/skychb4026.png`

However, we have svg version of the SD logo. Prettys sure its is possible to make a HD svg logo too.

**Comment by leec32** [comment]
yes that is where i got it from, i then re sized it to what i though is correct, i am novice to this...

is it something i could of done wrong re sizing it that makes it rough round the edges, im not to sure what you mean to be honest ha?

there is a few logos that are outdated that i would like to add new ones of but want to make sure im doing things correctly before i spend time doing them all and find out they are useless haha

**Comment by leec32** [comment]
![skypopmax](https://user-images.githubusercontent.com/30335438/31319743-9243c712-ac60-11e7-80d8-dfc196adc70f.png)

that also needs adding to replace the old channel name KiX

**Comment by leec32** [comment]
sorry for the size.

**Comment by AbuBaniaz** [comment]
Don't resize them. You should aim for svg files,. Otherwise highest resolution of png files. Do not resize them!

Are you actually checking if we have the updated logos already? I added pop max here
https://github.com/picons/picons-source/commit/6d0dec464ba1b1b2851484fa297bc618d2dfa9ef#diff-371603e5cdac00059815badc5fca5dd6

**Comment by leec32** [comment]
sorry i never noticed them, sky-fi was another i was going to add

i only installed the latest ipk today and they have not updated for me

using enigma2-plugin-picons-srp-full.220x132-220x132.light.on.transparent_2017-10-07--19-01-10_all.ipk

**Comment by leec32** [comment]
my sky greats hd channel shows picon sky hits still, can you recall changing that one also

**Comment by AbuBaniaz** [comment]
The links in SRP-index need editing. I corrected one here.
https://github.com/picons/picons-source/commit/256ce387dafedc2b08a0e1dbb522595cd0dad20d

Download the repository and check if the logos exist first. No point re-inventing the wheel! List all the ones that need adding, post here and we can correct them.

You should consider using SNP version!

**Comment by leec32** [comment]
thanks will do

**Comment by leec32** [comment]
here is a few for now that are showing wrong in srp but the .png logos are there for them in the repository 

sky greats hd showing sky brits hd

sky family hd showing disney pixar hd

sky drama romance hd showing sky valentine hd

sky-fi showing sci-fi and horror 

is that ok to list like above of do you need the actual .png names ?

thanks

**Comment by AbuBaniaz** [comment]
Wrong way of doing things. The logos exist and are correct, there is no need to update them. It is the links that are an issue. You should have just posted the links to add

```
EE7_7E8_2_11A0000=skycinemagreatshd
EEA_7E0_2_11A0000=skycinemafamilyhd
EE8_7E8_2_11A0000=skycinemadramaandromancehd
10D0_7DC_2_11A0000=skycinemaskyfi
```
I have committed some changes already, please report back after checking tomorrows set.

**Comment by leec32** [comment]
ah sorry, i understand now for next time 

all seems up to date now

thank you
