### ISSUE TITLE
Updated ZDFneo logo

### ISSUE THREAD

**Issue by tunip** [picons/picons-source#122]
Updated german ZDFneo logo (https://www.zdf.de/sender/zdfneo).

**SD**
logo: https://de.wikipedia.org/wiki/ZDFneo#/media/File:ZDFneo2017_Logo.svg

**srp-index**
```
6D6E_437_1_C00000=zdfneo
6D6E_437_1_FFFF0000=zdfneo
6D6E_437_66_FFFF0000=zdfneo
```

**snp-index**
```
zdfneo=zdfneo
```

`donkey monkey got issued`

**Comment by charlesduco** [comment]
Please follow the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md):
- Put entries to srp-index or snp-index **inside fenced code blocks**.
- Logos should be **inside an archive**, correctly named. Share the link.

**Comment by mocram** [comment]
>Unicorns

Never seen one, but they exist!

It's really a bit pointless to screencap a logo to prove it exists, if it can't be found. End result is still no logo.

**Comment by tunip** [comment]
It is not the first time, that I do not find new logos, but others find them. And sometimes it is not clear if new logos have a HD variant. In this case, no HD logo for ZDFneo.

**Comment by Lexzie** [comment]
What's the policy about this?
Can the SD logo be used for both the SD and the HD channel?
Otherwise the HD channel will have the old logo.

**Comment by charlesduco** [comment]
Common sense policy: Don't use old logos.
