### ISSUE TITLE
New Discovery Science logo

### ISSUE THREAD

**Issue by secuflag** [picons/picons-source#123]
Update in snp-index:
```
discoveryscience=discoveryscience
```
[discoveryscience.default.svg.tar.gz](https://github.com/picons/picons-source/files/1380098/discoveryscience.default.svg.tar.gz)

Thanks!

`donkey monkey got issued`

**Comment by Lexzie** [comment]
Right now only Discovery Science UK, Discovery Science UK +1 and Discovery Science Türkiye are using this logo.
The channel is also renamed to Science Channel. (See www.sciencechannel.com so at least for the UK version).

Or can we expect others will follow?

If not this logo should get a different name, f.e. `sciencechannel` and `sciencechannelplus1`
For the Discovery Science UK +1 logo someone should add '+1' to the logo.

**snp-index for Discovery Science UK and Discovery Science Türkiye:**
```
discscience=sciencechannel
discsciplus1=sciencechannelplus1
scienceturkeyhd=sciencechannel
1DBE_C544_7E_460000=sciencechannel
```
**srp-index for Discovery Science UK and Discovery Science Türkiye:**
```
183E_7F3_2_11A0000=sciencechannel
CCBA_831_2_11A0000=sciencechannelplus1
5DC_1_5E_30B022=sciencechannel
1DBE_C544_7E_460000=sciencechannel
```

Unfortunately I can't receive Türksat, so I cannot supply the names and reference ID's used there.

**Comment by secuflag** [comment]
I see this new logo also on Discovery Science Italy.

**Comment by Lexzie** [comment]
I was not able to check that, fortunately that channel (on Sky Italia) has a unique name.

**snp-index**
```
discoverysci=sciencechannel
discoveryscihd=sciencechannel
```
(Deleting the discoveryscihd link would be better).

**srp-index**
```
5BB_320_FBFF_820000=sciencechannel
2B13_1900_FBFF_820000=sciencechannel
```


If someone can produce a HD logo, all links for this new logo will be:

**snp-index**
```
discscience=sciencechannel
discsciplus1=sciencechannelplus1
scienceturkeyhd=sciencechannelhd
1DBE_C544_7E_460000=sciencechannel
discoverysci=sciencechannel
discoveryscihd=sciencechannelhd
```
**srp-index**
```
183E_7F3_2_11A0000=sciencechannel
CCBA_831_2_11A0000=sciencechannelplus1
5DC_1_5E_30B022=sciencechannelhd
1DBE_C544_7E_460000=sciencechannel
5BB_320_FBFF_820000=sciencechannel
2B13_1900_FBFF_820000=sciencechannelhd
```

**Comment by charlesduco** [comment]
No idea if HD and +1 logos exist or what they look like.

**Comment by AbuBaniaz** [comment]
The channel is still called "discovery science" on UK DVB-C

Cropped screenshot of +1 logo on broadcast attached.
![scienceplus1](https://user-images.githubusercontent.com/6644489/31574509-57dd1c82-b0c9-11e7-9053-60ef99e881e2.jpg)

**Comment by Lexzie** [comment]
You're right. When watching to the Turkish HD channel they still call the channel Discovery Science:
![afbeelding](https://user-images.githubusercontent.com/14023349/31575617-40c1724c-b0eb-11e7-8b02-d02a27f2cce0.png)
Here you also see that the logo on the Turkish HD-version is the same as on SD.

The website I referred to is for the US version, there it's called just 'Science' by the way: https://www.lyngsat.com/tvchannels/us/Science.html
But providers are not always so fast with changing the name of a channel.

Anyhow, since the current logo is also/still used, we need different names.
Maybe adding 'old' to the current logo? Or adding a random 10 character string.
If we agree this is a good idea I can check the snp-index and srp-index that all but the UK, Italian and Turkish versions are changed to the 'old' logo.

Could you supply the snp- and srp-index for UK DVB-C?

**Comment by secuflag** [comment]
@charlesduco 

![sci_hd](https://user-images.githubusercontent.com/372417/31578716-6fcbfaee-b127-11e7-8821-49c424fead62.PNG)

**Comment by Jasmeet181** [comment]
The plus sign in my screenshots (same source) look a bit different to yours Abu. If you zoom in, the horizontal line is quite thick and the bottom isn't aligned with the 1.
![ds1crop](https://user-images.githubusercontent.com/14339434/31579421-b3860f58-b12d-11e7-87ff-73de4fd475b6.png)

I ended up with this [https://github.com/Jasmeet181/mediaportal-uk-logos/blob/ad467cbf62c53ee4e2ac0d0fe2e36133c6c4c1d5/TV/Source/Discovery%20Science%20Plus%201.svg](https://github.com/Jasmeet181/mediaportal-uk-logos/blob/ad467cbf62c53ee4e2ac0d0fe2e36133c6c4c1d5/TV/Source/Discovery%20Science%20Plus%201.svg)

**Comment by AbuBaniaz** [comment]
Thanks @charlesduco

**Comment by secuflag** [comment]
Thanks @charlesduco!
