### ISSUE TITLE
New logo for RAI channels

### ISSUE THREAD

**Issue by secuflag** [picons/picons-source#124]
Hi, please consider to update these logo channels please:

`rai1hd=rai1hd`
svg: https://goo.gl/1TrC1f

```
rai1=rai1
raiuno=rai1
```
png: https://goo.gl/IFPGyu

`rai2hd=rai2hd`
svg: https://goo.gl/QZ3a7k

```
rai2=rai2
raidue=rai2
```
svg: https://goo.gl/gxqppN

`rai3hd=rai3hd`
png: https://goo.gl/DEDi91

```
rai3tgrfvg=rai3
rai3=rai3
raitre=rai3
```
svg: https://goo.gl/5zgqNm

`rai4=rai4`
svg: https://goo.gl/u2KiOa

**Comment by secuflag** [comment]
Awesome, thanks.

If possible, would you be so kind to add also the HD variant of Rai Premium?

`raipremiumhd=raipremiumhd`
png: https://goo.gl/v9bewv
Can't find any better resolution :(

**Comment by charlesduco** [comment]
Rai Premium HD logo was already in this repository, it was just a missing entry in snp-index.

**Comment by secuflag** [comment]
ups, I'm sorry I didn't see it.

Thank you.

**Comment by charlesduco** [comment]
If everything is okay for the rai channels, please close this issue.
