### ISSUE TITLE
Missing logos for 9E

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#125]
[logos_to_be_added.zip](https://github.com/picons/picons-source/files/1380949/logos_to_be_added.zip)

**snp-index**
```
athavanradio=athavanradio
athavantv=athavantv
carrefouriper=carrefour
carrefourexpress=carrefourexpress
carrefourmarket=carrefourmarket
cmusic=cmusictv
cmusictv=cmusictv
cnnturk=cnnturk
ebshd=ebs
karuselint=karusel
luxetv=luxetvhd
luxetvhd=luxetvhd
marcopolotv=marcopolotv
rfirmcmo=montecarlodoualiya
ntdtv=ntdtv
phoenixinfonews=phoenixinfonewschannel
rfifrancais=rfi
rtvd=rtvd
tfm=tfm
wettercomtv=wettercomtv
```
**srp-index**
```
8B1_191_A_5A0000=athavanradio
8A3_191_A_5A0000=athavantv
65E_1_64_5A0000=carrefour
640_1_64_5A0000=carrefourexpress
668_1_64_5A0000=carrefourmarket
8A_65_53_CE40000=cmusictv
41D_1_AA_5A0000=cmusictv
44C_1FA4_9C_5A0000=cnnturk
E9_170C_9E_5A0000=ebs
393_17D4_9E_5A0000=karusel
456_1AF4_9E_5A0000=luxetvhd
407_1_AA_5A0000=luxetvhd
ABE_1BBC_9C_5A0000=marcopolotv
3AA_17D4_9E_5A0000=montecarlodoualiya
460_1AF4_9E_5A0000=ntdtv
161_19C8_9E_5A0000=phoenixinfonewschannel
3A3_17D4_9E_5A0000=rfi
1FE_2134_9C_5A0000=rtvd
DB3_16A8_9C_5A0000=tfm
640_1FA4_9C_5A0000=wettercomtv
```

`donkey monkey got issued`

**Comment by charlesduco** [comment]
Some logos doesn't meet the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md).

**Comment by Lexzie** [comment]
I appreciate that you have reviewed all the logos, can you be specific on which logos are not okay?

**Comment by mocram** [comment]
athavanradio
athavantv
cmusictv
ntdtv

That's it for the png files, if you can't see for yourself what's wrong with them...Are you looking at them from a 15" crt monitor from 1990?

**Comment by Lexzie** [comment]
Unnecessary space? (ntdtv logo) Corrected:
Furter logos don't see what's wrong. Sorry.

Also I don't see why some of you have to be so sarcastic every time.

Another thing about the demanded (very) high quality: The logos are 800 pixels or (much) more, they will be displayed as a small picture on the screen, so why do they have to be in super quality?

**Comment by AbuBaniaz** [comment]
@charlesduco Can you add the OK ones please?

**Comment by charlesduco** [comment]
> I appreciate that you have reviewed all the logos, can you be specific on which logos are not okay?
And why?

I gave you feedback [26 days ago](https://github.com/picons/picons-source/pull/108#issuecomment-330584677).
It's all about empty space, transparency and resolution.

I fixed three logos as an example:

https://user-images.githubusercontent.com/2472660/31585129-912d3780-b1bc-11e7-9484-04616c765ba3.png
https://user-images.githubusercontent.com/2472660/31585130-914e8192-b1bc-11e7-8421-119d09e18171.png
https://gist.github.com/charlesduco/8171df31723227761b1ce10e5a4abe94

I have currently no time to fix the rest.

**Comment by Lexzie** [comment]
26 days ago was a Pull Request and as you all so delicately mentioned out to me a Pull Request needs to be exactly right, you have to have tested it yourself locally.
Since I cannot do that (yet?), also don't know (yet) how to edit svg-files I re-opened the case with the best logos with an issue instead of a pull request, since that's what you told me to do in that case.
Now I also have to meet all the requirements again I believe.

If space around the logos was still to much, here are the png-files where I cut away the space which was still left around the logo: 
[logos_to_be_added.zip](https://github.com/picons/picons-source/files/1385543/logos_to_be_added.zip)

I can see a difference in the Athavan logos, looks better indeed, but I haven't figured out yet how that is done, Then again, like I said above that's why I made an issue (instead of pull request).
Many thanks for improving the logos.
I hope when you do have time, or someone else, other logos can be reviewed too?

**Comment by mocram** [comment]
The "space" was the least of the problems, one logo seemed to be missing an entire top part, all the rest had jagged edges.

And please do tell who you think is being sarcastic.

**Comment by mocram** [comment]
The missing top part was a nuisance from Win 10 photo viewer, so was my fault for not opening GIMP, you can ignore that remark.

But your corrected cmusic logo still has mistakes.
![cmusictv default](https://user-images.githubusercontent.com/16463960/31602638-fdcc49fc-b25d-11e7-8eac-fd535cc31cd1.png)

I personally can live with some empty space around logos if you are 100% certain all the pixels are transparant, so no 1 pixel whites/blacks, removing empty space fixes this 100% of the time, besides it's easy.

You should really try looking at your logos with a white/black layer to see those ugly borders.

The reason for asking >800px is because we provide picons in the format 800x450, not everybody uses the same small low resolution display as you, lots of people are running this on 4K tv's with Kodi, they prefer high quality picons not 100x60. In a few years this will even be 8K, do you want to updates everything again....when that happens.

**Comment by mocram** [comment]
@Lexzie You planning on fixing these issues? Or are zero fucks given about all the time wasted on our end trying to help you? I understand that life can get in the way, but wasting our time by asking to explain in detail what is wrong, so that you can improve your skills and not having the decency to respond in nearly 2 days is plain rude.

**Comment by Lexzie** [comment]
Life got in the way in this case, I really did not had the time to respond.
Next week will also be very busy for me.
I'm hoping to look into this later.

**Comment by Lexzie** [comment]
Sorry guys, I need some help in what I thought should be simple.
I want to resize the canvas of carrefourexpress.default.svg to fit the image but it's not working out in Inkscape. F.e. with 'Resize page to selection', the canvas size is reduced to the size of the graphics but shifted, so the graphics are partly outside the canvas. Please help anybody?
[carrefourexpress.default.svg.zip](https://github.com/picons/picons-source/files/1407081/carrefourexpress.default.svg.zip)

**Comment by mcfly822** [comment]
@Lexzie The problem was that it was an embedded SVG, with grouping.
Here you are.

[carrefourexpress.default.zip](https://github.com/picons/picons-source/files/1407116/carrefourexpress.default.zip)

**Comment by Lexzie** [comment]
Still don't understand how you fixed it but thanks for fixing this!
Could you also get rid of the 'HD' in this logo, since they are not using that and there is a HD-version with the same name as an SD-version, so one logo for both SD and HD would simplify the snp-index.
[luxetvhd.default.svg.zip](https://github.com/picons/picons-source/files/1407172/luxetvhd.default.svg.zip)

**Comment by mcfly822** [comment]
Luxe TV: I found and svg without the "HD" sign. Isn't this good?
https://upload.wikimedia.org/wikipedia/commons/2/23/Luxe-TV-Logo.svg

Phoenix: here you are. Is this what you imagined?
[phoenixinfonewschannel.default.zip](https://github.com/picons/picons-source/files/1407384/phoenixinfonewschannel.default.zip)

**Comment by Lexzie** [comment]
Yes, this is okay. Although the logo for Luxe TV is already added I see.
With the Phoenix logo learnt something again about editing.

Here are all the logos again with snp- and srp indexes, I hope they logos are okay and there are no mistakes any more:

[logos_to_be_added.zip](https://github.com/picons/picons-source/files/1407995/logos_to_be_added.zip)

**snp-index**
```
athavanradio=athavanradio
athavantv=athavantv
carrefouriper=carrefour
carrefourexpress=carrefourexpress
carrefourmarket=carrefourmarket
cmusic=cmusictv
cmusictv=cmusictv
ebshd=ebs
ebsplushd=ebsplus
karuselint=karusel
marcopolotv=marcopolotv
rfirmcmo=montecarlodoualiya
rmcdoualia=montecarlodoualiya
mcdoualia=montecarlodoualiya
ntdtv=ntdtv
phoenixinfonews=phoenixinfonewschannel
rtvd=rtvd
wettercomtv=wettercomtv
```

**srp-index**
```
8B1_191_A_5A0000=athavanradio
8A3_191_A_5A0000=athavantv
65E_1_64_5A0000=carrefour
640_1_64_5A0000=carrefourexpress
668_1_64_5A0000=carrefourmarket
8A_65_53_CE40000=cmusictv
41D_1_AA_5A0000=cmusictv
1F6_2134_9C_5A0000=cmusictv
E9_170C_9E_5A0000=ebs
1B1_170C_9E_5A0000=ebsplus
393_17D4_9E_5A0000=karusel
ABE_1BBC_9C_5A0000=marcopolotv
3AA_17D4_9E_5A0000=montecarlodoualiya
33_1FD_2BE_1040000=montecarlodoualiya
2396_44A_1_C00000=montecarlodoualiya
460_1AF4_9E_5A0000=ntdtv
161_19C8_9E_5A0000=phoenixinfonewschannel
1FE_2134_9C_5A0000=rtvd
640_1FA4_9C_5A0000=wettercomtv
```

`donkey monkey got issued`

**Comment by mocram** [comment]
Use this logo for cmusic
[cmusictv.default.png.zip](https://github.com/picons/picons-source/files/1411337/cmusictv.default.png.zip)

**Comment by Lexzie** [comment]
Can someone please look at the last comment and commit it when all is okay?

**Comment by mocram** [comment]
Still had to fix a few things, like an abundance of white space around ntd logo, incorrect naming of logos, there is no need to add `tv` to logo names if it is not in the logo

**Comment by Lexzie** [comment]
Thought I already fixed the ntd logo, I guess I lastly uploaded the wrong one, sorry.
About the naming, I know that now, this was created before.

I see you have replaced the `marcopolo` logo, that was not the intention. 
My bad, should have named it correctly. The exisiting logo is for the Italian Marco Polo, this one is for the German one (at 9°E and should also be on German cable).
Could you revert that change and name the new one `marcopolo-wispelutri`?
Here are both logos as I intended:
[marcopolos-20171101.zip](https://github.com/picons/picons-source/files/1434556/marcopolos-20171101.zip)

And please change **snp-links** to:
```
marcopolotv=marcopolo-wispelutri

```
Also please add:
```
2FB7_2DB4_13E_820000=marcopolo
```
(Marco Polo on 13°E is named incorrectly `sporttelevision` and therefore linked to the wrong logo).
Thanks for your effort.

**Comment by mocram** [comment]
Why would you wanna add -wispelutri ?

It seems somebody also messed that up in the past....

**Comment by AbuBaniaz** [comment]
A change means something is already one thing, it will become become something else.

If you insist on asking for changes, can you please please say something along the lines

>change from `blah blah blah` to`blah blah blah` 

This is more tedious than deleting then adding because you have to find the entry, delete the unwanted part, copy the wanted part, then paste it again.  But hey ho.

**Comment by Lexzie** [comment]
> Why would you wanna add -wispelutri ?

Thought it was used for more German channels. But off course `-lespestovi` is perfectly okay.

**One last thing:**
Could you add to snp-index:
```
2FB7_2DB4_13E_820000=marcopolo
```

My thanks will be mighty.

**Comment by mocram** [comment]
It should be a new random string every time, unless you want to group related channels tighetter like for example sky uk and/or sky de channels.

**Comment by AbuBaniaz** [comment]
I'll add that link in next commit I do

**Comment by mocram** [comment]
Its already in or else im blind
