### ISSUE TITLE
pop max and chartshow hits

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#126]
pop max on 28.2

Logo: https://www.skymedia.co.uk/wp-content/uploads/2016/06/pop-max-logo.png
SRP: D061_83E_2_11A0000
SNP: popmax

Chartshow hits
Logo: https://www.skymedia.co.uk/wp-content/uploads/2016/01/Chart-Show-Hits-.png
SRP: D043_83E_2_11A0000
SNP: chartshowhits

Sorry, graphics is not my forte

**Comment by charlesduco** [comment]
For your information:You can find channel logos for uk in the pdf at https://www.freeview.co.uk/why-freeview/channels
And also at http://tv.sky.com/tv-guide/ which points to images like http://tv.sky.com/logo/80/35/skychb2002.png
You get full resolution by changing the url to http://tv.sky.com/logo/0/0/skychb2002.png

**Comment by AbuBaniaz** [comment]
Thanks. The 4 digits are just the EPG IDs.

Can I trouble you to add the following logos please? I'll submit a pull request for the index later. Many thanks. 

http://tv.sky.com/logo/0/0/skychb4215.png
http://tv.sky.com/logo/0/0/skychb4261.png
http://tv.sky.com/logo/0/0/skychb3612.png
http://tv.sky.com/logo/0/0/skychb1324.png
http://tv.sky.com/logo/0/0/skychb3643.png
http://tv.sky.com/logo/0/0/skychb3751.png
http://tv.sky.com/logo/0/0/skychb3351.png
http://tv.sky.com/logo/0/0/skychb3206.png

**Comment by AbuBaniaz** [comment]
Many thanks
