### ISSUE TITLE
Please add BR Heimat (radio station) SVG logo

### ISSUE THREAD

**Issue by connaisseur** [picons/picons-source#13]
New regional public radio station of Bayerischer Rundfunk, Germany. Was launched on 2015-02-02.

SVG Logo source can be found on de.wikipedia.org: http://de.wikipedia.org/wiki/BR_Heimat#/media/File:BR_Heimat_Logo.svg

Transmitted via Astra satellite system and local German Cable providers.

**Comment by picons** [comment]
```
When submitting an issue, make sure you follow these rules:

Entries to srindex, put them inside code blocks by using backticks (help) or if they are really big, use a gist.
Logos should be inside an archive, correctly named (see below). Share the link.
```

I can overlook the second part, but at least provide the serviceref.

**Comment by charlesduco** [comment]
added this already in my next pull request
