### ISSUE TITLE
Romance TV

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#132]
There are two versions of this channel, Romance TV Deutschland and Romance TV Polska.
Both use the same logo, romancetv-wispelutri (or romancetvhd-wispelutri).

![afbeelding](https://user-images.githubusercontent.com/14023349/31583974-40458a3c-b1a5-11e7-9e64-008205de3b00.png)
_Romance TV Deutschland_

![afbeelding](https://user-images.githubusercontent.com/14023349/31583982-6cf9f87e-b1a5-11e7-80d2-33bb635ba1e3.png)
_Romance TV Polska_

Afaik romancetv.default.svg and romancetvhd.default.svg are not used.

So imho should romancetv.default.svg and romancetvhd.default.svg be deleted and replaced with romancetv-wispelutri?

This will result in these snp- and srp-index:

**snp-index**
```
romancetv=romancetv
3ABE_514_13E_820000=romancetvhd
3ADC_514_13E_820000=romancetvhd
romancetvhd=romancetvhd
```

(delete 26_F_85_C00000=romancetv-wispelutri)

**srp-index**
```
26_F_85_C00000=romancetv
372B_8D_270F_FFFF0000=romancetv
4EEA_21FC_9C_5A0000=romancetv
3ABE_514_13E_820000=romancetvhd
3ADC_514_13E_820000=romancetvhd
```
`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
Link name does not have to use logo nane

**Comment by Lexzie** [comment]
I know, but read what I wrote. One of the logos isn't used, at least not by the mentioned stations.
Three of them have now the wrong picon.
Either way, if the name of the logo is changed or not, the snp- and srp-index is not correct.
Above are the links if the logo is renamed.
Below the links when the logo names stay unchanged:

**snp-index**
```
romancetv=romancetv-wispelutri
3ABE_514_13E_820000=romancetvhd-wispelutri
3ADC_514_13E_820000=romancetvhd-wispelutri
romancetvhd=romancetvhd-wispelutri
```
(26_F_85_C00000=romancetv-wispelutri still can be deleted)

**srp-index**
```
26_F_85_C00000=romancetv-wispelutri
372B_8D_270F_FFFF0000=romancetv-wispelutri
4EEA_21FC_9C_5A0000=romancetv-wispelutri
3ABE_514_13E_820000=romancetvhd-wispelutri
3ADC_514_13E_820000=romancetvhd-wispelutri
```

**Comment by mocram** [comment]
When it is clearly established that the logo `romancetv.default.svg` is not being used anymore and will not be used anymore worldwide, then we can start thinking about removing it. Otherwise link to -wispelutri

**Comment by AbuBaniaz** [comment]
The romancetv logo was being used by a reference. I have changed it to the one you have said.

**Comment by AbuBaniaz** [comment]
https://github.com/picons/picons-source/commit/94f697dbfd173712485df737c50e8f6813c3075a

**Comment by Lexzie** [comment]
Thanks!
