### ISSUE TITLE
New logo Discovery Historia

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#133]
I could only find this png-file, hope you can use it and also modify it to the "light"-version.

Source: http://mediafm.net/media/images/original/md5/2/6/266640cf4e60ec5724cc06c936a265cb/Discovery%20Historia%20Logo.png
[discoveryhistoria.default.png.zip](https://github.com/picons/picons-source/files/1385533/discoveryhistoria.default.png.zip)

**snp-index**
```
discoveryhistoria=discoveryhistoria
historiapoland=discoveryhistoria
```

**srp-index:**
```
DB2_2D50_13E_820000=discoveryhistoria
514_2_5E_E08B00F=discoveryhistoria
```

`donkey monkey got issued`

**Comment by mocram** [comment]
Are you certain that the current logo is updated by this new version for all tv stations?

**Comment by Lexzie** [comment]
Thanks!
