### ISSUE TITLE
column 2.28.2 has issues with multi-byte characters

### ISSUE THREAD

**Issue by andrsd** [picons/picons-source#136]
I was running the `1-build-servicelist.sh` script on raspberry pi 2 (arch linux), which has `column 2.28.2` installed and it was not able to deal with the multi-byte characters on line 203. When I replaced it with something like `$#`, all worked fine.

**Comment by mocram** [comment]
Is this still an issue or a one time occurence? Because, I haven't got a lot to work with here "multi-byte characters on line 203", which line 203 or what's on it? Is the line 203 the line number of the code or from the text file? What did you replace with `$#`?

**Comment by andrsd** [comment]
I think there is a multi-byte character on [1-build-servicelist.sh:203](https://github.com/picons/picons-source/blob/master/1-build-servicelist.sh#L203), it should be the paragraph glyph. I replaced `$'§'` with`$#`, but you may want to pick something else for the fix.

My version of column (2.28.2) was not able to deal with it. Maybe it is the way how arch linux for raspberry pi builds it.

> Does it also occur with an older version of column?

I did not try...

**Comment by mocram** [comment]
I understand now, I already used a lot of others, but it keeps coming back to bite me in the butt one way or another...

**Comment by mocram** [comment]
Could you check if the fix worked and produces proper output as in https://raw.githubusercontent.com/picons/picons-samples/master/servicelist-enigma2-snp

**Comment by charlesduco** [comment]
Output on Linux Mint 18 is really bad:
[servicelist-enigma2-snp](https://gist.githubusercontent.com/charlesduco/7108e8dc97349c9af6aaecf2adb45500/raw/c59269c3fc280cd477f3c503d24bc708a9cca8d0/servicelist-enigma2-snp)
[servicelist-enigma2-srp](https://gist.githubusercontent.com/charlesduco/a4cf3ff6353b05c53f3c17ff428026ce/raw/3e4a566284ad48424da9bc6fcc683666c25b733b/servicelist-enigma2-srp)

**Comment by mocram** [comment]
Can you try again...

**Comment by charlesduco** [comment]
Output seems okay now:
[servicelist-enigma2-srp](https://gist.githubusercontent.com/charlesduco/a82659fef06ca31206ba0750bc39ee65/raw/e8d99a9ac3df721c5ad62350c88c75b72c34f01d/servicelist-enigma2-srp)
[servicelist-enigma2-snp](https://gist.githubusercontent.com/charlesduco/3e1959523ee77217c638476ef38ab55b/raw/fa4c249498500cd8d85a677ee3565b04ffed055e/servicelist-enigma2-snp)

**Comment by mocram** [comment]
So the multi-byte error isn't happening anymore and we can close this issue?

**Comment by charlesduco** [comment]
Yes, I tested this also with Arch Linux in Virtualbox, output is fine.
