### ISSUE TITLE
updated logos 

### ISSUE THREAD

**Issue by leec32** [picons/picons-source#136]
another attempt, hope all is correct 

updated stream ref  `9_F4D_7F7_2_11A0000=skysportsnewshd`

logo change `10D0_7DC_2_11A0000=skycinemascifiandhorrorhd`

logo change `1133_7DC_2_11A0000=skycinemaanimation`
[skycinemaanimation.zip](https://github.com/picons/picons-source/files/1386986/skycinemaanimation.zip)

`donkey monkey got issued`

**Comment by mocram** [comment]
Sigh, sadly not.

**Comment by leec32** [comment]
bah what have i done wrong this time

**Comment by mocram** [comment]
- Put entries to srp-index or snp-index inside fenced code blocks
- Logos should be inside an archive, correctly named (see below). Share the link.
- A default version of a logo should get the identifier .default at the end of the filename, additional types are possible, by using for example .light, .dark, .black or .white as an identifier.

There's no way to now (besides guessing) if you want it added to snp or srp...
The logo is incorrectly named, depending on how the logo looks, I'm guessing it's a `light` version.
The logo contains transparent areas where there shouldn't be any... I think

**Comment by AbuBaniaz** [comment]
What is difference between ' updated stream ref' and 'logo change'?

Do you just want those links added?

**Comment by leec32** [comment]
Hi

Sky sports news Hd the stream ref has changed 

The logo for skyFi has changed back to skycinemascifiandhorrorhd

And 1133_7DC_2_11A0000=skycinemaanimation

Has changed from sky family (logo only)

Thanks

**Comment by AbuBaniaz** [comment]
The project is basically the following:

Logos:
Adding new logos
Updating/improving logos
Sometimes delete dead logos

Links:
SRP: Linking service reference to logos
SNP: Linking SNPname/service reference to logos 
Sometimes delete dead links

With regards to the links, all you had to say was 

Please add the following SRP links.
```
F4D_7F7_2_11A0000=skysportsnewshd
F2A_7F7_2_11A0000=skysportsnewshd
10D0_7DC_2_11A0000=skycinemascifiandhorror
EE9_7E8_2_11A0000=skycinemascifiandhorrorhd
```
The mentioning of 'logo change' is superfluous and confusing.  What needs changing in the logo? Nothing at all ! It is just a link change that is needed.

I couldn't find the reference you mentioned for skyportsnewshd.  I will add the links. The new logo can be added by the graphics experts.

`
http://tv.sky.com/logo/0/0/skychb1808.png
`

**Comment by AbuBaniaz** [comment]
Jasmeet added the logos here. IIRC, there was an issue about border style being different.

https://github.com/Jasmeet181/mediaportal-uk-logos/commit/802c55e2ae0a6c24e9685a3d3d20e141ad7009f7

**Comment by leec32** [comment]
hi

thanks for that, and i apologize i had left the extra digit on the ref for the sky sports news.

can you give me an example how to add a logo in future that has changed and you do not already have, i only know how to get png at the moment.

for example 

`EEA_7E0_2_11A0000=skyanimationhd`
`http://tv.sky.com/logo/00/00/skychb4018.png`

would the above be ok ?

thanks

**Comment by AbuBaniaz** [comment]
Already mentioned above. Attach the logo in zip format

**Comment by leec32** [comment]
will these changes go into tonight's build as i don't see them in 16/10

**Comment by mocram** [comment]
The logo you submitted in the zip is most certainly not going in tonight.

**Comment by leec32** [comment]
@mocram 

Jasmeet added the logos here. IIRC, there was an issue about border style being different.

Jasmeet181/mediaportal-uk-logos@802c55e

**Comment by AbuBaniaz** [comment]
There is scope for a lot of the skycinema png files to be replaced by svg files. We have some svg versions already. Only the the text is different. I dont know how to do it.

**Comment by charlesduco** [comment]
> I dont know how to do it.

[Learn Inkscape](https://www.youtube.com/results?search_query=inkscape), take existing vector text elements from the other logos or pdf sources on the web and combine them in a new logo. Use the png logo from the sky tv guide website as a background template.

Currently no time to do this, every single logo has four versions. So, this is a lot of work.

**Comment by leec32** [comment]
@charlesduco 

could you please check the srp for skysportsgolfhd, i noticed it was added around 5 days ago back but it is not working on the 17/10 build 

thanks

**Comment by charlesduco** [comment]
@leec32 Please provide a correct srp entry for skysportsgolfhd cause I currently have no access to the Astra 2E satellite.

**Comment by leec32** [comment]
https://github.com/charlesduco/picons-source/commit/f11309c9ff3167ad130158326c1f69cd5351107b

you did add it looking at this but i think it was when the build server didnt update for a few days so maybe something went wrong.

i will re check shortly because i have  just noticed some more stream references have changed on 2E in the past day

i will update them altogether

**Comment by leec32** [comment]
@charlesduco 

srp index 

`EDA_7F7_2_11A0000=skysportsmaineventhd`
`F57_7F7_2_11A0000=skysportspremierleaguehd`
`F63_7F7_2_11A0000=skysportsfootballhd`

skysportsgolfhd has been added to the srp index 5 days ago with the correct reference but the picon is not working on the 17/10 build but here it is again  

`F56_7F7_2_11A0000=skysportsgolfhd`

thanks
