### ISSUE TITLE
2-build-picons.sh checks for column command but never uses it

### ISSUE THREAD

**Issue by melo0187** [picons/picons-source#138]
Line 27 of the 2-build-picons.sh script has a list of required commands. If one or more of the commands is missing, the scripts exits. This is perfectly reasonable.
However the list of required commands contains column, which is never actually used  in the script.

**Comment by mocram** [comment]
Probably an oversight from copy/pasting from 1-build-....

**Comment by mocram** [comment]
Thanks for the sharp eye, should be fixed with (https://github.com/picons/picons-source/commit/c05cccc39f262079da78d45b096bc49122c3e43b)
