### ISSUE TITLE
SVG Logo Updates

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons-source#139]
Logos Include

1. (New) nick - default, light & white
2. (New) zdfneo - light & light
3. (New) ntv - light & white
4. Bibel TV HD - white

https://homeserver.smooth-ones.de/index.php/s/FRe0KC88wc3RSIj
Pw: Logo2017

**Comment by AbuBaniaz** [comment]
If Nickolodeon has just changed the logo they use, it is better to just replace the logo with the existing name. That way no further changes will be required for SRP links.

**Comment by SmoothMC** [comment]
but they also change the name from Nickolodeon to just nick

**Comment by AbuBaniaz** [comment]
OK to close?

**Comment by Lexzie** [comment]
Again, not all Nickelodeon channels have changed name and logo...

**Comment by AbuBaniaz** [comment]
We have both logos. Use the logo to make the picon you want.

Link + logo = picon
