### ISSUE TITLE
Update References Vodafone Deutschland DVB-C

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons-source#140]
SRP

D169_2717_F001_FFFF0000=comedycentral_viva
6E2D_431_1_FFFF0000=rbb
CF0E_2717_F001_FFFF0000=nick
6F46_41B_1_FFFF0000=srfernsehen

SNP

aljazeerainteng=aljazeera
bbcworldnewseng=bbcworldnews
brfernsehensüdhd=brhd
brfernsehenhd=brhd
brfernsehensüd=br
cnneng=cnn
comedycentralviva=comedycentral_viva
parlamentsfernsehen=parlamentsfernsehen
tv5mondefre=tv5mondeeurope
wdrhdköln=wdrhd
wdrköln=wdr
weltderwundertv=weltderwunder
sonlifeeng=sonlifetv
rtlplus=rtlplus-mathecraki
rtlii=rtl2
nick=nick

**Comment by AbuBaniaz** [comment]
Is this no longer a valid link?
```
CF0E_2717_F001_FFFF0000=nickelodeon_comedycentral
```

**Comment by SmoothMC** [comment]
correct this nick only

**Comment by AbuBaniaz** [comment]
I thought it was a shared channel. Is that not correct?

**Comment by SmoothMC** [comment]
on Vodafone 
comedycentral & viva is shared
nick is standalone ;)

**Comment by AbuBaniaz** [comment]
OK to close?

**Comment by AbuBaniaz** [comment]
Please close issues yourself when the commits have been made and issue is resolved.
