### ISSUE TITLE
New logos via existing logos

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#141]
- Can someone adjust the logo from Rebel (rebel.default.svg and rebel.light.svg) to the one for Rebel 2 by adding a '2'?
![afbeelding](https://user-images.githubusercontent.com/14023349/31915697-b5b2dc88-b84f-11e7-8e30-8116a8a8de42.png)
 
- In the logo for Fox Sports 5 (foxsportseredivisie5.default.svg) the F and O are missing.

- Can someone find the svg for AFN Family and combine it with the existing AFN Pulse logo to one logo (the two are time sharing one channel).

All indexes are:
**snp-index**
```
rebel2=rebel2
foxsports5=foxsportseredivisie5
afnfamilypulse=afnfamily_afnpulse
```

**srp-index**
```
316_C94_3_EB0000=rebel2
1AA_C40E_9E_5A0000=foxsportseredivisie5
9_1_9_5A0000=afnfamily_afnpulse
```
`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
>In the logo for Fox Sports 5 (foxsportseredivisie5.default.svg) the F and O are missing.

What are you viewing the logo with? I can see them. I hope we are talking about the logo and not the picon.

**Comment by Lexzie** [comment]
I'm viewing the logo with Inkscape, but more importantly the picon has the same fault otherwise I would not have noticed it and it would be okay.

**Comment by AbuBaniaz** [comment]
It is important to refer to the correct item. Logo and picon are two different things although one is made from the other. Strange that they show up in Internet Explorer. Nonetheless, needs fixing.

Which picon pack are you using?

**Comment by Lexzie** [comment]
Logo and picon are both wrong.
I use snp light on transparent.

**Comment by AbuBaniaz** [comment]
some logos here
```
https://www.breedbandwinkel.nl/zenders
```

**Comment by AbuBaniaz** [comment]
I have tweaked the HD ones. Can someone tweak the blue background in this SD ones. I tried to make it smaller, but lost the roundness.

[135sd.zip](https://github.com/picons/picons-source/files/1409342/135sd.zip)

**Comment by mocram** [comment]
[135sd.zip](https://github.com/picons/picons-source/files/1419642/135sd.zip)

**Comment by Lexzie** [comment]
Here are the logos captured from screen:
![afbeelding](https://user-images.githubusercontent.com/14023349/32071925-316cfc26-ba91-11e7-84c8-5bd2428020f8.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/32071976-5cfb2c28-ba91-11e7-9274-758af3d17a80.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/32072013-7eb7b34a-ba91-11e7-8f20-6cdcd39cfb20.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/32072034-8eb74008-ba91-11e7-8de1-5c8578c46c5d.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/32072104-b8305d52-ba91-11e7-90d6-5636bc67fba7.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/32072145-e0150516-ba91-11e7-859b-b69970aea283.png)

These are all captured on the HD-version of the channels.
By the way, the addition 'Eredivisie' (or 'International' for 2/4/6) and 'HD' are not used in the logo on screen anymore. Still the channels 1/3/5 are part of the Eredivisie-package and 2/4/6 are still part of the International=package.

**Comment by mocram** [comment]
So just 123456, without any text or HD markings for both the SD and the HD variants?

**Comment by Lexzie** [comment]
It should be enough I guess.

**Comment by Lexzie** [comment]
About the Rebel 2 logo, this should be Rebel 2 Slusnej Kanal.
I found this one on their Facebook page but I'm not sure if it's of good quality enough and I can't get Colour (white) to Alpha in GIMP to make background transparent. Maybe someone else is able to.
![rebel2slusnejkanal raw](https://user-images.githubusercontent.com/14023349/32145621-0f3ed0f6-bccc-11e7-8d86-503a15aeeb0e.png)

**Comment by mcfly822** [comment]
I can do it tonight.

**Comment by mocram** [comment]
Use the following svg's instead.
[svg.zip](https://github.com/picons/picons-source/files/1431822/svg.zip)

PS: ideally the letters should be white...

**Comment by Lexzie** [comment]
You mean import in Inkscape, like this:

![afbeelding](https://user-images.githubusercontent.com/14023349/32251967-999d18e8-be93-11e7-915a-9d14c0d4128b.png)

Then save as optimized svg?

By the way when saving as optimized svg, do I set more options or what is default selected?

![afbeelding](https://user-images.githubusercontent.com/14023349/32252465-d141efce-be95-11e7-86d8-ff6cc35e25ac.png)
 

The only thing I can't figure out how to cut down the canvas to image size... (in Inkscape).

I tried to make the letters white in rebel2slusnejkanal.default.svg, I hope I did it right.

[Rebel2slusnejkanal_20171031.zip](https://github.com/picons/picons-source/files/1432557/Rebel2slusnejkanal_20171031.zip)

**Comment by mocram** [comment]
No the above is only a first, but certainly not a last step. On it's own it is definately not allowed.

**Comment by mocram** [comment]
Never embed raster images.

**Comment by Lexzie** [comment]
Okay. well then I still have to learn what is meant with 'If it's possible to easily trace your png with Inkscape, only the svg is allowed. In most cases this is possible.'
The svg's in the zip-file I provided were created by you, I only added white to the letters. So it was not that I imported the png, I only asked if that was what you mean by 'easily trace your png with Inkscape'.
Also like to know when you have to save the svg as an optimized svg (and when not) and with which options..

But thanks for committing all logos.

**Comment by mocram** [comment]
Inkscape: Paths > Trace bitmap (Is I believe the function to convert a raster to a vector, the raster has to be manually deleted afterwards.)

I missed the zip, will look at it now.

Will give recommended settings for optimized svg.....

**Comment by mocram** [comment]
![1](https://user-images.githubusercontent.com/16463960/32280779-3ef1ec68-bf1d-11e7-94cb-ec4161df0e20.png)

![2](https://user-images.githubusercontent.com/16463960/32280780-4174f26e-bf1d-11e7-99e0-56abe0300f29.png)

![3](https://user-images.githubusercontent.com/16463960/32280784-4330f896-bf1d-11e7-968c-39b18d025898.png)

**Comment by Lexzie** [comment]
Thanks! And even in dutch!

Summarization:

- Open Inkscape and import png with Ctrl-i.
- After that convert a raster to a vector with Paths > Trace bitmap (Shift-Alt-b).
- Right there also a lot options:
![afbeelding](https://user-images.githubusercontent.com/14023349/32282760-c3cecbf4-bf22-11e7-813d-1eedf4168d45.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/32282770-c93fc750-bf22-11e7-8531-95fa3f9dabd3.png)
- Then delete the raster image.
- Then (if needed) Edit > Resize Page to Selection (Shift-Ctrl-R).
- Save as optimized svg

Should you also try to import every png?

Great learning all this!

**Comment by mocram** [comment]
Easy png with not too much color gradients going on and of high enough quality are worth a try, the rest will be hard to get right.

**Comment by Lexzie** [comment]
Okay, we'll see.

Thanks for all the explanation.
