### ISSUE TITLE
new logos for german sky sport and Bundesliga channels needed

### ISSUE THREAD

**Issue by CWempe** [picons/picons-source#145]
The german Sky SPort ans Sky Bundesliga channels got new logos since this August.

see: https://de.wikipedia.org/wiki/Sky_Sport_(Deutschland)#Sender

Unfortunatelly it looks like there are no vector images availabe yet.

see also: https://github.com/picons/picons-source/issues/146

**Comment by charlesduco** [comment]
I added a commit with the new logos.
If anything is missing or wrong please add a message in this issue.
