### ISSUE TITLE
missings picons channels

### ISSUE THREAD

**Issue by crapaola** [picons/picons-source#145]
hello

new channels are comings:

Booster TV : http://www.boostertv.ch/
CNN Money Switzerland : [http://cnnpressroom.blogs.cnn.com/2017/01/22/cnnmoney-switzerland-to-launch-as-countrys-first-national-english-language-business-channel/](url)
Polar+ : [https://fr.wikipedia.org/wiki/Polar%2B](url)

thanks

**Comment by mocram** [comment]
https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

**Comment by crapaola** [comment]
snp-index

boostertv=boostertv
CNN Money Switzerland=cnnmoneyswitzerland
polar+=polarplus

srp-index

1_0_19_255E_A2_1_FFFF0000_0_0_0=boostertv
1_0_19_24AA_4E_1_FFFF0000_0_0_0=cnnmoneyswitzerland
1:0:19:240C:AC:1:FFFF0000:0:0:0=polarplus

**Comment by crapaola** [comment]
any eta?

**Comment by AbuBaniaz** [comment]
The issue got closed because you did not follow the rules. You also posted dead links.

**Comment by crapaola** [comment]
ok syntax errors for the links , edited the modified ones

**Comment by AbuBaniaz** [comment]
The links you posted are wrong. Too much detail. SNP names are wrong. + must be raplaced with plus

Backticks mentioned in other one of your posts. You did it correctly in other post, so do same here please.

**Comment by crapaola** [comment]
```
snp-index

boostertv=boostertv
CNN Money Switzerland=cnnmoneyswitzerland
polar+=polarplus
```

```
srp-index

19_255E_A2_1=boostertv
19_24AA_4E_1=cnnmoneyswitzerland
19_240C_AC_1=polarplus
```
'donkey monkey got issued'

**Comment by mocram** [comment]
Please read the contributing guidelines.

**Comment by mocram** [comment]
Please provide some prove of the channelnames, to see if you know the correct meaning of SNP

**Comment by crapaola** [comment]
channels names are correct as my vu+duo2 see them like that.
maybe CNN Money Switzerland=cnnmoneyswitzerland isnt correct 
left is how the channels is in reality , and right is how my vu+ need to be named to have the picon recognized

**Comment by mocram** [comment]
Left is SNP name, right is the logo name. Any issue without this correct info and the correct logos inside a zip gets closed.

**Comment by mocram** [comment]
Your service references are also incorrect

**Comment by crapaola** [comment]
the service reference are those who provided by dreambox edit , so if it is not the good ones , i do not have a clue where to find them.

**Comment by mocram** [comment]
The full ref is correct, but the truncated unique part not.

**Comment by crapaola** [comment]
`snp-index

boostertv=boostertv
CNN Money Switzerland=cnnmoneyswitzerland
polarplus=polarplus

srp-index

255E_A2_1_FFFF0000=boostertv
24AA_4E_1_FFFF0000=cnnmoneyswitzerland
240C_AC_1_FFFF0000=polarplus`

[logos.zip](https://github.com/picons/picons-source/files/1430540/logos.zip)

i hope its correct now with the ref , i removed the 1_0_1_ and _0_0_0 part

**Comment by mocram** [comment]
Cnn money is not a correct snp

**Comment by crapaola** [comment]
```
snp-index

boostertv=boostertv
cnn=cnnmoneyswitzerland
polarplus=polarplus

srp-index

255E_A2_1_FFFF0000=boostertv
24AA_4E_1_FFFF0000=cnnmoneyswitzerland
240C_AC_1_FFFF0000=polarplus
```
[logos.zip](https://github.com/picons/picons-source/files/1430954/logos.zip)

`donkey monkey got issued`

**Comment by mocram** [comment]
I give up.

**Comment by crapaola** [comment]
instead of trying making sense with your rules of madness , why not telling what is wrong or not.
there's 3 new channels , excuse me not being a superstar of the syntax and a picon master here.
i try my best , so i give up too.

**Comment by mocram** [comment]
It's not my fault that you are too stupid to read a few simple lines of text. Don't have to bite of my head, go complain with your mother, it's her that made the dumb turd.

Consider yourself banned! Have fun being stupid elsewhere. We've had enough dumb for 1 week.

**Comment by christmasspincode** [comment]
indeed and you werent able to give me an answer which abu gave me.
and your simple lines of text are completly non sense for me as long as you do not answer to my problems.
And please let me mother rest in peace.

**Comment by mocram** [comment]
You are no longer welcome! The simple lines of text are not nonsense, they are however way above the level your brain is capable of understanding.

I'm not going to repeat every line of the CONTRIBUTING.md file like a parrot, because you are to stupid to read.
