### ISSUE TITLE
separate logos for each german Sky Sport and Bundesliga channels

### ISSUE THREAD

**Issue by CWempe** [picons/picons-source#146]
I don't know if this has been discussed already or if it is just the result of "nobody hase made the effort yet".
But I noticed the channels "Sky Sport HD1" .. "Sky Sport HD 10" all got the same logo.
The same goes for "Sky Bundesliga" and "Eurosport 360".

Anyway, thanks for the great work so far!

**Comment by charlesduco** [comment]
Please open only one issue for sky sport germany ==> #145
