### ISSUE TITLE
New channel münchen.tv HD

### ISSUE THREAD

**Issue by tunip** [picons/picons-source#146]
**LOGO**
https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/M%C3%BCnchen_tv_Logo.svg/2000px-M%C3%BCnchen_tv_Logo.svg.png

**SRP-INDEX**
```
16A9_3FF_1_C00000=muenchentv
```

**SNP-INDEX**
```
muenchentv=muenchentv
muenchentvhd=muenchentv
```

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
Is this a new logo for an existing channel change? Or is this a different channel to the one for which we have a logo?

https://github.com/picons/picons-source/blob/master/build-source/logos/munchentv.default.svg

**Comment by tunip** [comment]
The logo is not new. Only the HD channel is new. You could use the existing logo from your answer. Thx

**Comment by AbuBaniaz** [comment]
Maybe I asked question incorrectly. Is the existing logo on our repository correct?

**Comment by tunip** [comment]
Yes, the existing logo on your repository is correct. Sorry for the confusion.

**Comment by AbuBaniaz** [comment]
I have added the link in the SRP-index file, there is no need in the SNP-index.

**Comment by tunip** [comment]
Many thx. It works. I close this issue.
