### ISSUE TITLE
New logo Nick Austria

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#147]
Looks like Nick Austria is using an own logo:

![screenshot](https://user-images.githubusercontent.com/14023349/32107618-7017a0ae-bb2f-11e7-9dd0-4a7bb1cc32a6.png)

[logos_to_be_added.zip](https://github.com/picons/picons-source/files/1422259/logos_to_be_added.zip)

Source: http://www.viacom.de/medias?utf8=%E2%9C%93&serie_id=mediathek_photo_vimn_logos

**snp-index**
```
nickelodeonat=nickaustria
```

**srp-index**
```
3D_7_85_C00000=nickaustria
```
`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
That logo has jagged edges. This is a better, but in .jpg format. Needs editing.
[nick_AT-1.zip](https://github.com/picons/picons-source/files/1424299/nick_AT-1.zip)

**Comment by Lexzie** [comment]
Ha, that file was the source.
Let me see if I can do better.

**Comment by mocram** [comment]
![nick_at-1](https://user-images.githubusercontent.com/16463960/32136659-f0971fb0-bc11-11e7-9541-b77767a7b935.png)

**Comment by Lexzie** [comment]
I hope this is better.
[logos_to_be_added_20171028a.zip](https://github.com/picons/picons-source/files/1424438/logos_to_be_added_20171028a.zip)

**Comment by mocram** [comment]
```
default=standard logo as used by the tv station, looks good on background intended by tv station
light=modified default logo that makes darker parts lighter, looks good on darker backgrounds
dark=modified default logo that makes lighter parts darker, looks good on lighter backgrounds
white=fully white logo, no colors allowed (indexed 1-bit, black/white), looks good on dark backgrounds
black=fully black logo, no colors allowed (indexed 1-bit, black/white), looks good on light backgrounds
```

I admit it might be confusing, but default is mostly an unaltered version as they are found on the www/google, so in most cases they will be optimized for white background websites.

**Comment by Lexzie** [comment]
I know the definitions, but what is meant by "used by the tv station"?
As you can see it is white on the screenshot, but it's black on Viacom's website.
I don't care if default is dark or light (indeed mostly it's dark), but want to commit with the right naming.

@AbuBaniaz Thanks!

**Comment by mocram** [comment]
I admit it might be confusing, but default is mostly an unaltered version as they are found on the www/google, so in most cases they will be optimized for white background websites.

If the majority of logos found online are displaying a black/dark text, in no circumstance should you make it light/white and call it default, if the onscreen logo shows it like that. I'm assuming the onscreen logo is using a light version too instead of the default one, so to speak.

Channels sometimes use greyed out logos (or whatever it is called), we also don't go greying out our logos....

**Comment by Lexzie** [comment]
I understand it, thanks for the explanation.
(Good example about the greyed out logos).

**Comment by mocram** [comment]
To summarize, if you are going to be editing colors on the png/svg file, it will most likely not be a `default` logo
