### ISSUE TITLE
Nick HD

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#149]
For the HD channels who have changed from Nickelodeon to Nick.

[logos_to_be_added.zip](https://github.com/picons/picons-source/files/1423039/logos_to_be_added.zip)

Source: https://upload.wikimedia.org/wikipedia/commons/8/82/Nick_HD_Logo.svg

**snp-index**
```
nickelodeonhd=nickhd
nickelodeonhdat=nickhd
```
**srp-index**
```
5273_41D_1_C00000=nickhd
527D_41D_1_C00000=nickhd
E_3200_13E_820000=nickhd
E_1964_13E_820000=nickhd
E9_1644_9C_5A0000=nickhd
```
`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
We already have this link  in the SNP index file
```
nickelodeonhd=nickelodeonhd
```

**Comment by Lexzie** [comment]
Just like the SD channels, the HD channels changed logo too.

With Issue #139 the link
```
nickelodeon=nickelodeon
```
was changed to
```
nickelodeon=nick
```
so I presumed
```
nickelodeonhd=nickelodeonhd
```
should also change to
```
nickelodeonhd=nickhd
```

A few channels still use the old logo, I'm in doubt if to wait if they change logo too or supply a list with srp-links to be included in the snp-index for those channels.

**Comment by Lexzie** [comment]
And I see I made a typo, sorry.
The second **snp-index** should have been **srp-index**.
Already corrected it above.

**Comment by AbuBaniaz** [comment]
snp name + logo name = picon
srp +logo name = picon

If snp name is already in use, use srp.

Please do not presume.

Can yo also consider adding dates to your attachment names. They all have the same name. This is not a rule, just helps. Suppose would not matter if I delete the old ones.

**Comment by Lexzie** [comment]
There is still a double entry for 3D_7_85_C00000 in srp-index.
```
3D_7_85_C00000=nickelodeon
``` 
can be deleted,

In snp-index 
```
nickelodeonhdat=nickelodeonhd_comedycentralhd
```
must be changed to
```
nickelodeonhdat=nickhd
```
Nickelodeon is not time-sharing with Comedy Central anymore.

**Comment by Lexzie** [comment]
Summary with additions to the comment above:
There are still some double/wrong/unnecessary entries in snp-index

**please delete:**
```
5273_41D_1_C00000=nickelodeonhd_comedycentralhd
527D_41D_1_C00000=nickelodeonhd_comedycentralhd
nickelodeonhdat=nickelodeonhd_comedycentralhd
527D_41D_1_C00000=nickhd
3D_7_85_C00000=nickelodeon
```

**please add(change):**
```
nickelodeonhdat=nickhd
```

**Comment by AbuBaniaz** [comment]
Is this now done?

**Comment by Lexzie** [comment]
Yes, very good. Sorry, did not checked this after your commit.
Thanks!
