### ISSUE TITLE
28.2 missing logos

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#149]
Hello, can you be so kind as to add these please? Thanks in advance.
1st line= logo link
2nd line= SNP name
3rd line= SRP name

http://tv.sky.com/logo/0/0/skychb2304.png
christmasgold
1968_7E6_2_11A0000

http://tv.sky.com/logo/0/0/skychb3830.png
heartxmas
D747_82F_2_11A0000

http://tv.sky.com/logo/0/0/skychb2509.png
mtvxmas
1B60_7DA_2_11A0000

http://tv.sky.com/logo/0/0/skychb4541.png
nowxmas
CB2A_839_2_11A0000

http://tv.sky.com/logo/0/0/skychb1816.png
skychristams
157E_7DC_2_11A0000

http://tv.sky.com/logo/0/0/skychb2703.png
xmasgoldplus1
1DB5_82D:2_11A0000

Existing logo, SNP update required.
qvcchristmas=qvcchristmas

**Comment by charlesduco** [comment]
I added the logos.
Please provide snp names and srp names next time in the right format:
srp:
```
1968_7E6_2_11A0000=christmasgold
1DB5_82D_2_11A0000=christmasgoldplus1
D747_82F_2_11A0000=heartxmas
1B60_7DA_2_11A0000=mtvxmas
CB2A_839_2_11A0000=nowchristmas
157E_7DC_2_11A0000=skycinemachristmas
EE8_7E8_2_11A0000=skycinemachristmashd
CB3F_839_2_11A0000=heartxmas
```
snp:
```
christmasgold=christmasgold
xmasgoldplus1=christmasgoldplus1
heartxmas=heartxmas
mtvxmas=mtvxmas
nowxmas=nowchristmas
skychristmas=skycinemachristmas
skychristmshd=skycinemachristmashd
qvcchristmas=qvcchristmas
```

https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code
https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

**Comment by AbuBaniaz** [comment]
Many thanks.

Noted about the service reference. I was doing Rytec stuff just before and forgot to change from colon to underscore. Sorry.

However, I can't use filenames that do not yet exist. I thought adding the details in part would have been the helpful thing to do. Didn't mean to create work. Perhaps next time I will ask for logos to be made, once they are made, submit a pull request for amended index files.
