### ISSUE TITLE
Mexico travel channel

### ISSUE THREAD

**Issue by franory** [picons/picons-source#15]
Good morning I can find this picon in SRP but not in SNP
reference name: 74A1_41C_1_C00000
service name=méxicotravel
I don't know if spanish accents might be a problem.

Thanks and regards

**Comment by charlesduco** [comment]
There was a wrong entry in snp-index, é should be interpreted as e:
`mexicotravel=mexicotravelchannel`

**Comment by mocram** [comment]
Anybody know how the wrong entry got in, a copy paste from a servicelist generated by our script (in this case the script would have failed)? Or just a random error?

**Comment by charlesduco** [comment]
It's a bug in 1-build-servicelist.sh: MÉXICOTRAVEL is converted to MXICOTRAVEL
But it should be converted to  MEXICOTRAVEL like the original OpenVix-code does: https://github.com/OpenViX/enigma2/blob/master/lib/python/Components/Renderer/Picon.py#L88-L89

**Comment by franory** [comment]
Issue on mexico travel is solved. It appears OK now. I think this issue can be closed.
