### ISSUE TITLE
Replacement logo NPO FunX

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#150]
FunX is now named NPO FunX, so also a new logo:

[replacement_logo.zip](https://github.com/picons/picons-source/files/1423467/replacement_logo.zip)

**snp-index**
```
funx=npofunx
funxlokaal=npofunx
npofunxnl=npofunx
npofunxnlwebcam=npofunx
```
**srp-index**
```
45F_8A6_2210_EEEE0000=npofunx
51A0_C8B_3_EB0000=npofunx
27E9_806_600_FFFF0000=npofunx
37E1_CB_600_FFFF0000=npofunx
3F5_4_10EF_FFFF0000=npofunx
49C_65_8C9_FFFF0000=npofunx
2012_2_F3C_FFFF0000=npofunx
```
`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
SNP references already exist.

These already exist
```
51A0_C8B_3_EB0000=npofunx
27E9_806_600_FFFF0000=npofunx
```

**Comment by Lexzie** [comment]
So they do not need to be added.
Thanks.
