### ISSUE TITLE
Eska TV SRP 1B_1_2268_EEEE0000 rebrand

### ISSUE THREAD

**Issue by michalzielanski** [picons/picons-source#151]
**Eska TV** SRP `1B_1_2268_EEEE0000` changed name to **Ósemka TV** and logo to: https://pl.wikipedia.org/wiki/Ósemka_TV#/media/File:8tv.jpg

**Comment by michalzielanski** [comment]
Thanks, but SRP `1B_1_2268_EEEE0000` now exists twice. Once in line [1](/picons/picons-source/blob/3046194e1a54a401041078eece61026bdbcbadeb/build-source/srp-index#L1), two in line [1274](/picons/picons-source/blob/3046194e1a54a401041078eece61026bdbcbadeb/build-source/srp-index#L1274) file's [build-source/srp-index](/picons/picons-source/blob/3046194e1a54a401041078eece61026bdbcbadeb/build-source/srp-index). This is fine?

**Comment by AbuBaniaz** [comment]
The top line is used first.

**Comment by charlesduco** [comment]
From the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md#srp-index):
> New additions can go at the top. No need to cleanup old entries, but if you want to, go right ahead.

Feel free to add a pull request with a cleanup of srp-index, but it's just extra work that has no use.
