### ISSUE TITLE
showcase tv +1

### ISSUE THREAD

**Issue by leec32** [picons/picons-source#151]
please add following link to the srp index

`C481_811_2_11A0000=showcasetvplus1`
`F82_7E8_2_11A0000=tlchd`

thank you 

`donkey monkey got issued`

**Comment by mocram** [comment]
Thanks for the issue, just as a reminder.

Put entries to `srp-index` or `snp-index` inside fenced code blocks. You can create fenced code blocks by placing a new line with three backticks ` ``` ` before and after the code block. ([READ THIS GUIDE](https://help.github.com/articles/creating-and-highlighting-code-blocks/))

**Comment by leec32** [comment]
```srp-index

C481_811_2_11A0000=showcasetvplus1
F82_7E8_2_11A0000=tlchd```

**Comment by leec32** [comment]
```
C481_811_2_11A0000=showcasetvplus1
F82_7E8_2_11A0000=tlchd
```

**Comment by AbuBaniaz** [comment]
Issue closed as commits made.
