### ISSUE TITLE
Logo BYU TV

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#152]
Can someone have a look at this svg? Found it on https://upload.wikimedia.org/wikipedia/commons/6/6f/BYUtv_logo.svg
It might needs some editing/simplification with Atom or so. (Look at line endings and look at the end of the file).
And a light version needs to be created too.

Corrected default and light logos:
[byutv_20171031.zip](https://github.com/picons/picons-source/files/1430800/byutv_20171031.zip)

**snp-index**
```
byutv=byutv
byutvglobal=byutv
eaarmbul=byutv
eadutman=byutv
eaefiara=byutv
eaengfre=byutv
eaengger=byutv
eaengita=byutv
eaengpor=byutv
eaengrus=byutv
eaengspa=byutv
eaestukr=byutv
eafarlat=byutv
eagrecze=byutv
eahunrom=byutv
eanordan=byutv
eapolalb=byutv
easpapor=byutv
easwefin=byutv
```
**srp-index**
```
C9_2_1_D7A2D30=byutv
CA_2_1_D7A2D30=byutv
CB_2_1_D7A2D30=byutv
CC_2_1_D7A2D30=byutv
CD_2_1_D7A2D30=byutv
CE_2_1_D7A2D30=byutv
CF_2_1_D7A2D30=byutv
D0_2_1_D7A2D30=byutv
D1_2_1_D7A2D30=byutv
D2_2_1_D7A2D30=byutv
D3_2_1_D7A2D30=byutv
D4_2_1_D7A2D30=byutv
D5_2_1_D7A2D30=byutv
D6_2_1_D7A2D30=byutv
D7_2_1_D7A2D30=byutv
D8_2_1_D7A2D30=byutv
D9_2_1_D7A2D30=byutv
```
`donkey monkey got issued`

**Comment by mcfly822** [comment]
I cleaned the file.
I don't think that light version needed. It seem very good also on black and on white background.
[byutv.default.zip](https://github.com/picons/picons-source/files/1424557/byutv.default.zip)

**Comment by Lexzie** [comment]
It looks good on a white background, but on a black background imho it would be better to make the letters 'byu' white. Is that possible?

![afbeelding](https://user-images.githubusercontent.com/14023349/32138113-cf4f0482-bc2d-11e7-9e83-bd66bf0d2b17.png)

![afbeelding](https://user-images.githubusercontent.com/14023349/32138099-91cbc280-bc2d-11e7-9177-b4cece565aa5.png)

**Comment by mcfly822** [comment]
Yes, but for me it is not so simple. I'll try it, but anybody else who can do this, let's do! :)

**Comment by mcfly822** [comment]
I tried a lot of things, but the only method seems working, that I make a white circle background.
It is almost perfect, but not perfect...
Here is the file.
If anyone can do it better, please adjust it.
[byutv.light.zip](https://github.com/picons/picons-source/files/1424884/byutv.light.zip)

**Comment by Lexzie** [comment]
When I open the svg in Inkscape, export the picture to png, I still see transparent byu-letters.

**Comment by mcfly822** [comment]
Really, it was my mistake. 
Here is the modified file what I wanted to attach earlier:
[byutv.light.zip](https://github.com/picons/picons-source/files/1425579/byutv.light.zip)

**Comment by Lexzie** [comment]
Looks pretty okay to me, but I think the U should overlap the circle, so maybe some copy-paste from the left side of the 'U'?

**Comment by mcfly822** [comment]
The problem is that there is no this kind of logo on the web to check whether the U ovelaps the circle or not.
Every logos I watched have the same color inside the letters (B, Y, U) and in the background. So we don't know the "reality" :)

For example, black letters, black background:
![byublack](https://user-images.githubusercontent.com/22531870/32150014-4b506d02-bd0d-11e7-88cf-f4f33a2b348d.jpg)

Blue...
![byublue](https://user-images.githubusercontent.com/22531870/32150023-505ba528-bd0d-11e7-850e-c6c1bddf101b.png)

White...
![byuwhite](https://user-images.githubusercontent.com/22531870/32150025-56d182d8-bd0d-11e7-8eb7-bbf45f25b12a.jpg)

**Comment by mcfly822** [comment]
Here is the modified file (in png). I think, the previous version is better. But this is only my opinion 😃 
What do you think?
I can upload the svg, if this version will be the "winner".
![bitmap](https://user-images.githubusercontent.com/22531870/32165385-e2f80ae8-bd62-11e7-94b5-4a8916160172.png)

**Comment by Lexzie** [comment]
I think it's okay.

**Comment by AbuBaniaz** [comment]
Please upload the logos to add in a zip file so that a mistake is not made

**Comment by mcfly822** [comment]
[byutv.light.zip](https://github.com/picons/picons-source/files/1430453/byutv.light.zip)

**Comment by Lexzie** [comment]
Placed the default and light logo now in one zip-file in first comment in this issue.
Hope this will okay to be committed.

**Comment by Lexzie** [comment]
Thanks you both!
