### ISSUE TITLE
NPO Politiek/NPO Sport

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#153]
Can we make an `npopolitiek_nposport.default` logo please? This will be similar to `npopolitiek_npobest.default`

We have both `npopolitiek` and `nposport` already. 

I tried but my copy and paste attempts only copied the white background, not the text.

SNP
```
npopolitieknposport=npopolitieknposport
```

`
donkey monkey got issue
`

**Comment by mcfly822** [comment]
I adjusted it. Is it acceptable?
[npopolitiek_nposport.default.zip](https://github.com/picons/picons-source/files/1424849/npopolitiek_nposport.default.zip)

**Comment by AbuBaniaz** [comment]
Many thanks.
