### ISSUE TITLE
Problem with Pro TV picons

### ISSUE THREAD

**Issue by mcfly822** [picons/picons-source#155]
There is a problem with the SVG files in this commit:
https://github.com/picons/picons-source/commit/67b41224f8b173014b835de9354dd05f16f455d0
The final PNG's are weird... 
(For example:)
![progold](https://user-images.githubusercontent.com/22531870/32149223-645d8318-bd01-11e7-8abb-869aec80625e.png)
![protv](https://user-images.githubusercontent.com/22531870/32149227-727ce4ca-bd01-11e7-8c56-4fd18f8fed1d.png)

```donkey monkey got issued```

**Comment by mcfly822** [comment]
Here are the corrected logos.
@AbuBaniaz now it can be open correctly in GIMP.
@mocram I cannot check the rsvg convert at this moment.
If someone will make a commit, please check them.
[protvchannels_corrected.zip](https://github.com/picons/picons-source/files/1428216/protvchannels_corrected.zip)

**Comment by AbuBaniaz** [comment]
@mcfly822 
Which picons do you use? I'll try a local build.

**Comment by mcfly822** [comment]
@AbuBaniaz 220x132, light on transparent. Thanks!

**Comment by AbuBaniaz** [comment]
They worked fine. Thanks.

**Comment by mcfly822** [comment]
Thanks! 👏
