### ISSUE TITLE
[28.2] Chilled Christamas & DBN 

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#155]
Hello two new logos required for 28.2.

Chilled Christmas
http://tv.sky.com/logo/0/0/skychb3682.png

Determination TV
http://tv.sky.com/logo/0/0/skychb5216.png

SRP:
```
D74A_82A_2_11A0000=chilledchristmas
CBAA_83C_2_11A0000=determinationtv
```

SNP:
```
chilledxmas=chilledchristmas
dbn=determinationtv
```

Thanks

**Comment by charlesduco** [comment]
Added in last commit: https://github.com/picons/picons-source/commit/72f2b6af3dcbf5f354134f8e4483773c1d5c32b7
