### ISSUE TITLE
Various updates to srindex.

### ISSUE THREAD

**Issue by SimAda00** [picons/picons-source#16]
Some service references for channels within the West Midlands regions. 

`1680_1045_233A_EEEE0000=radio/bbcradio6music`
`1740_1045_233A_EEEE0000=radio/bbcasian`
`11C0_1045_233A_EEEE0000=tv/bbcfour`
`1100_1045_233A_EEEE0000=tv/bbcnews`
`1045_1045_233A_EEEE0000=tv/bbcone`
`1280_1045_233A_EEEE0000=tv/bbcparliament`
`1700_1045_233A_EEEE0000=radio/bbcradio1xtra`
`1600_1045_233A_EEEE0000=radio/bbcradio5live`
`1640_1045_233A_EEEE0000=radio/bbcradio5livesportsextra`
`1A40_1045_233A_EEEE0000=radio/bbcradio1`
`1A80_1045_233A_EEEE0000=radio/bbcradio2`
`1AC0_1045_233A_EEEE0000=radio/bbcradio3`
`1B00_1045_233A_EEEE0000=radio/bbcradio4`
`16C0_1045_233A_EEEE0000=radio/bbcradio4extra`
`1C00_1045_233A_EEEE0000=tv/bbcredbutton`
`1140_1045_233A_EEEE0000=tv/bbcredbutton`
`10C0_1045_233A_EEEE0000=tv/bbcthree`
`10BF_1045_233A_EEEE0000=tv/bbctwo`
`1780_1045_233A_EEEE0000=radio/bbcworldservice`
`1200_1045_233A_EEEE0000=tv/cbbc`
`1240_1045_233A_EEEE0000=tv/cbeebies`
`20C0_2006_233A_EEEE0000=tv/channel4`
`2104_2006_233A_EEEE0000=tv/channel4plus1`
`2134_2006_233A_EEEE0000=tv/channel5`
`5940_5040_233A_EEEE0000=radio/classicfm`
`2100_2006_233A_EEEE0000=tv/e4`
`20C1_2006_233A_EEEE0000=tv/filmfour`
`2046_2006_233A_EEEE0000=tv/itv`
`20AA_2006_233A_EEEE0000=tv/itvplus1`
`2085_2006_233A_EEEE0000=tv/itv2`
`3DF8_3006_233A_EEEE0000=tv/itvbeplus1`
`20FA_2006_233A_EEEE0000=tv/more4`
`8080_800E_233A_EEEE0000=tv/pop`
`8140_800E_233A_EEEE0000=tv/qvcextra`

There are a few extra's that need adding but I've not sorted the icons for them yet:
`5A90_5040_233A_EEEE0000=tv/trutvplus1`
`1805_1045_233A_EEEE0000=radio/bbcwm`
`804E_800E_233A_EEEE0000=tv/bigcentretv`
`5960_5040_233A_EEEE0000=radio/lbc`

**Comment by picons** [comment]
Please do not put every line in a seperate code block...
