### ISSUE TITLE
Logo Kurdistan 24

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#160]
If this logo is of enough quality, please add.

[kurdistan24_20171030.zip](https://github.com/picons/picons-source/files/1428304/kurdistan24_20171030.zip)

**snp-index**
```
e7wa=kurdistan24
k24=kurdistan24
k24radio=kurdistan24
kurdistan24=kurdistan24
```

**srp-index**
```
1_1_1_642D31=kurdistan24
1_1_FFFF_642D7D=kurdistan24
2_1_FFFF_642D7D=kurdistan24
3A0E_1FA4_13E_820000=kurdistan24
3A0F_1FA4_13E_820000=kurdistan24
3ED_320_800_DCA0000=kurdistan24
3F1_320_800_DCA0000=kurdistan24
409_320_800_DCA0000=kurdistan24
```

`donkey monkey got issued`

**Comment by mocram** [comment]
Why the first entry of snp-index?

**Comment by Lexzie** [comment]
Because the name is 'E7wA', which can change or could be used by others.

**Comment by mocram** [comment]
That is not a valid reason to use a service reference in snp

**Comment by Lexzie** [comment]
In that case it's will be
```
e7wa=kurdistan24
```
But what if a station is named 'test' or 'Service 1' or even doesn't have a name?

**Comment by mocram** [comment]
You call it test or service1. If it has no name there's no other way but to use the ref

**Comment by mocram** [comment]
If there is a channel called test on a popular sat, you can use the ref on a lesser popular sat

**Comment by Lexzie** [comment]
Clear.
Corrected the first comment, hope it's okay to submit it now.

**Comment by Lexzie** [comment]
Thanks
