### ISSUE TITLE
Add some UK logos 

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#160]
Hello, can you add the following channels please?

christmasfood
```
http://tv.sky.com/logo/0/0/skychb2308.png
```

christmasfoodplus1
```
http://tv.sky.com/logo/0/0/skychb2326.png
```

christmasfoodhd
```
http://tv.sky.com/logo/0/0/skychb4067.png
```

more4hd
```
http://tv.sky.com/logo/0/0/skychb4043.png
```

SRP index
```
196C_7E6_2_11A0000=christmasfood
1DCA_82D_2_11A0000=christmasfoodplus1
```

SNP index
```
xmasgoldplus1=christmasgoldplus1
xmasfoodplus1=christmasfoodplus1
christmasfood=christmasfood
christmasfoodhd=christmasfoodhd
more4hd=more4hd
```

For future reference, if I download myself, will they be in correct/acceptable format?
If so, I can add to my repo and submit a pull request.

**Comment by charlesduco** [comment]
You should always check each logo you download whether they meet the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md).

For logos from sky.com, it's important to check the following points:
- try to find or make a svg version of the logo
- background must be transparent without additional effects like borders or shadows
- default version of the logo is readable on light backgrounds
- light version of the logo is readable on dark backgrounds

For example, the more4hd logo you provided is not acceptable cause there is a shadow effect.
In this case I could easily edit the existing svg logo in the repository to get a clean version of the new hd-logo.

**Comment by AbuBaniaz** [comment]
Thanks
