### ISSUE TITLE
Logos LBC/LDC

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#161]
Please add these logos for the Lebanese LBC and LDC.

[LBC-LDC_20171030.zip](https://github.com/picons/picons-source/files/1428810/LBC-LDC_20171030.zip)

**snp-index**
```
lbceurope=lbceurope
ldc=ldc
ldcamerica=ldc-jusowanusw
```

**srp-index**
```
1F4_5_A_640000=lbceurope
1F5_5_A_640000=ldc
CFE_21_800_DCA0000=ldc
1F6_5_A_640000=ldc-jusowanusw
```
`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
Are you sure you want these? The picon will mostly be empty.

**Comment by Lexzie** [comment]
Well, this is how the logos are. Can't help it either.

https://www.lbcgroup.tv/

![afbeelding](https://user-images.githubusercontent.com/14023349/32233637-2201cbfe-be5b-11e7-8a39-eacd3faeca9d.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/32233817-99444462-be5b-11e7-9584-93527dfaa489.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/32233738-633cf120-be5b-11e7-8c82-5250cdeb2a96.png)

**Comment by AbuBaniaz** [comment]
You had a bit of space around the logos. I have trimmed them a bit more.

**Comment by mocram** [comment]
@AbuBaniaz You shouldn't have done that. You removed the drop shadow (partly)

**Comment by AbuBaniaz** [comment]
OK. I'll re-upload.
