### ISSUE TITLE
Logo AP

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#163]
Please add this logo and links.

[AP_20171030.zip](https://github.com/picons/picons-source/files/1428884/AP_20171030.zip)

Source: https://commons.wikimedia.org/wiki/File:Associated_Press_logo_2012.svg

**snp-index**
```
apgvw=ap
apdirect=ap
```

**srp-index**
```
64_1_1_64B15D=ap
C8_1_1_64B15D=ap
```
`donkey monkey got issued`

**Comment by Lexzie** [comment]
Thanks

**Comment by mocram** [comment]
It might be a good idea to call this logo associatedpress instead of ap....

**Comment by mocram** [comment]
Never mind! Good job
