### ISSUE TITLE
Hispasat picons

### ISSUE THREAD

**Issue by fabdslv** [picons/picons-source#164]
Is there any plan to integrate Hispasat (30°W) picons to this project? 

Thanks.

**Comment by mocram** [comment]
It's not on a TODO list I think, but there's also no reason that they can't be included.
Somebody with access to that sat just has to put in the effort.

**Comment by AbuBaniaz** [comment]
If you use the SNP version, you should find most work, not sure if they are correct as cannot clear them. I attach a list (zipped excel file) of the  missing ones. If you know that we have the logos on the repository, adding the references for them will be simple.

For the ones that do not have logos, you will have to provide links/logos.

[missing-picons-30w.zip](https://github.com/picons/picons-source/files/664674/missing-picons-30w.zip)
