### ISSUE TITLE
Logo request: Finnish C More channels

### ISSUE THREAD

**Issue by tjormola** [picons/picons-source#165]
Hi!

Image editing is not my special expertise so I request someone with more talent in the area to help me out. Perhaps @charlesduco  could help, I see he has contributed nice logos for other C More channels in the past. I'd like to see the black and white versions of the following C More channels added to picons.

High resolution source images available at https://www.mtv.fi/brandguide/logot (click the "C More – maksulliset palvelut ja kanavat" title)

- C More Max
- C More Max HD
- C More Juniori
- C More Juniori HD
- C More Sport 1
- C More Sport 1 HD
- C More Sport 2
- C More Sport 2 HD

After committing the logo files to the picons-source repo, I can then contribute a pull request for updating SNP and SRP indices with proper entries for these channels.

**Comment by dalmore72** [comment]
[Finland.zip](https://github.com/picons/picons-source/files/1430374/Finland.zip)

**Comment by mcfly822** [comment]
If @charlesduco has no ambition/time to do it, I can make them tomorrow.

**Comment by charlesduco** [comment]
No time this week.

**Comment by mcfly822** [comment]
@tjormola 

> I'd like to see the black and white versions of the following C More channels 

Do you mean really black and really white? Because the "dark" and "light" version is in use for all other picons. I will make "default" (dark brown color) and "light" (white color) logos. But besides, may I make fully black logos?

**Comment by tjormola** [comment]
Thanks!
