### ISSUE TITLE
SyFy+1 logo

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#166]
Can someone fix the SyFy+1 logo?

![afbeelding](https://user-images.githubusercontent.com/14023349/32246866-acd0b69e-be80-11e7-9f62-8cec3fc1f390.png)

**Comment by AbuBaniaz** [comment]
What is there to fix with the logo? They are using a `syfy` logo which we already have. The `+1` is separate and on the other side of the screen.

**Comment by AbuBaniaz** [comment]
https://github.com/picons/picons-source/blob/master/build-source/logos/syfy-spatupriho.default.svg

**Comment by Lexzie** [comment]
I meant adding the `+1` to the logo.
So, if not the logo has to be created, could you change the snp- and srp-links?

**snp-index**
```
syfyplus1=syfyhd-spatupriho
```
**srp-index**
```
CC38_83D_2_11A0000=syfyhd-spatupriho
```
(By the way: There's another link in srp-index (cable), but I cannot check if the logo is changed there too. Would make sense tho. I believe you have UK cable?)
This link is:
```
38C_9_F020_FFFF0000=syfyhd-spatupriho
```
`donkey monkey got issued`

**Comment by Lexzie** [comment]
Thanks
