### ISSUE TITLE
Missing picons plugin/script

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#167]
Not an issue. 
This has been posted on a few fora. Posting here for benefit of others who may have not seen it.

Once you run the plugin, it will create a zip file in the /tmp directory. There will be two csv files (best seen with excel or similar). One will list the picons found and locations. The other will list the missing picons. It will also list part of the required details for this project.

It will not identify incorrect picons. You can optionally place a different lamedb file in /tmp directory. The python file is by Huevos.

[enigma2-plugin-extensions-missingpicons_2017_08_28_all.zip](https://github.com/picons/picons-source/files/1432297/enigma2-plugin-extensions-missingpicons_2017_08_28_all.zip)

**Comment by mocram** [comment]
Isn't that kinda the same as 1-build-....  ?
