### ISSUE TITLE
channel logo issue

### ISSUE THREAD

**Issue by belhamraadil** [picons/picons-source#169]
hello firstable thank you for your work but can you juste remove HD from all canalsat channel as they dont use it in their logo since last year by the way can you add picon for crime district (asta 19)
thank you

**Comment by charlesduco** [comment]
It would help a lot of you could post a list of the logo names where the HD element should be removed.

**Comment by belhamraadil** [comment]
hello list of chaneel that use no more hd:
canal+decale
canal+cinema
canal+family
canal+series
ocsmax
ocs geant
ocs choc
ocscity
cine+premiere
cine+famiz
cine+club
cine+emotion
cine+frissons
thank you

**Comment by charlesduco** [comment]
I added all requested changes. If something is still wrong or missing, let me know.
If everything is as expected, you can close this issue.

**Comment by belhamraadil** [comment]
Hello everything IS perfect  now thanks for work
