### ISSUE TITLE
srp-index 28.2 

### ISSUE THREAD

**Issue by leec32** [picons/picons-source#169]
please add
```
srp-index
D101_832_2_11A0000=travelchannelplus1
D10B_832_2_11A0000=vintagetv
F42_7EB_2_11A0000=tcmhd-crecrawano.default
```

[tcmhd-crecrawano.default.zip](https://github.com/picons/picons-source/files/1443067/tcmhd-crecrawano.default.zip)

thanks 

`donkey monkey got issued`

**Comment by mocram** [comment]
`tcmhd-crecrawano.default` is not valid for srp-index

**Comment by leec32** [comment]
apart from it not been valid which i will leave to the experts from now on because i cant get to grips with these logos lol,  its the original one from sky

http://tv.sky.com/logo/00/00/skychb3811.png

could you possibly check sfyfy and syfy +1 also because some new ones got added to the index a few days ago and they are bright green and nothing like the sky ones which you already had anyway

thanks

**Comment by mocram** [comment]
Somebody should get fired at sky.com. Not sure what you mean about Syfy.

**Comment by leec32** [comment]
Hahaha I get you hint.

I'm out at the moment and will paste what I mean later, the first 2 references I added are just stream reference change and wrong logo, if they are ok to be added 

Thanks

**Comment by mocram** [comment]
first 2 added

**Comment by mcfly822** [comment]
I made a variation for tcmhd logos. Are these acceptable?
[tcmhd-201711041337.zip](https://github.com/picons/picons-source/files/1443200/tcmhd-201711041337.zip)
(Cannot make an svg, because the small "TM" is very ugly. Maybe later, if I have more time for this.)

**Comment by leec32** [comment]
@mocram 

this got added a few days ago and it is also the same for the +1 channel 
![syfyhd-spatupriho](https://user-images.githubusercontent.com/30335438/32405464-a6402a46-c15d-11e7-94ad-7ca0c5217e2c.png)

http://tv.sky.com/logo/00/00/skychb2505.png
http://tv.sky.com/logo/00/00/skychb2513.png

above are originals from sky site, not sure if there was a specific reason for the change as you already had logos very close to the sky ones, its not an issues just more curious  

syfyhd
syfyplus1

**Comment by mocram** [comment]
There are variations going around I believe....better ask @Lexzie , he knows more about it I think.

**Comment by AbuBaniaz** [comment]
Which logo is shown on the screen? Text on two tiers or one tier?

**Comment by leec32** [comment]
@AbuBaniaz 
2 tiers but its not bright lime/green lol

**Comment by Lexzie** [comment]
> There are variations going around I believe....better ask @Lexzie , he knows more about it I think.

I asked to make a '+1'-logo (Issue #166 ) but @AbuBaniaz said because the +1 was on the other side of the screen the standard logo was okay. so we just corrected the snp- and srp-links.

> Which logo is shown on the screen? Text on two tiers or one tier?

Two tiers.

> 2 tiers but its not bright lime/green lol

Logos on screen are often greyed out, not coloured. I'd like a coloured logo, otherwise choose white picons when installing.

**Comment by mocram** [comment]
@leec32 
It doesn't have to be exactly the same color as on-screen
The website uses a green color theme, so.....
http://www.syfy.com/

**Comment by leec32** [comment]
yes your right, i just thought the logos were the same as the sky official logos 

im not complaining guys was just more curious :)

**Comment by AbuBaniaz** [comment]
Is anything remaining to be done?

**Comment by leec32** [comment]
all done for me, thanks
