### ISSUE TITLE
IPKs not being refreshed on picons.eu

### ISSUE THREAD

**Issue by p17blo** [picons/picons-source#17]
More a question than an issue, but when do IPKs get refreshed on the picons.eu site? Is there anything I can do to force/push an IPK refresh here?

Last update was nearly 3 weeks ago

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
Any news @mocram

**Comment by mocram** [comment]
OOps, will investigate

**Comment by mocram** [comment]
A security measure did it's work, building again...

@p17blo They should get refreshed daily if any updates happend. So if today some commits happend and the picons are not updated tomorrow morning around 06:00AM, you can complain here :-) No need to wait 3 weeks.
