### ISSUE TITLE
missing channels

### ISSUE THREAD

**Issue by crapaola** [picons/picons-source#170]
hi,
missing those channels

France Info tv=Franceinfo
1:0:16:252:A4:1:FFFF0000:0:0:0=FranceInfo
https://fr.wikipedia.org/wiki/France_Info_(cha%C3%AEne_de_t%C3%A9l%C3%A9vision)

Evil angel Tv=evilangeltv
1:0:19:24CE:33:1:FFFF0000:0:0:0=Evil Angel TV
http://www.evilangel.tv/

TV5 Monde FBS (France,Belgique,Suisse)=tv5mondefbs
1:0:1:D5:A0:1:FFFF0000:0:0:0=TV5 Monde FBS

Misslabeled (.png is named as polar.png and should be cinepolar.png)
polar=cinepolarhd
1:0:19:2536:AC:1:FFFF0000:0:0:0=cinepolarhd

and there's problem with : 
canalpluscinema.png , canalplusdecale.png , canalplusserie.png no more HD logo although canalplussport and canalplusfamily still have.Check with the .png attached
![sans titre](https://cloud.githubusercontent.com/assets/22410757/21549912/f6ef7796-cdf5-11e6-8787-e1fcf8c18d50.png)

also with the cineplus channels , same problems as the canalplus channels , here is the png attached ( no more hd logos for those channels )
![sans titre2](https://cloud.githubusercontent.com/assets/22410757/21550467/5374cad0-cdfa-11e6-997f-e52416eabd1c.png)

maybe need an index update for those canalplus and cineplus channels
canalpluscinema=canalpluscinemahd
canalplusdecale=canalplusdecalehd
canalplusfamily=canalplusfamilyhd
 canalplusseries= canalplusserieshd
canalplussport=canalplussporthd
cineplusclassic=cineplusclassichd
cineplusclub=cineplusclubhd
cineplusemotion=cineplusemotionhd
cineplusfamiz=cineplusfamizhd
cineplusfrisson=cineplusfrissonhd
cinepluspremier=cinepluspremierhd

thanks

**Comment by charlesduco** [comment]
The hd logos are removed cause broadcaster canal+ doesn't use them anymore.
I added a commit with the missing channels.

**Comment by mocram** [comment]
![naamloos](https://cloud.githubusercontent.com/assets/16463960/21648511/8d12ad40-d29e-11e6-9fd4-532acfb7cea5.png)
