### ISSUE TITLE
New/updated channels logo

### ISSUE THREAD

**Issue by axlt2002** [picons/picons-source#171]
Dear developers, thanks for your great work that makes my TV usage on Kodi really pleasant every day.

I would like to provide a new channel logo that is actually missing in the current package:

- channel NOVE (logo [here](http://imgur.com/8ZhBzy0)); the background should be transparent

In addition, there are updates in some of the Mediaset logos (at least the ones that appears on the TV screen while watching the channels):

- channel ITALIADUE (logo [here](http://imgur.com/MGGDWBd)); similarly to the current version, it should have a white logo and a transparent background
- channels LA5 and TOPCRIME have now the MEDIASET word added at the bottom of the logo (similarly to ITALIADUE) but I dind't find any sample (it is possible to check the logos in the LIVE section on the Mediaset site)

Thanks for your attention.

**Comment by charlesduco** [comment]
I added a commit with the requested changes. Please check and if everything is okay, close this issue.

**Comment by axlt2002** [comment]
Thanks a lot Charles! You made really a perfect job!

Actually the only small modification to do is for TOPCRIME, where the background triangle is no more present (please take a look to this [screenshot](http://imgur.com/xH7KreX)). But this is rising the following question on my side...

Whixh is the usual way to proceed to decide a channel logo to be included in the package? TOPCRIME, for example, has actually two "different" logos: the one displayed on the channel itself (i.e. screenshot reported above) and the one used on the site (i.e. the one with the triangle in the background and without the MEDIASET word at the bottom). Which one should be included in the package?

Thanks for any clarification and have a nice day! :)

**Comment by charlesduco** [comment]
I usually add the original logos as shown in tv bumpers and idents or brochures provided by tv broadcasters.
For Topcrime, I think the triangle is still part of their brand identity: https://www.youtube.com/watch?v=1tR7vfBL_Lg

So I think I should rather remove the "mediaset" word instead of the triangle.

**Comment by axlt2002** [comment]
Hi charlesduco, Thanks for your answer.
Ok, what you say it is really making sense, I agree. So, as a reference, I think is always the best way to refer to the boradcasters site instead of what appears on the channel itself (that sometimes is just changing according to the program ongoing).
According to this, I think that all the actual mediaset channels logo should be updated by removing the "medisaet" word at the bottom of them. This is the current [logo list](http://imgur.com/N4PBMmY) that is possible to find on the mediaset site. The channels name are: Rete4, Canale5, ItaliaUno, La5, MediasetItaliaDue, MediasetExtra (this is already ok), TOPCrime, Iris, Mediaset TGCOM24 (this is already ok).
Can you take care of such updates? Thanks in advance!

**Comment by charlesduco** [comment]
I removed the mediaset captions. You can close this issue if the changes are as expected.

**Comment by axlt2002** [comment]
Thanks a lot charlesduco for your work! Really appreciated!
I have checked all the channel logos and ItaliaDue still need to have the "mediaset" word removed; just revert it back as it was when I opened this thread...sorry for that! ;)
After that, everything will be perfect! I hope that the new package will be released soon.
Cheers, Alex.

**Comment by mocram** [comment]
Packages start building at 0:00 daily, so every change that's commited here on github before 0:00 will be available around 06:00 next morning.

So if I update a logo today at 18:00 I can install it by downloading it from the website tommorrow give or take at around 06:00 in the morning.

**Comment by axlt2002** [comment]
Thanks for the clarification mocram. I just don't understand why if I go in the download section, the packages are from the 6th of January...I guess that these ones are not updated daily, right?

**Comment by mocram** [comment]
They are only updated if anything was changed/commited, so no change, no new package

**Comment by charlesduco** [comment]
>  I have checked all the channel logos and ItaliaDue still need to have the "mediaset" word removed; just revert it back as it was when I opened this thread...sorry for that! ;)

ItaliaDue is the only channel that has the mediaset caption in its tv bumpers between the programmes:
http://www.mediaset.it/quimediaset/video/italia-2-la-campagna-che-si-ispira-ai-meme_1153.shtml

I think the mediaset caption should remain in this specific logo.

**Comment by axlt2002** [comment]
@mocram: perfectly clear, thanks!
@charlesduco: you know italian channels better than me!!! Lol!!! Ok, to reach the perfection, it seems that Iris is the last one that needs to be updated now: watching the [promo bumper](https://www.youtube.com/watch?v=ARWoEuMnBWA) (as well as on the [Mediaset site](http://www.mediaset.it/iris/programmi/1006/iris-programmi-tv.shtml)), this is the [logo](http://www.ascoltitv.it/batillus/gallery/index.php?i=../../wp-content/uploads/2013/06/Iris-Logo-2013-3D-su-nero.jpg) that should be used. Thanks a lot for your really almost infinite patience and effort!

**Comment by axlt2002** [comment]
Thanks a lot charlesduco! I'm going to close the "issue".
Ciao,
Alex
