### ISSUE TITLE
RTP logos

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#171]
I noticed that the light-versions of the RTP logos are actually the white logos.
The default logos are perfectly as light logos, they are light enough to be displayed on a dark/black background.

So I propose to rename the following logos from xxx.light.svg to xxx.white.svg
```
rtp1.light.svg
rtp2.light.svg
rtp3.light.svg
rtp4k.light.svg
rtpacores.light.svg
rtpafrica.light.svg
rtpmadeira.light.svg
rtpmemoria.light.svg
```
to:
```
rtp1.white.svg
rtp2.white.svg
rtp3.white.svg
rtp4k.white.svg
rtpacores.white.svg
rtpafrica.white.svg
rtpmadeira.white.svg
rtpmemoria.white.svg
```
The logo rtpinternacional.light.svg is allready in colour. 

What also could be considered is to change the logos of rtp1, rtp2 and rtp3.
On screen they are like this:
![afbeelding](https://user-images.githubusercontent.com/14023349/32409897-a39dbf80-c1b5-11e7-988f-87d47335dc6e.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/32409912-fcc30cd2-c1b5-11e7-8968-76ef311dcac8.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/32409915-0b42c78e-c1b6-11e7-955b-4851d7a20a00.png)

Without the text RTP, just like the other logos rtpacores, rtpafrica, rtpmadeira and rtpmemoria.
I do not dislike the existing logos (besides the lack of colour), but maybe more people find these logos visual better.

Here are the svg's:
[RTP123-short_20171104.zip](https://github.com/picons/picons-source/files/1443596/RTP123-short_20171104.zip)

Sources:
RTP 1: http://logos.wikia.com/wiki/File:RTP1_Short_2016.svg
RTP 2: http://logos.wikia.com/wiki/File:RTP2_Short_2016.svg
RTP 3: http://logos.wikia.com/wiki/File:RTP3_Short_2016.svg

`donkey monkey got issued`

**Comment by mcfly822** [comment]
I agree, only RTP 4K ```default``` logo is no good for ```light``` logo.
So I made the ```light``` version.
[rtp4k.light.zip](https://github.com/picons/picons-source/files/1476389/rtp4k.light.zip)

**Comment by Lexzie** [comment]
Okay, I didn't supply a rtp4k picon for the record, so that was the already existing one.
(I can't receive RTP 4k, so I can give no service reference for that).

So can anyone first delete the logos:
```
rtp1.light.svg
rtp2.light.svg
rtp3.light.svg
rtpacores.light.svg
rtpafrica.light.svg
rtpmadeira.light.svg
rtpmemoria.light.svg
```
(Or rename them to rtp[xxx].white.svg)

Here are all the logos together to be added/replaced:
[RTP 20171115.zip](https://github.com/picons/picons-source/files/1476434/RTP.20171115.zip)

There's no need to update snp-index, the links are already there.

**Add to srp-index:**
```
32B_24_36_CE40000=rtp1
65_65_53_CE40000=rtp1
32C_24_36_CE40000=rtp2
66_65_53_CE40000=rtp2
65_24_36_CE40000=rtp3
69_65_53_CE40000=rtp3
3_56C_56C_CE40000=rtp3
67_24_36_CE40000=rtpacores
6B_65_53_CE40000=rtpacores
77_65_53_CE40000=rtpacores
68_24_36_CE40000=rtpmadeira
6A_65_53_CE40000=rtpmadeira
76_65_53_CE40000=rtpmadeira
519_67_53_CE40000=rtpmemoria
163_67_53_CE40000=rtpmemoria
520_67_53_CE40000=rtpafrica
16A_67_53_CE40000=rtpafrica
```
`donkey monkey got issued`

**Comment by mcfly822** [comment]
I made the modifications in PR #188 .
I didn't change the logos of rtp1, rtp2 and rtp3 ("RTP logos without the text RTP") because I couldn't decide that are they better than the existing logos or not... You wrote:

> maybe more people find these logos visual better

Or maybe not 😄 I think the owners will decide this.

**Comment by Lexzie** [comment]
I also changed my mind and therefor I did not include them in my last post.
