### ISSUE TITLE
Mapping by Service Reference not working

### ISSUE THREAD

**Issue by technicodepl** [picons/picons-source#172]
When I map by service name mapping work correctly:
`1_0_1_3AB7_514_13E_5140000_0_0_0 | AMC | 3AB7_514_13E_5140000=-------- | amc=amc`
https://pastebin.com/Uu16zwWX
but when I tried to map by service reference then:
`1_0_1_3AB7_514_13E_5140000_0_0_0 | AMC | 3AB7_514_13E_5140000=--------`
https://pastebin.com/cdKQavVA
I did the same few months ago and it worked fine. I'm doing something wrong?

I used TVH server mode

**Comment by mocram** [comment]
Upload a copy of your tvh channel files.

**Comment by technicodepl** [comment]
http://s000.tinyupload.com/?file_id=78966109038879626596

channels and input was generated by e22tvh 1.5a and then rescan by TVH

**Comment by mocram** [comment]
All your reference end with `5140000`, not a single reference like that is added to srp-index. So it is to be expected that they don't get mapped.
