### ISSUE TITLE
updatet service id's on cable unitymedia & missing picons list

### ISSUE THREAD

**Issue by pommesfrites** [picons/picons-source#172]
edit:
DB26_231_270F_FFFF0000=123tvhd
6210_83_270F_FFFF0000=ae
65FA_1CD_270F_FFFF0000=balkanikamusictelevision
201_3_85_FFFF0000=bluemovie
3B00_97_270F_FFFF0000=bongusto
3B07_97_270F_FFFF0000=cartoonnetwork
E86_1E1_270F_FFFF0000=cctv9
A85D_1AF_270F_FFFF0000=cnnhd
565F_DD_270F_FFFF0000=cnnturkradio
5A4D_E7_270F_FFFF0000=deutschesmusikfernsehen
69E7_79_270F_FFFF0000=disneychannelhd
2B5E_BF_270F_FFFF0000=disneychannel
6230_1D7_270F_FFFF0000=dmsat
3B03_97_270F_FFFF0000=eentertainment
5A41_E7_270F_FFFF0000=eurod
DB28_231_270F_FFFF0000=eurosport1hd
3AFE_97_270F_FFFF0000=extremesports
3B02_97_270F_FFFF0000=fashiontv
526D_D3_270F_FFFF0000=fixundfoxi
622A_1D7_270F_FFFF0000=france4
6DCE_1FF_270F_FFFF0000=ginxesportstv
71AF_1FF_270F_FFFF0000=haberturktv
5A4E_E7_270F_FFFF0000=h2d
65FE_1CD_270F_FFFF0000=hayat
CF71_213_270F_FFFF0000=hrfernsehenhd
65FB_1CD_270F_FFFF0000=hrttv1
98BD_187_270F_FFFF0000=kabeleinsclassicshd
46C5_B5_270F_FFFF0000=kabeleinsdoku
71B1_1FF_270F_FFFF0000=kazakhtv
660A_1E1_270F_FFFF0000=klassik
69EB_97_270F_FFFF0000=ktv
94D8_1AF_270F_FFFF0000=lustpurhd
759F_1CD_270F_FFFF0000=mad
6E46_431_A401_FFFF0000=mdrthueringen
9CA7_6F_270F_FFFF0000=mtvhd
5A4F_E7_270F_FFFF0000=n24doku
C79D_79_270F_FFFF0000=n24hd
526E_D3_270F_FFFF0000=natgeopeople
3AFF_97_270F_FFFF0000=nauticalchannel
6F1E_431_A401_FFFF0000=ndrblue
AC4A_1B9_270F_FFFF0000=nickelodeonhd
2B60_BF_270F_FFFF0000=nickelodeon_nicknight
AC64_1FF_270F_FFFF0000=nporadio1
AC65_1FF_270F_FFFF0000=nporadio5
4E91_15F_270F_FFFF0000=nrwision
5E2F_15F_270F_FFFF0000=nrwtv
C79E_79_270F_FFFF0000=ntvhd
AC58_1FF_270F_FFFF0000=ntvmir
6608_1CD_270F_FFFF0000=pearltv
3B05_97_270F_FFFF0000=penthouse
65FD_1CD_270F_FFFF0000=rtvpinkextra
621E_1D7_270F_FFFF0000=rtvpinkfilm
621F_1D7_270F_FFFF0000=rtvpinkfolk
65FF_1CD_270F_FFFF0000=rtvpinkmusic
65FC_1CD_270F_FFFF0000=rtvpinkplus
AC51_1FF_270F_FFFF0000=protvinternational
5E33_F1_270F_FFFF0000=radiobob
565B_DD_270F_FFFF0000=rai2
6229_1D7_270F_FFFF0000=rainews24
622B_1D7_270F_FFFF0000=raistoria
565A_DD_270F_FFFF0000=rai1
71AD_1FF_270F_FFFF0000=recordinternacional
42DF_AB_270F_FFFF0000=ric
6228_1D7_270F_FFFF0000=rtk1
94D7_14B_270F_FFFF0000=rtlcrimehd
CF6E_213_270F_FFFF0000=rtlhd
4E9C_E7_270F_FFFF0000=rtlplus-mathecraki
622C_1D7_270F_FFFF0000=rtssat
7D6A_141_270F_FFFF0000=sat1goldhd
CF6F_213_270F_FFFF0000=sat1hd
198_4_85_FFFF0000=sky1
93_C_85_FFFF0000=sky1hd
197_4_85_FFFF0000=skycinemafamily
204_2_85_FFFF0000=skycinemanostalgie
DD_3_85_FFFF0000=skysport1
14D_1_85_FFFF0000=skysport10
FD_2_85_FFFF0000=skysport11
81_6_85_FFFF0000=skysport1hd
DE_3_85_FFFF0000=skysport2
72_D_85_FFFF0000=skysport2hd
107_2_85_FFFF0000=skysport3
10C_6_85_FFFF0000=skysport3hd
111_3_85_FFFF0000=skysport4
116_D_85_FFFF0000=skysport4hd
11B_3_85_FFFF0000=skysport5
120_C_85_FFFF0000=skysport5hd
125_3_85_FFFF0000=skysport6
12F_3_85_FFFF0000=skysport7
139_1_85_FFFF0000=skysport8
143_1_85_FFFF0000=skysport9
DF_4_85_FFFF0000=skysportbundesliga1
FC_2_85_FFFF0000=skysportbundesliga10

missing picons plz add them THX :)
A&E HD
CMC
HRT HR1
JSTV Radio Japan
Klan Kosova
Kohavision TV
Kral FM Avrupa
Pink Radio
Radio 21
radio B2
Radio ZET
RCK TV
Slow Turk
Telebom / Tele Dom
Turk Muzigi
WDRCosmo

**Comment by charlesduco** [comment]
I added a commit with the service references and some additional logos.

Next time, please provide service names and service references in the right format:
https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

**Comment by pommesfrites** [comment]
update on 1st post

**Comment by mocram** [comment]
Please create a new issue with your updates, and use backtiks.
