### ISSUE TITLE
Logos Insight HD and Insight UHD

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#173]
I found a svg-logo for Insight. (And mcfly822 made them awesome).
[insight.mcfly822.zip](https://github.com/picons/picons-source/files/1463813/insight.mcfly822.zip)

Source: https://bilder.fernsehserien.de/logos/svg/819.svg
If they are okay can some replace the existing png's?

------------------------------------
For Insight UHD there was no logo.

[Insight UHD 2017-11-07.zip](https://github.com/picons/picons-source/files/1451469/Insight.UHD.2017-11-07.zip)
(Could not find a svg unfortunately).

**snp-index**
```
insighttvuhd=insightuhd
insighttvuhdspain=insightuhd
insightuhdrussia=insightuhd
```

**srp-index**
```
7D0_1_1_C00000=insightuhd
7D1_1_1_C00000=insightuhd
7D5_1_1_C00000=insightuhd
```
`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
Got this error opening with GIMP
```
Opening 'C:\Users\User\Downloads\!Satellite\! ! ! Picon\! Ocram\Insight.HD.2017-11-07\insight.light.svg' failed: Could not open 'C:\Users\User\Downloads\!Satellite\! ! ! Picon\! Ocram\Insight.HD.2017-11-07\insight.light.svg' for reading: Error domain 1 code 9 on line 97 column 31 of file:///C:/Users/User/Downloads/!Satellite/!%20!%20!%20Picon/!%20Ocram/Insight.HD.2017-11-07: Input is not proper UTF-8, indicate encoding !
Bytes: 0xFF 0x27 0x20 0x69
```

**Comment by Lexzie** [comment]
I had tried to save the files (with Inkscape) as 'optimized SVG' but that failed. So I saved them as 'Plain SVG'.

If I open the original file from the source with GIMP and that file does not give an error.
But when I made the letters 'INSIGHT' white and saved as a normal Inkscape file, that file also gives an error in GIMP.
Maybe someone else can edit the original file to make a light variant and get rid of all the unnecessary content of the original svg-file?

-----------------

The logos for Insight UHD are okay and can be added with the links?

**Comment by mcfly822** [comment]
I will repair the svgs today morning.

**Comment by mcfly822** [comment]
Here are the logos, optimized svg.
I made the ```light``` version also, some modification, not only on the word "insight" but on the big "IN".
Tested with GIMP & rsvg (with this repo's build script).
[insight.mcfly822.zip](https://github.com/picons/picons-source/files/1452996/insight.mcfly822.zip)

**Comment by Lexzie** [comment]
Great work, thanks.

I updated the first comment, could someone update the source?

**Comment by Lexzie** [comment]
Thanks!
