### ISSUE TITLE
BeIN Movistar+ (spanish package)

### ISSUE THREAD

**Issue by Jglez3** [picons/picons-source#173]
Hello.

BeIN have a new rebranded image since January 1st 2017.

Logos to rebuild: BeIN Sports, BeIN LaLiga (plus BeIN LaLiga 1,2,3,4,5,6,7,8), BeIN Max (1,2,3,4,5,6,7,8)

All channels now use SD logo version, so no need to rebuild HD logos. Because of that, these srp equivalences can be replaced.

```
78B4_3EC_1_C00000=beinsports
7861_41A_1_C00000=beinsportsmax1
7864_41A_1_C00000=beinsportsmax2
750E_420_1_C00000=beinsportsmax3
```

Source: 
http://logos.wikia.com/wiki/BeIN_Sports_(Spain)
http://logos.wikia.com/wiki/BeIN_Sports_La_Liga
http://www1.movistarplus.es/canal/Bein+Max1/BEMAX1

Thanks!!

**Comment by charlesduco** [comment]
I added the new logos and service references, but for BeIN LaLiga I have no idea what the individual logos should look like. For now they have all the same logo without the channel number.

**Comment by Jglez3** [comment]
Thanks @charlesduco 

Seems all BeIN LaLiga channels are using the same logo at this moment.

**Comment by mocram** [comment]
Create new issue if it's not solved
