### ISSUE TITLE
6 picons missing on Astra 19.2°E ?

### ISSUE THREAD

**Issue by Arkoth79** [picons/picons-source#174]
Hello,

I download the "snp-full.100x60-86x46.**light.on.black**_2017-01-04--19-44-51.hardlink.tar.xz" and I put the "*.png" on my usb key in /media/usb/picon
After restarting my DM800HDSE (Openpli 4), all picons are ok and very good skin. Thank you !

But there is 6 picons that did'nt work:

`1F45_42E_1_C00000=franceinfo`
`189D_3F4_1_C00000=beinsport1hd`
`189E_3F4_1_C00000=beinsport2hd`
`18A0_3F4_1_C00000=beinsports3hdfrance`
`265D_460_1_C00000=france3parisiledefrance`
`2654_460_1_C00000=viastella`

my bouquet (channels names) is made with dreamset - internet with king of sat website: 
[http://fr.kingofsat.fr/pos-19.2E_fra.php](http://fr.kingofsat.fr/pos-19.2E_fra.php)

Maybe I forget to do something ?
Please help me to have this 6 picons to work ;)

Thank you for your help

**Comment by charlesduco** [comment]
I added the following service name entries to snp-index, may this will fix your problem:
```
franceinfo=franceinfo
beinsport1hd=beinsports1
beinsport2hd=beinsports2
beinsports3hdfrance=beinsports3
france3parisiledefrance=france3
viastella=france3
```
More info on how service name picons work: https://github.com/picons/picons-source#snp---service-name-picons

**Comment by Arkoth79** [comment]
Hello,

Ok I understand now the idea for snp picons with the name in the "snp-index" file, it will create the png file with an other png file. 
With this syntax: the new file before the "=", the original file after the "=" ?

It's ok for me for the 5 last channel name you write, it will create in the next release/build (maybe tomorrow ?) the 5 png file, that's ok, I understand this.

Just, I don't understand your first line ? 
`franceinfo=franceinfo`
For "franceinfo", there is a file "franceinfortv.png" in the "tar.xz"
I think it will be:
`franceinfo=franceinfortv`
no ?

Thank you for your help charlesduco

**Comment by charlesduco** [comment]
No, you don't understand yet.
The part before the "=" sign is a simplified name derived from the channel names in your OpenPli channel list.
For example:
`France 24 (en Francais)` in your OpenPli Channel list becomes `france24enfrancais`

The part after the "=" sign is the logo name without suffixes from our [build source directory](https://github.com/picons/picons-source/tree/master/build-source/logos) with high quality logos, not the generated png files in the tar.xz!
In the build source directory, you find the high quality logo `france24.default.svg`, that becomes `france24`

So, the snp entry for `France 24 (en Francais)` becomes:
 `france24enfrancais=france24`

**Comment by Arkoth79** [comment]
Ok, thanks for the explanations.

Have a good day ;)

**Comment by AbuBaniaz** [comment]
You do not have to have the "hd" at the end. The picon code checks for the service reference picon, then the snp name. If last last two letters are "hd" and there isn't a matching SNpicon, it will take one without the "hd".

The picon code is smart enough to deal with it on its own. The only exception is the "hd" is not at the end of name.

https://github.com/OpenViX/enigma2/blob/master/lib/python/Components/Renderer/Picon.py#L92
