### ISSUE TITLE
Fransat - existing logos but missing reference

### ISSUE THREAD

**Issue by pexner** [picons/picons-source#176]
191:4FB0:55F:DDE0000=tf1
12D:4F4C:55F:DDE0000=france2
193:4FB0:55F:DDE0000=m6
1A5:4FB0:55F:DDE0000=w9
BB8:4E84:55F:DDE0000=hd1
BC6:4E84:55F:DDE0000=cstar
1A6:4FB0:55F:DDE0000=6ter
BC5:4E84:55F:DDE0000=c8
1A8:4FB0:55F:DDE0000=nt1
BBB:4E84:55F:DDE0000=numero23
BBD:4E84:55F:DDE0000=cherie25
12E:4F4C:55F:DDE0000=france3
12F:4F4C:55F:DDE0000=france4
1A3:4FB0:55F:DDE0000=france5
BC3:4E84:55F:DDE0000=cnewshd
130:4F4C:55F:DDE0000=franceo
194:4FB0:55F:DDE0000=artehd
1A7:4FB0:55F:DDE0000=tmc
1A1:4FB0:55F:DDE0000=nrj12
131:4F4C:55F:DDE0000=franceinfo
133:4F4C:55F:DDE0000=lci
1A9:4FB0:55F:DDE0000=lcp
BC4:4E84:55F:DDE0000=bfmtv
BC7:4E84:55F:DDE0000=gulli
BB9:4E84:55F:DDE0000=lequipetv
BBC:4E84:55F:DDE0000=rmcdecouverte
B85:51A4:55F:DDE0000=kto
B89:51A4:55F:DDE0000=tv8montblanc
A36:5078:55F:DDE0000=bfmbusiness
BBC:4E84:55F:DDE0000=rmcdecouvertehd
a35:5078:55f:dde0000=qvc
259:5078:55f:dde0000=tv5mondefbs
19a:4fb0:55f:dde0000=boing
19b:4fb0:55f:dde0000=boomerang
19c:4fb0:55f:dde0000=toonami
bbe:4e84:55f:dde0000=canalj
bbf:4e84:55f:dde0000tiji

### STILL MISSING IN ACTION
# Fransat Info HD	142:4f4c:55f:dde0000	( https://dl.dropboxusercontent.com/u/23135995/fransat_new.svg )
# D!CITV	1F5:5014:55F:DDE0000	( https://fr.wikipedia.org/wiki/D!CI_TV )
# GRAND LILLE	BA2:51A4:55F:DDE0000 	( https://fr.wikipedia.org/wiki/Grand_Lille_TV )
# VOSGES TV	b83:51a4:55f:dde0000=vosges 	( http://www.lumieremonde.org/wp-content/uploads/2013/10//logo-vosges_television_BLEU.jpg )

**Comment by pexner** [comment]
Sorry for the formatting above. Strangely everything is HUGE !!! :)

**Comment by mocram** [comment]
https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

**Comment by pexner** [comment]
Yeah. I read that. What's wrong in my issue?
