### ISSUE TITLE
What's wrong with my issue #176 ?

### ISSUE THREAD

**Issue by pexner** [picons/picons-source#177]
What's wrong with my issue?
https://github.com/picons/picons-source/issues/176

**Comment by mocram** [comment]
After reading the rules, you also have to apply them. Just telling us that you read it and apologizing that it's wrong won't help...

What's up with al the `:::::::`? Did you misread the parts about, uppercase, the sample of how the serviceref is written, etc.

Do you really think that if we would copy/paste that in, it would work?
