### ISSUE TITLE
Joyne logo

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#177]
Please add this logo and links:
[joyne 20171109.zip](https://github.com/picons/picons-source/files/1459572/joyne.20171109.zip)

Sources:
https://pbs.twimg.com/media/DKouv1IXoAEfunh.jpg (logo)
https://www.joyne.nl/site/pages/design/graphics/logo_pages.png (for the right color)

**sno-index**
```
joynetest=joyne
```
**srp-index**
```
1B0_C40E_9E_5A0000=joyne
```
`donkey monkey got issued'

**Comment by Lexzie** [comment]
I se you transformed it to an SVG? Great work! Thanks!

**Comment by charlesduco** [comment]
No, I downloaded the pdf folder from https://veldmeyer.nl/joyne/ and edited the vector logo in Inkscape.

**Comment by Lexzie** [comment]
Even so great job.
I didn't know about that site and don't know (yet) how to get a vector logo out of a pdf.
