### ISSUE TITLE
build server not working 

### ISSUE THREAD

**Issue by leec32** [picons/picons-source#178]
is the build server not working, latest is 04/11

**Comment by mocram** [comment]
Probably the line endings commit have confused git on the server, will have to force it manually

**Comment by leec32** [comment]
hi
any update on this please, its still showing 04/11
thanks

**Comment by mocram** [comment]
Relax, I'll get too it 😀

**Comment by leec32** [comment]
haha thanks

**Comment by mocram** [comment]
It is fixed, can you wait until tonight/tomorrow morning or do you want a release today?

**Comment by leec32** [comment]
tonight/tomorrow is fine

thanks
