### ISSUE TITLE
Wrong links for dutch Sky Radio

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#179]
For the terrestrial version.

It should be:
**snp-index**
```
skyradio101fm=skyradio-deswephosp
```

The link for the terrestrial channel in srp-index is okay, but the one for the Joyne package (9°E) not.
Plus links for three cable providers are missing.

It should be:
**srp-index**
```
1B8_C40E_9E_5A0000=skyradio-deswephosp
C3A_67_8C9_FFFF0000=skyradio-deswephosp
3F0_1_10EF_FFFF0000=skyradio-deswephosp
21B1_6_F3C_FFFF0000=skyradio-deswephosp
```
`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
If it shoukd be something else, it is something now.

As mentioned before a change involves a "from" and a "to".

Yes we can just add to the top and that will be used. I don't want the SNP index to become like the SRP index where there are/were duplicates and dead entries.

Thank you for understanding.

**Comment by AbuBaniaz** [comment]
https://github.com/picons/picons-source/commit/f05260178374df39dca77b41704152b4040f19cb

**Comment by Lexzie** [comment]
For future reference it should have been like this?

### Please delete:
**snp-index**
```
skyradio101fm=skyradio-phibruspel
```
**srp-index**
```
1B8_C40E_9E_5A0000=skyradio-phibruspel
```

### And add:

**snp-index**
```
skyradio101fm=skyradio-deswephosp
```

**srp-index**
```
1B8_C40E_9E_5A0000=skyradio-deswephosp
C3A_67_8C9_FFFF0000=skyradio-deswephosp
3F0_1_10EF_FFFF0000=skyradio-deswephosp
21B1_6_F3C_FFFF0000=skyradio-deswephosp
```
`donkey monkey got issued`
