### ISSUE TITLE
SVG Cleaner breaks svg rendering with librsvg

### ISSUE THREAD

**Issue by charlesduco** [picons/picons-source#18]
I had to revert https://github.com/picons/picons-source/commit/65cc9bbdad4423e431c96d8e626e83b1e88a4cf0 cause it breaks svg rendering with librsvg on linux for most of the picons. After the revert, all picons are back okay.
All downloads on https://picons.xyz/downloads are affected as well as my Linux Mint machine. 

It's most likely a problem with librsvg, so many, if not all Debian-based Linux machines will be affected.

**Comment by mocram** [comment]
ok, thanks, I thought I checked it, but apparently not good enough.
