### ISSUE TITLE
CNN Türk

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#181]
The logo cnnturkradio.default.svg is not the right one.
Also a light version is missing.
The logo for CNN Türk Radio is this one:
![cnnturkradyo925 default](https://user-images.githubusercontent.com/14023349/32700303-371fe1f8-c7c3-11e7-8505-d00f52ce8e44.png)
Source: http://www.radyocular.com/cnn-turk-radyo-yayin-agini-genisletiyor.html
Official website: https://www.cnnturk.com/servisler/radyo/

If anyone can find/make a better logo, please be my guest. For now this png isn't acceptable I think.

------

For CNN Türk please accept these logos and links:
[CNN Turk.zip](https://github.com/picons/picons-source/files/1464847/CNN.Turk.zip)

**snp-index**
```
cnnturk=cnnturk
```
**srp-index**
```
44C_1FA4_9C_5A0000=cnnturk
6A9_C4E0_7E_460000=cnnturk
```
`donkey monkey got issued`

**Comment by mcfly822** [comment]
If no one do it until tomorrow, I will make it in SVG.

**Comment by mocram** [comment]
Logos are in, now the correct links

**Comment by Lexzie** [comment]
> Logos are in, now the correct links

No not all logos are in, I only see the new logo of CNN Türk Radio in picons-source/build-source/logos/ not the ones for CNN Türk (the TV station) as requested in the first comment (below the line).
Here is the logo for CNN Türk again:
[CNN Turk.zip](https://github.com/picons/picons-source/files/1464847/CNN.Turk.zip)
Please upload these logos as well.

### Please delete these links:
**snp-index**
```
565F_DD_270F_FFFF0000=cnnturkradio
```
**srp-index**
```
565F_DD_270F_FFFF0000=cnnturkradio
565F_DD_270F_FFFF0000=cnnturkradio
4A0_36_DE_FFFF0000=cnnturkradio
```
### Please add these links:
**snp-index**
```
cnnturk=cnnturk
565F_DD_270F_FFFF0000=cnnturkradyo
```
**srp-index**
```
44C_1FA4_9C_5A0000=cnnturk
6A9_C4E0_7E_460000=cnnturk
565F_DD_270F_FFFF0000=cnnturkradio
565F_DD_270F_FFFF0000=cnnturkradio
4A0_36_DE_FFFF0000=cnnturkradio
```

**Comment by mcfly822** [comment]
I edited & added (PR #185 ) the missing logos.
Please someone (maybe @AbuBaniaz ? 😄 ) modify the srp and snp-indexes.

**Comment by Lexzie** [comment]
Better the logos this way, great work!
Can someone please also have a look at the other still open Issues?

**Comment by Lexzie** [comment]
@mcfly822 Yeah, I still would like to learn that too. Finding logos and editing them already takes a lot of time and off course there is also still the "normal" life ;-)
Take your time, but I thought no-one had noticed it, since one issue is already open for 10 days.

**Comment by Lexzie** [comment]
Thanks.
Sorry for the typo but I had not the intention to change the logo name (although that is technically correct), because of existing links.
