### ISSUE TITLE
missing Logos Unitymedia

### ISSUE THREAD

**Issue by pommesfrites** [picons/picons-source#185]
A&E HD
CMC
HRT HR1
JSTV Radio Japan
Klan Kosova
Kohavision TV
Kral FM Avrupa
Pink Radio
QVC Plus HD
Radio 21
radio B2
Radio Dukagjini
Radio ZET
RCK TV 
Slow Turk
Telebom / Tele Dom
Turk Muzigi
WDRCosmo

**Comment by charlesduco** [comment]
For the following channels I didn't find a particular logo. But you can use a general logo of the broadcaster:
```
 Pink Radio = rtvpink
 Turk Muzigi = stingraymusic
```
