### ISSUE TITLE
Cosmo - WDR Funkhaus Europa rebrand

### ISSUE THREAD

**Issue by badkarmaboy** [picons/picons-source#188]
Hello,

since January 1st the service "WDR Funkhaus Europa" changed it's name and logo to "Cosmo" (Astra 19.2E), as written [here](http://www1.wdr.de/radio/funkhauseuropa/ueber-uns/funkhaus-europa-wird-cosmo-100.html)

Could you please add / update the logo with the new one found [here](http://www1.wdr.de/radio/funkhauseuropa/ueber-uns/cosmo-logo-102~_v-gseapremiumxl.jpg)

Thank you very much!

**Comment by pexner** [comment]
PS: There's also a SVG version of the logo on Wikimedia:
https://upload.wikimedia.org/wikipedia/commons/a/a4/COSMO_Radio_Logo_2017.svg
