### ISSUE TITLE
.deb packages and install-destination directory

### ISSUE THREAD

**Issue by pexner** [picons/picons-source#189]
Hi,
I'm absolutely no coder, but I have a question/ 2 requests.

1)
Would it be possible to add into the backgrounds.conf a destination directory into which the picons will be installed when creating an isnstall package?
Example:
```100x60;86x46;light;transparent;/dev/sdb1/picons```

2)
Would it be possible to create .deb packages?

PS: how is it possible to prevent building packages at all?

Tanks in advance.

**Comment by mocram** [comment]
1) No
2) No
PS) Don't run the script

The reality however is, you can fork and modify your fork until all of your features work.
