### ISSUE TITLE
Who can make logos with regional versions for RCF

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#190]
For RCF there are 24 different regional versions and one national version on Eutelsat 5 West A at 5.0°W, the logos are like these examples, but each with another text.
![afbeelding](https://user-images.githubusercontent.com/14023349/32925357-d18f46da-cb41-11e7-9c19-7ddff215bd58.png) ![afbeelding](https://user-images.githubusercontent.com/14023349/32925559-c9ee01fe-cb42-11e7-8ecd-8a0ed60a2cb7.png) ![afbeelding](https://user-images.githubusercontent.com/14023349/32925696-8fbdd7ba-cb43-11e7-8a52-74af5acfc120.png) ![afbeelding](https://user-images.githubusercontent.com/14023349/32925715-a231a034-cb43-11e7-9caf-61729be682e0.png)

I cannot find them for all regional versions, certainly not of enough quality but maybe someone can make them, or give me a start on how to.

In this zip-file a few of the best quality I could find:
[RCF.zip](https://github.com/picons/picons-source/files/1480841/RCF.zip)

One can be without extra text (the national version) and is simply called `rcf.default.png`.
The text that must be below the RCF logo and corresponding logo name:
```
text             logo filename

Allier           rcfallier.default.png
Alpes-Provence   rcfalpesprovence.default.png
Ardèche          rcfardeche.default.png
Aube Haute-Marne rcfaubehautemarne.default.png
en Berry         rcfenberry.default.png
Besançon         rcfbesancon.default.png
Bordeaux         rcfbordeaux.default.png
en Bourgogne     rcfenbourgogne.default.png
Corrèze          rcfcorreze.default.png
Drôme            rcfdrome.default.png
Haute-Loire      rcfhauteloire.default.png
Haute-Normandie  rcfhautenormandie.default.png
Haute-Savoie     rcfhautesavoie.default.png
Isère            rcfisere.default.png
Loir-et-Cher     rcfloiretcher.default.png
Lyon             rcflyon.default.png
Marne et Meuse   rcfmarneetmeuse.default.png
Pays d'Aude      rcfpaysdaude.default.png
Pays de l'Ain    rcfpaysdelain.default.png
Poitou           rcfpoitou.default.png
Reims-Ardennes   rcfreimsardennes.default.png
Savoie           rcfsavoie.default.png
Touraine         rcftouraine.default.png
Vaucluse         rcfvaucluse.default.png
```

**snp-index**
```
rcf=rcf
rcfnational=rcf
rcf03allier=rcfallier
rcf05hautesalpes=rcfalpesprovence
rcf07vivarais=rcfardeche
rcf10aube=rcfaubehautemarne
rcf25besancon=rcfbesancon
rcf33bordeaux=rcfbordeaux
rcfcorreze=rcfcorreze
rcf26=rcfdrome
rcf18berry=rcfenberry
rcf21=rcfenbourgogne
rcf43lepuyenvelay=rcfhauteloire
rcf76=rcfhautenormandie
rcf74hautesavoie=rcfhautesavoie
sectdf2rcf38=rcfisere
rcf41=rcfloiretcher
rcf69lyonfourviere=rcflyon
rcf51marnemeuse=rcfmarneetmeuse
rcf11paysdaude=rcfpaysdaude
rcf01paysdelain=rcfpaysdelain
rcf86poitou=rcfpoitou
rcf51=rcfreimsardennes
rcf73savoie=rcfsavoie
rcf37=rcftouraine
rcf84lumieres=rcfvaucluse
```

**srp-index**
```
49F_526C_55E_DDE0000=rcf
BA0_51A4_55F_DDE0000=rcf
4A8_526C_55E_DDE0000=rcfallier
4AA_526C_55E_DDE0000=rcfalpesprovence
496_526C_55E_DDE0000=rcfardeche
4AC_526C_55E_DDE0000=rcfaubehautemarne
4AB_526C_55E_DDE0000=rcfbesancon
4A9_526C_55E_DDE0000=rcfbordeaux
499_526C_55E_DDE0000=rcfcorreze
49A_526C_55E_DDE0000=rcfdrome
498_526C_55E_DDE0000=rcfenberry
4A3_526C_55E_DDE0000=rcfenbourgogne
4A1_526C_55E_DDE0000=rcfhauteloire
4A6_526C_55E_DDE0000=rcfhautenormandie
4A7_526C_55E_DDE0000=rcfhautesavoie
258_2711_90_DDE0000=rcfisere
49B_526C_55E_DDE0000=rcfloiretcher
4A0_526C_55E_DDE0000=rcflyon
4AE_526C_55E_DDE0000=rcfmarneetmeuse
497_526C_55E_DDE0000=rcfpaysdaude
495_526C_55E_DDE0000=rcfpaysdelain
4AD_526C_55E_DDE0000=rcfpoitou
4A5_526C_55E_DDE0000=rcfreimsardennes
49C_526C_55E_DDE0000=rcfsavoie
4A4_526C_55E_DDE0000=rcftouraine
4A2_526C_55E_DDE0000=rcfvaucluse
```
`donkey monkey got issued`

**Comment by mocram** [comment]
Pays de l'Ain    rcfpaysdelai.default.png

Spelling mistake. Isn't a generic rcf good enough?

**Comment by Lexzie** [comment]
> Pays de l'Ain rcfpaysdelai.default.png
> 
> Spelling mistake.

Yes, otherwise it would mean "land of the garlic".

For me it's enough, but I thought it was not allowed for so many stations. Otherwise I have also a bunch of Stingray music stations that could do with one generic logo. I was told that that would not be accepted.

**Comment by mcfly822** [comment]
I also think that the generic RCF logo is good enough for all these stations.
I made it in svg, attached.
[rcf.default.zip](https://github.com/picons/picons-source/files/1484906/rcf.default.zip)

**Comment by Lexzie** [comment]
Great! If someone can upload it to the source?

**Comment by mocram** [comment]
rcfpaysdelai     n      .default.png
^^^^^

Who told you a generic logo is not allowed?

**Comment by charlesduco** [comment]
The font used for the regional variants is Brandon Grotesque Bold, you can download the font at https://github.com/cohort/cohortstudio.com/blob/master/font/brandon-grotesque-bold/brandon_bld.ttf

Feel free to edit this Inkscape SVG for all variants: https://gist.github.com/charlesduco/f96dbf8d61e4080c935b1f9d767f0601

To export the variants, convert the text object to paths and save as optimized svg.

**Comment by Lexzie** [comment]
Is this the same font?
![afbeelding](https://user-images.githubusercontent.com/14023349/32985039-74c23162-ccb1-11e7-9544-69ec081cacb3.png) 
![afbeelding](https://user-images.githubusercontent.com/14023349/32985040-7b850d94-ccb1-11e7-8a98-5db7e734668b.png)

> rcfpaysdelai n .default.png
> ^^^^^

Already corrected in first post.

> Who told you a generic logo is not allowed?

I'd 

> rather not tell, not my style and does not add to helping eachother.

**Comment by AbuBaniaz** [comment]
>For me it's enough, but I thought it was not allowed for so many stations. Otherwise I have also a bunch of Stingray music stations that could do with one generic logo. I was told that that would not be accepted.

The stations were all different names.  Wasn't as if it was `stingray berlin`, `stingray hamburg` or `stingray london`  in which case one picon would have done.

**Comment by Lexzie** [comment]
Okay that's a difference. I'm trying to see if I can add the texts myself like charlesduco said.

**Comment by Lexzie** [comment]
Already done a few ones:
[RCF (incomplete).zip](https://github.com/picons/picons-source/files/1485168/RCF.incomplete.zip)
So W,I,P.

@charlesduco : Is this what you meant?

**Comment by Lexzie** [comment]
Et voilá:
[RCF (all).zip](https://github.com/picons/picons-source/files/1486120/RCF.all.zip)


**Add to snp-index**
```
rcf=rcf
rcfnational=rcf
rcf03allier=rcfallier
rcf05hautesalpes=rcfalpesprovence
rcf07vivarais=rcfardeche
rcf10aube=rcfaubehautemarne
rcf25besancon=rcfbesancon
rcf33bordeaux=rcfbordeaux
rcfcorreze=rcfcorreze
rcf26=rcfdrome
rcf18berry=rcfenberry
rcf21=rcfenbourgogne
rcf43lepuyenvelay=rcfhauteloire
rcf76=rcfhautenormandie
rcf74hautesavoie=rcfhautesavoie
sectdf2rcf38=rcfisere
rcf41=rcfloiretcher
rcf69lyonfourviere=rcflyon
rcf51marnemeuse=rcfmarneetmeuse
rcf11paysdaude=rcfpaysdaude
rcf01paysdelain=rcfpaysdelain
rcf86poitou=rcfpoitou
rcf51=rcfreimsardennes
rcf73savoie=rcfsavoie
rcf37=rcftouraine
rcf84lumieres=rcfvaucluse
```

**Add to srp-index**
```
49F_526C_55E_DDE0000=rcf
BA0_51A4_55F_DDE0000=rcf
4A8_526C_55E_DDE0000=rcfallier
4AA_526C_55E_DDE0000=rcfalpesprovence
496_526C_55E_DDE0000=rcfardeche
4AC_526C_55E_DDE0000=rcfaubehautemarne
4AB_526C_55E_DDE0000=rcfbesancon
4A9_526C_55E_DDE0000=rcfbordeaux
499_526C_55E_DDE0000=rcfcorreze
49A_526C_55E_DDE0000=rcfdrome
498_526C_55E_DDE0000=rcfenberry
4A3_526C_55E_DDE0000=rcfenbourgogne
4A1_526C_55E_DDE0000=rcfhauteloire
4A6_526C_55E_DDE0000=rcfhautenormandie
4A7_526C_55E_DDE0000=rcfhautesavoie
258_2711_90_DDE0000=rcfisere
49B_526C_55E_DDE0000=rcfloiretcher
4A0_526C_55E_DDE0000=rcflyon
4AE_526C_55E_DDE0000=rcfmarneetmeuse
497_526C_55E_DDE0000=rcfpaysdaude
495_526C_55E_DDE0000=rcfpaysdelain
4AD_526C_55E_DDE0000=rcfpoitou
4A5_526C_55E_DDE0000=rcfreimsardennes
49C_526C_55E_DDE0000=rcfsavoie
4A4_526C_55E_DDE0000=rcftouraine
4A2_526C_55E_DDE0000=rcfvaucluse
```
`donkey monkey got issued`

**Comment by charlesduco** [comment]
Logo `rcfenberry.default.svg` has a wrong font.

**Comment by Lexzie** [comment]
Damn! Thought I checked them all... :$
I will correct it later today!

**Comment by Lexzie** [comment]
All I could see it has the right font (Brandon Grotesque Bold) but the text object was not converted to paths. Am I right?
Complete zip again:
[RCF (all) 20171120.zip](https://github.com/picons/picons-source/files/1488072/RCF.all.20171120.zip)

**Comment by charlesduco** [comment]
Logo for `rcfmarneetmeuse` is missing.

**Comment by Lexzie** [comment]
Okay, comming up later today.

**Comment by Lexzie** [comment]
Thanks!
