### ISSUE TITLE
Missing & changed hungarian logos

### ISSUE THREAD

**Issue by mcfly822** [picons/picons-source#190]
Missing:
Digi Sport 1 HD: http://www.lyngsat-logo.com/tvchannel/hu/Digi-Sport-1-HD-Hungary.html
Digi Sport 2 HD: http://www.lyngsat-logo.com/tvchannel/hu/Digi-Sport-2-HD-Hungary.html
(The original Digi Sport logos incuding the HD logos are on the channel's website: http://www.digisport.hu/images/logo_digisport.zip )
Izaura TV: http://www.lyngsat-logo.com/tvchannel/hu/Izaura-TV.html
Zenebutik: http://www.lyngsat-logo.com/tvchannel/hu/Zenebutik.html
Spíler TV: http://www.lyngsat-logo.com/tvchannel/hu/Spiler-TV.html
RTL Spike: http://www.lyngsat-logo.com/tvchannel/hu/RTL-Spike.html
PAX TV: https://scontent-frt3-1.xx.fbcdn.net/v/t31.0-8/337244_287864964653370_1418784285_o.jpg?oh=b65555bfeb9d8b18356d3818d55c0b79&oe=591DCB3E (only the right part, the text "PAX")
Prime: https://upload.wikimedia.org/wikipedia/commons/6/69/NewPRIMElogo.jpg
Mozi+: http://www.lyngsat-logo.com/tvchannel/hu/Mozi--.html
IDX HD: http://www.lyngsat-logo.com/tvchannel/us/Investigation-Discovery-Xtra-HD.html
RTL Klub HD: http://www.lyngsat-logo.com/tvchannel/hu/RTL-Klub-HD.html
C8: http://www.lyngsat-logo.com/tvchannel/hu/C8.html

Changed:
ECHO TV: http://oroszbal.hu/wp-content/uploads/2014/02/ECHO_TV.png (sorry for the bad resolution, I cannot find elsewhere. The logo is like on the channel's website: http://www.echotv.hu/ )
Discovery Channel Hungary: https://upload.wikimedia.org/wikipedia/en/thumb/4/46/Discovery_Channel_International.svg/1280px-Discovery_Channel_International.svg.png
Film Café: http://www.lyngsat-logo.com/tvchannel/hu/Film-Cafe-.html
M2: http://www.lyngsat-logo.com/tvchannel/hu/M2.html
M2 HD: http://www.lyngsat-logo.com/tvchannel/hu/M2-HD.html

And another problem, the changes of this commit:
https://github.com/picons/picons-source/commit/c9f4696880f43c98b531b888cd07b77087b6e7b2
are missing from snp index. The srp index is good.

**Comment by duduama** [comment]
some added

**Comment by duduama** [comment]
added rtlspike,zenebutik

**Comment by charlesduco** [comment]
I think all requested logos are added the the repository with the last commit.

Could you provide the missing service references and service names for srp-index and snp-index, cause I have no access to 0.8W or hungarian cable operators.

**Comment by mcfly822** [comment]
Great, thank you! :) Only Digi Sport 1 & 2 HD are missing now.
I'll provide the service names and references soon, as I have time to do it.

**Comment by charlesduco** [comment]
Logos should be okay now.

**Comment by mcfly822** [comment]
Very good, thanks aain!
As I did the srp&snp index, i will close this issue.

**Comment by mcfly822** [comment]
snp-index new entries:

galaxy=galaxy
humorplus=humorplus
kiwitv=kiwitv
m4sport=m4sport
m4sporthd=m4sport
m4hd=m4sport
m5hd=m5
m5=m5
izauratv=izauratv
moziplus=moziplus
mplus=moziplus
paxtv=paxtv
prime=prime
spikehungary=rtlspike
rtlspike=rtlspike
spilertv=spilertv
zenebutik=zenebutik
idextraeuropehd=investigationdiscoveryxtrahd
idextrahd=investigationdiscoveryxtrahd
investigationdiscoveryxtrahd=investigationdiscoveryxtrahd
digisport1hd=digisport1hd
digisport1hdhu=digisport1hd
digisport1hdro=digisport1hd
digisport2hd=digisport2hd
digisport2hdhu=digisport2hd
digisport2hdro=digisport2hd
rtlklubhd=rtlklubhd

Is it right, or should I modify this? (Sorry for any mistake, I am a rookie :) )

**Comment by mcfly822** [comment]
remaining index entries:

snp-index

75FB_2BE_600_E080000=filmplus-velirajeha
79F3_2C8_600_E080000=filmplus2-velirajeha
13C_3_22C7_EEEE0000=c8-slasluspor
78B7_2C5_600_E080000=discoverychannel
discoveryhu=discoverychannel

srp-index

FB4_D_1_E082E2F=digisport1hd
7DC_AF2_BB_E080000=digisport1hd
FE6_D_1_E082E2F=digisport1hd
7DD_AF2_BB_E080000=digisport2hd
FDC_D_1_E082E2F=digisport2hd
FF0_D_1_E082E2F=digisport2hd
7728_2C1_600_E080000=rtlklubhd
A8C_2_5E_E08B00F=investigationdiscoveryxtrahd
A8D_2_5E_E08B00F=investigationdiscoveryxtrahd
A8E_2_5E_E08B00F=investigationdiscoveryxtrahd
75FB_2BE_600_E080000=filmplus-velirajeha
79F3_2C8_600_E080000=filmplus2-velirajeha
13C_3_22C7_EEEE0000=c8-slasluspor
78B7_2C5_600_E080000=discoverychannel
A0A_5_1_E083113=discoverychannel

If you also find everything good, I will close this issue.

**Comment by charlesduco** [comment]
Please provide the entries for snp-index and srp-index in the right format as described in the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md)

**Comment by pexner** [comment]
Like this?

Edited:
remaining index entries:

snp-index

```75FB_2BE_600_E080000=filmplus-velirajeha
79F3_2C8_600_E080000=filmplus2-velirajeha
13C_3_22C7_EEEE0000=c8-slasluspor
78B7_2C5_600_E080000=discoverychannel
discoveryhu=discoverychannel```

srp-index

```FB4_D_1_E082E2F=digisport1hd
7DC_AF2_BB_E080000=digisport1hd
FE6_D_1_E082E2F=digisport1hd
7DD_AF2_BB_E080000=digisport2hd
FDC_D_1_E082E2F=digisport2hd
FF0_D_1_E082E2F=digisport2hd
7728_2C1_600_E080000=rtlklubhd
A8C_2_5E_E08B00F=investigationdiscoveryxtrahd
A8D_2_5E_E08B00F=investigationdiscoveryxtrahd
A8E_2_5E_E08B00F=investigationdiscoveryxtrahd
75FB_2BE_600_E080000=filmplus-velirajeha
79F3_2C8_600_E080000=filmplus2-velirajeha
13C_3_22C7_EEEE0000=c8-slasluspor
78B7_2C5_600_E080000=discoverychannel
A0A_5_1_E083113=discoverychannel```

**Comment by mcfly822** [comment]
Last try:

snp-index update:

'''chili=chilitv
digisport4=digisport4
digisport5=digisport5
galaxy=galaxy
humorplus=humorplusz
kiwitv=kiwitv
m4=m4sport
m4sport=m4sport
m4sporthd=m4sport
m4hd=m4sport
m5hd=m5
m5=m5
izauratv=izauratv
moziplus=moziplus
mplus=moziplus
paxtv=paxtv
prime=prime
spikehungary=rtlspike
rtlspike=rtlspike
spilertv=spilertv
zenebutik=zenebutik
idextraeuropehd=investigationdiscoveryxtrahd
digisport1hd=digisport1hd
digisport1hdhu=digisport1hd
digisport1hdro=digisport1hd
digisport2hd=digisport2hd
digisport2hdhu=digisport2hd
digisport2hdro=digisport2hd
rtlklubhd=rtlklubhd
7603_2BE_600_E080000=atv-wapadedrud
discoveryhdshowcase=discoveryshowcasehd
doq=doq
fem3hu=fem3
hbo3hu=hbo3
m2petofi=m2
m3anno=m3
muzsikatv=muzsikatv
natgeohdhun=nationalgeographichd
nickjrhungary=nickjr
79EC_2C8_600_E080000=rtl2-wapadedrud
slagertv=slagertv-wapadedrud
sorozatplus=sorozatplusz
spektrumhome=spektrumhome
7727_2C1_600_E080000=sport1hd-duslelaslu
7598_2BD_600_E080000=sport1-duslelaslu
supertv2=supertv2-wapadedrud
tv2=tv2-wapadedrud
viasat3=viasat3
viasat6=viasat6
vivahungary=viva
digiworldhdhu=digiworld
htmusicchannel=hitmusicchannel
magyarslagertv=slagertv-wapadedrud
musicchannelhu=1musicchannel
A32_5_1_E083113=sport1-duslelaslu
superone=superonehd
tlchu=tlc
75FB_2BE_600_E080000=filmplus-velirajeha
79F3_2C8_600_E080000=filmplus2-velirajeha
13C_3_22C7_EEEE0000=c8-slasluspor
78B7_2C5_600_E080000=discoverychannel
discoveryhu=discoverychannel'''

**Comment by mcfly822** [comment]
Dear charlesduco, can I here ask correction for a mistyped entry, or should I open a new issue for it?
Wrong:
idextraeuropehd=investigationdiscoveryxtrahd
Right:
```idxtraeuropehd=investigationdiscoveryxtrahd```

**Comment by mcfly822** [comment]
Thank you very much! And thanks all your efforts, doing this picons project so good!
