### ISSUE TITLE
New channels and missing links 5W

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#191]
### Better logo for Radio Courtoisie
For Radio Courtoisie I found a logo with higher resolution, but I couldn't manage to get all the white backgroud transparent, maybe someone else can:
http://www.lalettre.pro/photo/art/grande/17474880-21960431.jpg
(links are already present).

### Ready made logos
These logos can be added to the source:
[DiscFam+MyCuisine.zip](https://github.com/picons/picons-source/files/1483714/DiscFam.MyCuisine.zip)

Sources:
https://vignette1.wikia.nocookie.net/logopedia/images/5/51/Discovery_Family.svg
https://www.mycuisine.com/wp-content/themes/mcs/img/logo.svg

**Add to snp-index**
```
berberetv=berberetelevision
sectdf1radiocourtoisie=courtoisie
discoveryfamily=discoveryfamily
francebleunatio=francebleu
francebleuchampagne=francebleuchampagneardenne
francebleusaintetienne=francebleufrancebleusaintetienneloire
mycuisine=mycuisine
```

**Add to srp-index**
```
B9B_51A4_55F_DDE0000=berberetelevision
1F60_12_6E_DCA0000=berberetelevision
1F4_2711_90_DDE0000=courtoisie
51B_5208_55F_DDE0000=discoveryfamily
517_5208_55F_DDE0000=mycuisine
192_68_53_CE40000=mycuisine
```
`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
Some of those svg files are not quite right. Inkscape kicks up errors.

**Comment by Lexzie** [comment]
I guess it's about the Discovery Family logos?
Anyone able to have a look at them or the source and maybe fix that? Maybe @mcfly822 , if you have time?

**Comment by mcfly822** [comment]
Yes, I will check them as soon as I have time.

**Comment by mcfly822** [comment]
I checked the logos.
Radio Courtoisie: made to transparent background.
D. Family: I think that it is  not good to embed the 'earth' picture in an svg. So exported them to png.

Here are all 3 logos, checked with gimp and rsvg-convert.

[issue191_mcfly822_20171118.zip](https://github.com/picons/picons-source/files/1484574/issue191_mcfly822_20171118.zip)

**Comment by Lexzie** [comment]
I did not do any embedding or editing besides making the black letters white for the white version.
Just downloaded the logo like this.

Thanks for making these logos, great!


Here below all information (forget previous post(s)).
These logos can be added to the source:
[issue191_mcfly822_20171118.zip](https://github.com/picons/picons-source/files/1484605/issue191_mcfly822_20171118.zip)


Sources:
https://vignette1.wikia.nocookie.net/logopedia/images/5/51/Discovery_Family.svg
https://www.mycuisine.com/wp-content/themes/mcs/img/logo.svg
http://www.lalettre.pro/photo/art/grande/17474880-21960431.jpg

**snp-index**
```
discoveryfamily=discoveryfamily
mycuisine=mycuisine
```

**srp-index**
```
51B_5208_55F_DDE0000=discoveryfamily
517_5208_55F_DDE0000=mycuisine
192_68_53_CE40000=mycuisine
```
`donkey monkey got issued`

**Comment by mcfly822** [comment]
Yes, I know that not you were the one who embed the image. This is such default for discovery svg logos (due to the Earth part).

**Comment by Lexzie** [comment]
It also explains why the svg's were so large.
Another question (since I cannot communicate with you directly):
You once said you could provide the logos for the Hungarian radiostations?
If you have some time, could you commit those?

**Comment by mcfly822** [comment]
Of coursr, I forgot it :-) as I'll be at my pc, I will upload them.

**Comment by Lexzie** [comment]
I'm happy to supply the srp- and snp-links for those, if needed (at least for 9.0°E, 1.0°W and 4.0°W).

**Comment by Lexzie** [comment]
Thanks!

**Comment by mcfly822** [comment]
@Lexzie I will make the hungarian radio logos in svg soon. Just some days, it is in my todo list 😺
