### ISSUE TITLE
More RDP logos

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#194]
Some more RDP logos.
[RDP(2).zip](https://github.com/picons/picons-source/files/1485794/RDP.2.zip)

Source: http://media.rtp.pt/empresa/identidade-grafica/
ZigZag Radio: http://img0.rtp.pt/play/zigzag/images/btn-nav-live-radio.svg

Only have streams so have no srp-links.

**Add to snp-index**
```
antena2jazzin=antena2jazzin
radiozigzag=radiozigzag
rdpacoresantena1=rdpacoresantena1
rdpmadeiraantena1=rdpmadeiraantena1
rdpmadeiraantena3=rdpmadeiraantena3
```
`donkey monkey got issued`

**Comment by charlesduco** [comment]
Had to optimize the logos, fixed the bad radial gradient in `rdpmadeiraantena3` and fixed wrong colors in `radiozigzag `

**Comment by Lexzie** [comment]
Thanks for correcting the logos (if/when I know why and how I would have/will correct it myself) and for uploading the changes!
