### ISSUE TITLE
La 2 HD And Clan HD (from DVB-T in Spain).

### ISSUE THREAD

**Issue by daviddrf1** [picons/picons-source#195]
Hello. First of all I want to say thank you for all your great job with those amazing picons. I would like to ask you if it would be possible to do picons for two new spanish channels which are in DVB-T. These two channels are called "La 2 HD" and "Clan HD":
La 2 HD: https://www.adslzone.net/app/uploads/2017/09/la-2-hd.jpg
Clan HD: https://www.adslzone.net/app/uploads/2017/09/clan-hd.jpg
I use 400x240 light on transparent picons. Thank you in advance and sorry for any inconvenience or mistake I could make.

**Comment by AbuBaniaz** [comment]
`https://en.wikipedia.org/wiki/La_2_(Spanish_TV_channel)#/media/File:Se15.png`

`https://upload.wikimedia.org/wikipedia/commons/9/94/Logo_clan.png`

**Comment by daviddrf1** [comment]
Thank you AbuBaniaz but those picons are not for HD versions of those channels...

**Comment by AbuBaniaz** [comment]
I provided those to aid finding logos. We can the add them so that the picons are made. If you have links for the HD logos, please provide them/links.

We will still need the service reference

Logo + reference = picon

**Comment by daviddrf1** [comment]
Ahh OK. The only useful logos I found are the two ones I put in my first message. The reference changes depending of the region you are because of the DVB-T standard. These are my region's service refereces anyway:
La 2 HD: 1_0_19_206_3F2_22D4_EEEE0000_0_0_0
Clan HD: 1_0_19_9C41_9C40_22D4_EEEE0000_0_0_0
Thank you!

**Comment by mcfly822** [comment]
I also didn't find the logos in HD version, so I made them.
[issue195_mcfly822_20171121.zip](https://github.com/picons/picons-source/files/1491432/issue195_mcfly822_20171121.zip)

**Comment by daviddrf1** [comment]
WOW! Stunning work mcfly822! How did you do that?!

**Comment by mcfly822** [comment]
In inkscape, drawind the lines. The base for La2HD is the existing La2 SVG, I added the HD logo by a manual drawing over the JPG (what you attached in the first post), then color gradient for the 'HD' letters.
The Clan HD almost the same (base: the existing low-res tveclanhd png), but after finish I exported it to png, because it is not allowed to make embed images in svg. It vas a bit harder to make "well-looking"... yet not perfect.
A little correction for clanhd: 
[20171121_tveclanhd.default_corrected.zip](https://github.com/picons/picons-source/files/1491537/20171121_tveclanhd.default_corrected.zip)

**Comment by daviddrf1** [comment]
I think you did an awesome job. Thank you for your help! These two picons are amazing!

**Comment by mcfly822** [comment]
@daviddrf1 Thanks, mate 😉 

So, I think the final issue will be this:

Please add these logos:
[tveclanhd_tvela2hd_20171121.zip](https://github.com/picons/picons-source/files/1491704/tveclanhd_tvela2hd_20171121.zip)

srp-index:
```
206_3F2_22D4_EEEE0000=tvela2hd
9C41_9C40_22D4_EEEE0000=tveclanhd
```
```donkey monkey got issued```

**Comment by daviddrf1** [comment]
Thank you again!

**Comment by AbuBaniaz** [comment]
>The reference changes depending of the region you are because of the DVB-T standard. 

This is why some people use the SNP version

**Comment by daviddrf1** [comment]
Aha...

**Comment by AbuBaniaz** [comment]
committed here 
https://github.com/picons/picons-source/commit/a5ce1b93343ebd1bf96360d31690aeeb1d328689
