### ISSUE TITLE
new unitymedia picons + added srvid on 1 other

### ISSUE THREAD

**Issue by pommesfrites** [picons/picons-source#196]
Pink Radio
https://dl.dropboxusercontent.com/u/23135995/pinkradio-default.png
```
6602_1CD_270F_FFFF0000=pinkradio
```

Turk Muzigi
```
2B81_8D_270F_FFFF0000=stingraymusic
```

**Comment by pexner** [comment]
Pink Radio new logo and stingraymusic existing logo:
Logo Pink Radio here:
https://dl.dropboxusercontent.com/u/23135995/pinkradio-default.png
```6602_1CD_270F_FFFF0000=pinkradio
2B81_8D_270F_FFFF0000=stingraymusic```

**Comment by mocram** [comment]
This could be turned into a SVG
