### ISSUE TITLE
Teleclub zoom

### ISSUE THREAD

**Issue by daviok** [picons/picons-source#197]
hi

Please add this logo
[logo.zip](https://github.com/picons/picons-source/files/1498616/logo.zip)
sorry for the low res but that is the best i have found

Add to snp-index

`teleclubzoom=teleclubzoom`

Add to srp-index

`1B8F_DC_1_FFFF0000=teleclubzoom`

`donkey monkey got issued`

**Comment by mcfly822** [comment]
Made in inkscape.
[teleclubzoom.default.svg.zip](https://github.com/picons/picons-source/files/1498883/teleclubzoom.default.svg.zip)

**Comment by daviok** [comment]
Thanks mcfly822 👍
