### ISSUE TITLE
Update for some german Sky Sports channels

### ISSUE THREAD

**Issue by tunip** [picons/picons-source#198]
Sky Sport Bundesliga 6 HD
133_8_85_C00000

Sky Sport Bundesliga 7 HD
13D_9_85_C00000

Sky Sport 7 HD
134_8_85_C00000

Sky Sport 8 HD
13E_9_85_C00000

Eurosport360HD 5
136_8_85_C00000

Eurosport360HD 6
140_9_85_C00000

**Comment by charlesduco** [comment]
Wrong format. Read https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

**Comment by tunip** [comment]
SRP-INDEX

NEW
```
133_8_85_C00000=skysportbundesliga6hd
13D_9_85_C00000=skysportbundesliga7hd
134_8_85_C00000=skysport7hd
13E_9_85_C00000=skysport8hd
136_8_85_C00000=eurosport360hd
140_9_85_C00000=eurosport360hd
```

OLD
```
133_A_85_C00000=skysportbundesliga6hd
13D_E_85_C00000=skysportbundesliga7hd
134_A_85_C00000=skysport7hd
13E_E_85_C00000=skysport8hd
136_A_85_C00000=eurosport360hd
140_E_85_C00000=eurosport360hd
```
