### ISSUE TITLE
Motorvision.tv

### ISSUE THREAD

**Issue by pwallner** [picons/picons-source#20]
hi,

in srp-index the channel motorvision is not correct.

Old:
```A8_9_85_C00000=motorvisiontv```

New:
```A8_E_85_C00000=motorvisiontv```

I have also included another image (SVG). Maybe you will use it because most of the picon developers are using this layout...

[motorvisiontv.zip.txt](https://github.com/picons/picons-source/files/973778/motorvisiontv.zip.txt)

Please remove extension *.txt. I was not able to upload the zip...

Regards
Patrick

**Comment by AbuBaniaz** [comment]
We also prefer .svg files. I have added the reference. I'll leave logos to experts.
