### ISSUE TITLE
Eleven Sports Polska

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#200]
Eleven Polska had rebranded their channels and added a fourth channel.

This were the best logos I could find/make:
[Eleven Sports Polska.zip](https://github.com/picons/picons-source/files/1499514/Eleven.Sports.Polska.zip)

Sources:
https://static.multimediago.pl/channels_icons/Eleven_Sports_1_HD.png
https://static.multimediago.pl/channels_icons/Eleven_Sports_2_HD.png
https://static.multimediago.pl/channels_icons/Eleven_Sports_3_HD.png
http://mediafm.net/media/images/thumbnail/md5/9/0/90a10511e6484f4f3dd8e4aef64748be/Eleven_Sports_4_1.jpg

**Delete from snp.index**
```
elevenhd=eleven
elevensportshd=elevensports
elevenextrahd=elevensportsextra
```

**Add to snp.index**
```
elevensports1hd=elevensports1
elevensports2hd=elevensports2
elevensports3hd=elevensports3
elevensports4hd=elevensports4
```

**Delete from srp.index**
```
13F3_5DC_13E_820000=eleven
32E2_190_13E_820000=eleven
13F5_5DC_13E_820000=elevensports
3B64_12C_13E_820000=elevensports
35DC_1388_13E_820000=eleven-seseclifre
13F8_5DC_13E_820000=elevensportsextra
```
**Add to srp.index**
```
13F3_5DC_13E_820000=elevensports1
13F5_5DC_13E_820000=elevensports2
13F8_5DC_13E_820000=elevensports3
32CE_190_13E_820000=elevensports4
```
`donkey monkey got issued`

**Comment by mocram** [comment]
FYI: snp-index and srp-index are renamed to snp.index and srp.index

**Comment by Lexzie** [comment]
Thanks, did not noticed yet.

**Comment by mcfly822** [comment]
The commit is merged. If no more things to do, please close this issue. Thanks!

**Comment by Lexzie** [comment]
Great. (Had to do some sleeping unfortunately).
Thanks!
