### ISSUE TITLE
French channels to delete

### ISSUE THREAD

**Issue by monsieurcoyote** [picons/picons-source#201]
Hello,

here is some information about French or Walloon (Belgian French) channels :
- 1_0_1_1D0_26AC_13F_820000_0_0_0 (AB4) : not on satellite anymore. Keep logo for cable network only.
- 1_0_1_1D1_26AC_13F_820000_0_0_0 (Lucky Jack TV) : not on satellite anymore. Keep logo for cable network only.
- 1_0_1_1F4F_42E_1_C00000_0_0_0 (Planete Thalassa) : stopped broadcast in 01/2016. To delete.
- 1_0_1_1FAB_2454_13E_820000_0_0_0 (OCS Choc) : stopped broadcast on Hotbird in 01/2017
- 1_0_1_1FAA_2454_13E_820000_0_0_0 (OCS City) : stopped broadcast on Hotbird in 01/2017
- 1_0_1_4478_1F40_13E_820000_0_0_0 (OCS City) : stopped broadcast on Hotbird in 01/2017
- 1_0_1_1FAD_2454_13E_820000_0_0_0 (OCS Geants) : stopped broadcast on Hotbird in 01/2017
- 1_0_1_1FB7_2454_13E_820000_0_0_0 (Melody) : no broadcast on Hotbird anymore.
- 1_0_1_1FB0_2454_13E_820000_0_0_0 (Teletoon+) : no broadcast on Hotbird anymore.
- 1_0_1_1FC2_2454_13E_820000_0_0_0 (OCS Max) : stopped broadcast on Hotbird in 01/2017
- 1_0_1_37B0_44C_13E_820000_0_0_0 (Planete+) : program does not exist anymore
- 1_0_1_196B_44E_1_C00000_0_0_0 (Kombat Sport) : no broadcast on Astra anymore
- 1_0_1_197C_44E_1_C00000_0_0_0 (TF6) : stopped broadcast on 12/2014.
- 1_0_1_251D_456_1_C00000_0_0_0 (TF6) : stopped broadcast on 12/2014.
- 1_0_1_323A_45F_35_C00000_0_0_0 (Plug RTL) moved to Hotbird. New SRP already in the file.
- 1_0_1_323D_45F_35_C00000_0_0_0 (Pure / radio) moved to Hotbird. New SRP already in the file.
- 1_0_1_323E_45F_35_C00000_0_0_0 (Classic 21 / radio) moved to Hotbird. New SRP already in the file.
- 1_0_1_323F_45F_35_C00000_0_0_0 (Vivacite / radio) moved to Hotbird. New SRP already in the file.
- 1_0_1_377E_44C_13E_820000_0_0_0 (Planete+) : program does not exist anymore
- 1_0_1_377D_44C_13E_820000_0_0_0 (Teletoon+) : no broadcast on Hotbird anymore.
- 1_0_1_379B_44C_13E_820000_0_0_0 (Teletoon+) : no broadcast on Hotbird anymore.
- 1_0_1_379C_44C_13E_820000_0_0_0 (Planete+) : program does not exist anymore
- 1_0_1_428D_446_1_C00000_0_0_0 (Stylia)  : stopped broadcast on 12/2014.
- 1_0_1_1163_2AF8_13E_820000_0_0_0 (Planete+) : program does not exist anymore
- 1_0_1_3233_45F_35_C00000_0_0_0 (La Une HD) moved to Hotbird. New SRP already in the file.
- 1_0_1_3234_45F_35_C00000_0_0_0 (La deux) moved to Hotbird. New SRP already in the file.
- 1_0_1_3235_45F_35_C00000_0_0_0 (La Trois) moved to Hotbird. New SRP already in the file.
- 1_0_1_3238_45F_35_C00000_0_0_0 (RTL TVi HD) moved to Hotbird. New SRP already in the file.
- 1_0_1_3239_45F_35_C00000_0_0_0 (Club RTL) moved to Hotbird. New SRP already in the file.
- 1_0_1_3240_45F_35_C00000_0_0_0 (Musiq 3 / radio) moved to Hotbird. New SRP already in the file.
- 1_0_1_3241_45F_35_C00000_0_0_0 (La Premiere / radio) moved to Hotbird. New SRP already in the file.
- 1_0_1_3244_45F_35_C00000_0_0_0 (Mint / radio) moved to Hotbird. New SRP already in the file.
- 1_0_1_3245_45F_35_C00000_0_0_0 (Bel RTL / radio) moved to Hotbird. New SRP already in the file.
- 1_0_1_3246_45F_35_C00000_0_0_0 (Radio contact / radio) moved to Hotbird. New SRP already in the file.

There will be more to come within the next few days.

Regards,
monsieurcoyote

**Comment by charlesduco** [comment]
Thanks for the information. But there is no need to delete old entries in srp-index as stated in the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md).

If you really want to have these entries deleted, please provide them in the right format and provide only the entries that should be deleted.

The channel logos may only be deleted if we are 100% sure that the broadcaster has shut down the channel completely on all networks. So, again, please provide the logo names in the right format and provide only the logo names that should be deleted.

**Comment by AbuBaniaz** [comment]
The removals of references listed above have been actioned by merge. So maybe issue can be closed?

Although no need to remove, it is indeed a good idea to remove defunct entries. If using SRP, I think it would be a better idea to encourage people to remove duplicate/invalid entries.

I appreciate that the way the picons are made, it uses the first entry found.

**Comment by monsieurcoyote** [comment]
It is going to be hard work but thère should be some 300 entries to delete on Astra, all obsolété       And duplicate entries mainly due to Canalsat 's regular changes.

**Comment by AbuBaniaz** [comment]
Maybe you should consider using SNP version. Less susceptible to changes.

Just to repeat, cleaning up is not required,  the first value is used. However, at some stage, we will need to do something otherwise the file will just keep growing. Easiest method is to replace old entries with new instead of just adding at the top.

If you still want to remove the dead/incorrect entries, here are attachments for you. I have extracted the 19.2 entries. One copy should be exactly in the same order as official file. Another is sorted by the logo name.  The third one is sorted by the reference. Each has its benefit.  For example sorting by reference lets you find issues like this 
```
7732_416_1_C00000=crimeandinvestigation
7732_416_1_C00000=tviinternacional
```
Sorting by logo allows you to identify the channels easily. 

List the entries you want to remove.
[srp_192_asis.txt](https://github.com/picons/picons-source/files/727987/srp_192_asis.txt)
[srp_192_logo.txt](https://github.com/picons/picons-source/files/727988/srp_192_logo.txt)
[srp_192_ref.txt](https://github.com/picons/picons-source/files/727986/srp_192_ref.txt)

**Comment by monsieurcoyote** [comment]
Thanks for the files. They will sure be helpful.

As an estimate one of the latest versions of the srf files has 1530 entries.
Kingofsat has 1328 entries.
You are missing some 40 French radio stations.
Are there are a few data system entries which get no picon.
So there should be some 250-300 entries to remove.

**Comment by charlesduco** [comment]
@monsieurcoyote If you opened another issue for this problem, please close this issue.

**Comment by mocram** [comment]
If somebody want's to cleanup old obsolete entries, they should create a proper pull request, not a info overload dump in a issue.

If you build yourself against your own list, they aren't even used.
