### ISSUE TITLE
Eleven Sports Belgium

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#202]
Eleven Sports Belgium has started on satellite and uses different logos than the old and new logos of Eleven Sports Polska.
I can't find better logos than these png's and a svg but not with the right text.
Maybe someone can create the right logos from the svg?
Please keep the letters white and not transparent.
After that I will provide the links.

[Eleven Sports Belgium examples.zip](https://github.com/picons/picons-source/files/1502577/Eleven.Sports.Belgium.examples.zip)

**Comment by mcfly822** [comment]
Hello Lexzie,
I made them in vector format. 
[elevensportsbelgium_mcfly822_20171124.zip](https://github.com/picons/picons-source/files/1502655/elevensportsbelgium_mcfly822_20171124.zip)
What do you think?

**Comment by Lexzie** [comment]
What do I think?
Amazingly, this fast and they look very good!

Here's the complete posting ready to be committed:
Logos:
[elevensportsbelgium_mcfly822_20171124.zip](https://github.com/picons/picons-source/files/1502683/elevensportsbelgium_mcfly822_20171124.zip)

**snp.index**
```
elevensports1=evensports1-swomuchaho
velevensports1=evensports1-swomuchaho
elevensports2=evensports2-swomuchaho
velevensports2=evensports2-swomuchaho
```
**srp.index**
```
101E_451_35_C00000=evensports1-swomuchaho
1032_451_35_C00000=evensports1-swomuchaho
5246_C99_3_EB0000=evensports2-swomuchaho
52AA_C99_3_EB0000=evensports2-swomuchaho
```
`donkey monkey got issued`

**Comment by mcfly822** [comment]
Thank you 😉 
Honestly, today I worked a lot on the eleven sport poland logos, so for these logos there was many things prepared (for example, the text. I also did not found the font, so drawed every letters...)
To make the polish logos are a bit harder work, but in progress 😄

**Comment by mcfly822** [comment]
@Lexzie Are the index entries right?
velevensports1?
evensports1-swomuchaho?

**Comment by Lexzie** [comment]
The velevensports is correct, the evensports isn't.
Thanks for noticing.

**Comment by mcfly822** [comment]
Ok, thanks for the correcting!

**Comment by Lexzie** [comment]
Thank you all.
