### ISSUE TITLE
Additions for Belgian cable operator Voo

### ISSUE THREAD

**Issue by monsieurcoyote** [picons/picons-source#203]
Hello,

additions :

4E86_C9_1_FFFF0000=ladeuxhd
4E87_C9_1_FFFF0000=latroishd

Rgds.

**Comment by charlesduco** [comment]
Please use triple backticks as described in https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

**Comment by AbuBaniaz** [comment]
This change has been included in my pull request

**Comment by charlesduco** [comment]
Okay
