### ISSUE TITLE
New logo Insight TV

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#206]
Insight TV changed it's logos:
![afbeelding](https://user-images.githubusercontent.com/14023349/33241813-860e9b2a-d2cb-11e7-85b5-9af97f945784.png) ![afbeelding](https://user-images.githubusercontent.com/14023349/33241815-908949d8-d2cb-11e7-9a3f-13af6649fc78.png)

I could only find this logo of Insight TV/Insight HD.
[insight.zip](https://github.com/picons/picons-source/files/1504031/insight.zip)

Source: https://www.mediastages.nl/data/bedrijfslogo/INsight.png

Can someone create the Insight UHD logo?
Also notice the colour difference.

If accepted the current `insight` and `insightuhd` logos can be deleted or renamed.
In that way links don't have to change.

**Comment by mocram** [comment]
Where did you get those pictures from? Are you not just comparing badly calibrated screen modes? Or perhaps watching a HDR channel on a non HDR TV?

**Comment by Lexzie** [comment]
The pictures are from screenshot I made.
Here are they in full screen:
![insight hd](https://user-images.githubusercontent.com/14023349/33242386-80e65c60-d2d4-11e7-8e6a-9178b5a5ead7.jpg)
![insight uhd](https://user-images.githubusercontent.com/14023349/33242388-82a077ca-d2d4-11e7-9fef-ff3f4aacacd6.jpg)

I don't understand what you mean with the rest.
