### ISSUE TITLE
Hotbird RAI new parameters & new picons

### ISSUE THREAD

**Issue by cavocaldo** [picons/picons-source#207]
Rai 2 HD
1_0_19_D4A_1450_13E_820000_0_0_0

Rai 3 HD
1_0_19_D4B_1450_13E_820000_0_0_0

Rai 5 HD
1_0_19_452F_30D4_13E_820000_0_0_0
new logo: http://www.exporete.net/picons/Rai_5_HD.svg

Rai Sport 1 HD
1_0_19_D4C_1450_13E_820000_0_0_0

Rai Storia HD
1_0_19_D4E_1450_13E_820000_0_0_0
new logo: http://www.exporete.net/picons/Rai_Storia_HD.svg

Rai Scuola HD
1_0_19_4533_30D4_13E_820000_0_0_0
new logo: http://www.exporete.net/picons/Rai_Scuola_HD.svg

Rai Gulp HD
1_0_19_4530_30D4_13E_820000_0_0_0
new logo: http://www.exporete.net/picons/Rai_Gulp_HD.svg

Rai Yoyo HD
1_0_19_4531_30D4_13E_820000_0_0_0
new logo: http://www.exporete.net/picons/Rai_Yoyo_HD.svg

Rai News24 HD
1_0_19_D4D_1450_13E_820000_0_0_0
shared same logo with Rai News24 (sd)

Rai 5
1_0_1_CEE_1518_13E_820000_0_0_0

Rai Premium
1_0_1_CED_1518_13E_820000_0_0_0

Rai Storia
1_0_1_CE8_1518_13E_820000_0_0_0

Rai Scuola
1_0_1_CEB_1518_13E_820000_0_0_0

Rai Gulp
1_0_1_CE9_1518_13E_820000_0_0_0

Rai Yoyo
1_0_1_CEA_1518_13E_820000_0_0_0

To remove:
RaiMed (channel no longer exists)
Rai HD (channel no longer exists)

**Comment by charlesduco** [comment]
Wrong format. Please read the contributing rules: https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md
You have to provide service references in the right format.
