### ISSUE TITLE
Help for editing Radio 100,7 logo

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#207]
Can anyone help me with this logo?
I want to make the white background transparent.
After that the black must also be converted to white for the `light` version.
[radio100komma7.zip](https://github.com/picons/picons-source/files/1506267/radio100komma7.zip)

**Comment by mcfly822** [comment]
Here you are.
[rkomma7_mcfly822.zip](https://github.com/picons/picons-source/files/1506381/rkomma7_mcfly822.zip)

**Comment by mcfly822** [comment]
Thanks, mate! 😉
