### ISSUE TITLE
Light logos for swiss radio stations

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#209]
These logos are with default version hardly visible on a dark background.

Please add these logos:
[Swiss(light).zip](https://github.com/picons/picons-source/files/1510163/Swiss.light.zip)

Also please add these links.

**snp.index**
```
schweiz5=schweiz5
```

'donkey monkey got issued'

**Comment by mocram** [comment]
No idea what you did, but something is of with the logos, radiosrf3 needs fixing, when resizing the page to fit the logo, there's a lot of whitespace added, the default version does not suffer from this. The other logo I made myself from the default version.

**Comment by mcfly822** [comment]
> when resizing the page to fit the logo, there's a lot of whitespace added, the default version does not suffer from this

This happens when man inverts the color by a filter in inkscape. I also don't know the reason. So if I want to invert a color, I watch the color's RGB code, then I search a website which can say the iverse of this code, and in inkscape I change the original code to the inverted.

**Comment by Lexzie** [comment]
That's what I did invert the colour in Inkscape. Have to take some time to look at the solution @mcfly822 mentioned.

**Comment by mcfly822** [comment]
@Lexzie I made the light version, see PR #211 .
The "filters>color>invert" makes a filter, which says that the colors must be rendered in inverted format, but the colors are in fact not changed!
I found that the color inversion must be done not by these "filters" in inkscape, but "Extensions>color>negative". This really inverts the colors.

**Comment by mocram** [comment]
Great job @mcfly822 !

**Comment by mcfly822** [comment]
Thanks!

**Comment by Lexzie** [comment]
Thanks for all.
