### ISSUE TITLE
sat1emotions

### ISSUE THREAD

**Issue by pwallner** [picons/picons-source#21]
Hi,

old srp-index:
```125D_3F7_1_C00000=sat1emotions```

should be
```14C1_407_1_C00000=sat1emotions```

I also added an SVG file (please rename the extension to *.svg)
[sat1emotions.default.svg.txt](https://github.com/picons/picons-source/files/973840/sat1emotions.default.svg.txt)

**Comment by AbuBaniaz** [comment]
svg file still needs to be added

Please zip next time

**Comment by charlesduco** [comment]
The provided svg file doesn't comply with the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md), please read them before submitting an issue:

> It's not allowed for svg files to contain base64 encoded images.
