### ISSUE TITLE
True movies rename

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#210]
Hello, can you add the following channel logos which had a rename please?

True Movies
```
http://tv.sky.com/logo/0/0/skychb3643.png
```

True Movies+1
```
http://tv.sky.com/logo/0/0/skychb3751.png
```

SRP index
```
D04D_83E_2_11A0000=truemoviesplus1
D048_83E_2_11A0000=truemovies
```

I'll add the SNP index by a pull request

**Comment by monsieurcoyote** [comment]
@AbuBaniaz could you contact me @ `mynacknamehere` on gmail?
