### ISSUE TITLE
Logos and links for (mostly) Astra 3B

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#210]
Found+created logos for mostly Astra 3B 23.5E.
Also added and corrected links.

Inside this archive the logos to add (left out the logos already added):
[logos_Astra3B.zip](https://github.com/picons/picons-source/files/1539863/logos_Astra3B.zip)

**Delete from snp.index**
```
13C2_C95_3_EB0000=ceskoslovensko
crojazz=crojazz
junior=junior
1F4B_CA1_3_EB0000=skylink
132A_CA2_3_EB0000=stv2-wapadedrud
```

**Add to snp.index**
```
radioaktual=aktual
barrandovplushd=barrandovplushd
ceskoslovensko=ceskoslovensko
ct1smhd=ct1hd
ct1jmhd=ct1hd
croddur=ddurceskyrozhlas
crodvojka=dvojkaceskyrozhlas
132A_CA2_3_EB0000=dvojkahd
crojazz=jazzceskyrozhlas
ockostar=ockostar
playradio=play
croplus=plusceskyrozhlas
radio1007letzebuerg=radio100komma7
antenarock=radioantenarock
devin=radiodevin
radiofm=radiofm
jemnemelodies=radiojemne
jemnemelodiev=radiojemne
jemnemelodiez=radiojemne
13_3_85_C00000=junior
croradiojunior=radiojunior
junior=radiojunior-uowrefreja
litera=radiolitera
patriafm=radiopatria_fm
patriard=radiopatria_devin
croradiopraha=radioprahaceskyrozhlas
pyramida=radiopyramida
reginaba=radioregina
reginabb=radioregina
reginake=radioregina
slovakia=radioslovakiainternational
slovensko=radioslovensko
croradiowave=radiowave
croradiozurnal=radiozurnalceskyrozhlas
croreginadab=reginadabprahaceskyrozhlas
2AF8_B_3_EB0000=rmf
rmffm=rmf
2EE0_B_3_EB0000=rmfclassic
32C8_B_3_EB0000=rmfmaxxx
36B0_B_3_EB0000=rmfmaxxx
3A98_B_3_EB0000=rmfmaxxx
3E80_B_3_EB0000=rmfmaxxx
4268_B_3_EB0000=rmfmaxxx
rmfmaxxx=rmfmaxxx
skylinkochutnavk=skylink
crotestdd=vltavaceskyrozhlas
crovltava=vltavaceskyrozhlas
radiovlna=vlnaradio
```

**Delete from srp.index**
```
1B62_65_1771_E080000=213sport
336D_C93_3_EB0000=crojazz
1330_CA2_3_EB0000=ct2
132F_CA2_3_EB0000=ct1
132E_CA2_3_EB0000=markizahd
1325_CA2_3_EB0000=ct1hd
1326_CA2_3_EB0000=ct2hd
1328_CA2_3_EB0000=ctsporthd
```

**Add to srp.index**
```
1333_CA2_3_EB0000=213sport
178A_AF6_BB_E080000=213sport
1337_CA2_3_EB0000=aktual
1F79_CA1_3_EB0000=ddurceskyrozhlas
1F74_CA1_3_EB0000=dvojkaceskyrozhlas
1F7A_CA1_3_EB0000=jazzceskyrozhlas
1335_CA2_3_EB0000=ockostar
C355_4B0_64_EB0000=play
1F76_CA1_3_EB0000=plusceskyrozhlas
1349_CA2_3_EB0000=radioantenarock
147E_C98_3_EB0000=radio100komma7
133D_CA2_3_EB0000=radiodevin
133E_CA2_3_EB0000=radiofm
1345_CA2_3_EB0000=radiojemne
1346_CA2_3_EB0000=radiojemne
1347_CA2_3_EB0000=radiojemne
1F78_CA1_3_EB0000=radiojunior
1341_CA2_3_EB0000=radiojunior-uowrefreja
1340_CA2_3_EB0000=radiolitera
1342_CA2_3_EB0000=radiopatria_fm
1343_CA2_3_EB0000=radiopatria_devin
1F7D_CA1_3_EB0000=radioprahaceskyrozhlas
133F_CA2_3_EB0000=radiopyramida
133A_CA2_3_EB0000=radioregina
133B_CA2_3_EB0000=radioregina
133C_CA2_3_EB0000=radioregina
1344_CA2_3_EB0000=radioslovakiainternational
1339_CA2_3_EB0000=radioslovensko
1F77_CA1_3_EB0000=radiowave
1F73_CA1_3_EB0000=radiozurnalceskyrozhlas
1F7B_CA1_3_EB0000=reginadabprahaceskyrozhlas
2AF8_B_3_EB0000=rmf
1C98_1CE8_71_820000=rmf
1002_F001_2268_14A0000=rmf
2EE0_B_3_EB0000=rmfclassic
1C9A_1CE8_71_820000=rmfclassic
32C8_B_3_EB0000=rmfmaxxx
36B0_B_3_EB0000=rmfmaxxx
3A98_B_3_EB0000=rmfmaxxx
3E80_B_3_EB0000=rmfmaxxx
4268_B_3_EB0000=rmfmaxxx
1C9E_1CE8_71_820000=rmfmaxxx
1003_F001_2268_14A0000=rmfmaxxx
1334_CA2_3_EB0000=tuty
1F75_CA1_3_EB0000=vltavaceskyrozhlas
1F7E_CA1_3_EB0000=vltavaceskyrozhlas
1427_CA2_3_EB0000=vlnaradio
```

`donkey monkey got issued`

**Comment by mocram** [comment]
You are supplying logos already added.

**Comment by Lexzie** [comment]
They are changed.

**Comment by mocram** [comment]
Radio 100,7

Stopped looking after that.

**Comment by mocram** [comment]
@Lexzie FYI: I'm happy to see your continued effort getting a lot of updates in, but for me it's not neccesarry to waste your time listing all the source links, I rather see a 100% correct zip then a list full of source url's.

**Comment by Lexzie** [comment]
Understood. I just followed the contribution guidelines.
I'm happy to see I have learnt a lot already.
I check if logos and links already exist and make the updates accordingly..
I could not find a logo for Radio 100,7.
I searched with different names in the logo database and within the snp- and srp.index.
If f.e. in srp.index still an old reference ID is used, I cannot find it.
And furthermore it's still human to oversee a existing logo or link.
I'm busy this week, but will try to check this issue a.s.a.p.

**Comment by mocram** [comment]
https://github.com/picons/picons-source/blob/master/build-source/logos/radio100komma7.default.svg
https://github.com/picons/picons-source/issues/207
https://github.com/picons/picons-source/commit/9d4e01f61f4356b31cc91e629d5781ee08122db8

**Comment by Lexzie** [comment]
Weird, I am sure I searched for `radio100` (and more).

**Comment by Lexzie** [comment]
I asked in Issue #207 for creating the svg with the intention to be added in this issue.
Didn't mean to have it added right away and didn't notice you did that, sorry.
I will leave it out of the zip-file, the links for 'radio100komma7' still needs to be added.
Checked al other logos and links, they are not present or I added the change (delete links and then add the new links).
I'll wait for @mcfly822 excellent logos and will add all logos at once.

**Comment by mcfly822** [comment]
I only had pay attention to png's. I made almost all of them in .svg.
The 'play.default.png' is not needed to modify, I think it is acceptable.

The problem is 'radioantenarock'. I cannot make it in svg, it is too complicated for me. But the .png what @Lexzie provided is not acceptable, because it is not transparent. I made a transparent version, but very low resolution (347x213). Not so good, but at this time I cannot provide better version.
[issue210_mcfly822_20171130.zip](https://github.com/picons/picons-source/files/1517211/issue210_mcfly822_20171130.zip)

**Comment by charlesduco** [comment]
Logo for Radio Antena Rock:
http://www.radioservices.sk/wp-content/uploads/2017/11/brandbook_2017.pdf
https://www.google.com/search?q=filetype%3Apdf+site%3Aradioservices.sk

**Comment by mcfly822** [comment]
@charlesduco cannot imagine how you do this. I searched almost an hour for pdf's which contains logofor Radio Antena Rock. I found some, but not in vector format, just embedded image. Thanks a lot!
Besides, now the Rádio Jemné logo also can be taken from here, much better then I previously drawed.
[radiojemne.default.zip](https://github.com/picons/picons-source/files/1517411/radiojemne.default.zip)

**Comment by Lexzie** [comment]
Wow guys, this is great!
I have been busy for a couple of days for all these logos and searched a long time too.
For now I can only reply shortly, will supply all logos in one zip ASAP.

**Comment by charlesduco** [comment]
@mcfly822:
Always look first at the website and social media accounts of the broadcaster: http://antenarock.sk/
Look for marketing or advertising material/links: http://antenarock.sk/p/reklama

Then use google with [search operators](https://moz.com/learn/seo/search-operators) to narrow your search to specific sites and filetypes:
`"radio antena rock" filetype:pdf site:radioservices.sk` and other variations

**Comment by mcfly822** [comment]
@charlesduco great work! Some of these 'operators' (e.g. filetype) I knew and used, but in the future I can narrowing the search. Thanks!

**Comment by Lexzie** [comment]
First I check the channel on Lyngsat for it's website and on what satellites the station is broadcasting. If I can receive the broadcast I can include all links. Then I search on the website, also with inspection of the website (F12), again for svg-files. Already used `filetype:svg`, but not yet for PDF. Don't know yet how to extract images from pdf's. I ounce imported one in Inkscape and it resulted in one big embedded image.
But I'm sure going to search for PDF's too.
Thanks

**Comment by mcfly822** [comment]
@Lexzie When will you have time to add the logos?

**Comment by Lexzie** [comment]
Probably tomorrow.
I wasn't home for a week.

**Comment by Lexzie** [comment]
Added the zip with logos not yet committed in the first comment.
Also please submit the changes to snp- and srp.index.

**Comment by AbuBaniaz** [comment]
The editing of posts makes following the issue, and more importantly, applying the required changes  difficult as you have to keep going back and forth.

Please post what needs to be done with current attachments. 

Thanks in advance.

**Comment by Lexzie** [comment]
No problem, copy-paste:

Found+created logos for mostly Astra 3B 23.5E.
Also added and corrected links.

Inside this archive the logos to add (left out the logos already added):
[logos_Astra3B.zip](https://github.com/picons/picons-source/files/1539863/logos_Astra3B.zip)


**Delete from snp.index**
```
13C2_C95_3_EB0000=ceskoslovensko
crojazz=crojazz
junior=junior
1F4B_CA1_3_EB0000=skylink
132A_CA2_3_EB0000=stv2-wapadedrud
```

**Add to snp.index**
```
radioaktual=aktual
barrandovplushd=barrandovplushd
ceskoslovensko=ceskoslovensko
ct1smhd=ct1hd
ct1jmhd=ct1hd
croddur=ddurceskyrozhlas
crodvojka=dvojkaceskyrozhlas
132A_CA2_3_EB0000=dvojkahd
crojazz=jazzceskyrozhlas
ockostar=ockostar
playradio=play
croplus=plusceskyrozhlas
radio1007letzebuerg=radio100komma7
antenarock=radioantenarock
devin=radiodevin
radiofm=radiofm
jemnemelodies=radiojemne
jemnemelodiev=radiojemne
jemnemelodiez=radiojemne
13_3_85_C00000=junior
croradiojunior=radiojunior
junior=radiojunior-uowrefreja
litera=radiolitera
patriafm=radiopatria_fm
patriard=radiopatria_devin
croradiopraha=radioprahaceskyrozhlas
pyramida=radiopyramida
reginaba=radioregina
reginabb=radioregina
reginake=radioregina
slovakia=radioslovakiainternational
slovensko=radioslovensko
croradiowave=radiowave
croradiozurnal=radiozurnalceskyrozhlas
croreginadab=reginadabprahaceskyrozhlas
2AF8_B_3_EB0000=rmf
rmffm=rmf
2EE0_B_3_EB0000=rmfclassic
32C8_B_3_EB0000=rmfmaxxx
36B0_B_3_EB0000=rmfmaxxx
3A98_B_3_EB0000=rmfmaxxx
3E80_B_3_EB0000=rmfmaxxx
4268_B_3_EB0000=rmfmaxxx
rmfmaxxx=rmfmaxxx
skylinkochutnavk=skylink
crotestdd=vltavaceskyrozhlas
crovltava=vltavaceskyrozhlas
radiovlna=vlnaradio
```

**Delete from srp.index**
```
1B62_65_1771_E080000=213sport
336D_C93_3_EB0000=crojazz
1330_CA2_3_EB0000=ct2
132F_CA2_3_EB0000=ct1
132E_CA2_3_EB0000=markizahd
1325_CA2_3_EB0000=ct1hd
1326_CA2_3_EB0000=ct2hd
1328_CA2_3_EB0000=ctsporthd
```

**Add to srp.index**
```
1333_CA2_3_EB0000=213sport
178A_AF6_BB_E080000=213sport
1337_CA2_3_EB0000=aktual
1F79_CA1_3_EB0000=ddurceskyrozhlas
1F74_CA1_3_EB0000=dvojkaceskyrozhlas
1F7A_CA1_3_EB0000=jazzceskyrozhlas
1335_CA2_3_EB0000=ockostar
C355_4B0_64_EB0000=play
1F76_CA1_3_EB0000=plusceskyrozhlas
1349_CA2_3_EB0000=radioantenarock
147E_C98_3_EB0000=radio100komma7
133D_CA2_3_EB0000=radiodevin
133E_CA2_3_EB0000=radiofm
1345_CA2_3_EB0000=radiojemne
1346_CA2_3_EB0000=radiojemne
1347_CA2_3_EB0000=radiojemne
1F78_CA1_3_EB0000=radiojunior
1341_CA2_3_EB0000=radiojunior-uowrefreja
1340_CA2_3_EB0000=radiolitera
1342_CA2_3_EB0000=radiopatria_fm
1343_CA2_3_EB0000=radiopatria_devin
1F7D_CA1_3_EB0000=radioprahaceskyrozhlas
133F_CA2_3_EB0000=radiopyramida
133A_CA2_3_EB0000=radioregina
133B_CA2_3_EB0000=radioregina
133C_CA2_3_EB0000=radioregina
1344_CA2_3_EB0000=radioslovakiainternational
1339_CA2_3_EB0000=radioslovensko
1F77_CA1_3_EB0000=radiowave
1F73_CA1_3_EB0000=radiozurnalceskyrozhlas
1F7B_CA1_3_EB0000=reginadabprahaceskyrozhlas
2AF8_B_3_EB0000=rmf
1C98_1CE8_71_820000=rmf
1002_F001_2268_14A0000=rmf
2EE0_B_3_EB0000=rmfclassic
1C9A_1CE8_71_820000=rmfclassic
32C8_B_3_EB0000=rmfmaxxx
36B0_B_3_EB0000=rmfmaxxx
3A98_B_3_EB0000=rmfmaxxx
3E80_B_3_EB0000=rmfmaxxx
4268_B_3_EB0000=rmfmaxxx
1C9E_1CE8_71_820000=rmfmaxxx
1003_F001_2268_14A0000=rmfmaxxx
1334_CA2_3_EB0000=tuty
1F75_CA1_3_EB0000=vltavaceskyrozhlas
1F7E_CA1_3_EB0000=vltavaceskyrozhlas
1427_CA2_3_EB0000=vlnaradio
```

'donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
I have committed these. I renamed two of the logos owing to this

```
NO spaces, fancy symbols or .-+_*, except for the exceptions below.
```

**Comment by Lexzie** [comment]
I guess you mean `radiopatria_fm` and `radiopatria_devin`?
They are named that way because it's a combined channel of `radiopatria` during the day and `radiodevin` resp. `radiofm` during evenings/nights.
Below a screenshot of these channels on Lyngsat.
Off course I have monitored and confirmed it also myself.

![afbeelding](https://user-images.githubusercontent.com/14023349/33773659-f2bde278-dc38-11e7-893a-67c2de565598.png)

It is just like f.e. `comedycentral_viva`.

I don't mind if the logos are named without `_`, I just thought this was the right naming.
Or maybe I should have named them `radiopatria_radiofm` and `radiopatria_radiodevin`?

I see I forgot a `light` version for these logos, I will upload them later in a separate issue.

Thanks for committing all logos and links.

**Comment by mocram** [comment]
radiopatria_radiofm would be correct

**Comment by Lexzie** [comment]
I don't have the rights to rename the files.

**Comment by AbuBaniaz** [comment]
Upload the light version here. Ill rename logos later

**Comment by Lexzie** [comment]
Thanks everyone!
