### ISSUE TITLE
Duplicate entry 13E rai channels

### ISSUE THREAD

**Issue by cavocaldo** [picons/picons-source#213]
Please remove these entries, bad icon due to duplicates records with different names

```
D4B_1450_13E_820000=rai3
D4E_1450_13E_820000=raiscuola
4533_30D4_13E_820000=raisport1hd
4256_2F44_13E_820000=rai2hd
4257_2F44_13E_820000=rai3hd
```

**Comment by AbuBaniaz** [comment]
Included in pull request

**Comment by AbuBaniaz** [comment]
This can be closed

**Comment by mocram** [comment]
Where these records at the top? The good ones being at the bottom?

**Comment by AbuBaniaz** [comment]
> Where these records at the top? The good ones being at the bottom?
Good ones are at the top, old ones at the bottom

**Comment by mocram** [comment]
>Please remove these entries, bad icon due to duplicates records with different names

This indicates to me that either the wrong ones were at the top or the script fucked up. Or I'm missing the point and all is well.

**Comment by AbuBaniaz** [comment]
Service references get re-used. If a new/different channel uses an old abandoned reference, the new channel will use the wrong picon. 

You'd rather have no logo than the wrong logo. This is why I assume that @cavocaldo wanted them removed.

**Comment by mocram** [comment]
Ah OK, makes sense... I was just worried that perhaps something wen amiss with the script.
