### ISSUE TITLE
Some channel logos for consideration

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#215]
As you know, my graphic skills are next to none.  Someone has asked for these logos to be considered for inclusion.

Could you kindly look at them if  you get a moment?

Thanks in advance

[Folder 1.zip](https://github.com/picons/picons-source/files/737961/Folder.1.zip)
[Folder 2.zip](https://github.com/picons/picons-source/files/737962/Folder.2.zip)
[SRP additions.txt](https://github.com/picons/picons-source/files/737963/SRP.additions.txt)

**Comment by charlesduco** [comment]
I'll will look into it, but it will take some time cause some logos are unacceptable.

**Comment by AbuBaniaz** [comment]
Thank you
