### ISSUE TITLE
Movistar Star Wars

### ISSUE THREAD

**Issue by Jglez3** [picons/picons-source#217]
```
76C4_40E_1_C00000=movistarstarwars
```

The logo needs to be updated, this is the new one.

https://vignette.wikia.nocookie.net/logopedia/images/5/54/Movistar_Star_Wars.svg/revision/latest?cb=20171129122126

Edit: Also, there's a new logo for `nonstoppeople` (at least in Spain): http://www.movistarplus.es/canal/non-stop-people?id=NONSTP

Thank you.

`donkey monkey got issued`

**Comment by Lexzie** [comment]
Please also add to **snp.index**
```
mstarwars=movistarstarwars
```

**Comment by AbuBaniaz** [comment]
I have replaced the default one with this `https://github.com/picons/picons-source/blob/7393c5b9c7fd0151e1973336f4db7033ff15a352/build-source/logos/movistarstarwars.default.svg`
The light version of the picon will need to be remade.

**Comment by mcfly822** [comment]
@AbuBaniaz Oops, I see, that it is not a real svg, just contains the logo in embedded raster format, not traced...

**Comment by mcfly822** [comment]
I made them in vector format:
[mstarwars.zip](https://github.com/picons/picons-source/files/1526539/mstarwars.zip)

**Comment by AbuBaniaz** [comment]
Thanks. Both files committed
