### ISSUE TITLE
Lowercase logos

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#218]
The Sky logos were changed recently so that the text is lower case. Are the attached acceptable? I got them from Jasmeet's repo. I have already added them to the lowercase branch on my fork.

If they are not OK, please provide feedback as to what needs changing.

Thanks in advance.

`donkeymonkey got issue`
[lowercase.zip](https://github.com/picons/picons-source/files/1525629/lowercase.zip)

**Comment by mocram** [comment]
Shouldn't you know this by now? :-)

**Comment by mocram** [comment]
I checked a few, I think they are OK.

**Comment by AbuBaniaz** [comment]
Thanks.

https://github.com/picons/picons-source/commit/ea9f6a852fb69de623775028f71d6ffb6050df64

**Comment by leec32** [comment]
could we have Disney for these also please 
http://tv.sky.com/logo/00/00/skychb4013.png
