### ISSUE TITLE
Picons for ISP SFR IPTV

### ISSUE THREAD

**Issue by Arkoth79** [picons/picons-source#220]
Hello,

I've tried to do picons for IPTV as we said in the other issue...
It works with snp-full :+1: for IPTV for my channels from ISP SFR in France.

What I do:

First, the logos for the channels:

[Logo bfmsport](https://fr.wikipedia.org/wiki/BFM_Sport#/media/File:BFM_Sport.svg)
I put it in build-source/logos and renamed it: bfmsport.default.svg

The other logos are already in the build-source/logos and are ok, so I don't do anything for them:
[Logo sfrsport1](https://fr.wikipedia.org/wiki/SFR_Sport#/media/File:Logo_sfr_sport1.jpg)
[Logo sfrsport2](https://fr.wikipedia.org/wiki/SFR_Sport#/media/File:SFR_Sport_2_logo_2016.png)
[Logo sfrsport3](https://fr.wikipedia.org/wiki/SFR_Sport#/media/File:SFR_Sport_3.jpg)
[Logo sfrsport4k](https://fr.wikipedia.org/wiki/SFR_Sport#/media/File:Sfr_sport_4k_logo.jpg)
[Logo sfrsport5](https://fr.wikipedia.org/wiki/SFR_Sport#/media/File:Logo_sfr_sport5.jpg)

After, I've modified the file snp-index like this:
```
bfmsport=bfmsport
sfrsport1=sfrsport1
sfrsport2=sfrsport2
sfrsport3=sfrsport3
sfrsport4k=sfrsport4k
sfrsport4=sfrsport4k
sfrsport5=sfrsport5
```

Then, I launch the command:
`./2-build-picons.sh snp-full`
no error

The picons are ok, I test it with light.on.black on my OpenPli

I hope this is ok for you.

For srp, I did not succeed... 

Thanks for your help.

**Comment by AbuBaniaz** [comment]
Apart from bfmsport, all the others have been added in this request
https://github.com/picons/picons-source/pull/221

**Comment by Arkoth79** [comment]
Why you don't take bfmsport ? I make a mistake ?

It's same as sfrsport... from the ISP SFR: [https://fr.wikipedia.org/wiki/BFM_Sport](https://fr.wikipedia.org/wiki/BFM_Sport)

Thank you for the other channels ;)

**Comment by mocram** [comment]
The bfmsport logo was indeed not OK according the rules, that's why charles left it out.
