### ISSUE TITLE
Non Stop People

### ISSUE THREAD

**Issue by Jglez3** [picons/picons-source#221]
This was probably not seen in my last issue, so here I am again.

This channel, at least in Spain, has a new logo.

The bad news... I couldn't find a good quality logo, I hope you can.

http://www.movistarplus.es/canal/non-stop-people?id=NONSTP

`donkey monkey got issued`

**Comment by mcfly822** [comment]
[nonstoppeople.default.zip](https://github.com/picons/picons-source/files/1533283/nonstoppeople.default.zip)

**Comment by Jglez3** [comment]
Hey @mcfly822 

If you check the page I linked, you'll be able to see that the logo is different. Black on top and pink on bottom.

I don't know if it's the same logo for all the providers or this one is just for the Movistar+ (Spain) platform.

**Comment by mcfly822** [comment]
@Jglez3 Yes, I see, but the official website: http://www.non-stop-people.com/ has the logo which I provided. Top pink, black bottom.
If my logo is not good or acceptable, just skip/ignore it. No problem :)

**Comment by dalmore72** [comment]
original from nonstoppeople.es  
[NonStopPeople-Main.zip](https://github.com/picons/picons-source/files/1534376/NonStopPeople-Main.zip)
:)

**Comment by mcfly822** [comment]
Ok, so this logo should be used.
And everything is good, no resolution problem, it is svg file.

**Comment by Lexzie** [comment]
Please also update snp.index:

**Add to snp.index**
```
nonstopeople=nonstoppeople
```
