### ISSUE TITLE
Problem with new SKY logos

### ISSUE THREAD

**Issue by mcfly822** [picons/picons-source#223]
Hello,

there is problem with some new sky logo (mostly from commit https://github.com/picons/picons-source/commit/40eb0075694d0aff38f24f2688a68e07617c771a )
The generated pngs are weird.

For example:
![skyspnews](https://user-images.githubusercontent.com/22531870/33713691-86c5980a-db4c-11e7-9b77-7e2b614c5836.png)
![skysportscricket](https://user-images.githubusercontent.com/22531870/33713692-86e24b26-db4c-11e7-8cdf-6296106547da.png)
![skysportsfootball](https://user-images.githubusercontent.com/22531870/33713694-86ff01a8-db4c-11e7-8d3c-211df8f88e99.png)
![skysportspl](https://user-images.githubusercontent.com/22531870/33713696-872c58b0-db4c-11e7-8f6c-22d8d5432e64.png)
![skysportsaction](https://user-images.githubusercontent.com/22531870/33714024-c24d6cbc-db4d-11e7-95a4-f48dace4d67d.png)

**Comment by mocram** [comment]
Don't you mean commit ea9f6a852fb69de623775028f71d6ffb6050df64

**Comment by AbuBaniaz** [comment]
Those sports logos were added many weeks ago. Strange that the issue has come about now. Ill double check them.

**Comment by mcfly822** [comment]
@mocram no, at this commit there are no sky sport logos. The problem is with the logos in commit what I linked.
@AbuBaniaz yes, many weeks ago, but you checked them after adding, and were them okay?

**Comment by AbuBaniaz** [comment]
The following need fixing. I tried with inkscape, save as optimised, but it did not work. This worked for other logos before. The HD version of the same logos do not have the problem.

```
skysportsarena.default.svg
skysportscricket.default.svg
skysportsf1.default.svg
skysportsfootball.default.svg
skysportsgolf.default.svg
skysportsmainevent.default.svg
skysportsmix.default.svg
skysportsnews.default.svg
skysportspremierleague.default.svg
```
[to be fixed.zip](https://github.com/picons/picons-source/files/1539406/to.be.fixed.zip)

**Comment by AbuBaniaz** [comment]
Whilst we are here, shall we use the two tier logos instead?

**Comment by mocram** [comment]
Do I feel stupid now 😀 was mixing stuff up.

Two tier logos? You lost me...

**Comment by mcfly822** [comment]
Here are the fixed svgs.
[fixed.zip](https://github.com/picons/picons-source/files/1540550/fixed.zip)

**Comment by AbuBaniaz** [comment]
@mcfly822 Can you do `skysports.default.svg` too please? I missed it from the attachment.

@mocram, sorry bad description on my part. text on two levels as in the attachment.
[two tier.zip](https://github.com/picons/picons-source/files/1540625/two.tier.zip)

**Comment by mcfly822** [comment]
Sure.
[skysports.default.zip](https://github.com/picons/picons-source/files/1540874/skysports.default.zip)

**Comment by mcfly822** [comment]
@AbuBaniaz , thanks for the commits!

**Comment by AbuBaniaz** [comment]
Shall we use the other logos I uploaded?

**Comment by mocram** [comment]
Regarding two tier, I think it will improve readability, so sure go ahead.

**Comment by mcfly822** [comment]
Agree.
