### ISSUE TITLE
Italian channels logo: some updates

### ISSUE THREAD

**Issue by axlt2002** [picons/picons-source#223]
Hi,
Please find at the following [link](http://imgur.com/a/IpdIN) some logo to be updated. In particular:

- Rai 1, 2, 3 and 4 (including HD versions): corrected colors
- Iris: removed the artifacts that are visible in the current version
- Sportitalia: better quality with a slightly modified font
- Focus: updated logo (new colors and "F" font)

I would be glad if you can take them into consideration.

Thanks as usual for your effort.

**Comment by charlesduco** [comment]
Please check if the logos are okay now.

**Comment by axlt2002** [comment]
Hi charlesduco,
Thanks for considering the updates.
Actually the only two that need refinements are Focus and Iris. The first one should be white over a red background; the second (now the dimension is perfect) should be in "gold style".
For your convenience I have edited a little the two logos so that you have just to put them in the resources folder to be compiled. You can find them [here](http://imgur.com/a/woyoN) (just enlarge each one and copy on your desktop).
Thanks and have a nice day.

**Comment by charlesduco** [comment]
The "gold style" Iris logo doesn't meet the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md), the transparency is not okay on a white background.
I have no transparent source for it and I prefer to use the "clean" black-white versions instead.

**Comment by axlt2002** [comment]
Thanks charlesduco!
Honestly I didn't catch very well the issue of the "gold style" but I completely trust in your excellent experience in this work.
I'm going to close the issue then. And thanks for updating Focus Tv logo.
Keep in touch!
