### ISSUE TITLE
Wrong logo for MTV Brand New

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#227]
I saw the channel MTV Brand New is using the standard MTV logo.
This is because of a wrong extra link in snp.index.
Furtermore the srp-link for Delta cable is missing.

**Please delete from snp.index**
```
mtvbrandnew=mtv
```
**Please add to srp.index**
```
4269_11_10EF_FFFF0000=mtvbrandnew
```
`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
The logo is correct. The link is wrong

**Comment by Lexzie** [comment]
Sorry, that's what I meant.

Thanks for correcting this!
