### ISSUE TITLE
HRT logos

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#228]
I saw that the logos are of poor quality and not all are the current logos.
I only found svg's for HRT TV1 and HRT TV2, I hope someone can make the HRT TV3 and HRT TV4?
[HRT1+2.zip](https://github.com/picons/picons-source/files/1545198/HRT1.2.zip)
Examples for HRT TV3 and HRT TV4:
![afbeelding](https://user-images.githubusercontent.com/14023349/33800443-febfdd76-dd3f-11e7-82d2-1bb251570571.png)![afbeelding](https://user-images.githubusercontent.com/14023349/33800439-f5671be0-dd3f-11e7-813f-6b5d19ebf392.png)

Note: Although the logos should be named `hrt1` respectively `hrt2`, I used these names because it's also the name of the existing logos in the source.

**Comment by mcfly822** [comment]
I see in many sites, that hrt3 and hrt 4 use another logo, not like hrt1 and 2.
For example:
https://de.wikipedia.org/wiki/Hrvatska_radiotelevizija

And on the croatian national DVB-T provider's site (OIV), there is also these logo variations:
http://www.oiv.hr/broadcasting/tables/dtv_channel_hr.aspx

So, should we use the hrt1-2 like logo for 3 and 4, or the "official", different logos?

**Comment by Lexzie** [comment]
All the same kind logos. That was kinda the whole idea for replacing the logos.
If Wikipedia or a DVB-T provider uses certain logos that would not necessary have to mean those are the official ones.
If you look at Logopedia, you'll see that the HRT3 logo you found is used until 2016 (http://logos.wikia.com/wiki/HRT3) and the one for HRT4 until 2014 (http://logos.wikia.com/wiki/HRT4).

Unfortunately [the website of HRT](http://www.hrt.hr) doesn't show the individual logos.

These are the logos used onscreen on Eutelsat 16A by HRT-TV:
![afbeelding](https://user-images.githubusercontent.com/14023349/33833780-11d74222-de81-11e7-8ade-5913765ccc00.png) ![afbeelding](https://user-images.githubusercontent.com/14023349/33833968-aead6478-de81-11e7-8e42-109ce59daf43.png) 
![afbeelding](https://user-images.githubusercontent.com/14023349/33833758-f2bc0b70-de80-11e7-889a-0d9cd221a531.png) ![afbeelding](https://user-images.githubusercontent.com/14023349/33833713-d4c57f70-de80-11e7-8bc8-d2467e4e9708.png)

Even on Teletext they use those logos:
![afbeelding](https://user-images.githubusercontent.com/14023349/33833917-827ba644-de81-11e7-8950-d4539ce5267a.png)![afbeelding](https://user-images.githubusercontent.com/14023349/33834037-eae4b9a0-de81-11e7-9053-b94cb50ecba1.png)

**Comment by mcfly822** [comment]
Ok, this was what I need to know, which logo appears on screen. So, the HRT3 and HRT4 vector logo need to make.
If I will have time tomorrow, I will draw them. (I also didn't find them in vector format).

**Comment by mcfly822** [comment]
@Lexzie I had a little time tonight, so I made them :)

I didn't rename 'hrttv' to 'hrt', if anyone wants, lets do it. But then it is needed to update the indexes (snp & srp) also.

**Comment by Lexzie** [comment]
I agree, no need to do extra work.

I have some more logos for Croatian Public Radio.

Some might need some polishing/converting to svg.
If it cannot be done and quality is too low, just don't upload them to the source.
(Especially HRT-HR3 I could not find anything better).
HRT-HR1 is already an svg in the source.  (picons-source/build-source/logos/hrthr1.default.svg)

[HRTradio.zip](https://github.com/picons/picons-source/files/1549866/HRTradio.zip)

**Comment by mcfly822** [comment]
I made svg for hr2 and hr3, and resized the catholic radio logo.
[HRTradio_mcfly822.zip](https://github.com/picons/picons-source/files/1553297/HRTradio_mcfly822.zip)

I think that the local version only for PULA is irrelevant, if we pick it to the repo, we shold pick all local versions...
HR Dubrovnik
HR Knin
HR Osijek
HR Pula
HR Rijeka
HR Sljeme 
HR Split
HR Zadar

**Comment by Lexzie** [comment]
Pula is the only one on satellite.

**Comment by mcfly822** [comment]
Ok, I didn't know this.
But I don't find the appropriate font for text. I can draw without it, but it would be better to know which font should I use...

**Comment by Lexzie** [comment]
I don't know how to know which font it is. In my opinion if you have a font quite similar just use it,
Otherwise, too bad for that logo. Could you or did you already made a pull request for the radio logos?

**Comment by mcfly822** [comment]
Ok, I'll try to find a similar font (maybe tomorrow, hope I have time for this). After that, I'll upload all the radio logos.

**Comment by mcfly822** [comment]
I uploaded the radio logos.
@Lexzie , please provide _.index_ entries.

**Comment by Lexzie** [comment]
I hope here is okay or maybe a new issue?

**Please add to snp.index**
```
hrthr1=hrthr1
hrthr2=hrthr2
hrthr3=hrthr3
hrtrpula=hrtradiopula
htv1=hrttv1
htv2=hrttv2
htv3=hrttv3
htv4=hrttv4
hkr=hrvatskikatolickiradio
```

**Please add to srp.index**
```
389_4E84_16E_A00000=hrthr1
38A_4E84_16E_A00000=hrthr2
38B_4E84_16E_A00000=hrthr3
38D_4E84_16E_A00000=hrtradiopula
385_4E84_16E_A00000=hrttv1
35D_C3B4_16E_A00000=hrttv1
709_C5A8_16E_A00000=hrttv1
127_2_40_A00000=hrttv1
386_4E84_16E_A00000=hrttv2
35E_C3B4_16E_A00000=hrttv2
70A_C5A8_16E_A00000=hrttv2
128_3_40_A00000=hrttv2
387_4E84_16E_A00000=hrttv3
714_C5A8_16E_A00000=hrttv3
C6_3_40_A00000=hrttv3
388_4E84_16E_A00000=hrttv4
732_C5A8_16E_A00000=hrttv4
38E_4E84_16E_A00000=hrvatskikatolickiradio
```

`donkey monkey got issued`
