### ISSUE TITLE
Modifying some logos - POLL

### ISSUE THREAD

**Issue by mcfly822** [picons/picons-source#229]
Regarding the opinions I read here recently, I made alternative variations for some logos. I'd like to ask you, which one is better - the existing or the modified. I don't want to decide alone.

**1. Discovery Science**
Existing
![discoveryscience](https://user-images.githubusercontent.com/22531870/33805457-9c72c1e0-ddb9-11e7-8755-59c7f936e505.png)
Modified
![discoveryscience](https://user-images.githubusercontent.com/22531870/33805462-b0c90672-ddb9-11e7-86db-9da86b13194b.png)

**2. Discovery Science HD**
Existing
![discoverysciencehd](https://user-images.githubusercontent.com/22531870/33805469-cb755b42-ddb9-11e7-88cd-387d2e214838.png)
Modified
![discoverysciencehd](https://user-images.githubusercontent.com/22531870/33805472-d210eb56-ddb9-11e7-878d-d79410de81df.png)

**3. Fishing&Hunting**
Existing
![fishingandhunting](https://user-images.githubusercontent.com/22531870/33805521-af9eb71e-ddba-11e7-8aa3-f1e488d38253.png)
Modified
![fishingandhunting](https://user-images.githubusercontent.com/22531870/33805512-8f3d2fa0-ddba-11e7-8ad7-6fb7914db082.png)

**4. Non Stop People**
Existing
![nonstopeople](https://user-images.githubusercontent.com/22531870/33805482-f44232fc-ddb9-11e7-9510-4835895cb20e.png)
Modified
![nonstoppeople](https://user-images.githubusercontent.com/22531870/33805485-fbc2e5c6-ddb9-11e7-9c42-1fd78244c8e7.png)

Please write the number (1-4) and then "existing" or "E" if leave the existing one in repo, or "modified" or "M"if the new one would better.

Thanks in advance 😉 

p.s. If this kind of issue (making a poll) is not allowed or not supported, I will close the issue immediately and don't make in the future.

**Comment by mocram** [comment]
Modified

**Comment by Lexzie** [comment]
Modified

**Comment by AbuBaniaz** [comment]
1&2 = E (no objection if you change it though)
3&4 = M

**Comment by mcfly822** [comment]
Thaks for the votes! No more? Maybe @charlesduco ?
I will close this issue tomorrow evening.
