### ISSUE TITLE
Schweiz 5

### ISSUE THREAD

**Issue by pwallner** [picons/picons-source#23]
found a svg logo for schweiz 5

```3401_3ED_1_C00000=schweiz5```

Please rename *.txt to *.svg (how can I upload a zip file without any error?)
[schweiz5.default.svg.txt](https://github.com/picons/picons-source/files/975304/schweiz5.default.svg.txt)

**Comment by charlesduco** [comment]
Zip uploading works fine. 
Maybe you're creating a wrong file format: https://www.google.com/webhp#q=how+to+make+a+zip+file
[schweiz5.default.svg.zip](https://github.com/picons/picons-source/files/975392/schweiz5.default.svg.zip)
