### ISSUE TITLE
M. eSports

### ISSUE THREAD

**Issue by Jglez3** [picons/picons-source#231]
Movistar+ added a new channel today.

```
76C5_40E_1_C00000=mesports
```

The reference could be this one or movistaresports, your choice.

Logo's here: 
http://www1.movistarplus.es/canal/M.+eSports/ESPORT
http://logos.wikia.com/wiki/Movistar_eSports

Thanks!

`
donkey monkey got issued
`

**Comment by mocram** [comment]
Too bad only the familiar faces know how to read :-)
