### ISSUE TITLE
channel itele renamed - new picon exists already

### ISSUE THREAD

**Issue by pexner** [picons/picons-source#239]
The channel `itele` was renamed to `cnews` on multiple sats and cable.
The frequencies/service references didn't change.
The new `cnews.default.svg` picon exists already in the repo.
The `itele` picons (`.default` and `.light`) can be deleted.

How does a "good" issue has to look like for a situation like this?
Do i have to put all service references again?
Or could you make a search/replace/g on your side?
I didn't find an example in the CONTRIBUTING section for a situation like this.

`donkey monkey got issued`

**Comment by pexner** [comment]
Maybe this should do?

for srp-index
```
4469_1F40_13E_820000=itele
13C_3E1C_13F_820000=itele
226A_438_1_C00000=itele
4469_1F40_13E_820000=itele
```

for snp-index
```
itele=cnews
itelehd=cnews
```

```donkey monkey got issued```

**Comment by mocram** [comment]
See https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md#samples

If you really want something to be removed add it in a seperate block which clearly says that it has to be removed and hope it's done. If it's in a PR it will probably be merged if correct.

The `donkey monkey got issued` is only for first time posters that have a tendancy to tell their life story about how their favorite channel has a missing or wrong picon, all rambled into one long sentence/confusing issue. Then they go back to their couch in the hope it will show up the next day. Some to be never heard of again.
