### ISSUE TITLE
cnewshd=cnews

### ISSUE THREAD

**Issue by pexner** [picons/picons-source#240]
snp
```
cnews=cnews
cnewshd=cnews
```

**Comment by mocram** [comment]
@AbuBaniaz What's your opinion on this one?

**Comment by pexner** [comment]
there's a channel "cnews hd" which has the same picon as "cnews".

**Comment by AbuBaniaz** [comment]
There is no need to include the reference.
```
cnewshd=cnews
```

If we add just 
```
cnews=cnews
```
the cnews picon will show for both cnews and cnewshd. This applies to ***all*** E2 images that have adopted the SNPicon code.

**Comment by mocram** [comment]
If both cnews hd and cnews sd use the same logo, it could be allowed in see https://github.com/picons/picons-source/pull/229#issuecomment-282321460

It seems we are somewhat in a transition phase of not differentiating hd/sd anymore, correct?

**Comment by AbuBaniaz** [comment]
In life, we do things to achieve a goal. If the goal is achieved by one thing, I don't see the purpose of doing two things. Less is more!

We want the cnews logo to show for cnewshd and cnews. That is achieved by the one entry. There is no need for two.

The comment you made in the other issue is slightly misleading in that it suggests only OpenViX will do this. **All** Enigma2 images that have adopted the SNP code do this.

This is your project. If you decide to add them in, I will respect your decision.

**Comment by mocram** [comment]
I don't really care if it's added or not, I was just mentioning that if it isn't wrong it could get added. OpenVIX or anyother image using SNP falling back to the sd image, doesn't give it the status "wrong" inside this project. Therefor it is allowed to add it.

The added redundancy by doing two things, will become clear in the future if something has to change, being lazy will get you one way or the other.

If we generate a servicelist with missing/non missing picons, it will show up as missing, so as far as this project is concerned, the goal is not achieved.

Just my 2 cents, I'm back to being lazy now.... :-)
