### ISSUE TITLE
missing/changed SRP unitymedia

### ISSUE THREAD

**Issue by pommesfrites** [picons/picons-source#242]
missing Picons:
```
eoTV                                  |  4AAD_BF_270F_FFFF0000=--------
Kinder                                |  2B75_BF_270F_FFFF0000=--------
MOTORVISION TV HD        |  AC4B_1B9_270F_FFFF0000=--------
ntv HD                               |  C79E_79_270F_FFFF0000=--------
ZDF_neo HD                       |  A08F_191_270F_FFFF0000=--------
```
changed Picons:
```
E2F8_245_270F_FFFF0000=anixehd
E2F7_245_270F_FFFF0000=eentertainmenthd
759F_1CD_270F_FFFF0000=ertworld
6F24_431_A401_FFFF0000=rbbinforadio
B02F_1C3_270F_FFFF0000=juwelotvhd
46C6_B5_270F_FFFF0000=mtv
A475_1A5_270F_FFFF0000=natgeowildhd
BBE5_1E1_270F_FFFF0000=ntvmir
AC58_1FF_270F_FFFF0000=ocko
206_1_85_FFFF0000=romancetv-wispelutri
5A45_E7_270F_FFFF0000=rtvd
9CA8_191_270F_FFFF0000=sportdigitalhd
6215_F1_270F_FFFF0000=tvn24
```

**Comment by upwhatever** [comment]
More missing Unitymedia (BW) SRPs, most are radio channels:

`8B2A_172_A018_FFFF0000=regiotv
AC66_1F5_270F_FFFF0000=oe1
AC67_1F5_270F_FFFF0000=oe2vorarlberg
AC68_1F5_270F_FFFF0000=oe3
AC69_1F5_270F_FFFF0000=domradio
AC71_1F5_270F_FFFF0000=nrj
AC73_1F5_270F_FFFF0000=antennebayern
AC74_1F5_270F_FFFF0000=radiosrf1
AC75_1F5_270F_FFFF0000=srf2kultur
AC76_1F5_270F_FFFF0000=radiosrf3
AC77_1F5_270F_FFFF0000=swissclassic
AC78_1F5_270F_FFFF0000=swisspop
AC79_1F5_270F_FFFF0000=swissjazz
B03A_1F5_270F_FFFF0000=rtlradio
B419_1F5_270F_FFFF0000=tf1`

**Comment by mocram** [comment]
https://github.com/picons/picons-source/blob/master/.github/CONTRIBUTING.md

**Comment by AbuBaniaz** [comment]
I have added some links in this commit
https://github.com/picons/picons-source/commit/b884cc672e503c3827be1fbdb0ae0a8dd20678aa

Link + logo = picon

If you want kinks added, please say, "please add these links".
If you want logos and links added, please attach the logos and say so.

**Comment by upwhatever** [comment]
Thank you for the srp links, please add these logos and links:

srp.index
```
893A_172_A018_FFFF0000=ltv
AC59_1F5_270F_FFFF0000=planetradio
AC6C_1F5_270F_FFFF0000=dieneue1077
AC6E_1F5_270F_FFFF0000=radioregenbogen
AC6F_1F5_270F_FFFF0000=dieneuewelle
AC70_1F5_270F_FFFF0000=antenne1
AC72_1F5_270F_FFFF0000=radioton
AC7D_1F5_270F_FFFF0000=alternativefm
AC7E_1F5_270F_FFFF0000=rocklandradio
```

snp.index
```
ltv=ltv
planetradio=planetradio
dieneue1077=dieneue1077
radioregenbogen=radioregenbogen
dieneuewelle=dieneuewelle
antenne1=antenne1
radioton=radioton
alternativefm=alternativefm
rocklandradio=rocklandradio
```

Logos: [logos.zip](https://github.com/picons/picons-source/files/1592174/logos.zip)

@pommesfrites: Sorry for hijacking your issue, I should have opened a separate one for my additions.

**Comment by AbuBaniaz** [comment]
@mcfly822 
Can you have a look at making these logos in svg format please? (Some are already)

**Comment by mcfly822** [comment]
Yes, but later (maybe on weekend).

**Comment by mcfly822** [comment]
Here are the logos.
I think alternative fm and rockland radio is good in png, it is unnecessary to make in svg, a lot work, but not much less in file size and the png resolution also acceptable.
I made a little correction in altenativefm, the white strip on the right side removed.
The other logos are the same as in @upwhatever 's attached zip.

[issue242_mcfly822.zip](https://github.com/picons/picons-source/files/1606786/issue242_mcfly822.zip)
