### ISSUE TITLE
HRT 5 logo

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#243]
First of all I wish everyone and your loved ones all the best for the new year!

I saw the hrttv logos aren't in the same size ratio, so I made them evenly sized.
Could the logos be replaced?
[HRT1-4(20180101).zip](https://github.com/picons/picons-source/files/1596516/HRT1-4.20180101.zip)

HRT has started a fifth channel, logo design is just like the logos of hrttv1-4.
Screenshot:
![afbeelding](https://user-images.githubusercontent.com/14023349/34471810-6d178124-ef52-11e7-845e-c5d7dbf7fcd3.png)

@mcfly822 could you make the hrttv5 logo?

When submitting please add:

**snp.index**
```
hrthtv5=hrttv5
```

**srp.index**
```
38F_4E84_16E_A00000=hrttv5
522_3D54_13E_820000=hrttv5
```
`donkey monkey got issued`

**Comment by mcfly822** [comment]
@Lexzie , thanks, the same best for you and for everyone here for the new year!
Here are the HRT 5 logos:
[hrt5_mcfly822.zip](https://github.com/picons/picons-source/files/1600367/hrt5_mcfly822.zip)

**Comment by Lexzie** [comment]
Thank you for making the logo.
I resized all five logos to resemble each other.
[HRT1-5(20180103).zip](https://github.com/picons/picons-source/files/1601020/HRT1-5.20180103.zip)

Can anyone submit these logos by replacing `hrttv1-4` and adding `hrttv5`?


**Please add to snp.index**
```
hrthtv5=hrttv5
```

**Please add to srp.index**
```
38F_4E84_16E_A00000=hrttv5
522_3D54_13E_820000=hrttv5
```
`donkey monkey got issued`

**Comment by Lexzie** [comment]
Great! Thanks!
