### ISSUE TITLE
srp.index update 28.2

### ISSUE THREAD

**Issue by leec32** [picons/picons-source#245]
please update srp.index 28.2 
```
1968_7E6_2_11A0000=gold
1DB5_82D_2_11A0000=goldplus1
F1B_7EB_2_11A0000=goodfoodhd
1DCA_82D_2_11A0000=goodfoodplus1
EE8_7E8_2_11A0000=skycinemadramaandromancehd
F3D_7E0_2_11A0000=skycinemaselecthd
F64_7D8_2_11A0000=skysportsarenahd
1B60_7DA_2_11A0000=mtvclassic
1B5A_7DA_2_11A0000=vh1
D747_82F_2_11A0000=hearttv
```

If someone could please make the logo for this.

http://tv.sky.com/logo/00/00/skychb3682.png
`D74A_82F_2_11A0000=now90s`

thank you

`donkey monkey got issued`

**Comment by leec32** [comment]
@AbuBaniaz can you check `EE8_7E8_2_11A0000=skycinemadramaandromancehd` please as it is showing the old version for some reason.

thanks

**Comment by AbuBaniaz** [comment]
Link + Logo = Picon

Link is fine. I changed the logo for newer type last night.
