### ISSUE TITLE
New channels 16/03/2017

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#245]
Hello,

Can you please add:

Urdu 1
```
https://www.urdu1.tv/
```
SRP&SNP
```
C4EA_837_2_11A0000
```

Quest red
```
http://tv.sky.com/logo/0/0/skychb2411.png
```

SRP
```
CD46_844_2_11A0000
```

SNP
```
questred
```

Quest red +1
```
http://tv.sky.com/logo/0/0/skychb4547.png
```

SRP
```
CD4C_844_2_11A0000
```
SNP
```
questredplus1
```

sky monsters
```
http://tv.sky.com/logo/0/0/skychb1807.png
```
SNP
```
skymonsters=skycinemamonsters
```

New logo for motorsport tv
```
http://tv.sky.com/logo/0/0/skychb3735.png
```
SRP
```
D01C_83F_2_11A0000
```
SNP
```
motorsporttv
```

Can you also add these new cahnensl to SNP index file

```
76C4_40E_1_C00000=movistardisneyprincess
4228_3DB8_13E_820000=vividtouch
3EC_5_AA_5A0000=sirinatvhd
```

Many thanks

`donkey monkey got issued`

**Comment by charlesduco** [comment]
Please combine all entries to snp-index and srp-index next time, much easier to copy-paste, just like the samples on the contributing page: https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md#samples
