### ISSUE TITLE
1_0_1_ vs 1_0_19_

### ISSUE THREAD

**Issue by vpont** [picons/picons-source#247]
Hi there,

I notices some picons are missing in my box because of different "prefix".
The symlinks are like "1_0_1_" when in my services they appear as "1_0_19_" thus, not showing up correctly.
I remember reading some discussion about this a while back.
@mocram what was the problem causing this?
Thanks!

**Comment by AbuBaniaz** [comment]
It depends on your image or picon renderer if there is a separate one.

Most will treat 1,2 and 19 the same

**Comment by vpont** [comment]
Nevermind.
Checking out create-symlinks.sh I found out I should be using "srp" option instead of "srp-full" which creates the symlinks based on info from srp.index
