### ISSUE TITLE
Logo addition request

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#247]
Hello
Can you add the following channel logos please?

cbsactionplus1
sewingquarter

These cable ones too. Ignore the numbers, I have just added them to aid finding them

400 virgin movies
836 NDTV India
837 NDTV Spice
198 Youtube

```
https://www.freeview.co.uk/tv-guide
https://f2d78c226c9f792968c8-c9730d8d68a82b7a6046ad5bfa4ad816.ssl.cf3.rackcdn.com/3/channel/bds-sewingquarter.png
https://f2d78c226c9f792968c8-c9730d8d68a82b7a6046ad5bfa4ad816.ssl.cf3.rackcdn.com/3/channel/bds-cbsactionP1.png

http://anywhere.virginmedia.com/tv-listings/
```
I shall add the references in a pull request

Thanks in advance

`donkey monkey got issued`

**Comment by charlesduco** [comment]
I didn't find a good quality logo for NDTV Spice.

**Comment by AbuBaniaz** [comment]
Many thanks.

I could only find NDTV, not NDTV Spice
```
https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/NDTV_logo.svg/1000px-NDTV_logo.svg.png
```
For info, the logo on TV looks like this
![ndtv spice](https://cloud.githubusercontent.com/assets/6644489/24316197/13158baa-10e4-11e7-95ba-3e8af6bdf7c8.png)

**Comment by Jasmeet181** [comment]
I have it in my set: 
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/TV/Source/NDTV%20Spice.svg

**Comment by AbuBaniaz** [comment]
I think we have found a gold mine! 
@charlesduco @mocram 
Apart from names, is the quality of the following logos OK?

```
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/TV/Source/NDTV%20India.svg
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/TV/Source/NDTV%20Spice.svg
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/TV/Source/New%20Vision%20TV.png
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/Future/Jus%20Punjabi.svg
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/Radio/Source/Ahomka%20Radio.png
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/Radio/Source/Absolute%20Classic%20Rock.svg
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/Radio/Source/Desi%20Radio.png
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/Radio/Source/Heart%2080s.svg
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/Radio/Source/Heat%20Radio.svg
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/Radio/Source/Kanshi%20Radio.png
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/Radio/Source/Liberty%20Radio.svg
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/Radio/Source/Radio%20Khushkhabri.png
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/Radio/Source/Newstalk.svg
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/Radio/Source/Planet%20Rock.png
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/Radio/Source/Panjab%20Radio.png
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/Radio/Source/RNIB%20Connect%20Radio.svg
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/Radio/Source/Sukh%20Sagar%20Radio.png
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/Radio/Source/UCB%20Ireland.svg
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/Radio/Source/WRN%20Broadcast.svg
```

**Comment by Jasmeet181** [comment]
Just to note, the SVGs aren't optimised and I'm using light coloured logos by default, not dark. If there's a dark version it has a ' - Dark' suffix in the filename.

**Comment by mocram** [comment]
@AbuBaniaz At first glance they seem OK, taking @Jasmeet181 remarks into account.

NOTE: Some of the png's are indeed less than 800px, but if no other logo is found besides a smaller one, you can still use that. The rules are mainly there because people tend to be lazy and when they are using a picon pack from someone else in 100x60, they provide those images, instead of quality ones. Even if a better one is found.

But as a last resort it could be used. It will obviously not look great on higher resolution picon packs.

**Comment by charlesduco** [comment]
I agree with @mocram. This project is voluntary and best effort based. So lower quality is still possible, > 800px is a target, no strict obligation. But < 100 px is unacceptable.

@ AbuBaniaz  Please provide a zip with correctly named logos to add to this project. I will look into it and do some graphic optimization if necessary.

**Comment by AbuBaniaz** [comment]
[20170330.zip](https://github.com/picons/picons-source/files/883224/20170330.zip)
I hope i got the light naming correct.

**Comment by charlesduco** [comment]
You got the light naming wrong but I fixed it.

**Comment by AbuBaniaz** [comment]
many thanks again
