### ISSUE TITLE
Picons are only for satellite?

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#249]
I noticed that a lot of channels available on (dutch) cable are not covered in this source.
Is it okay to add the names to the snp-index? For picons who are already in the source but have a slightly different name.
Maybe later when I know how to do that also add picons who are totally absent?
Or are only picons allowed for satellite channels?

**Comment by charlesduco** [comment]
Yes, it's okay to add new entries for cable channels to snp-index, but don't mess up the existing entries for the satellite channels.
You can also provide a list and sources for missing logos. I'll will add them if they meet the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md) or look for a better quality logo if I have time.

**Comment by Lexzie** [comment]
First of all, how do I check if a logo already exists? Just by looking in my own picons who were downloaded to my receiver? There are 2424 png-files in my picon/logo directory and 3927 files (symlinks) in the picon directory.
Of I have to download the whole source somewhere?

Are all the symlinks (for snp-picons) present in https://github.com/picons/picons-source/blob/master/build-source/snp-index ?
So, 4860 entries? (So, why do I have 3927 entries?)

I was told to put the missing names in the snp-index (https://github.com/picons/picons-source/blob/master/build-source/snp-index) on top of the file like this:

```
disneyxdhd_veronicahd=veronicahd_disneyxdhd
omroepzeeland=omroepzeeland
disneyxd_veronica=veronica_disneyxd
vrtcanvas=canvas
vrtcanvashd=canvashd
vrtketnetop12=ketnet
omroepbrabant=omroepbrabant
nauticalchannel=nauticalchannel
mtvvh1=vh1
mtvvh1classic=vh1classic
comedycentralfamily=comedycentralfamily
### first existing line ###

```
I read in the contributing rules I have to put them inside code blocks by using TRIPLE backticks? Or is that if I submit these lines in an issue (like this thread).

And I have to put the text 'donkey monkey got issued' above the ### first existing line ###?

And after that I have to submit a pull request?


About the logos:

A lot of logos are missing, I had already added them myself in my own receiver because a lot of them don't meet the contributing requirements. F.e. I almost never find a svg-file and resolution is almost never 800 px but I just want a logo, even if it's a bad one.

Can you give a example on how to submit missing logos?

Sorry for all these questions, but I guess this is the right place to correct missing logos and missing entries in the snp-index rather than that I correct them only on my own receiver.

I also have a lot of picons for IPTV and -radio streams.

**Comment by charlesduco** [comment]
Before contributing, you have to download the full repository and learn which logos and service entries exists already: https://github.com/picons/picons-source/blob/master/README.md
The first line of the readme explains it all:
`All the full resolution channel logos and their link to the actual channel (=serviceref) are kept up2date in this repository.`

About submitting logos, there are plenty of instructions in the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md) to know how to submit an issue:
`Logos should be inside an archive, correctly named (see below). Share the link.`

I'll add the missing service names you submitted to snp-index.
But you submitted service names that are already present in this repository, please check this before submitting.
```
omroepzeeland=omroepzeeland
omroepbrabant=omroepbrabant
comedycentralfamily=comedycentralfamily

**Comment by mocram** [comment]
If you want to see what is missing... generate a servicelist against your up2date channellist and look in the servicelist what is missing.

When submitting a PR none of that backticks and donkey monkey... applies. A PR should be correct 100% and you should be able to do that on your own. If you make a PR for some Python project you also don't start asking for an explanation how to write Python code and a git tutorial 101.

**Comment by Lexzie** [comment]
"But you submitted three service names that are already present in this repository, please check this before submitting:"

So why do I not have a picon for those channels?

**Comment by Lexzie** [comment]
If I get comments like the one above like 'read again' (because you are stupid) then I will stop and NOT contribute ANYTHING!
Like I said, in my receiver I already have all the picons because I entered them myself, now I'd like to do something for the community and I am not an supernerd so that I understand directly how everything works on GitHub. I find the GitHub very hard to understand, sometimes I feel like it is made so hard on purpose, so that only the few who understand it feel superior to others.
A little help please for those who are not so smart as you please!

**Comment by AbuBaniaz** [comment]
To find out which logos exist in the project, you will have to download the project and look at the logo directory.

If you look at the logo directory of picon packs you download, they only contain the created .png that were used during the build process.

> So why do I not have a picon for those?

Unless someone has a copy of your bouquet/lamedb files, difficult to say.

**Comment by mocram** [comment]
> Picons are only for satellite?

No, the picons are for DVB-S, DVB-C, DVB-T, IPTV, any other format in the future.

Closing this issue as resolved.
