### ISSUE TITLE
Logo Enjoy.tv

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#249]
Please upload this logo of Enjoy.tv and add the links.
[enjoytv(20180104).zip](https://github.com/picons/picons-source/files/1603781/enjoytv.20180104.zip)

https://www.lyngsat.com/tvchannels/nl/EnjoyTV.html
http://www.enjoytv.tv/

**snp.index**
```
enjoytv=enjoytv
```

**srp.index**
```
204_C364_9E_5A0000=enjoytv
```
`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
@mcfly822 Can you add this to your svg files too?

**Comment by mcfly822** [comment]
Yes.

**Comment by mcfly822** [comment]
I made the svg. The text is a little bit different as in the original, but really a little :smile_cat: 
[enjoytv.default.zip](https://github.com/picons/picons-source/files/1606792/enjoytv.default.zip)

**Comment by Lexzie** [comment]
I can't even see the difference.

Please add this logo to the source and add the links.
[enjoytv.svg.mcfly822.zip](https://github.com/picons/picons-source/files/1606801/enjoytv.svg.mcfly822.zip)


**snp.index**
```
enjoytv=enjoytv
```

**srp.index**
```
204_C364_9E_5A0000=enjoytv
```
`donkey monkey got issued`

**Comment by Lexzie** [comment]
Thanks!
