### ISSUE TITLE
XZ compression bug

### ISSUE THREAD

**Issue by Joannnn** [picons/picons-source#25]
Hello.
XZ command have a 'bug' with machines with less than 1GB of memory that are using newer versions of xz. The problem is caused because newer versions doesn't have a memlimit setup by default like older versions.

If you can, please add the option --memlimit=XX% (40% is a good one) because if not, all people who uses your repository need to modify the bashrc file to add an XZ_DEFAULTS option.

Thank you.

**Comment by picons** [comment]
Should be as requested...
