### ISSUE TITLE
RT France

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#250]
Who can make the RT France logo (in svg) from the standard RT logo?
Text should be white (instead of black) and the text 'F R A N C E' below RT.
Example:
![rt france](https://user-images.githubusercontent.com/14023349/34574285-40ab194e-f177-11e7-90b9-31dfedd09a43.png)

![afbeelding](https://user-images.githubusercontent.com/14023349/34574505-ddf96188-f177-11e7-9e14-8578fe84a20f.png)

If submitted, also add:
**snp.index**
```
rtfrance=rtfrance
```

**srp.index**
```
584_5398_55F_DDE0000=rtfrance
18EF_3F4_1_C00000=rtfrance
```
`donkey monkey got issued`

**Comment by mcfly822** [comment]
Here you are.
[rtfrance.default.zip](https://github.com/picons/picons-source/files/1604771/rtfrance.default.zip)

**Comment by Lexzie** [comment]
Thanks to the both!
