### ISSUE TITLE
logo request 20170401

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#251]
Another raid of @Jasmeet181 's repository
seetv should be fine.

I hope the others are acceptable, if not please ignore
[20170401.zip](https://github.com/picons/picons-source/files/887945/20170401.zip)

`donkey monkey got issued`

**Comment by Jasmeet181** [comment]
XXX Public Pickups was replaced with XXX HomeVids [yesterday](http://channelpedia.yavdr.com/gen/DVB-S/S28.2E/changelog.html), I don't have a logo for this yet.

XXX Mums has a [new logo](https://www.buyadultpack.com/frontend/assets/images/logos/xxx_mums.png), I'm not sure when it changed.

[https://github.com/Jasmeet181/mediaportal-uk-logos/blob/30b6cb7e17fd928d6d036467c4cc5eeb613738c1/TV/Source/XXX%20Mums.svg](https://github.com/Jasmeet181/mediaportal-uk-logos/blob/30b6cb7e17fd928d6d036467c4cc5eeb613738c1/TV/Source/XXX%20Mums.svg)

**Comment by AbuBaniaz** [comment]
I am now 5 commits ahead. If I submit a pull request, can you squash and merge instead of just merging?
https://github.com/blog/2243-rebase-and-merge-pull-requests

**Comment by mocram** [comment]
Like this https://github.com/picons/picons-source/commit/ab0fdaefcca6c9a19276ba0620c2afc9d457c8e5

**Comment by AbuBaniaz** [comment]
No. I had not created the request.  Anyway, you have added the references, so I will close the request.

Looks like I will have to trash my fork and start again. Again!

**Comment by mocram** [comment]
The end result would have been the same, I just created the PR for you. If you wanna keep your fork, you should create a branch based on master, do your work in that branch and create a PR based on that branch. After merging your PR, you can delete the branch and do a pull/update of your master and start over by creating another branch based on the new state of master.
