### ISSUE TITLE
New logos for French channels (5W)

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#251]
Please add these logos and links.
[France5W(20180104).zip](https://github.com/picons/picons-source/files/1604102/France5W.20180104.zip)

**add to snp.index**
```
mblive=mblivetv
sfrsat=sfr
```

**Add to srp.index**
```
13D9_3EA_1_C00000=mblivetv
B89_51A4_55F_DDE0000=mblivetv
581_5398_55F_DDE0000=sfr
```
`donkey monkey got issued`

**Comment by Lexzie** [comment]
Thanks!

**Comment by AbuBaniaz** [comment]
The following is returned:
This svg contains text or a png image: movistardisney.default.svg
This svg contains text or a png image: sfr.default.svg

**Comment by Lexzie** [comment]
I don't know what that means...sorry.

**Comment by mcfly822** [comment]
@Lexzie , there is problem with these svgs. They contains embedded images, which is not allowed.
The solution is make svgs wihout embedded images, or make them in png format.

I made the movistar disney logo in inkscape, and the sfr logo in gimp.
[issue251_mcfly822.zip](https://github.com/picons/picons-source/files/1607856/issue251_mcfly822.zip)

**Comment by Lexzie** [comment]
The Movistar Disney logo was not mine, by the way.
Thanks all of you.
