### ISSUE TITLE
CS Mini/CS Film/Horor Film

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#252]
Could someone combine these three logos to one logo?
 picons-source/build-source/logos/csmini.default.svg 
 picons-source/build-source/logos/csfilm.default.svg 
 picons-source/build-source/logos/hororfilm.default.svg 

Please name it `csmini_csfilm_hororfilm`.

There is allready a combined logo of CS Film/CS Mini: 
 picons-source/build-source/logos/csfilm_csmini.default.svg 

It is used with these links:
**Add to snp.index**
```
csminicsfilmhororfilm=csmini_csfilm_hororfilm
csfilmcsminihororfilm=csmini_csfilm_hororfilm
```

**Delete from srp.index**
```
7597_2BD_600_E080000=csfilm_csmini
75A1_2BD_600_E080000=ta3
```

**Add to srp.index**
```
482_76C0_16E_A00000=csmini_csfilm_hororfilm
4B4_76C1_16E_A00000=csmini_csfilm_hororfilm
7597_2BD_600_E080000=csmini_csfilm_hororfilm
75A1_2BD_600_E080000=csmini_csfilm_hororfilm
```
`donkey monkey got issued`

**Comment by mcfly822** [comment]
I made two variants. The 'vertical' is the common format in time-shared channels, all the logos are in a column (below each other).
But I think it would be better - as we discussed earlier with @mocram - that in this case the three logos would be in a 'triangle' layout, which is better for using in rectangular picons.
You can see the variants attached.
[csminicsfilmhororfilm_mcfly822.zip](https://github.com/picons/picons-source/files/1608249/csminicsfilmhororfilm_mcfly822.zip)

**Comment by Lexzie** [comment]
In my opinion the rectangular is better, otherwise it is getting to small.

**Comment by AbuBaniaz** [comment]
what about something like this? If agreeable, we would need a light version.
[csmini_csfilm_hororfilm_v2.default.svg.zip](https://github.com/picons/picons-source/files/1609461/csmini_csfilm_hororfilm_v2.default.svg.zip)

**Comment by mcfly822** [comment]
I found only two picons, which contains 3 time-shared channels:
https://github.com/picons/picons-source/blob/master/build-source/logos/donautv_isartv_trp1.default.svg
https://github.com/picons/picons-source/blob/master/build-source/logos/viasatnature_viasatcrime_playboytv.default.png
@Lexzie , you can see, none of them is in a vertical arrangement. You wrote, and this is is the problem, that the resulted picon getting too small in vertical arrangement.

@AbuBaniaz it is also good for me. (I don't watch this channel..)

**Comment by Lexzie** [comment]
In my opinion the combining of the two `CS` logos doesn't improve the 3 time-shared channel logo, because the width stays almost the same.
![afbeelding](https://user-images.githubusercontent.com/14023349/34650749-716e8e02-f3c6-11e7-83bd-60344bad5c46.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/34650776-b706c06a-f3c6-11e7-8d25-bc4bb13ba68e.png)

It would improve the existing `csfilm_csmini` logo though. That one has white backgrounds, is that right?
Existing logo:
![afbeelding](https://user-images.githubusercontent.com/14023349/34650785-d9f833ce-f3c6-11e7-8b74-2a8e7fd15ced.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/34650835-9daae604-f3c7-11e7-939b-ed725ac79b1f.png)

By the way, although the name of the 2 time-shared channel is `CS Film/CS Mini` I'd prefer the `mini` logo on top because `CS Mini` broadcasts in the morning and `CS Film` during the afternoon and evening.

In this zip-file all logos as I would prefer them, but I'm not the one who desides.
[CSMini-Film-Horor.zip](https://github.com/picons/picons-source/files/1609896/CSMini-Film-Horor.zip)

Changes to the links would then be:

**Delete from snp.index**
```
csfilmcsmini=csfilm_csmini
```

**Add to snp.index**
```
csfilmcsmini=csmini_csfilm
csminicsfilmhororfilm=csmini_csfilm_hororfilm
csfilmcsminihororfilm=csmini_csfilm_hororfilm
```

**Delete from srp.index**
```
1423_C85_3_EB0000=csfilm_csmini
36EA_C8C_3_EB0000=csfilm_csmini
7597_2BD_600_E080000=csfilm_csmini
75A1_2BD_600_E080000=ta3
```

**Add to srp.index**
```
36EA_C8C_3_EB0000=csmini_csfilm
482_76C0_16E_A00000=csmini_csfilm_hororfilm
4B4_76C1_16E_A00000=csmini_csfilm_hororfilm
7597_2BD_600_E080000=csmini_csfilm_hororfilm
75A1_2BD_600_E080000=csmini_csfilm_hororfilm
```
`donkey monkey got issued`

**Comment by mcfly822** [comment]
@Lexzie sorry, but the csmini_csfilm logo what you provided in the last zip file, is not good.
The aspect ratio is fault.
The original (existing) logos:
![cs_1](https://user-images.githubusercontent.com/22531870/34665432-6ba839c4-f460-11e7-9a35-cd2e59b5cc9c.png)

And your svg file:
![cs_2](https://user-images.githubusercontent.com/22531870/34665442-733498ea-f460-11e7-87eb-942947e06089.png)

You can see that your version is "compressed", not good.

**Comment by mcfly822** [comment]
I corrected the ratio:
![csmf](https://user-images.githubusercontent.com/22531870/34665858-24a52e54-f462-11e7-9086-d373f17462c0.png)

I think the logos now can be added. @AbuBaniaz , will you add the logos and the index changes, or may I add by a PR?

**Comment by Lexzie** [comment]
That one is even better, thanks!

**Comment by AbuBaniaz** [comment]
Sorry, missed the comment. I have merged pull request, so closing this.

**Comment by mcfly822** [comment]
No problem, thanks.
But the cs film logo changes, so we should update the logo in the repo. But now, it is impossible to use a big "CS" before "film" and "mini", because the word "CS" differs... 
Will this be good?
![g1321](https://user-images.githubusercontent.com/22531870/34825158-a24f7820-f6d1-11e7-9993-f2d449738ab2.png)
