### ISSUE TITLE
Missing/corrected links (mostly Scandinavian)

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#254]
Please accept these changes:

**Delete from snp.index**
```
primatvro=prima
svt2talandetextremsa=svt1
```

**Add to snp.index**
```
6erensd=6eren
lusitania=antena1lusitania
automotorogsporttv=automotorsport
comedycentralnorway=comedycentral
discoverychannelno=discovery
discoverychannelse=discovery
discoveryhungaryczech=discovery
discoverylifepoland=discoverylife-lichoridas
discoverycentraleuropehd=discoveryhd
discoveryhungaryhd=discoveryhd
discoverypolandhd=discoveryhd
discoveryturkeyhd=discoveryhd
disneychannelno=disneychannel
disneychannelse=disneychannel
echotvsvt=echotv
epicdrama=epicdrama
erox=eroxhd
esp1clean=eurosport1
esp1cleande=eurosport1
esp2blclean=eurosport2
esp2clean=eurosport2
esp2cleande=eurosport2
eurosportdk=eurosport2
eurosportdenmark=eurosport2
esp2panhd=eurosport2hd
historyhds=historyhd
kanal4=kanal4-pistohicra
kanal5dk=kanal5-pistohicra
natgeonorway=nationalgeographic
nickdk=nickelodeon
nickelodeonse=nickelodeon
noe=noetv
paramountcomedy=paramountcomedy
rtrmoldova=rtrmoldova_md
svt2talandetextremsa=svt2
svtb=svtb_svt24
svtbarnkanalen=svtb_svt24
svt24=svtb_svt24
svtbsvt24hdtext=svtb_svt24
explorespicefss=viasatexplorer_spice
viasathockeysdhd=viasathockey
viasatnatureeastfss=viasatnature
viasatsportsverige=viasatsport
```

**Delete from srp.index**
```
1F4B_319C_13E_820000=zdf
```

**Add to srp.index**
```
FF_66_53_CE40000=antena1lusitania
```

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
What is wrong with `primatvro=prima`

**Comment by AbuBaniaz** [comment]
why are you asking for `erox=eroxhd`

**Comment by AbuBaniaz** [comment]
>What is wrong with `primatvro=prima`

Never mind, seen the issue

**Comment by Lexzie** [comment]
> What is wrong with `primatvro=prima`

It's the wrong logo.
![afbeelding](https://user-images.githubusercontent.com/14023349/34626095-9fb0538e-f25b-11e7-837e-1a7b14ae26fc.png)
This is the channel, ([link](https://www.lyngsat.com/tvchannels/ro/Prima-TV.html)) checked also 31.5E/12012V and 1.0W/12687H, they have also the wrong logo.

**Please delete from snp.index**
```
prima=prima
```

I found the logo in svg, but in my opinion the 'p' should be white.

[prima.zip](https://github.com/picons/picons-source/files/1607835/prima.zip)


> why are you asking for `erox=eroxhd`

The channel is called Erox HD although on these two channels it is not in HD.

**Comment by AbuBaniaz** [comment]
We now have two logos: `prima.default.svg` and `primatv-priphuthas.default.svg` 

I will not be deleting `prima=prima`. It is correct as far as I can tell.

**Comment by Lexzie** [comment]
There was no logo named `primatv`, so if you're adding `tv` to the logo name you did not had to use `-priphuthas`, right?

The link `prima=prima` used to be for the SD channel on Astra 3B (23.5°E). (The link is still present in srp.index, `3355_C93_3_EB0000=prima` but that reference ID is totally not in use anymore).
That channel is not present in SD on Astra 3B anymore, only in HD with the name `Prima HD`.
That same channel is also broadcasting on three other satellites with the names `Prima HD` and `Prima TV`.
The name `Prima` is now only in use for the Romanian `Prima TV` (`primatv-priphuthas`).
Would you still prefer to keep `prima=prima`?
I will provide the snp. and srp.-links depending on your answer and on the name for the new logo.

**Comment by AbuBaniaz** [comment]
Can you please forget you mission to rename the logos. This is what has been a headache/obstacle/confusion  with your requests. Leave them and concentrate on linking references with logos, whatever the logos are called.  You do so much good work. If you forget your quest, the benefit to others will increase.

Does it matter what the logo is called? I tend to leave them as they are unless absolutely necessary or to avoid confusion. I added the suffix to make the logos distinctly different. yes I did not have to use the suffix, but I did. They are distinct, nobody can get confused. There are no hard and fast rules. Nobody's life depends on the logos having specific names.

If the channel has ceased broadcasting, surely the better thing to do would be to also delete the logo?  

Link +logo = picon. 

`prima=prima`  is/was used to create a picon called `prima.png` using a logo called `prima.default.svg`. The objective is to make the picons correct. If there is no longer a channel with an snp name `prima/primahd`, the picon won't be used.

Please submit any changes based on the current names. I have already committed the new logo.

**Comment by Lexzie** [comment]
Okay, I understand. By the way, I have no mission, it just was because I was told as long as there is no `tv` in the logo, it shouldn't be used in the name, so I already expected a name like `prima-priphuthas`, because the logo `prima` allready exists.
Anyhow, with the goal to have **picons** it indeed doesn;t matter how the logo is named.
Sorry.

This would be the links:

**Add to snp.index**
```
1FA6_1460_A7_13B0000=primatv-priphuthas
3EE_1_1_E08318F=primatv-priphuthas
1_1F4_5_A00000=primatv-priphuthas
```

**Add to srp.index**
```
1FA6_1460_A7_13B0000=primatv-priphuthas
3EE_1_1_E08318F=primatv-priphuthas
1_1F4_5_A00000=primatv-priphuthas
```
`donkey monkey got issued`

**Comment by mcfly822** [comment]
I think this issue is also done.

**Comment by Lexzie** [comment]
All picons okay now, thanks!
