### ISSUE TITLE
[Missing] SES Astra 2G - GN TV, GN Radio, Now90s

### ISSUE THREAD

**Issue by Corin-EU** [picons/picons-source#255]
SES Astra 2G at  28,2° East -- missing picons

--------------------

tv service: GN TV
(Groupe Nduom TV, not to be confused with GNTV Media Ministry)

Astra 2G transponder 78 DVB-S 11597 Vertical 22000 5/6
sid: 53525  vpid: 2305  apid: 2306 eng
reference 1_0_1_D115_832_2_11A0000_0_0_0

website at  https://www.groupenduom.com/
logo    at  https://www.facebook.com/gntvuk

--------------------

radio service: GN Radio
(Groupe Nduom Radio, currently transmitted with service label Ahomka RD, branding changed to GN Radio to match newly launched GN TV)

Astra 2G transponder 105 DVB-S 11224 Horizontal 27500-2/3
sid: 52090   apid: 2350 eng
reference 1_0_1_CB7A_839_2_11A0000_0_0_0

website at  https://www.groupenduom.com/
logo    at  https://tunein.com/radio/GN-Radio-UK-s188143/

--------------------

tv service: Now 90s 
(replaced Chilled TV, which was temporarily branded "Chilled 90s")

Astra 2G transponder 95 11553 Horizontal 22000-5/6
sid: 55114  vpid: 2560  apid: 2561 eng
reference 1:0:1:D74A:82F:2:11A0000:0:0:0

website at  http://www.nowmusic.com/
logo    at  http://www.nowmusic.com/news/now90stv/

--------------------

**Comment by AbuBaniaz** [comment]
Link +Logo = Picon

We already had the logos, the links were missing from the snp.index. I have added them now.

Please take the time to read the contributing guide.
