### ISSUE TITLE
[Request] SES Astra 2G -- HD variant picons for Arirang, Bloomberg Europe, Record TV Europa, RT, and TRT World

### ISSUE THREAD

**Issue by Corin-EU** [picons/picons-source#256]
SES Astra 2G at 28,2° East  -- request for HD variants of picons

It has been a while since most of these stations launched a service in HD, so it would be nice to have picons featuring the HD label for them.

--------------------

tv service:  Arirang HD

Astra 2G transponder 106 DVB-S2 11224 Vertical 23000 2/3
sid: 53150  vpid: 2309  apid: 2311 eng 
reference 1:0:19:CF9E:83A:2:11A0000:0:0:0

website at  http://www.arirang.co.kr/

--------------------

tv service:  Bloomberg Europe HD

Astra 2G transponder 104 DVB-S2 11686 Vertical 23000 2/3
sid: 55392  vpid: 2335  apid: 2336 eng, 2337 eng AC3
reference 1:0:19:D860:838:2:11A0000:0:0:0

website at  https://www.bloomberg.com/europe

--------------------

tv service:  Record TV Europa HD

Astra 2G transponder 99 DVB-S2 11612 Horizontal 23000 2/3
sid: 55405  vpid: 2321  apid: 2322 pt
reference 1:0:19:D86D:833:2:11A0000:0:0:0

website at  https://www.recordeuropa.com/

--------------------

tv service:  RT HD
Astra 2G transponder 106 DVB-S2 11224 Vertical 23000 2/3
sid: 53148  vpid: 2348  apid: 2349 eng
reference 1:0:19:CF9C:83A:2:11A0000:0:0:0

website at  https://www.rt.com/

--------------------

tv service:  TRT World HD
Astra 2G transponder 92 DVB-S2 11509 Vertical 23000 2/3
sid: 55273  vpid: 2320  apid: 2321 eng (AC3), 2322 eng
referemce 1:0:19:D7E9:82C:2:11A0000:0:0:0

website at  https://www.trtworld.com/

--------------------

**Comment by AbuBaniaz** [comment]
Please read the contributing guide.

None of those channels have HD on the onscreen logo. It is not an exact science. They can be added, but you have to provide the logos in zipped format. The websites do not event have the logos with HD

**Comment by mcfly822** [comment]
@Corin-EU Yes, AbuBaniaz is right. These channels has no HD logo, as far as I know.
So, if on the screen there is no 'HD' text in the logo, why should we make a new logo with 'HD' label...?

**Comment by AbuBaniaz** [comment]
Can we/you close this issue? The channels do not have HD in their logos.
