### ISSUE TITLE
New Channel Kabel Vodafone 

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons-source#257]
there is a change in the srp.index

from
1_0_1_CF0C_2714_F001_FFFF0000_0_0_0    |  MTV               | CF0C_2714_F001_FFFF0000=bloomberg
to
1_0_1_CF0C_2714_F001_FFFF0000_0_0_0    |  MTV               |  CF0C_2714_F001_FFFF0000=mtv

greats

**Comment by AbuBaniaz** [comment]
To avoid confusion, what needs to be done? The entries you have quoted do not exist in the srp.index

I prefer posts made in the following way:

Please change from x to y.  (This is where you specify the current entry and also the new entry) 
Please add x (This is where you specify the requested entry)
please delete x (This is where you specify the requested entry)

**Comment by AbuBaniaz** [comment]
I have changed
`CF0C_2714_F001_FFFF0000=bloomberg`
to
`CF0C_2714_F001_FFFF0000=mtv`

I hope that is what you mean
