### ISSUE TITLE
Sky Sport Bundesliga 8 HD

### ISSUE THREAD

**Issue by pwallner** [picons/picons-source#26]
Missing:
```147_10_85_C00000=skysportbundesliga8hd```

[skysportbundesliga8hd.default.svg.txt](https://github.com/picons/picons-source/files/975598/skysportbundesliga8hd.default.svg.txt)

**Comment by charlesduco** [comment]
Please follow the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md) and only submit missing or wrong logos:

> Logos should be inside an archive, correctly named. Share the link.
