### ISSUE TITLE
New logos for two new Skylink channels.

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#261]
Please accept these logos and links.

[Skylink.zip](https://github.com/picons/picons-source/files/1609972/Skylink.zip)

**Add to snp.index**
```
markizaplus1hd=markizaplus1hd
novaplus1hd=novaplus1hd
```

**Add to srp.index**
```
372D_C8E_3_EB0000=markizaplus1hd
372C_C8E_3_EB0000=novaplus1hd
```

`donkey monkey got issued`

**Comment by Lexzie** [comment]
The 'markizaplus1hd' picon is shown with a white background. The logo I provided ('markizaplus1hd.default.png') has transparent background.
Apparently something has gone wrong when changing it to svg?

I converted the png with Inkscape but don't know for sure if I did it right.

[markizaplus1hd(svg).zip](https://github.com/picons/picons-source/files/1629291/markizaplus1hd.svg.zip)

**Comment by mcfly822** [comment]
@Lexzie no-no ⛔️  It is not allowed to embed a raster (base64) image in svg.
Your logo contains embedded image...
(This causes also the problem with the background)

Here is the logo in svg.
[markizaplus1hd.default.zip](https://github.com/picons/picons-source/files/1630783/markizaplus1hd.default.zip)

**Comment by Lexzie** [comment]
As I already concluded that it was not done right. Filesize was much too big.
I guess I cannot do that in Inkscape. Great job @mcfly822 !
Can anyone with the rights to do please so replace the logo?

**Comment by Lexzie** [comment]
Picon is okay now, thanks!
