### ISSUE TITLE
Unitymedia

### ISSUE THREAD

**Issue by pommesfrites** [picons/picons-source#262]
SRP Index

Picon missing:
```
4AAD_BF_270F_FFFF0000=--------
```
Picon: https://upload.wikimedia.org/wikipedia/commons/3/3f/EO_TV_Logo.png

Picons missing + wrong name:
```
AC4B_1B9_270F_FFFF0000=motorvisiontvhd
```
Picon: https://cdn-007.mobile2morrow.com/wp-content/uploads/2017/04/MVTV_HD_Logo_2017_Schwarz_Hoch_RGB.PNG.png?x63310

```
 C79E_79_270F_FFFF0000=ntvhd
```
Picon: https://upload.wikimedia.org/wikipedia/commons/f/fd/N-tv-HD-September.svg

```
A08F_191_270F_FFFF0000=zdfneohd
```
Picon: https://www.telekom.de/is-bin/INTERSHOP.static/WFS/EKI-PK-Site/EKI-PK/de_DE/themen/senderwall/page/images/channel-wall/logos/senderlogo-zdfneo-hd.png

**Comment by mcfly822** [comment]
@pommesfrites my advice is that you should correct this issue regarding the contributing rules
https://github.com/picons/picons-source/blob/master/.github/CONTRIBUTING.md
otherwise the admins will deny and close this issue without questions...

**Comment by AbuBaniaz** [comment]
>>>
Changed Channel:
```
B420_1CD_270F_FFFF0000=gotv
```
must be:
```
B420_1CD_270F_FFFF0000=nhkworld
```

**Comment by AbuBaniaz** [comment]
I have done this
```C79E_79_270F_FFFF0000=ntvhd```

@mcfly822 
If you get a chance, can you make logos for the other two. We already have SD versions. I cant find a good logo for eotv

**Comment by AbuBaniaz** [comment]
I've committed the remaining ones. Thanks.
There is already a zdfneo.white I'll leave for Charles/Mocram to decide on it.

**Comment by charlesduco** [comment]
I agree with @mcfly822 on the light/white issue.

**Comment by mcfly822** [comment]
Thanks @AbuBaniaz !
Yes, we should only revert the .light logo to Charles' version, which I linked above.

**Comment by AbuBaniaz** [comment]
Done. OK to close?

**Comment by mcfly822** [comment]
@AbuBaniaz thank you very much! 👍 
For me, its ok to.close.

**Comment by dalmore72** [comment]
@AbuBaniaz 

svg logo for eotv you find here  :)

https://www.fernsehserien.de/serien-nach-sendern

**Comment by mcfly822** [comment]
Wow, thanks @dalmore72 !!
But everybody be careful before committing, these svgs contain embedded base64 images! So it is needed to delete these images from the svg.
