### ISSUE TITLE
Missing logos for several BBC and other channels on UK Freeview

### ISSUE THREAD

**Issue by philpem** [picons/picons-source#269]
Several UK Freeview channels have no logos:

```
1_0_1_3B68_3006_233A_EEEE0000_0_0_0    |  695                     |  3B68_3006_233A_EEEE0000=--------
1_0_1_3B48_3006_233A_EEEE0000_0_0_0    |  696                     |  3B48_3006_233A_EEEE0000=--------
1_0_1_5FB4_5040_233A_EEEE0000_0_0_0    |  697                     |  5FB4_5040_233A_EEEE0000=--------
1_0_1_6F68_6040_233A_EEEE0000_0_0_0    |  698                     |  6F68_6040_233A_EEEE0000=--------
1_0_1_3C98_3006_233A_EEEE0000_0_0_0    |  ADULT Party             |  3C98_3006_233A_EEEE0000=--------
1_0_1_3B60_3006_233A_EEEE0000_0_0_0    |  ADULT Section           |  3B60_3006_233A_EEEE0000=--------
1_0_1_6BC0_6040_233A_EEEE0000_0_0_0    |  ADULT Section           |  6BC0_6040_233A_EEEE0000=--------
1_0_1_6B80_6040_233A_EEEE0000_0_0_0    |  ADULT smileTV2          |  6B80_6040_233A_EEEE0000=--------
1_0_1_5780_5040_233A_EEEE0000_0_0_0    |  ADULT smileTV3          |  5780_5040_233A_EEEE0000=--------
1_0_1_184F_104A_233A_EEEE0000_0_0_0    |  BBC Humberside          |  184F_104A_233A_EEEE0000=--------
1_0_1_180A_104A_233A_EEEE0000_0_0_0    |  BBC Leeds               |  180A_104A_233A_EEEE0000=--------
1_0_1_180F_104A_233A_EEEE0000_0_0_0    |  BBC Lincolnshire        |  180F_104A_233A_EEEE0000=--------
1_0_1_184A_104A_233A_EEEE0000_0_0_0    |  BBC Sheffield           |  184A_104A_233A_EEEE0000=--------
1_0_1_188A_104A_233A_EEEE0000_0_0_0    |  BBC York                |  188A_104A_233A_EEEE0000=--------
```

Channel IDs are for the Yorkshire region.

The BBC stations are all BBC local radio -- they could be generated from e.g. "bbcradionewcastle", however the fonts have been converted to paths.
@masticman originally added these -- they may be able to provide the source images and font or create new logos for the channels which don't have them.

695 through 698 are buffer channels between the adult and radio LCNs (to give a "safety gap" for people who hit the channel-down button on the first radio channel).

**Comment by AbuBaniaz** [comment]
The logos are available on jasmeet's mediaportal repository. They will need to be renamed to our style. As a general rule, his `dark` is our `default`

**Comment by AbuBaniaz** [comment]
what logos do you want for 695-698. They don't tune for me.

**Comment by philpem** [comment]
@AbuBaniaz 695 through 698 are buffer channels between the radio and the adult channels - so they probably shouldn't have a logo at all. They're not actually channels, just programme-guide entries.

**Comment by AbuBaniaz** [comment]
I've added some more logos and links. Please close the issue when satisfied.
