### ISSUE TITLE
snp links for Magic

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#272]
There are two snp links refering to the logo of `magic`:
`magic=magic` and `magictv=magic`.
The channel on satellite is named `magic`.
`magictv` is a Bulgarian TV station (on four satellites).

Is the link `magictv=magic` old or maybe refering to the naming on cable?
Perhaps someone here has UK cable to verify this?

If it is an old link, I would like it to be deleted from snp.index, so it can be used for the Bulgarian `magictv`.
Otherwise we would need four srp-links in snp.index (no problem, but undesirable if not necessary).

**Comment by AbuBaniaz** [comment]
I've freed it up.
https://github.com/picons/picons-source/commit/fcef8cc3ba688f0f07bc2792c829f7e89ef85006

**Comment by Lexzie** [comment]
Thanks!
