### ISSUE TITLE
"N24" name change to "WELT"

### ISSUE THREAD

**Issue by jadero** [picons/picons-source#276]
German channel "N24" changed the name to "WELT". Please update the icon for the following references:
```
1_0_1_2F4E_A1_270F_FFFF0000_0_0_0.png  -> logos/n24.png
1_0_1_2F4E_BF_270F_FFFF0000_0_0_0.png -> logos/n24.png
1_0_1_30D6_7D_DE_FFFF0000_0_0_0.png -> logos/n24.png
1_0_1_35_7_85_C00000_0_0_0.png -> logos/n24.png
1_0_1_445F_453_1_C00000_0_0_0.png -> logos/n24.png
1_0_1_5274_41D_1_C00000_0_0_0.png -> logos/n24hd.png
1_0_1_527E_41D_1_C00000_0_0_0.png -> logos/n24hd.png
1_0_1_C79D_79_270F_FFFF0000_0_0_0.png -> logos/n24hd.png
1_0_1_D17B_2718_F001_FFFF0000_0_0_0.png -> logos/n24.png
```

Thank you.

**Comment by AbuBaniaz** [comment]
Not according to to contribution requirements.

I found svg file here. But it has wrong colours.
```
https://upload.wikimedia.org/wikipedia/commons/e/e9/WELT_Logo_2016.svg
```
Logo should be like this

```
https://www.welt.de/favicon-152.png
```

**Comment by AbuBaniaz** [comment]
German channel "N24" changed the name to "WELT". 

Can we have new logos and add the following references please?

```
2F4E_A1_270F_FFFF0000=n24
2F4E_BF_270F_FFFF0000=n24
30D6_7D_DE_FFFF0000=n24
35_7_85_C00000=n24
445F_453_1_C00000=n24
D17B_2718_F001_FFFF0000=n24
5274_41D_1_C00000=n24hd
527E_41D_1_C00000=n24hd
C79D_79_270F_FFFF0000=n24hd
```

Thank you.

```
Donkey monkey got issue
```

**Comment by mcfly822** [comment]
If no other do this until tonight, I will correct the colors.

**Comment by mcfly822** [comment]
@AbuBaniaz  I made the logo in correct color. Made two variations, choose the one which you like better.
I don't know how to name the logos, N24 or WELT or WELT TV? So please rename according the rules.

[n24welt_mcfly822.zip](https://github.com/picons/picons-source/files/1644765/n24welt_mcfly822.zip)

The color for ```light``` logo is taken from welt website, from the header (the light blue part).

**Comment by Lexzie** [comment]
### Please note these are the correct changes to snp. and srp.index:
I rescanned all (satellite) frequencies checked the logos to make sure these are the correct namings.
Notice that `n24austria` has changed to `n24docu` and that naming of the Austrian channels are still the old names.

**Please delete in snp.index**
```
n24=n24
n24austria=n24
n24doku=n24doku
n24hd=n24hd
n24hdaustria=n24hd
```

**Please add to snp.index**
```
n24austria=n24docu
n24hdaustria=welt
welt=welt
```

**Please delete in srp.index**
```
2F4E_A1_270F_FFFF0000=n24
2F4E_BF_270F_FFFF0000=n24
30D6_7D_DE_FFFF0000=n24
35_7_85_C00000=n24
445F_453_1_C00000=n24
D17B_2718_F001_FFFF0000=n24
5274_41D_1_C00000=n24hd
527E_41D_1_C00000=n24hd
C79D_79_270F_FFFF0000=n24hd
```

**Please add to srp.index**
```
2F4E_A1_270F_FFFF0000=welt
2F4E_BF_270F_FFFF0000=welt
30D6_7D_DE_FFFF0000=welt
35_7_85_C00000=n24docu
445F_453_1_C00000=welt
5274_41D_1_C00000=welt
527E_41D_1_C00000=welt
C79D_79_270F_FFFF0000=welt
C79D_79_270F_FFFF0000=welt
D17B_2718_F001_FFFF0000=welt
CB_14B4_9C_5A0000=welt
```

**Comment by jadero** [comment]
Thanks for your effort. Very appreciated. Could you also consider making a variant of the logo with white text on transparent? I think this would work best with the current default Kodi theme.
