### ISSUE TITLE
MCS new entry

### ISSUE THREAD

**Issue by Joannnn** [picons/picons-source#28]
```
1903_3FA_1_C00000=tv/machainesport
```

**Comment by picons** [comment]
don't add .svg

**Comment by Joannnn** [comment]
Ok, I added the image below in png format.

```
1903_3FA_1_C00000=tv/machainesport.png
```

![machainesport](https://cloud.githubusercontent.com/assets/9308819/7379956/f33f1e96-edf8-11e4-9b6c-2a8825e62f02.png)

**Comment by picons** [comment]
Do they no longer have a seperate HD logo/channel? Or different channel, but same logo as SD?

**Comment by Joannnn** [comment]
MCS and MCS Extreme have HD channel too, but I couln't get the logo.

MCS Bien-etre has SD channel only.

**Comment by charlesduco** [comment]
I'm pretty sure there is no separate HD-logo anymore. (http://www.canalsat.fr/chaines/298_ma-chaine-sport-hd)
It would be beneficial to add a guideline in the CONTRIBUTING.md file on how to handle such cases:
Do you have to place the logo two times in the build-source directory or can you just refer to one file for the SD and HD version?

I added already SVG-versions for all MaChaineSport-channels in my next pull request.

**Comment by picons** [comment]
We are dealing with logos in this project, so the SD and HD channel if using the same logo should point to the same file.... also duplicating the same logo seems.... a bit stupid :-)

**Comment by picons** [comment]
@charlesduco 
I have given you push access to the repo, so you no longer have to create PR.

**Comment by charlesduco** [comment]
Ok, thanks.
