### ISSUE TITLE
ART logo

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#280]
Can someone (@mcfly822 ?) make a `default` and `light` svg from this png?

![arttv](https://user-images.githubusercontent.com/14023349/35176057-3a4e7800-fd77-11e7-8b8e-dfd88a7fd7b4.png)
Obviously with transparent background.

By the way: It's a Greek station, so in Greek it's `ΑΡΤ` (uppercase) or `αρτ` (lowercase) which in Latin characters spells `ART` (uppercase) or `art` (lowercase).

When adding to the picon-source:

**Please add these to snp.index**
```
art=art
3FA_6_AA_5A0000=art
```

**Please add these to srp.index**
```
15E_64_212C_1E0000=art
3FA_6_AA_5A0000=art
```

`donkey monkey got issued`

**Comment by mcfly822** [comment]
Sure, I can do it soon.

**Comment by mcfly822** [comment]
[art_mcfly822.zip](https://github.com/picons/picons-source/files/1649769/art_mcfly822.zip)

**Comment by AbuBaniaz** [comment]
Thanks. Done. Closed

**Comment by Lexzie** [comment]
Looking great again! Thank you all.
