### ISSUE TITLE
(Euro)Star logo

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#281]
The `eurostar` logo is actually the logo for the national Turkish `Star TV`.
Also found a svg for `Star TV`.

If anyone wants to add the links for Türksat, go ahead, I can't receive the bird.

**Please replace this logo**
[eurostar.zip](https://github.com/picons/picons-source/files/1648378/eurostar.zip)

**Please add this logo**
[Star(Turkey).zip](https://github.com/picons/picons-source/files/1648381/Star.Turkey.zip)

**Please add to snp.index**
```
6D2_C4E0_7E_460000=star-drispocupr
startvhd=star-drispocupr
```

**Please add to srp.index**
```
1EEA_51A4_7E_460000=eurostar
1F3A_51A4_7E_460000=eurostar
6D2_C4E0_7E_460000=eurostar
1EEA_51A4_7E_460000=star-drispocupr
1F3A_51A4_7E_460000=star-drispocupr
6D2_C4E0_7E_460000=star-drispocupr
```

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
Thanks. Committed. Closed

**Comment by Lexzie** [comment]
Thanks
