### ISSUE TITLE
Add entries to srp.index and snp.index for german DVB-C supplier LWLcom

### ISSUE THREAD

**Issue by chiefymuc** [picons/picons-source#283]
All the logos and names are available, just the links are missing:

For SNP - it's strange that there are the german umlauts? maybe this is a software issue that it is not converted to "u" or "ue" ?
```
brfernsehensüd=br
brfernsehensüdhd=brhd
wdrhdköln=wdrhd
wdrköln=wdr
```

For SRP:
```
2B8E_3F2_1_FFFF0000=3sathd
1158_404_1_FFFF0000=aljazeera
2FC_5_85_FFFF0000=anixe
6F47_445_1_FFFF0000=ardalpha
283E_3FB_1_FFFF0000=artehd
F0_14B4_9C_FFFF0000=bbcworldnews
F1_14B4_9C_FFFF0000=bloomberg
2753_402_1_FFFF0000=bloomberg
2855_401_1_FFFF0000=brhd
1132_404_1_FFFF0000=canal24horas
1B02_3FE_1_FFFF0000=cgtn
1B00_3FE_1_FFFF0000=cgtndocumentary
272E_402_1_FFFF0000=cnbceurope
1146_404_1_FFFF0000=cnn
283D_3FB_1_FFFF0000=daserstehd
F6_14B4_9C_FFFF0000=deluxemusic
F3_14B4_9C_FFFF0000=deutschesmusikfernsehen
701_5_85_FFFF0000=disneychannel
3F_21_85_FFFF0000=dmax
1153_404_1_FFFF0000=deutschewelle
114E_404_1_FFFF0000=deutschewelle
79F4_443_1_FFFF0000=euronews
79E0_443_1_FFFF0000=eurosport1
1AFA_3FE_1_FFFF0000=france24
445E_453_1_FFFF0000=kabeleins
2B98_3F2_1_FFFF0000=kikahd
6E44_431_1_FFFF0000=mdr
30_5_85_FFFF0000=n24doku
6E42_431_1_FFFF0000=ndr
2857_401_1_FFFF0000=ndrhd
D5_14B4_9C_FFFF0000=nick
2F1D_441_1_FFFF0000=rtlnitro
2F3A_441_1_FFFF0000=ntv
285B_401_1_FFFF0000=phoenixhd
4461_453_1_FFFF0000=prosiebenmaxx
445D_453_1_FFFF0000=prosieben
6EE1_4B1_1_FFFF0000=radiobrementv
2F_21_85_FFFF0000=regiotv
1_1FA4_13E_FFFF0000=rit
2EF4_441_1_FFFF0000=rtl2
2EE6_441_1_FFFF0000=rtl
332E_45B_1_FFFF0000=rtlnitro
2F30_441_1_FFFF0000=rtlplus
2EE3_441_1_FFFF0000=rtl
1AF8_3FE_1_FFFF0000=rt
445C_453_1_FFFF0000=sat1
4460_453_1_FFFF0000=sat1gold
F5_14B4_9C_FFFF0000=servustv
3336_45B_1_FFFF0000=servustv
1332_3EF_1_FFFF0000=servustvhd
308_5_85_FFFF0000=sixx
384_21_85_FFFF0000=sport1-wispelutri
6F46_445_1_FFFF0000=srfernsehen
2F08_441_1_FFFF0000=superrtl
283F_3FB_1_FFFF0000=swrhd
33_21_85_FFFF0000=tele5
2EFE_441_1_FFFF0000=toggoplus
F2_14B4_9C_FFFF0000=tv5monde
1B03_3FE_1_FFFF0000=tv5mondeeurope
1131_404_1_FFFF0000=tveinternacional
D8_14B4_9C_FFFF0000=comedycentral_viva
2F1C_441_1_FFFF0000=vox
6EA5_4B1_1_FFFF0000=wdrhd
445F_453_1_FFFF0000=welt
2B66_3F3_1_FFFF0000=zdfhd
2BA2_3F2_1_FFFF0000=zdfinfohd
2B84_3F3_1_FFFF0000=zdfkulturhd
2B7A_3F3_1_FFFF0000=zdfneo
```

**Comment by AbuBaniaz** [comment]
I've added the SRP links.

Can you attach you lamedb file please?

**Comment by chiefymuc** [comment]
Thanks for including this!

I am struggling to find the lamedb file. 
I am running Libreelec on a RPi 3 using tvheadend as the server. I can't find the "enigma2" folder neither the /home/hts folder.

**Comment by AbuBaniaz** [comment]
Thanks for looking. lamedb file are only on enigma2.

The SNP code in E2 omits non-compliant characters. TVHeadend my treat differerntly. If it does, we can add them to the index files. Test by adding symlinks or building your own picon packs.

Please close the issue when satisfied.

**Comment by chiefymuc** [comment]
It works partly. The SNP is recognized but the output filename does not have the actual umlaut - e.g. "brfernsehensÃ¼d.png".

So i'm not sure what to do with this. It does the job half-way but not to completion.

**Comment by AbuBaniaz** [comment]
Enigma2 will show the picons, even with the umlauts missing.

If TVHeadend uses the umlauts instead of omitting, maybe this project can be adapted. Can you test by creating symlinks/renaming filed? There will be a logos folder in the picon folder

**Comment by chiefymuc** [comment]
I'd be happy to help more, but I'm not that familiar with this. 
Can you tell me the exact steps that I need to do? How do I create the symlinks?

**Comment by AbuBaniaz** [comment]
For now, copy the following `wdrhd.png` located in /picon/logos/ rename it to `wdrhdköln.png` and place it in /picon/logos/ Does it show?

**Comment by chiefymuc** [comment]
OK I renamed the file to `wdrhdköln.png`.

Then switched TVheadend to prefer SNP, cleared the cache and let it fetch all icons again.

For this channel, it expects the Icon name to be:
`file:///storage/picons/tvh/wdrhdkoln.png`

I guess this means it does not work..

**Comment by AbuBaniaz** [comment]
If you know that it expects a certain name, try it. We can add the names tvheadend uses too.

**Comment by chiefymuc** [comment]
It does work with `wdrhdkoln.png`.

So it seems:
- the picons script evaluates the necessary logo name to be "wdrhdköln" from the TVheadend connection and creates image accordingly
- however, the actual name should be "wdrhdkoln" so it can be used by TVheadend

How would it be possible to change this?

**Comment by AbuBaniaz** [comment]
I am afraid you are reaching wrong conclusions.

What Enigma2 does is one thing
What TVHeadend does is another thing
What this project does is another thing. 

Please request the links you want for your system.

I shall add these links for TVHeadend users
```
brfernsehensud=br
brfernsehensudhd=brhd
wdrhdkoln=wdrhd
wdrkoln=wdr
```

**Comment by AbuBaniaz** [comment]
The links I mentioned are there already. I shall close this issue now.

**Comment by chiefymuc** [comment]
Maybe I'm misunderstanding something, but it does not work like it is now.

When running `1-build-servicelist.sh` with SNP, the result is:
`1_0_19_6EA5_4B1_1_FFFF0000_0_0_0    |  WDR HD Köln                  |  6EA5_4B1_1_FFFF0000=--------    |  wdrhdköln=wdrhd`

After that, running `2-build-picons.sh` the files will be created with the name:
`wdrhdkÃ¶ln.png`

What TVheadend needs is `wdrhdkoln.png`.

So I guess that the fix should be made in `2-build-picons.sh`.

**Comment by AbuBaniaz** [comment]
>What TVheadend needs is wdrhdkoln.png.
These snp links were there already.

Are you asking or stating what tvheadend uses? Forget this project for time being, establish what tvheadend requires. then come back to this project.

**Comment by chiefymuc** [comment]
I am stating what tvheadend uses!

Maybe TVheadend has a inconsistency:
When `1-build-servicelist.sh` asks TVheadend "Hey, what is the name you need?", TVheadend says `wdrhdköln`

But when TVheadend wants to use the logo from the folder, it will only find `wdrhdkoln.png`. I tried and TVheadend does NOT find `wdrhdköln.png`!

I hope it is clear now?

**Comment by AbuBaniaz** [comment]
Are you building your own picons?

**Comment by chiefymuc** [comment]
Yes, I'm building my own.

**Comment by AbuBaniaz** [comment]
Try the pre-built ones or test a build of the "all" ones

**Comment by chiefymuc** [comment]
Of course that will work, I have no doubt about it ;)

**Comment by AbuBaniaz** [comment]
So the root issue is that tvheadend does one thing, enigma2 does another.

This project will need to do different things depending on what file it is handling.
