### ISSUE TITLE
Use whitish "default" icons for "white" binary builds

### ISSUE THREAD

**Issue by jadero** [picons/picons-source#284]
I did a srp build (not a full one) for my specific channel setup with logotype set to "white" and noticed that there were some all black logos which obviously do not match the chosen type. Interestingly the "light" icon variants would match the "white" style perfectly since they are all white. The logos that I found inappropriate for the "white" style with a whitish "light" variant are:
```
build-source/logos/mtv.light.svg
build-source/logos/nicetv.light.png
```
Sure this applies to a lot more logos. I guess this needs some cleanup...

**Comment by mocram** [comment]
Not a lot of white, if any, are added, so the default is used. No need to cleanup anything, just start submitting pull requests with correct white versions.
