### ISSUE TITLE
TBN Europe and TBN España

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#290]
TBN Europe has a new logo, TBN España is assigned the logo for Enlace, which is another different (Spanish spoken) channel of the Trinity Broadcasting Family aimed at Latin America.

![afbeelding](https://user-images.githubusercontent.com/14023349/35441202-e14025e8-02a2-11e8-9ed6-a7de42d6a975.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/35441239-0ac034a8-02a3-11e8-9787-50b8a6d1e3f0.png)

I found these logos but I'm in doubt if they are of enough quality:
http://www.governanceministries.org/wp/wp-content/uploads/2016/04/tbn-europe.jpg
I converted it to this: 
[tbneurope.zip](https://github.com/picons/picons-source/files/1667865/tbneurope.zip)

https://tbnespaña.es/wp-content/uploads/2017/01/logoWeb.png
[tbnespana.zip](https://github.com/picons/picons-source/files/1667897/tbnespana.zip)

Or:
https://scontent-ams3-1.xx.fbcdn.net/v/t31.0-8/15493659_1818384381713294_2430555504941629589_o.jpg?oh=5b683918d1d5ad51ac0ac85c8c79ad2b&oe=5ADD4609
Removing the background seems an impossible job with this logo.

Are they okay or can anyone improve the logos?

**Delete from snp.index**
```
tbnespana=tbnenlace
```

**Add to snp.index**
```
tbnespana=tbnespana
```

**Delete from srp.index**
```
7A49_410_1_C00000=tbnenlace
321_3BC4_13E_820000=tbneurope
CB9C_8FE_2_11A0000=tbneurope
```

**Add to srp.index**
```
1EA_D_28_CE40000=tbnespana
7A49_410_1_C00000=tbnespana
```

`donkey monkey got issued`

**Comment by mcfly822** [comment]
I made the two logos in svg. Honestly, this made my evening... :smile_cat:
Not a perfect work, but I think (and I hope) acceptable.
[issue290_itwasalotofwork_mcfly822.zip](https://github.com/picons/picons-source/files/1669182/issue290_itwasalotofwork_mcfly822.zip)

**Comment by Lexzie** [comment]
Ha, ha, well somebody have to keep you off the streets. 😜 
Glad I could be of help to keep you busy. 😉 

I can only say: Wow, great work!

Please someone upload them to the source and add/change the links.

**Comment by AbuBaniaz** [comment]
There is an embedded image in tbneurope

**Comment by mcfly822** [comment]
Not image, text:
<text transform="scale(1.0544 .94841)" x="-75.89296" y="262.57843" font-family="'Brandon Grotesque'" font-size="28.695px" letter-spacing="0px" stroke-width=".71737" word-spacing="0px" style="line-height:1.25" xml:space="preserve"><tspan x="-75.89296" y="262.57843" fill="url(#a)" font-family="Verdana" stroke-width=".71737">O</tspan></text>

Sorry, it was late... I modified the letter "O" at the end of the work,  and I forget to convert text to path.
Fixed in #293 .

**Comment by mcfly822** [comment]
Not image, text:
```<text transform="scale(1.0544 .94841)" x="-75.89296" y="262.57843" font-family="'Brandon Grotesque'" font-size="28.695px" letter-spacing="0px" stroke-width=".71737" word-spacing="0px" style="line-height:1.25" xml:space="preserve"><tspan x="-75.89296" y="262.57843" fill="url(#a)" font-family="Verdana" stroke-width=".71737">O</tspan></text>```

Sorry, it was late... I modified the letter "O" at the end of the work,  and I forget to convert text to path.
Fixed #

**Comment by Lexzie** [comment]
Thanks all for the great work!
