### ISSUE TITLE
Spanish logos

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#291]
A lot missing Spanish logos:

[España.zip](https://github.com/picons/picons-source/files/1669356/Espana.zip)

**Delete from snp.index**
```
kissfm=kiss
```

**Add to snp.index**
```
fmzaragoza=aragonradio
fmhuesca=aragonradio
fmteruel=aragonradio
cadena100=cadena100
10847vsid0x7599=cadenaser
extremadurafm=canalextremaduraradio
canalextremadurasat=canalextremadurasat
parlamento=canalparlamento
cope=cope
dark=dark
agenciaefe=efe
eferadio=efe
efetv=efe
esradio=esradio
europafm=europafm
hitfm=hitfm
kissfm=kissfm
megastar=megastarfm
ondamelodia=melodiafm
maximafm=maximafm
musicam1=musicaambiental
ondacero=ondacero
radiotest1=peperadio
intereconomia=radiointereconomia
radiomarca=radiomarca
radiole=radiole
radiosolidaria=radiosolidaria
rockfm=rockfm
sol=solmusica
somos=somos
feeds2tsa=telefonica
feeds3tsa=telefonica
xtrm=xtrm
```

**Add to srp.index**
```
3A_65_0_CE4ACF6=aragonradio
3B_65_0_CE4ACF6=aragonradio
3C_65_0_CE4ACF6=aragonradio
A_65_0_CE4ACF6=cadena100
7599_422_1_C00000=cadenaser
74_65_0_CE4ACF6=canalextremaduraradio
4_F_2_CE4AA8A=canalextremadurasat
2_F_2_CE4AA8A=canalparlamento
25_65_0_CE4ACF6=cope
4_6_6_CE40000=dark
65_65_0_CE4ACF6=efe
34_65_0_CE4ACF6=esradio
2_65_0_CE4ACF6=europafm
1A_65_0_CE4ACF6=hitfm
19_65_0_CE4ACF6=kissfm
27_65_0_CE4ACF6=megastarfm
3_65_0_CE4ACF6=melodiafm
F_F_2_CE4AA8A=musicaambiental
9_3138_FF01_CE4AAA5=peperadio
26_65_0_CE4ACF6=radiointereconomia
1D_65_0_CE4ACF6=radiomarca
7_F_2_CE4AA8A=radiosolidaria
B_65_0_CE4ACF6=rockfm
1_65_0_CE4ACF6=ondacero
6_6_6_CE40000=solmusica
8_6_6_CE40000=somos
5_F_2_CE4AA8A=telefonica
6_F_2_CE4AA8A=telefonica
3_6_6_CE40000=xtrm
```

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
jpg files not allowed

**Comment by mcfly822** [comment]
SVG:
[ondacero.default.zip](https://github.com/picons/picons-source/files/1669898/ondacero.default.zip)

**Comment by Lexzie** [comment]
> jpg files not allowed

Don't know how that ended up in the zip....sorry.
@mcfly822 Great work converting it to svg, thanks! (Still not able to do that myself).

**Comment by mcfly822** [comment]
@Lexzie thanks, but this time I did not made the logo, I found it on wikimedia.
Besides, converting is not so simple, sometimes its more worth to draw the logo in inkscapes. Lines by lines, dots by dots, shapes by shapes :-)

**Comment by Lexzie** [comment]
I guess I missed that on Wikimedia. I also check that normally.
`solmusica.default.png` can be deleted again, I now see `solmusica.default.svg` already existed. Sorry...

Anyhow, now `ondacero` can be added too, and the links:
https://github.com/picons/picons-source/files/1669898/ondacero.default.zip

**snp.index**
```
ondacero=ondacero
```
**srp,index**
```
1_65_0_CE4ACF6=ondacero
```

`donkey monkey got issued`

**Comment by Lexzie** [comment]
Something went wrong with the `xtrm` logo, it's empty.
It goes wrong when I want to save the logo as Optimized svg.
Here is the logo as "normal" svg, please first have a look if the logo is okay to commit.
[xtrm.zip](https://github.com/picons/picons-source/files/1671158/xtrm.zip)

This is the source: https://vignette.wikia.nocookie.net/logopedia/images/6/67/XTRM_Teuve.svg/revision/latest?cb=20100617134811
I deleted the `HD` because the channel on Hispasat is not the HD-version.

Otherwise it might have to be exported to a png?

**Comment by mcfly822** [comment]
Sorry, not ok. It contains embedded image. You can check any svg if you open it in a text editor, e.g. notepad++, and search for this word "base64".
I also modified dthe color, regarding to the website (http://canalxtrm.es/) and facebook profile image color. It is now orange, maybe the older logo was black&white.

Here is the corrected svg:
[xtrm_mcfly822.zip](https://github.com/picons/picons-source/files/1671606/xtrm_mcfly822.zip)

**Comment by Lexzie** [comment]
Lyngsat took me to the wrong website, so I did a search for the logo.
Thanks for the tip about detecting an embedded image.
Current logo is always better.
Logo looks good, so the current (wrong) one can be replaced.

**Comment by mcfly822** [comment]
If no more to do with this, issue can be closed.

**Comment by Lexzie** [comment]
I was busy making the French logos and did not check if the xtrm logo is okay now.
All is okay, so I'll close the issue.
