### ISSUE TITLE
Missing links (26-1-2018)

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#292]
Again, I found some missing links:

**Delete from snp.index**
```
alraiuplink=alraitv
kurdsatsd=kurdsat
```

**Add to snp.index**
```
tva3=algerie3
1B_1_FFFF_D343181=algerie4
1A_1_FFFF_D343181=algerie5
france24i=franche24
ftv=fashiontv
globo=tvglobo
kurdsat=kurdsat
10847vsid0x759a=m80
motorvision=motorvisiontv
preestv=presstv
```

**Delete from srp.index**
```
43A6_2CEC_13E_820000=kurdsat
```

**Add to srp.index**
```
1_1_FFFF_D343181=algerie3
1B_1_FFFF_D343181=algerie4
1A_1_FFFF_D343181=algerie5
2_1_FFFF_D343181=canalalgerie
4_1_FFFF_D343181=entv
578_FFDC_77E_DC00000=kurdsat
16AC_3A_800_DCA0000=kurdsat
58C_FFDC_77E_DC00000=kurdsat
89F_1F4_13E_820000=kurdsat
759A_422_1_C00000=m80
```

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
I have not deleted the two snp entries.

Rest done including correction

**Comment by Lexzie** [comment]
> I have not deleted the two snp entries.

You're absolutely right, thanks for correcting that.
(The link `alraiuplink=alraitv` was for a channel which is now gone, maybe the name will come back one day).

**Comment by Lexzie** [comment]
Thanks
