### ISSUE TITLE
Vivid logos

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#294]
I found a much better quality logo for `vivideurope` (please replace existing logo).
[vividtveurope.zip](https://github.com/picons/picons-source/files/1670032/vividtveurope.zip)

And made the `vividred` logo.
[vividred.zip](https://github.com/picons/picons-source/files/1670033/vividred.zip)

**Add to snp.index**
```
vividred=vividred
```

**Delete from srp.index**
```
1CBB_1CE8_71_820000=bluehustler
```

**Add to srp.index**
```
1CBB_1CE8_71_820000=vivideurope
1F45_319C_13E_820000=vividred
```

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
Thanks. Done

**Comment by Lexzie** [comment]
Thanks
