### ISSUE TITLE
CTV (City TV Albania) logo

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#297]
I tried to make this logo as svg, but I can't figure out the letters (font).
I hope someone can do the job?
![afbeelding](https://user-images.githubusercontent.com/14023349/35476795-6091518c-03b6-11e8-86a7-0678d6507235.png)
The color red is #AC0123

When adding to the source, this are the links:
**Add to snp.index**
```
3FE_50DC_16E_A00000=ctv
```

**Add to srp.index**
```
3FE_50DC_16E_A00000=ctv
```

`donkey monkey got issued`

**Comment by mcfly822** [comment]
Tomorrow I will make the logo.

**Comment by mcfly822** [comment]
If no more to do with this, issue can be closed.

**Comment by Lexzie** [comment]
Logo is okay, thanks!
