### ISSUE TITLE
New logos and renamed french channels 

### ISSUE THREAD

**Issue by daviok** [picons/picons-source#301]
Hi,

**NT1 become TFX** with new logo.Can delete NT1 logo and entries and replace to SFX
https://fr.wikipedia.org/wiki/TFX
[TFX_logo.zip](https://github.com/picons/picons-source/files/1673483/TFX_logo.zip)
**HD1 become TF1 séries films**
https://fr.wikipedia.org/wiki/HD1
[logo_TF1_Séries_Films.zip](https://github.com/picons/picons-source/files/1673584/logo_TF1_Series_Films.zip)
**New logos for all france television channels (france1ere,france2,france3,france4,france5,franceô)**
[new_francetelevision_logos.zip](https://github.com/picons/picons-source/files/1673587/new_francetelevision_logos.zip)
**New logo for lci** ( that is the highest res i could find )
[LCI_logo_2017.zip](https://github.com/picons/picons-source/files/1673604/LCI_logo_2017.zip)

delete from snp-index and logos
`nt1=nt1`
`hd1=hd1`
`hd1hd=hd1`

add to snp-index
`tfx=tfx`
`tfxhd=tfx`
`france1=france1`
`france1hd=france1hd`
`france2=france2`
`france2hd=france2hd`
`france3=france3`
`france3hd=france3hd`
`france4=france4`
`france4hd=france4hd`
`france5=france5`
`france5hd=france5hd`
`france=franceo`
`franceo=franceo`
`franceohd=franceohd`
`tf1seriefilms=tf1seriesfilms`
`tf1seriefilmshd=tf1seriesfilms`
`lci=lci`
`lcihd=lci`

`donkey monkey got issued`

thanks, 
hope everything is all good 
if something is wrong let me know I will edit my post:)

**Comment by Lexzie** [comment]
I was already busy with the logos, please if anyone else is also making logos, let me know,
No need to do the same work twice.

**Comment by daviok** [comment]
well i did not know , did not see on the closed issues

**Comment by mcfly822** [comment]
@Lexzie have a good work! 😉 If you need help, I can. And I also can check your files before committing.

**Comment by Lexzie** [comment]
> well i did not know , did not see on the closed issues

That's not what I mean, I did not make an issue yet.
But I really want to make sure I am not doing all the work for nothing if anyone else is already on it.

**Comment by Lexzie** [comment]
> @Lexzie have a good work! 😉 If you need help, I can. And I also can check your files before committing.

The logos of France Television are in `eps` format. So should be simply converting to `svg` and saving as optimized svg.
**Firstly**: The logos are of type `cmjn`, `rvb` or `pantone`, I don't know which one is best to convert.

**Secondly:** When trying to convert the logos, f.e. `france_2_logo_rvb_2_couleur_blanc.eps` with the command
```
inkscape   france_2_logo_rvb_2_couleur_blanc.eps   --export-plain-svg=france_2_logo_rvb_2_couleur_blanc.svg
```
I get this error:

```
france_2_logo_rvb_2_couleur_blanc.eps:1: parser error : Start tag expected, '<' not found
┼ðËã
^
france_2_logo_rvb_2_couleur_blanc.eps:1: parser error : Start tag expected, '<' not found
┼ðËã
^

** (inkscape.exe:12052): WARNING **: Specified document france_2_logo_rvb_2_couleur_blanc.eps cannot be opened (does not exist or not a valid SVG file)
```
Do I need extra options?

**Comment by mcfly822** [comment]
@Lexzie your 2nd question: inkscape cannot open eps files. So it is useless to convert eps to svg. You need to convert with another software (e.g. Illustrator) or by an online converter.

1st question: I don't know, tomorrow I will convert the eps to svg or pdf, and I can decide after I see the images :)

**Comment by mcfly822** [comment]
I converted in https://cloudconvert.com/, eps to svg. Then I opened in inkscape, and checked whether everything is okay or not. Then saved as optimized svg.

[france2_mcfly822.zip](https://github.com/picons/picons-source/files/1675372/france2_mcfly822.zip)

**Comment by Lexzie** [comment]
@mcfly822 You say Inkscape cannot convert eps to, still I have done that before (can't find the FAQ right away). [This](https://inkscape.org/nl/learn/faq/) is what I found so far:

> Inkscape natively supports opening or importing many different formats, such as SVG, SVGZ (gzipped SVG), PDF, EPS, and AI (Adobe Illustrator) formats.

I need to convert 56 logos (Fr2/3/4/5/Ô+Fr3 regional in default and light), so a command line would be nice.
But I'll try the cloudconvert.

**Comment by mcfly822** [comment]
Interesting. I can not ever open eps in inkcape... this time also an error message while opening. This also happens in another computer....

**Comment by Lexzie** [comment]
Cloudconvert without account only allowed to convert 10 files per day, and with a (free) account I could convert "25 minutes". Had to make two accounts to complete all files.
Tomorrow I will save all the files to optimized svg's and upload them, together with the links.

**Comment by mcfly822** [comment]
I see. It was just an idea, there are many other online converters which you can use. Cloudconvert was the first result in goole when I searched "eps to svg" :)

**Comment by Lexzie** [comment]
Now busy on converting them to optimized svg's.

I hoped that it could be done in command line, you can export f.e. to Plain svg but not to optimized svg, as far as I could find out.
Source: https://inkscape.org/nl/doc/inkscape-man.html

So, I have to open them all one-by-one, select the logo, reduce page size to selection and save as optimized svg.

**Comment by mcfly822** [comment]
Exactly. And don't forget to check the logos, e.g. embedded images, and any other problems. There can be errors in svg, as in TF1 série...

**Comment by daviok** [comment]
hehe nice job guys :)
I appreciate

**Comment by Lexzie** [comment]
Finally, here they are. I hope I did not left anything out.
[FranceTelevision2018.zip](https://github.com/picons/picons-source/files/1678140/FranceTelevision2018.zip)

**Delete from snp.index**
```
f3alpes=france3
f3aquitaine=france3
f3auvergne=france3
f3bnormandie=france3
f3bourgogne=france3
f3bretagne=france3
f3centre=france3
f3champardenne=france3
f3corseviastella=france3
f3cotedazur=france3
f3franchecompte=france3
f3franchecomte=france3
f3hnormandie=france3
f3languedocrou=france3
f3limousin=france3
f3lorraine=france3
f3midipyrenees=france3
f3nordpdc=france3
f3parisidf=france3
f3paysdeloire=france3
f3picardie=france3
f3poitouchar=france3
f3provalpes=france3
f3rhonealpes=france3
france2hd=france2hd
france3amiens=france3
france3besancon=france3
france3bordeaux=france3
france3caen=france3
france3clermontferrand=france3
france3dijon=france3
france3grenoble=france3
france3lille=france3
france3limoges=france3
france3lyon=france3
france3marseille=france3
france3montpellier=france3
france3nancy=france3
france3nantes=france3
france3nice=france3
france3orleans=france3
france3paris=france3
france3parisiledefrance=france3
france3poitiers=france3
france3reims=france3
france3rennes=france3
france3rouen=france3
france3strasbourg=france3
france3toulouse=france3
france3viastella=france3
viastella=france3
france3hd=france3hd
france4hd=france4hd
france5hd=france5hd
franceohd=franceohd
```

**Add to snp.index**
```
f3alpes=france3alpes
france3grenoble=france3alpes
f3alsace=france3alsace
france3strasbourg=france3alsace
f3aquitaine=france3aquitaine
france3bordeaux=france3aquitaine
f3auvergne=france3auvergne
france3clermontferrand=france3auvergne
france3caen=france3bassenormandie
f3bourgogne=france3bourgogne
france3dijon=france3bourgogne
f3bretagne=france3bretagne
france3rennes=france3bretagne
f3centre=france3centre
france3orleans=france3centre
f3champardenne=france3champagneardenne
france3reims=france3champagneardenne
f3corseviastella=france3corse
france3viastella=france3corse
viastella=france3corse
f3cotedazur=france3cotedazur
france3marseille=france3cotedazur
f3franchecomte=france3franchecomte
france3besancon=france3franchecomte
f3languedocrou=france3languedocroussillon
france3montpellier=france3languedocroussillon
f3limousin=france3limousin
france3limoges=france3limousin
f3lorraine=france3lorraine
france3nancy=france3lorraine
f3midipyrenees=france3midipyrenees
france3toulouse=france3midipyrenees
f3nordpdc=france3nordpasdecalais
france3lille=france3nordpasdecalais
f3bnormandie=france3normandie
f3hnormandie=france3normandie
france3rouen=france3normandie
f3parisidf=france3parisiledefrance
france3paris=france3parisiledefrance
f3paysdeloire=france3paysdelaloire
france3nantes=france3paysdelaloire
f3picardie=france3picardie
france3amiens=france3picardie
f3poitouchar=france3poitoucharentes
france3poitiers=france3poitoucharentes
f3provalpes=france3provencealpes
france3nice=france3provencealpes
f3rhonealpes=france3rhonealpes
france3lyon=france3rhonealpes
```

**Delete from srp.index**
```
12E_3E1C_13F_820000=france2hd
245A_440_1_C00000=france2hd
4F52_CB_1_FFFF0000=france2hd
2330_442_1_C00000=france5hd
245D_440_1_C00000=france3hd
25E5_45E_1_C00000=france3
25E6_45E_1_C00000=france3
25E7_45E_1_C00000=france3
25E8_45E_1_C00000=france3
25E9_45E_1_C00000=france3
25EA_45E_1_C00000=france3
25EB_45E_1_C00000=france3
25EC_45E_1_C00000=france3
25ED_45E_1_C00000=france3
25EE_45E_1_C00000=france3
25EF_45E_1_C00000=france3
25F0_45E_1_C00000=france3
2649_460_1_C00000=france3
264A_460_1_C00000=france3
264B_460_1_C00000=france3
264C_460_1_C00000=france3
264D_460_1_C00000=france3
264E_460_1_C00000=france3
264F_460_1_C00000=france3
2650_460_1_C00000=france3
2651_460_1_C00000=france3
2652_460_1_C00000=france3
2653_460_1_C00000=france3
2654_460_1_C00000=france3
2655_460_1_C00000=france3
2656_460_1_C00000=france3
2657_460_1_C00000=france3
2658_460_1_C00000=france3
2659_460_1_C00000=france3
265A_460_1_C00000=france3
265B_460_1_C00000=france3
265C_460_1_C00000=france3
265D_460_1_C00000=france3
265E_460_1_C00000=france3
265F_460_1_C00000=france3
2660_460_1_C00000=france3
```

**Add to srp.index**
```
12D_4F4C_55F_DDE0000=france2
12E_3E1C_13F_820000=france2
245A_440_1_C00000=france2
4F52_CB_1_FFFF0000=france2
12E_4F4C_55F_DDE0000=france3
12F_3E1C_13F_820000=france3
245D_440_1_C00000=france3
3_5140_55F_DDE0000=france3
1007_5078_55F_DDE0000=france3alpes
2650_460_1_C00000=france3alpes
1022_5014_55F_DDE0000=france3alsace
2652_460_1_C00000=france3alsace
1003_5078_55F_DDE0000=france3aquitaine
2657_460_1_C00000=france3aquitaine
1005_5078_55F_DDE0000=france3auvergne
2658_460_1_C00000=france3auvergne
1004_5140_55F_DDE0000=france3bassenormandie
1006_5140_55F_DDE0000=france3bourgogne
264D_460_1_C00000=france3bourgogne
1020_5078_55F_DDE0000=france3bretagne
2659_460_1_C00000=france3bretagne
1016_5140_55F_DDE0000=france3centre
264C_460_1_C00000=france3centre
1019_5014_55F_DDE0000=france3champagneardenne
264F_460_1_C00000=france3champagneardenne
1024_5014_55F_DDE0000=france3corse
2654_460_1_C00000=france3corse
1011_5078_55F_DDE0000=france3cotedazur
264B_460_1_C00000=france3cotedazur
1002_5140_55F_DDE0000=france3franchecomte
2660_460_1_C00000=france3franchecomte
1012_5078_55F_DDE0000=france3languedocroussillon
2653_460_1_C00000=france3languedocroussillon
1009_5078_55F_DDE0000=france3limousin
265A_460_1_C00000=france3limousin
1013_5014_55F_DDE0000=france3lorraine
265B_460_1_C00000=france3lorraine
1023_5014_55F_DDE0000=france3midipyrenees
265C_460_1_C00000=france3midipyrenees
1008_5014_55F_DDE0000=france3nordpasdecalais
2651_460_1_C00000=france3nordpasdecalais
1021_5140_55F_DDE0000=france3normandie
2649_460_1_C00000=france3normandie
2656_460_1_C00000=france3normandie
1017_5140_55F_DDE0000=france3parisiledefrance
265D_460_1_C00000=france3parisiledefrance
1014_5078_55F_DDE0000=france3paysdelaloire
264A_460_1_C00000=france3paysdelaloire
1001_5014_55F_DDE0000=france3picardie
265E_460_1_C00000=france3picardie
1018_5014_55F_DDE0000=france3poitoucharentes
264E_460_1_C00000=france3poitoucharentes
1015_5014_55F_DDE0000=france3provencealpes
2655_460_1_C00000=france3provencealpes
1010_5078_55F_DDE0000=france3rhonealpes
265F_460_1_C00000=france3rhonealpes
```

`donkey monkey got issued`

**Comment by daviok** [comment]
ah yea did not check about all those regional france3 channels.
Good jobs guys thanks again :)

**Comment by mcfly822** [comment]
@Lexzie logos seems to be okay. Good work!

**Comment by AbuBaniaz** [comment]
There were only 24 out 41 valid deletion requests for the srp.index. I did not check the snp index.

If any more are needed, please post back. I know its not required to delete them, but it is good practice to prevent re-used service references being used in future.

**Comment by Lexzie** [comment]
> ah yea did not check about all those regional france3 channels.

A lot of them were already in the source with the old logo but the channels were all linked to `france3`, so had to delete all those links and add new ones.

Anyhow, these I did wrong:

**Please delete from srp.index**
```
1004_5140_55F_DDE0000=france3bassenormandie
```

**Please add to snp.index**
```
1004_5140_55F_DDE0000=france3normandie
```
 
I forgot to delete one in snp.index:

**Please delete in snp.index**
```
f3alsace=france3
```

And the new links in snp.index are not added:

**Please add to snp.index**
```
f3alpes=france3alpes
france3grenoble=france3alpes
f3alsace=france3alsace
france3strasbourg=france3alsace
f3aquitaine=france3aquitaine
france3bordeaux=france3aquitaine
f3auvergne=france3auvergne
france3clermontferrand=france3auvergne
f3bourgogne=france3bourgogne
france3dijon=france3bourgogne
f3bretagne=france3bretagne
france3rennes=france3bretagne
f3centre=france3centre
france3orleans=france3centre
f3champardenne=france3champagneardenne
france3reims=france3champagneardenne
f3corseviastella=france3corse
france3viastella=france3corse
viastella=france3corse
f3cotedazur=france3cotedazur
france3marseille=france3cotedazur
f3franchecomte=france3franchecomte
france3besancon=france3franchecomte
f3languedocrou=france3languedocroussillon
france3montpellier=france3languedocroussillon
f3limousin=france3limousin
france3limoges=france3limousin
f3lorraine=france3lorraine
france3nancy=france3lorraine
f3midipyrenees=france3midipyrenees
france3toulouse=france3midipyrenees
f3nordpdc=france3nordpasdecalais
france3lille=france3nordpasdecalais
f3bnormandie=france3normandie
f3hnormandie=france3normandie
france3caen=france3normandie
france3rouen=france3normandie
f3parisidf=france3parisiledefrance
france3paris=france3parisiledefrance
f3paysdeloire=france3paysdelaloire
france3nantes=france3paysdelaloire
f3picardie=france3picardie
france3amiens=france3picardie
f3poitouchar=france3poitoucharentes
france3poitiers=france3poitoucharentes
f3provalpes=france3provencealpes
france3nice=france3provencealpes
f3rhonealpes=france3rhonealpes
france3lyon=france3rhonealpes
```

By the way these logos are also the old ones and not in use anymore:
```
france2hd
france3hd
france4hd
france5hd
franceohd
```
