### ISSUE TITLE
New French logos (1)

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#302]
While waiting for an answer in issue #301 first the changes for TF1 Groupe:

**New logos:**
[TF1 Groupe.zip](https://github.com/picons/picons-source/files/1675054/TF1.Groupe.zip)

Logo of `lci` also changed (a little), but this was the best logo to be found until now, so maybe waiting if a better one is found:
[lci.zip](https://github.com/picons/picons-source/files/1675056/lci.zip)

**Delete from snp.index**
```
hd1=hd1
hd1hd=hd1
nt1=nt1
nt1hd=nt1
```

**Add to snp.index**
Names have not been changed on all three satellites, so for now:
```
hd1=tf1seriesfilms
nt1=tfx
```

**Delete from srp.index**
```
140_3E1C_13F_820000=hd1
232B_442_1_C00000=hd1
5DF_F_1_FFFF0000=hd1
A01_A_20FA_EEEE0000=hd1
BB8_4E84_55F_DDE0000=hd1
137_3E1C_13F_820000=nt1
1A8_4FB0_55F_DDE0000=nt1
21FE_44C_1_C00000=nt1
608_6_20FA_EEEE0000=nt1
```

**Add to srp.index**
```
140_3E1C_13F_820000=tf1seriesfilms
232B_442_1_C00000=tf1seriesfilms
5DF_F_1_FFFF0000=tf1seriesfilms
A01_A_20FA_EEEE0000=tf1seriesfilms
BB8_4E84_55F_DDE0000=tf1seriesfilms
137_3E1C_13F_820000=tfx
1A8_4FB0_55F_DDE0000=tfx
21FE_44C_1_C00000=tfx
608_6_20FA_EEEE0000=tfx
```

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
jpg here for conversion
`
http://www.fortuneo-banque-l-offre-de-parrainage.fr/wp-content/uploads/2017/10/LCI-Logo-700.jpg
`

**Comment by Lexzie** [comment]
Converted, the currect one can be replaced:
[lci(AbuBaniaz).zip](https://github.com/picons/picons-source/files/1675382/lci.AbuBaniaz.zip)

**Comment by mcfly822** [comment]
I had a little time tonight, so I drawed this logo in inkscape :)
But unfortunately, the color gradient is not ok when opening in internet explorer or in GIMP, only okay in inkscape. I don't know why...
So I exported to png.
Here are the svg and the png. The svg is useless in this format, I upload just for watching.
[lci_mcfly822.zip](https://github.com/picons/picons-source/files/1675512/lci_mcfly822.zip)

**Comment by dalmore72** [comment]
Found svg files here. https://www.tf1.fr/tfx/
[French logos.zip](https://github.com/picons/picons-source/files/1677114/French.logos.zip)

**Comment by Lexzie** [comment]
Excellent. Yesterday there was no sign of the new channels on tf1.fr (still NT1 and HD1).
There is something wrong with the text _Séries Films_ in the TF1 Séries Films logo maybe @mcfly822 can fix that?

![tf1seriesfilms](https://user-images.githubusercontent.com/14023349/35565998-14612fce-05c0-11e8-861d-461cb0661639.png)


Here are LCI and TFX in optimized svg format and the correct filenames, can someone replace the png's?
[LCI+TFX.zip](https://github.com/picons/picons-source/files/1677609/LCI.TFX.zip)

**Comment by mcfly822** [comment]
@Lexzie yes, there was a problem with TF1 Séries logo.
I worked on it a lot 😺 
Added some more logos in this PR.
Thanks @dalmore72 for the source!
