### ISSUE TITLE
Arena Sport logos

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#304]
Current logos for Arena Sport 1-6 are png's.
I found svg's for Arena Sport 1-4, but they contain a embedded image:
[ArenaSport1-4.zip](https://github.com/picons/picons-source/files/1679907/ArenaSport1-4.zip)
I don't know if it can be fixed. (Otherwise export to png? What size?)

Still to find/make svg for Arena Sport 5 and Arena Sport 6.

Besides that the current logos have to much space left and right, I edited that out in the Arena Sport 5 & 6 logos:
[ArenaSport5+6.zip](https://github.com/picons/picons-source/files/1679924/ArenaSport5.6.zip)

All links are already present.

`donkey monkey got issued`

**Comment by mcfly822** [comment]
@Lexzie Wow, thanks for the svg logos!
Unfortunately, they really contains base64 part, and I could delete them only line by line in text editor.
I checked them after, and it is good in GIMP. I will upload them immediately.

And yes, you're right, sometiems it is the only option to export the svgs with embedded images to png.
Size is a good question, I think 1500-2000px is enough.
