### ISSUE TITLE
Can the svg logo of Earth TV be adjusted?

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#309]
Can this logo easily be adjusted that it still can be used as a svg?
Otherwise export as png (1000x1000 pixels?).
[earthtv.zip](https://github.com/picons/picons-source/files/1693419/earthtv.zip)

**Comment by mcfly822** [comment]
Yes, it is good in svg. Just a little correction was needed.
[earthtv.default.zip](https://github.com/picons/picons-source/files/1694277/earthtv.default.zip)

**Comment by Lexzie** [comment]
Yes, now it can be opened (normally) in GIMP.
Can the logo be added to the sourde?
https://github.com/picons/picons-source/files/1694277/earthtv.default.zip

**Please add to snp.index**
```
earthtv=earthtv
```

**Please add to srp.index**
```
134_9EFC_7E_462C51=earthtv
1FC_765C_7E_462C28=earthtv
```
`donkey monkey got issued`

**Comment by Lexzie** [comment]
Looking good, thank you all!
