### ISSUE TITLE
nc+ new logos

### ISSUE THREAD

**Issue by vpont** [picons/picons-source#31]
nc+ has changed the logos of their channels:

![new logos](http://media2.pl/g/0/45897.jpg)
http://media2.pl/g/0/45897.jpg

I have yet to find them in good quality + transparent, but just in case someone does before me.

**Comment by charlesduco** [comment]
I found the logos in vector format. I will add a global nc+ update later this evening.

**Comment by vpont** [comment]
Thanks Charles!
