### ISSUE TITLE
Newer Skylink CZ/SK logos

### ISSUE THREAD

**Issue by mprajsler** [picons/picons-source#31]
STV 1 HD
http://www.lyngsat-logo.com/hires/rr/rtv_sk_1_hd.png
1_0_1_1329_CA2_3_EB0000_0_0_0

STV 2 HD
http://www.lyngsat-logo.com/hires/rr/rtv_sk_2_hd.png
1_0_1_132A_CA2_3_EB0000_0_0_0

TV JOJ
http://www.lyngsat-logo.com/hires/jj/joj_tv_sk.png
1_0_1_13ED_C87_3_EB0000_0_0_0

TV JOJ HD
http://www.lyngsat-logo.com/hires/jj/joj_tv_sk_hd.png
1_0_1_3398_C89_3_EB0000_0_0_0

Markiza
http://www.lyngsat-logo.com/hires/mm/markiza_tv_sk.png
1_0_1_13EF_C87_3_EB0000_0_0_0

Markiza HD
http://www.lyngsat-logo.com/hires/mm/markiza_tv_sk_hd.png
1_0_1_13B4_C95_3_EB0000_0_0_0

Nova HD
http://www.lyngsat-logo.com/hires/nn/nova_cz_tv_hd.png
1_0_1_3391_C89_3_EB0000_0_0_0

Nova Cinema HD
http://www.lyngsat-logo.com/hires/nn/nova_cz_cinema_hd.png
1_0_1_3395_C89_3_EB0000_0_0_0

Prima HD
http://www.lyngsat-logo.com/hires/pp/prima_tv_cz_hd.png
1_0_1_3392_C89_3_EB0000_0_0_0

Prima COOL HD
http://www.lyngsat-logo.com/hires/pp/prima_cool_cz_hd.png
1_0_1_3396_C89_3_EB0000_0_0_0

Prima COOL
http://www.lyngsat-logo.com/hires/pp/prima_cool_cz.png
1_0_1_3351_C93_3_EB0000_0_0_0

TV Barrandov HD
http://www.lyngsat-logo.com/hires/bb/barrandov_cz_tv_hd.png
1_0_1_132B_CA2_3_EB0000_0_0_0

Kino Barrandov HD
http://www.lyngsat-logo.com/hires/bb/barrandov_cz_kino_hd.png
1_0_1_132C_CA2_3_EB0000_0_0_0

Barrandov Plus HD
http://www.lyngsat-logo.com/hires/bb/barrandov_cz_plus_hd.png
1_0_1_132D_CA2_3_EB0000_0_0_0

Thank you

**Comment by janky69** [comment]
Hi, next is Prima MAX
http://www.lyngsat-logo.com/hires/pp/prima_max_cz.png

and Prima MAX HD
http://www.lyngsat-logo.com/hires/pp/prima_max_cz_hd.png

Thank you!

**Comment by mocram** [comment]
https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

**Comment by mprajsler** [comment]
Hi janky69 Prima MAX is there in latest version thanks to charlesduco
https://github.com/picons/picons-source/issues/27

**Comment by janky69** [comment]
Sorry!

**Comment by charlesduco** [comment]
@janky69 @mprajsler 
Please check if everything is updated as expected.
If not, provide me with the missing service references or logos and please stricttly follow the contributing rules when submitting.

**Comment by janky69** [comment]
Thank you very much! Your work is great!
Dne 1. 2. 2016 20:27 napsal uživatel "charlesduco" <notifications@github.com

**Comment by mprajsler** [comment]
Big thanks!
