### ISSUE TITLE
Sony Crime channels

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#314]
Sony Channel, Sony Channel +1 and True Crime are renamed to
Sony Crime Channel, Sony Crime Channel +1 and Sony Crime Channel 2.

Made a light version and the other logos myself, I hope they can get your approval, but if anyone wants them differently or have a better source, no problem, I'm open to suggestions.
[Logos_to_add.zip](https://github.com/picons/picons-source/files/1707846/Logos_to_add.zip)

Logos of @dalmore72 are better i.m.o., see below.

**Comment by dalmore72** [comment]
Made these yesterday :)

[Sony Crime Channel.zip](https://github.com/picons/picons-source/files/1707997/Sony.Crime.Channel.zip)

**Comment by Lexzie** [comment]
All fine with me, should have know that 28.2E is well kept. 😄 

I renamed your logos to the correct naming, result is:

[Logo_to_replace.zip](https://github.com/picons/picons-source/files/1708026/Logo_to_replace.zip)
[Logos_to_add.zip](https://github.com/picons/picons-source/files/1708027/Logos_to_add.zip)


**Add to snp.index**
```
sonycrime=sonycrimechannel
sonycrime2=sonycrimechannel2
sonycrimeplus1=sonycrimechannelplus1
```

**Delete from srp.index**
```
D089_83E_2_11A0000=sonychannel
D08E_83E_2_11A0000=sonychannelplus1
CD41_844_2_11A0000=truecrime
```

**Add to srp.index**
```
D089_83E_2_11A0000=sonycrimechannel
CD41_844_2_11A0000=sonycrimechannel2
D08E_83E_2_11A0000=sonycrimechannelplus1
```

`donkey monkey got issued`

**Comment by dalmore72** [comment]
When searching for logos for 28.2, it's a good idea to use UK at the end of search Words

https://www.google.no/search?biw=1536&bih=745&tbm=isch&sa=1&ei=hoR8WuGYHcavsQGq4LmICA&q=Sony+Crime+Channel+uk&oq=Sony+Crime+Channel+uk&gs_l=psy-ab.3..0i19k1.55525.55848.0.57006.2.2.0.0.0.0.166.326.0j2.2.0....0...1c.1.64.psy-ab..0.2.325....0.nGtJhAEh98g#imgrc=-LrqRR1KZ6lpHM:&spf=1518109888885

**Comment by mocram** [comment]
Adding `filetype:png` or `filetype:svg` also helps

https://www.google.no/search?biw=1400&bih=919&tbm=isch&ei=-rt9WpKiPMWZkwXaj6DYBA&oq=Sony+Crime+Channel+uk+filetype:png&gs_l=psy-ab.3...13194.19064.0.19519.13.13.0.0.0.0.58.661.13.13.0....0...1c.1.64.psy-ab..0.0.0....0.CF9JYhMEQLU&q=Sony+Crime+Channel+uk&tbs=ift:png

**Comment by AbuBaniaz** [comment]
Added some here
https://github.com/picons/picons-source/commit/10c5abb33080b5e47ee4f2281909dd34cfa2b6de

**Comment by Lexzie** [comment]
The `light` versions are not uploaded.
[sonycrime.light.zip](https://github.com/picons/picons-source/files/1713474/sonycrime.light.zip)

**Comment by AbuBaniaz** [comment]
I can't see the difference. I'll leave to mocram and charlesduco

**Comment by Lexzie** [comment]
No difference??

![afbeelding](https://user-images.githubusercontent.com/14023349/36229784-acd78cfc-11d8-11e8-8df7-f6290708dd58.png)![afbeelding](https://user-images.githubusercontent.com/14023349/36229795-b216fa04-11d8-11e8-84d2-2e58d09606ab.png)

I can't see f.e. the `+1` on a dark background.

Further more, the current logo of `sonycrimechannel` is still the 230x266 pixel version.

**Please replace `sonycrimechannel.default.png':**
[sonycrimechannel.default(20180214).zip](https://github.com/picons/picons-source/files/1725776/sonycrimechannel.default.20180214.zip)

**Please add the `light` versions:**
[light-logos(20180214).zip](https://github.com/picons/picons-source/files/1725787/light-logos.20180214.zip)

**Comment by Lexzie** [comment]
Looking great! Thanks.
