### ISSUE TITLE
BBC channels logo variation (poll)

### ISSUE THREAD

**Issue by mcfly822** [picons/picons-source#317]
Hi all,
I made an alternative logo for BBC Earth.
The text is from the offcial logo, and the colors from the channel's facebook profile image.
http://logos.wikia.com/wiki/File:BBC_Earth.svg
https://www.facebook.com/bbcearth/

I just made the color of the letters from the background color.

Existing:
![bbcearth](https://user-images.githubusercontent.com/22531870/36029002-a4aa6832-0da1-11e8-95ff-8abc9a3dcc7e.png)

New alternative:
![bbcearth_alternative](https://user-images.githubusercontent.com/22531870/36029465-98e5dfc0-0da3-11e8-9b4d-b494e54fb6e7.png)

What do you think about this variation? Which one is better, the alternative or the (existing) original?

**Comment by dalmore72** [comment]
New is better.
Can you make one for HD
[BBC earth hd.zip](https://github.com/picons/picons-source/files/1711327/BBC.earth.hd.zip)

**Comment by mcfly822** [comment]
@dalmore72 thanks!
Of course, I can make, but not yet, I'm not at my PC. Maybe later this weekend.
Besides, your attached image is much better, because it has better arrangement. I thik about it to use this arrangement also for SD logo.

Any opinion or suggests are highly appreciated :wink

**Comment by mocram** [comment]
new one

**Comment by AbuBaniaz** [comment]
New one. Please submit a pull request

**Comment by Lexzie** [comment]
The new one seems better, but I think both are okay.
The logo on screen does not show `HD` in the name.
![afbeelding](https://user-images.githubusercontent.com/14023349/36036816-20bb6de0-0dbb-11e8-81e4-41c90d5411f3.png)

Maybe considering coloring all BBC logos?
![afbeelding](https://user-images.githubusercontent.com/14023349/36038352-bb4c729c-0dbf-11e8-954d-81dfe9fe518e.png) ![afbeelding](https://user-images.githubusercontent.com/14023349/36038398-e3e31cd8-0dbf-11e8-9650-95cd4c6f7cbb.png) ![afbeelding](https://user-images.githubusercontent.com/14023349/36038435-028fe49a-0dc0-11e8-8725-d25c04b77bad.png)
![afbeelding](https://user-images.githubusercontent.com/14023349/36038508-3599051a-0dc0-11e8-980b-61a8a3dfe66d.png) ![afbeelding](https://user-images.githubusercontent.com/14023349/36038525-41155f4c-0dc0-11e8-9cdb-2cf18d4ecae1.png) ![afbeelding](https://user-images.githubusercontent.com/14023349/36038567-523d87d6-0dc0-11e8-85b5-5bdd2cc7a920.png)

BBC Four and BBC First have a alomost black background, so can not be done on the `light` logos, only the `default` ones. Perhaps for BBC HD and BBC Brit too (dark purple and dark blue).
![afbeelding](https://user-images.githubusercontent.com/14023349/36038787-efc7d240-0dc0-11e8-9e61-13338715b269.png) ![afbeelding](https://user-images.githubusercontent.com/14023349/36038793-f3c5da72-0dc0-11e8-8b05-98cf0495a24d.png)

**Comment by mcfly822** [comment]
Thank you all for the answers!

Two more questions:

1. vertical or horizontal arrangement?

Vertical:
![vert](https://user-images.githubusercontent.com/22531870/36044804-1552b878-0dd4-11e8-9ad2-50c4c7fef467.png)

Horizontal:
![hor](https://user-images.githubusercontent.com/22531870/36044814-1fec35f2-0dd4-11e8-97df-5b062346f41e.png)

2. As @Lexzie suggested. should I make logos in this style for all the BBC channels? (BBC One, Entertainment, etc.)

**Comment by AbuBaniaz** [comment]
On two lines will look better for picons. On one line, it will be too small.

**Comment by mcfly822** [comment]
Here are other BBC logo in this style.
I did not made any HD logos, because as far as I know that there are no HD logos in use (nor for BBC Earth, I made it because dalmore72 asked).
Some of the logos was not reasonable to make as @Lexzie mentioned.
I made the BBC Brit logo light format from a main color on BBC Brit website.

Please give me some feedback about these logos. When everything is okay, I will upload them.
[bbcvariations_mcfly822.zip](https://github.com/picons/picons-source/files/1716261/bbcvariations_mcfly822.zip)

**Comment by AbuBaniaz** [comment]
In my opinion, there is too much space between `bbc` and next line.
Are colours correct?
```
https://www.bbc.co.uk/tv
```

**Comment by mcfly822** [comment]
I did not chamge the arrangement, only the colors. So if these logos have too big space between the lines, the origibals have also :-) 
I think the colors are okay, but I will check again.

**Comment by mcfly822** [comment]
@AbuBaniaz 

> In my opinion, there is too much space between bbc and next line.

Which logos? Only BBC Arabic, or any others?

**Comment by mcfly822** [comment]
So, what do you think? Should I make them with less gap? But then it will not be the official format.
I can make, just say "do it" 😺 
The colors on the website are a bit different, I will correct them.

**Comment by AbuBaniaz** [comment]
So long as they look good. I'll leave to your better judgement.

**Comment by mcfly822** [comment]
Thanks 👍 
I'll do them soon.

**Comment by mcfly822** [comment]
I'm working on this issue.
I checked every colors again, a little correction was needed.
But about the gap between words, I think it is no problem. The word "BBC" is the company, the channel family, and the other words like "one", "two", "news", etc. are the exact channel names. The font size of "BBC" and e.g. "WORLD NEWS" are also different. So I think, it is no problem that the gap is a bit bigger by some pixels.
(Besides, you cannot see this difference in a little picon. At bigger picons, maybe viewable.)

So I vote to leave the logos arrangement as they are now, only change the colors.
But as I said, I can change them, and I'm open for every ideas.

**Comment by mcfly822** [comment]
@AbuBaniaz any other suggestions? Do you agree with me?

**Comment by AbuBaniaz** [comment]
Do what you feel is best. Im sure we can improve if there are complaints

**Comment by mcfly822** [comment]
Thanks!

**Comment by Lexzie** [comment]
HD logos 'bbconehd`, `bbctwohd`, `bbcnewshd` are still in the old layout.
Or the hd-links have to be removed, so one logo is used for both SD and HD versions?

**Comment by mcfly822** [comment]
@Lexzie I think it is better to use the same logo for SD and HD channels, because (AFAIK) there is no "HD" sign on the on-screen logos.
Maybe we can also delete the BBC Earth HD logo.

**Comment by Lexzie** [comment]
Okay, if all agree on linking the `HD` channels to the same (general) logo, the following changes are needed:

**Delete from snp.index**
```
bbcnewshd=bbcnewshd
6945=bbconehd
bbc1hd=bbconehd
bbc1scothd=bbconehd
bbconehd=bbconehd
bbconenihd=bbconehd
bbconescothd=bbconehd
bbconewalhd=bbconehd
bbc2hd=bbctwohd
bbctwohd=bbctwohd
```

**Add to snp.index**
```
6945=bbcone
bbc1scothd=bbcone
bbconewalhd=bbcone
```

**Delete from srp.index**
```
A000_A000_233A_EEEE0000=bbcnewshd
22D9_80D_2_11A0000=bbcnewshd
EDC_26_F020_FFFF0000=bbcnewshd
28AA_68_F020_FFFF0000=bbconehd
28A9_68_F020_FFFF0000=bbconehd
28A8_68_F020_FFFF0000=bbconehd
4484_4083_233A_EEEE0000=bbconehd
4F4D_CB_1_FFFF0000=bbconehd
1B33_802_2_11A0000=bbconehd
1B31_802_2_11A0000=bbconehd
BBA_1E_25A8_FFFF0000=bbconehd
4484_4085_233A_EEEE0000=bbconehd
4484_4084_233A_EEEE0000=bbconehd
1B1D_802_2_11A0000=bbconehd
1B1F_802_2_11A0000=bbconehd
1B21_802_2_11A0000=bbconehd
22C5_80D_2_11A0000=bbconehd
22CF_80D_2_11A0000=bbconehd
4484_4082_233A_EEEE0000=bbconehd
28A7_68_F020_FFFF0000=bbconehd
4E36_802_600_FFFF0000=bbconehd
4440_4083_233A_EEEE0000=bbctwohd
1B30_802_2_11A0000=bbctwohd
A2A_1A_25A8_FFFF0000=bbctwohd
4440_4085_233A_EEEE0000=bbctwohd
4440_4084_233A_EEEE0000=bbctwohd
1B1C_802_2_11A0000=bbctwohd
4440_4082_233A_EEEE0000=bbctwohd
A8D_1B_F020_FFFF0000=bbctwohd
4BA9_817_600_FFFF0000=bbctwohd
```

**Add to srp.index**
```
A000_A000_233A_EEEE0000=bbcnews
22D9_80D_2_11A0000=bbcnews
EDC_26_F020_FFFF0000=bbcnews
28AA_68_F020_FFFF0000=bbcone
28A9_68_F020_FFFF0000=bbcone
28A8_68_F020_FFFF0000=bbcone
4484_4083_233A_EEEE0000=bbcone
4F4D_CB_1_FFFF0000=bbcone
1B33_802_2_11A0000=bbcone
1B31_802_2_11A0000=bbcone
BBA_1E_25A8_FFFF0000=bbcone
4484_4085_233A_EEEE0000=bbcone
4484_4084_233A_EEEE0000=bbcone
1B1D_802_2_11A0000=bbcone
1B1F_802_2_11A0000=bbcone
1B21_802_2_11A0000=bbcone
22C5_80D_2_11A0000=bbcone
22CF_80D_2_11A0000=bbcone
4484_4082_233A_EEEE0000=bbcone
28A7_68_F020_FFFF0000=bbcone
4E36_802_600_FFFF0000=bbcone
4440_4083_233A_EEEE0000=bbctwo
1B30_802_2_11A0000=bbctwo
A2A_1A_25A8_FFFF0000=bbctwo
4440_4085_233A_EEEE0000=bbctwo
4440_4084_233A_EEEE0000=bbctwo
1B1C_802_2_11A0000=bbctwo
4440_4082_233A_EEEE0000=bbctwo
A8D_1B_F020_FFFF0000=bbctwo
4BA9_817_600_FFFF0000=bbctwo
```

`donkey monkey got issued`

**Comment by mcfly822** [comment]
I cannot reopen this issue.
Maybe @AbuBaniaz will make this changes, please :-)

**Comment by mcfly822** [comment]
Thanks! :-) 
Will you make the changes, or may I add them by a PR?

**Comment by AbuBaniaz** [comment]
I won't be doing it nor merging the pull request. I'll leave it to Charles and Mocram if they want to stop using the BBC HD logos.

**Comment by mcfly822** [comment]
@AbuBaniaz You're right.
Please @charlesduco or @mocram decide about this.

**Comment by mcfly822** [comment]
It was easier to make the HD version of these 3 logos instead of waitin' for the decision, and delete all of the HD logos.
Now these HD logos are in the style as I described in the first post..
@AbuBaniaz please accept my PR and I can close this issue forever ⛪️ 😄

**Comment by mcfly822** [comment]
Great, thanks @AbuBaniaz !
