### ISSUE TITLE
Logos Iceland

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#319]
Getting svg's out of the pdf's supplied by @dalmore72

**Comment by dalmore72** [comment]
:)
[Logos Iceland.zip](https://github.com/picons/picons-source/files/1713290/Logos.Iceland.zip)

**Comment by Lexzie** [comment]
Thanks @dalmore72 , great work!
All the logos are svg's now, put them together here:
[Iceland(20180210).zip](https://github.com/picons/picons-source/files/1713526/Iceland.20180210.zip)

Please add these logos and links.


**Add to snp.index**
```
krakkaruv=krakkaruv
n4=n4
ruvras1=ras1
ruvras2=ras2
ruvrondo=rondo
ruv=ruv
ruv1=ruv
ruv2=ruv2
```

**Add to srp.index**
```
AFC_22_46_E080000=ruv
```

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
Your attachment had .png and .svg I have not added the .png files

**Comment by Lexzie** [comment]
Weird, I thought I had removed the png's from the zip. Of course only the svg's need to be added.

**Comment by Lexzie** [comment]
Thanks
