### ISSUE TITLE
TvHeadned server mode

### ISSUE THREAD

**Issue by janky69** [picons/picons-source#32]
Hi,

in last version is this mode disabled, its true?

**Comment by mocram** [comment]
Where should it be disabled? In TvHeadend or?

Try to make your question understandable.

**Comment by janky69** [comment]
Sorry for my bad english. When I run first script (1-build...) it run only
in file mode, not in server mode even when I place config file into
build-input folder.

Thank you very much for your time!
Dne 31. 1. 2016 9:22 napsal uživatel "mocram" <notifications@github.com>:

**Comment by mocram** [comment]
What is the output on the console? Perhaps you incorrectly named the file tvheadend.serverconf
