### ISSUE TITLE
Empty picons

### ISSUE THREAD

**Issue by encript** [picons/picons-source#32]
cp: cannot stat ‘/dev/shm/picons-tmp/newbuildsource/symlinks/*’: No such file or directory

I cannot seem to build these icons. The resulting build folder contains empty tar files. No images.

**Comment by picons** [comment]
Could you upload your `servicelist_*``file?

**Comment by encript** [comment]
Here is the output that I receive. Your assistance is greatly appreciated, 

![screenshot from 2015-06-07 14-16-19](https://cloud.githubusercontent.com/assets/3502737/8025323/d28b41f2-0d1f-11e5-9ab2-1b30d282fa75.png)

1_0_0_9_7DF_FFFF_DDDD0000_0_0_0   --------  Aliento
1_0_0_4_875_FFFF_DDDD0000_0_0_0   --------  Antenna
1_0_0_8_7DF_FFFF_DDDD0000_0_0_0   --------  Azteca
1_0_0_1_8095_FFFF_DDDD0000_0_0_0  --------  BizTV
1_0_0_5_7E3_FFFF_DDDD0000_0_0_0   --------  BOUNCE 
1_0_0_2_1_FFFF_DDDD0000_0_0_0     --------  CCTV 4
1_0_0_3_1_FFFF_DDDD0000_0_0_0     --------  CCTV Sp
1_0_0_4_7DF_FFFF_DDDD0000_0_0_0   --------  CGN-TV
1_0_0_4_86F_FFFF_DDDD0000_0_0_0   --------  COZI-TV
1_0_0_3_877_FFFF_DDDD0000_0_0_0   --------  CUNY   
1_0_0_2_86D_FFFF_DDDD0000_0_0_0   --------  DECADES
1_0_0_3_20C1_FFFF_DDDD0000_0_0_0  --------  GCN
1_0_0_2_8095_FFFF_DDDD0000_0_0_0  --------  Hope
1_0_0_8_879_FFFF_DDDD0000_0_0_0   --------  HSN
1_0_0_2_13A7_FFFF_DDDD0000_0_0_0  --------  ICN CH
1_0_0_3_879_FFFF_DDDD0000_0_0_0   --------  ION
1_0_0_5_879_FFFF_DDDD0000_0_0_0   --------  IONLife
1_0_0_B_7DF_FFFF_DDDD0000_0_0_0   --------  KCBN
1_0_0_4_7DB_FFFF_DDDD0000_0_0_0   --------  KIDS
1_0_0_3_873_FFFF_DDDD0000_0_0_0   --------  LAFF
1_0_0_2_873_FFFF_DDDD0000_0_0_0   --------  LivWell
1_0_0_3_211D_FFFF_DDDD0000_0_0_0  --------  MeTV
1_0_0_5_871_FFFF_DDDD0000_0_0_0   --------  Movies!
1_0_0_6_7E3_FFFF_DDDD0000_0_0_0   --------  MundoFx
1_0_0_7_7DF_FFFF_DDDD0000_0_0_0   --------  NTDTV
1_0_0_2_877_FFFF_DDDD0000_0_0_0   --------  NYGOV  
1_0_0_1_877_FFFF_DDDD0000_0_0_0   --------  NYLIFE 
1_0_0_3_875_FFFF_DDDD0000_0_0_0   --------  PIX11  
1_0_0_4_879_FFFF_DDDD0000_0_0_0   --------  qubo
1_0_0_7_879_FFFF_DDDD0000_0_0_0   --------  QVC
1_0_0_6_879_FFFF_DDDD0000_0_0_0   --------  Shop
1_0_0_5_7DF_FFFF_DDDD0000_0_0_0   --------  SinoEng
1_0_0_6_7DF_FFFF_DDDD0000_0_0_0   --------  SinoVSN
1_0_0_4_7D5_FFFF_DDDD0000_0_0_0   --------  TeleX  
1_0_0_5_875_FFFF_DDDD0000_0_0_0   --------  ThisTV 
1_0_0_1_20C1_FFFF_DDDD0000_0_0_0  --------  UAN
1_0_0_5_7DB_FFFF_DDDD0000_0_0_0   --------  V-Me
1_0_0_1_1_FFFF_DDDD0000_0_0_0     --------  W41DO-D
1_0_0_1_873_FFFF_DDDD0000_0_0_0   --------  WABC-HD
1_0_0_3_13A7_FFFF_DDDD0000_0_0_0  --------  WASA.3
1_0_0_1_13A7_FFFF_DDDD0000_0_0_0  --------  WASA-HD
1_0_0_4_13A7_FFFF_DDDD0000_0_0_0  --------  WASA-SD
1_0_0_1_86D_FFFF_DDDD0000_0_0_0   --------  WCBS-HD
1_0_0_A_7DF_FFFF_DDDD0000_0_0_0   --------  WDNJ
1_0_0_2_7E1_FFFF_DDDD0000_0_0_0   --------  WFUT-DT
1_0_0_3_7DF_FFFF_DDDD0000_0_0_0   --------  WMBC DT
1_0_0_3_8095_FFFF_DDDD0000_0_0_0  --------  WMBQ 3
1_0_0_4_8095_FFFF_DDDD0000_0_0_0  --------  WMBQ 4
1_0_0_1_1783_FFFF_DDDD0000_0_0_0  --------  WMUN-CD
1_0_0_3_86F_FFFF_DDDD0000_0_0_0   --------  WNBC   
1_0_0_3_7DB_FFFF_DDDD0000_0_0_0   --------  WNET-HD
1_0_0_3_7D5_FFFF_DDDD0000_0_0_0   --------  WNJU-HD
1_0_0_3_871_FFFF_DDDD0000_0_0_0   --------  WNYW   
1_0_0_4_7E3_FFFF_DDDD0000_0_0_0   --------  WNYW-SD
1_0_0_1_0_FFFF_DDDD0000_0_0_0     --------  WPXO-D1
1_0_0_2_0_FFFF_DDDD0000_0_0_0     --------  WPXO-D2
1_0_0_4_871_FFFF_DDDD0000_0_0_0   --------  WWOR-SD
1_0_0_3_7E3_FFFF_DDDD0000_0_0_0   --------  WWOR-TV
1_0_0_1_7E1_FFFF_DDDD0000_0_0_0   --------  WXTV-DT

**Comment by picons** [comment]
Those servicerefs are not included in srindex, so it's to be expected that you get no picons.
What kind of channel source are you watching? iptv? Because I have never seen DDDD0000.....

**Comment by encript** [comment]
I watch TV using OTA (over-the-air). I guess that explains my issue. But how do people who capture TV via the airwaves get icons like others?

**Comment by encript** [comment]
Am I to understand OTA users can not receive picons?

**Comment by rousslabs** [comment]
Same exact issue here with over the air channels using tvheadend.

**Comment by picons** [comment]
It should either be EEEE0000 or FFFF0000 for DVB-T (air) or DVB-C (cable), I didn't know about DDDD0000, I thought it was something that tvheadend came up with for IPTV, or as it turns out a bug again in tvheadend.

**Comment by rousslabs** [comment]
Ahh. Is picons only for DVB? I'm trying to tune ATSC channels and maybe DDDD0000 is associated with that. Judging by the channel lineup encript is doing the same.

**Comment by encript** [comment]
I am also ATSC.

**Comment by picons** [comment]
DDDD0000 could indeed be used for ATSC, picons originated from enigma2 tuners wich are as far as I'm aware not suited for ATSC. If the servicerefs for ATSC (DDDD0000) are added, the picons wil also work for ATSC.
