### ISSUE TITLE
Movistar Oscars

### ISSUE THREAD

**Issue by Jglez3** [picons/picons-source#323]
```
76C4_40E_1_C00000=movistaroscars
7607_408_1_C00000=movistaresports
```

Logo: http://www.movistarplus.es/recorte/m-NEO/canal/MOSCAR.png

I couldn't find a better one.

Thank you!

`donkey monkey got issued`

**Comment by mcfly822** [comment]
I made in vector format:
[movistaroscars.default.svg_mcfly822.zip](https://github.com/picons/picons-source/files/1727490/movistaroscars.default.svg_mcfly822.zip)
