### ISSUE TITLE
Sky 1 +1 HD (Astra 19.2) wrong Logo

### ISSUE THREAD

**Issue by TLeuchte** [picons/picons-source#324]
Hello,

the Channel Sky 1+1HD has the Old Sky Atlantic +1 HD Logo

In SRP is this the Line:
```
90_10_85_C00000=skyatlanticplus1hd
```

Correct this please to: 
```
90_10_85_C00000=sky1plus1
``` 
(No HD Logo available in Repo)

Thanks

**Comment by dalmore72** [comment]
Sky 1 +1 HD logo

[Sky 1 +1 HD.zip](https://github.com/picons/picons-source/files/1729362/Sky.1.1.HD.zip)

**Comment by AbuBaniaz** [comment]
I have made the .default one. Could someone assist with a .light version please?
[sky1plus1hd.default.svg.zip](https://github.com/picons/picons-source/files/1735515/sky1plus1hd.default.svg.zip)

**Comment by mcfly822** [comment]
Why is it needed to make .light version?
This logo is more than good at dark backround:
![sky1pl1](https://user-images.githubusercontent.com/22531870/36372535-9e38e55c-1565-11e8-9382-9ba58403329d.png)

**Comment by AbuBaniaz** [comment]
Well, the others have it too.

**Comment by charlesduco** [comment]
Default + light for `sky1plus1hd` are here:
[sky1plus1hd.zip](https://github.com/picons/picons-source/files/1739290/sky1plus1hd.zip)

**Comment by mcfly822** [comment]
@AbuBaniaz you are right, I didn't checked this. Sorry.
(I just started to make the light version, but I see now it is done by charles.)
