### ISSUE TITLE
Sky Logos German

### ISSUE THREAD

**Issue by TLeuchte** [picons/picons-source#329]
Hi

any Sky Logos for the German Channels have the old Style.

New Style Logo
![skyaction](https://user-images.githubusercontent.com/17363482/36417606-ada2e822-162c-11e8-8c3a-f69336e455b4.png)

Old Style Logos
![skycinemaemotion](https://user-images.githubusercontent.com/17363482/36417635-c192c424-162c-11e8-967e-06c082e91855.png)
![skycinemahd](https://user-images.githubusercontent.com/17363482/36417648-c4f2f350-162c-11e8-9b63-157ef7ead9c4.png)
![skycinema](https://user-images.githubusercontent.com/17363482/36417697-e5ae1304-162c-11e8-9de9-8f60ab0c098e.png)
![skycinemaplus1hd](https://user-images.githubusercontent.com/17363482/36417701-e8ec5d64-162c-11e8-820c-dea49d1682de.png)
![skycinemaplus1](https://user-images.githubusercontent.com/17363482/36417704-eadf2ba6-162c-11e8-9912-7957c698cdeb.png)
![skycinemaplus24hd](https://user-images.githubusercontent.com/17363482/36417708-ed2d1fd0-162c-11e8-8512-7e31ca437e63.png)
![skycinemaplus24](https://user-images.githubusercontent.com/17363482/36417711-eed3fc32-162c-11e8-8399-641cdffed720.png)
![skycinemanostalgie](https://user-images.githubusercontent.com/17363482/36417715-f1b00ce8-162c-11e8-9eb6-16385f515af7.png)

All Sky Sport 1-11+HD and Sky Sport Bundesliga 1-10 +HD

In the Channellist that seems so: 
![image](https://user-images.githubusercontent.com/17363482/36418085-11045094-162e-11e8-8892-e4a9700f1b76.png)

Best Regards

**Comment by mcfly822** [comment]
I cannot watch the onscreen logo at this moment, but on the offcial SKY Deutschland website, there are the 'old style' logos (capital letters)...
https://sport.sky.de/bundesliga

**Comment by mcfly822** [comment]
I checked now the Sky Sports 2 HD (Deutschland), and the word "SPORTS" is fully capital letters.
The German Sky still using the "old style" logos.
So I think it is not needed to update the logos in this issue.
![1_0_19_72_d_85_c00000_0_0_0](https://user-images.githubusercontent.com/22531870/36510474-65bb0f98-1763-11e8-8bd9-0b64c71f68cf.jpg)

**Comment by TLeuchte** [comment]
Hi,

but we use at this time two different types for the German Sky Logos.
In the Channellist shows that not so nice.
Comedy, Family and Hits has the new Style

**Comment by mcfly822** [comment]
@TLeuchte maybe correcting the references can solve this problem.
Assign the old style logos for the German Sky channels.

But it is also good to use the new logos.
For me, it is "scheißegal" 😸

**Comment by AbuBaniaz** [comment]
I presume you are using the SNP version. We can add the SRP links to so that a specific  logo can be used to make the picons.

I'll have to undelete some logos. Please list the wrong ones, including service reference

**Comment by AbuBaniaz** [comment]
@mcfly822, can you convert the capital version into svg files please?

**Comment by mcfly822** [comment]
Sure.
As soon as my boss and my wife don't give me another tasks :fearful: :smile_cat:

**Comment by TLeuchte** [comment]
Hi,

sorry for the long delay.
I can't use the snp Version. The Problem is, when is use this, the RTL Plus Logo uses the Wrong version.

Best Regards

**Comment by mcfly822** [comment]
I looked for in this repo, and the previous version of the new style logos are in capital.
So here you can find the capital version of these logos: Comedy, Family and Hits (@TLeuchte wrote that these logos are not good):

https://github.com/picons/picons-source/blob/090f9daeb9aa2547f1cb2c06cff10b25b1a024d4/build-source/logos/skycinemacomedy.default.svg
https://github.com/picons/picons-source/blob/090f9daeb9aa2547f1cb2c06cff10b25b1a024d4/build-source/logos/skycinemacomedy.light.svg
https://github.com/picons/picons-source/blob/090f9daeb9aa2547f1cb2c06cff10b25b1a024d4/build-source/logos/skycinemafamily.default.svg
https://github.com/picons/picons-source/blob/090f9daeb9aa2547f1cb2c06cff10b25b1a024d4/build-source/logos/skycinemafamily.light.svg
https://github.com/picons/picons-source/blob/090f9daeb9aa2547f1cb2c06cff10b25b1a024d4/build-source/logos/skycinemahits.default.svg
https://github.com/picons/picons-source/blob/090f9daeb9aa2547f1cb2c06cff10b25b1a024d4/build-source/logos/skycinemahits.light.svg

Only it must be renamed (add some random characters to the filename) and assign the german sky channels to them.

**Comment by AbuBaniaz** [comment]
>I can't use the snp Version. The Problem is, when is use this, the RTL Plus Logo uses the Wrong version.

Which is the correct logo?
What is the service reference?

**Comment by mcfly822** [comment]
Is there anything to do with this issue?

**Comment by AbuBaniaz** [comment]
Needs someone with German TV to check.

**Comment by Lexzie** [comment]
The logos for Sky Deutschland on screen and on their website are still in the old format.
Also found some incorrect and some missing links.
The logos for Sky UK have changed, I guess that's why the Sky Cinema Comedy (Germany) logo was wrong.
Right now, this is the only one in the German Sky package which needs to be corrected.
Sky Italia also still uses the old logos, but the old logos of Sky Cinema Comedy HD, Sky Cinema Classic and Sky Classics HD are not in the source (anymore?).
I checked snp and srp as well.

**Please delete from snp.index**
```
cinemacomedy=skycinemacomedy
skycinemacomedy=skycinemacomedy
cinemacomedyhd=skycinemacomedyhd
cinemafamily=skycinemafamily
cinemafamilyhd=skycinemafamilyhd
197_4_85_C00000=skycinemafamily-phibruspel
8B_8_85_C00000=skycinemafamilyhd-phibruspel
FD_2_85_FFFF0000=skysport11
102_E_85_C00000=skysport11hd
```

**Please add to snp.index**
```
skycinemaanimation=skycinemaanimation-phibruspel
skycinemaanimationhd=skycinemaanimationhd-phibruspel
584_1A90_FBFF_820000=skyatlantic-phibruspel
3792_2008_FBFF_820000=skyatlantichd-phibruspel
cinemacomedy=skycinemacomedy-phibruspel
skycinemacomedy=skycinemacomedy-phibruspel
cinemafamily=skycinemafamily-phibruspel
skycinemafamily=skycinemafamily-phibruspel
cinemafamilyhd=skycinemafamilyhd-phibruspel
skycinemafamilyhd=skycinemafamilyhd-phibruspel
maxcollectionhd=skycinemamaxcollectionhd
skysport11=skysport11
skysport11hd=skysport11hd
```

**Please delete from srp.index**
```
584_1A90_FBFF_820000=skyatlantic
8_3_85_C00000=skycinemacomedy
2DCD_1A2C_FBFF_820000=skycinemacomedy
2B16_1900_FBFF_820000=skycinemacomedyhd
2B61_19C8_FBFF_820000=skycinemafamily
197_4_85_C00000=skycinemafamily-phibruspel
8B_8_85_C00000=skycinemafamilyhd
1C57_206C_FBFF_820000=skycinemafamilyhd
8B_8_85_C00000=skycinemafamilyhd-phibruspel
```

**Please add to srp.index**
```
197_4_85_C00000=skycinemaanimation-phibruspel
8B_8_85_C00000=skycinemaanimationhd-phibruspel
584_1A90_FBFF_820000=skyatlantic-phibruspel
3792_2008_FBFF_820000=skyatlantichd-phibruspel
8_3_85_C00000=skycinemacomedy-phibruspel
2DCD_1A2C_FBFF_820000=skycinemacomedy-phibruspel
2B16_1900_FBFF_820000=skycinemacomedy-phibruspel
2B61_19C8_FBFF_820000=skycinemafamily-phibruspel
1C57_206C_FBFF_820000=skycinemafamilyhd-phibruspel
```
`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
I have removed/added those links.

I'll close this now
