### ISSUE TITLE
Movistar+ package

### ISSUE THREAD

**Issue by Jglez3** [picons/picons-source#33]
As always, to add on srp-index.

```
7826_428_1_C00000=eurosport1hd
788C_414_1_C00000=cero
7478_3F0_1_C00000=cero
```

#0 (official name) is a new channel which starts at this moment on the Movistar+ package. I put the entry as 'cero' (spanish word of 'zero') because I don't know if you want to use just XXX_XXX=0 (just zero number).

I don't know what logo will finally stays in the channel because they use some different logos.

For example (from Movistar+ website):
http://www1.plus.es/recorte/m-NEO/canal/MV3 (black)
http://www.plus.es/assets/images/logo-cero.png (yellow/white)
http://tienda.plus.es/abonateacanalplus/modulo?idmodulo=1 (you can see a blue/black logo under "Entretenimiento")

From official #cero twitter:
https://pbs.twimg.com/profile_images/681420332322918400/-CD4VuPl.png

Also they are using full white logo at this moment on TV:
http://i.imgur.com/2k0A2DU.jpg

Thanks for all!

**Comment by charlesduco** [comment]
Thanks for the comprehensive information about this new channel. I found the vector logo in the brochure http://www.movistar.es/Microsites/revista-tienda/nav/LaTiendaCast/
I adapted the vector logo following the example of twitter.

**Comment by Jglez3** [comment]
Thank you for make all the logos, I just provide the info I can find.

Just one more thing, Movistar uses yellow/white combination on their IPTV STBs because they've a dark skin. If you can modify light version of the logo for the yellow/white one, it will be perfect.

http://www.plus.es/assets/images/logo-cero.png

Thank you again.

**Comment by Jglez3** [comment]
Everything is ok now so I close the issue.
