### ISSUE TITLE
Empty Servicelist with TVHeadend API

### ISSUE THREAD

**Issue by doe1097** [picons/picons-source#335]
Hello,
I tried to use your picon tool with TVHeadendand used my laptop to query the API. Everything seems to work and the CLI output counts the channels, but unfortunately the created servicelist is empty - no matter if SNP or SRP.

My TVH version is version 4.2.5-43~ga2fab13

Am I doing something wrong or can you please give me a hint?

Best regards,
Henry

**Comment by kruemelro** [comment]
Hi,
i run into the same problem. My TVheadend version is 4.2.5-43~ga2fab13ad.

I've tried to copy the TVheadend directory into the build-input directory but the scripts stucks on converting the first channel. 

Thanks
Phil

**Comment by doe1097** [comment]
Hi,
I solved this issue by browsing through old tickets... It's mandatory to activate the picons first in TVHeadend and generate the picons afterwards.

So, under _Configuration -> General -> Base_ you'll need to define a path to your future picons directory and the save. TVH should now generate the links and the picons-source-tool should work.
Maybe this should be part of the Documentation?

Best,
Henry

**Comment by AbuBaniaz** [comment]
The instructions have been modified.

https://github.com/picons/picons-source/commit/97c5f61987875a303af33cd94889f56c6c57f8bf


OK to close?

**Comment by mocram** [comment]
I've enabled the Wiki, perhaps that should be the best place for these type of things. Don't wanna go turn the README in a full blown guide on how to configure third party apps....

**Comment by kruemelro** [comment]
That solves the Problem, thanks!

**Comment by doe1097** [comment]
Thanks @AbuBaniaz I think this issue is solved.

@mocram I'll try to make a step-by-step TvH guide for the Wiki in the next two weeks.
