### ISSUE TITLE
Tunesian Logos

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#342]
I'm busy with logos of Tunisian stations.
`televisionnationale1tunisia` and `televisionnationale2tunisia` have new logos and I have a lot more.
[televisionnationaletunisia-Lexzie.zip](https://github.com/picons/picons-source/files/1816976/televisionnationaletunisia-Lexzie.zip)

But I want to make the `1` and the `2` white but I can't do it.
Maybe @mcfly822 can do the job please?
When that is done, I have more logos and will submit all the links.

**Comment by mcfly822** [comment]
Here you are.
What you think about the 2nd channel logo? A round edge for numer '2' would be better? O is this good now?
[televisionnationaletunisia-mcfly822v1.zip](https://github.com/picons/picons-source/files/1817067/televisionnationaletunisia-mcfly822v1.zip)

**Comment by Lexzie** [comment]
This is the logo on screen:
![afbeelding](https://user-images.githubusercontent.com/14023349/37496858-4893393c-28b5-11e8-903b-248a17be6d30.png)
So how you did it is great! Thanks.

**Please replace these logos:**
[Tunesia-logos_to_replace-20180315.zip](https://github.com/picons/picons-source/files/1817507/Tunesia-logos_to_replace-20180315.zip)

**Please add these logos:**
[Tunesia-logos_to_add-20180315.zip](https://github.com/picons/picons-source/files/1817568/Tunesia-logos_to_add-20180315.zip)

**Add to snp.index**
```
aljanoubiatv=aljanoubiyatv
attesiatv=attesia
elhiwarettounsi=elhiwarettounsi
ettounisia=elhiwarettounsi
hannibaltv=hannibaltv
mtunisia=mtunisia
nessma=nessma
rtunisieculture=radiotunisieculture
tunisculture=radiotunisieculture
rtunisienationale=radiotunisienationale
tunisnational=radiotunisienationale
rtunisieinternatio=rtci
rtunisieinternationale=rtci
tunisinternational=rtci
telvzatv=telvzatv
tunisietelevision1=tunisiatv1
tunisna=tunisna
```

**Add to srp.index**
```
8_1_1_DCAAD8A=aljanoubiyatv
4_1_1_DCAAD8A=attesia
2_1_1_DCAAD8A=elhiwarettounsi
1_1_FFFF_1E30F3=elhiwarettounsi
B_1_1_DCAAD8A=hannibal
5_1_1_DCAAD8A=mtunisia
1_1_1_1EB120=nessma
1C32_1C20_13E_820000=radiotunisieculture
E26_24_800_DCA0000=radiotunisieculture
11_1_1_DCAAD8A=radiotunisieculture
1C52_1C20_13E_820000=radiotunisienationale
E25_24_800_DCA0000=radiotunisienationale
D_1_1_DCAAD8A=radiotunisienationale
1C53_1C20_13E_820000=rtci
E24_24_800_DCA0000=rtci
F_1_1_DCAAD8A=rtci
7_1_1_DCAAD8A=telvzatv
1_1_1_DCAAD8A=televisionnationale1tunisia
E11_24_800_DCA0000=televisionnationale1tunisia
1C22_1C20_13E_820000=televisionnationale1tunisia
6_1_1_DCAAD8A=televisionnationale2tunisia
FAD_28_800_DCA0000=televisionnationale2tunisia
1018_29_800_DCA0000=tunisiatv1
3_1_1_DCAAD8A=tunisna
```

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
I t has almost been a week since the requested were made,. Can this be closed now? If not, please post what needs to be done now.

**Comment by Lexzie** [comment]
I was already busy checking this:

Sorry, I made a mistake with the naming of the Attessia TV logo.
It should be `attessia.default.png`, not `attesia.default.png`.
Could you rename the logo and change the links, and add another link?

**Delete from snp.index**
```
attesiatv=attesia
```

**Delete from srp.index**
```
4_1_1_DCAAD8A=attesia
```

**Add to snp.index**
```
attessiatv=attessia
tunisietelevsion1=tunisiatv1
```

**Add to srp.index**
```
4_1_1_DCAAD8A=attessia
```

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
I am not going to spend my time renaming logos

**Comment by Lexzie** [comment]
That makes it simple:

**Please delete from snp.index**
```
attesiatv=attesia
```

**Please add to snp.index**
```
attessiatv=attessia
tunisietelevsion1=tunisiatv1
```

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
There is no logo called `attessia` in the project. Please submit a pull request if changing the name is so important

**Comment by Lexzie** [comment]
No changing the name was not the reason, I just made another typo again..sorry.

Thank you for making the changes!
