### ISSUE TITLE
(More) MBC logos

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#343]
I have logos for MBC Maghreb Al-Arabia and MBC Maser.
![afbeelding](https://user-images.githubusercontent.com/14023349/37516390-3a0b0bd4-290e-11e8-96d6-e348c4d2c865.png)![afbeelding](https://user-images.githubusercontent.com/14023349/37516450-7155abb2-290e-11e8-8378-19ca7026d1d9.png)

1. Can anyone make the background for the logo of MBC Maghreb Al-Arabia transparent without damaging the logo? @mcfly822 maybe?
[mbc.zip](https://github.com/picons/picons-source/files/1818877/mbc.zip)

2. Is the naming of this logo (`mbc.default.png`) right?

3. Should the logo for MBC Masr be with the letters `MBC` (like on the [website](http://www.mbc.net/ar/mbc-maser/)) or without the letters `MBC` (as on screen)?
[MBC_Maser.zip](https://github.com/picons/picons-source/files/1818886/MBC_Maser.zip)

**Comment by mcfly822** [comment]
1. Sorry, it is very complicated, because the letters also contains white parts. So remove the white from the picture also removes white from the letters.
![mbc default](https://user-images.githubusercontent.com/22531870/37527122-8cd1a7b0-2931-11e8-9172-ce17b67620be.png)

It should be cutted the edges, I can do it, but the result will not be nice (and I can do this only later).

2. others will say :)

3. I vote for the screen version, without letters.

**Comment by mcfly822** [comment]
I found a png, without background 😺 
[mbc.default.png_mcfly822.zip](https://github.com/picons/picons-source/files/1819685/mbc.default.png_mcfly822.zip)

**Comment by Lexzie** [comment]
That logo is good enough.
Still waiting for answers on the other questions.

**Comment by AbuBaniaz** [comment]
There is no right/wrong. There is: `Does it meet the requirements` , some `common sense`, `practicality` and `ease`.

The fixation with `wrong` and `right` leads to a lot of senseless and a wastage of time. You do a lot for the project, I'd like to be able to just add what needs to be added and remove what needs to be removed without having to go through discussions that do not lead to enhancement of the project. You spend quite a lot of time and I suppose it is frustrating for you when things are not added. 

I find it too confusing to go through the various posts and having to work out what is required to be done to the project. 

As before, we are interested in making picons. These are made up of links and logos.

Please submit all the logos and links that need to be added.

**Comment by AbuBaniaz** [comment]
Some logos on this site if any use
```http://www.mbc.net/en/corporate/channels.html```

**Comment by Lexzie** [comment]
Until now, I did not find any svg or high-res png logos on that site.
The logos look great, many thanks!
