### ISSUE TITLE
#0 on SNP

### ISSUE THREAD

**Issue by franory** [picons/picons-source#35]
Related to issue 33, I can't find this channel on SNP. I suppose It should be somethink like
#0=cero
or 
0=cero?
on SNP index.
Not pretty sure on # symbol on SNP.

Thanks and regards!

**Comment by AbuBaniaz** [comment]
If unsure just add the SRP reference.

The SNP aspect of Ocrams script will also take the SRP references. This is needed to avoid conflicts between chanenls with same name. The same things applies to channels with awkward/silly names like "?tv". The SNP name is just "tv.png" which is a bit strange.

When new channels are added to SRP reference, it would be greatly appreciated if they can also be added by use of the SRP reference. For instance, when wellbeing network was added, it was still a test channel so had no name to add to snp-index.
