### ISSUE TITLE
Logo addition request 19 May 2017

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#35]
Can the following logos be considered please?

Some  are from
```
https://github.com/Jasmeet181/mediaportal-uk-logos
```
I hope I got the naming correct this time.

I will add the references later. Thanks in advance

```
donkey monkey got issued
```

[19 may.zip](https://github.com/picons/picons-source/files/1015817/19.may.zip)

**Comment by charlesduco** [comment]
I didn't add the Sky Cinema svg logos cause the shadow effect is missing or wrong compared to the existing png images.

**Comment by AbuBaniaz** [comment]
Many thanks once again.
