### ISSUE TITLE
Changed NPO TV stations

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#352]
TV stations  NPO ZappXtra/Best, NPO Cultura and NPO 101 have been renamed to NPO 1 Extra, NPO 2 Extra and NPO 3 Extra.
Here are the new logos:
[NPO_Extra_123.zip](https://github.com/picons/picons-source/files/1845795/NPO_Extra_123.zip)

**Please delete from snp.index:**
```
npo101=npo101
npobest=npobest
npocultura=npocultura
npoculture=npocultura
npodoc=npodoc
npohumortv=npohumortv
npozappxtra=npozappxtra
npozappxtrabest=npozappxtra_npobest
npozappxtranpobest=npozappxtra_npobest
npozappxtranpohumortv=npozappxtra_npohumortv
```

**Please add these links to snp.index:**
```
npo1extra=npo1extra
npo2extra=npo2extra
npo3extra=npo3extra
```

**Please delete from srp.index:**
```
4B6B_814_600_FFFF0000=npo101
4B56_813_600_FFFF0000=npobest
5179_C8B_3_EB0000=npobest
70D_12_25A8_FFFF0000=npobest
4C1C_836_600_FFFF0000=npocultura
177F_C82_3_EB0000=npodoc
4B55_813_600_FFFF0000=npodoc
4B43_812_600_FFFF0000=npohumortv
7D3_14_25A8_FFFF0000=npohumortv
2842_2_25A8_FFFF0000=nporadio6
45D_8A4_2210_EEEE0000=nporadio6
4845_837_600_FFFF0000=nporadio6
5184_C8B_3_EB0000=nporadio6
4E50_803_600_FFFF0000=npozappxtra
7D6_14_25A8_FFFF0000=npozappxtra
1789_C82_3_EB0000=npozappxtra_npohumortv
1789_C82_3_EB0000=npozappxtra_npobest
```

**Please add to srp.index:**
```
1789_C82_3_EB0000=npo1extra
4B56_813_600_FFFF0000=npo1extra
4E50_803_600_FFFF0000=npo1extra
70D_12_25A8_FFFF0000=npo1extra
7D6_14_25A8_FFFF0000=npo1extra
4C1C_836_600_FFFF0000=npo2extra
4B43_812_600_FFFF0000=npo3extra
4B6B_814_600_FFFF0000=npo3extra
7D3_14_25A8_FFFF0000=npo3extra
2842_2_25A8_FFFF0000=nporadio2soulandjazz
45D_8A4_2210_EEEE0000=nporadio2soulandjazz
4845_837_600_FFFF0000=nporadio2soulandjazz
5184_C8B_3_EB0000=nporadio2soulandjazz
```

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
I tried to make an svg out of this, got stuck.
[npothemakanalen.zip](https://github.com/picons/picons-source/files/1845874/npothemakanalen.zip)

**Comment by Lexzie** [comment]
svg would be nice but I could not find them yet.
I thought 2306x1600 is good enough?

**Comment by AbuBaniaz** [comment]
All the other npo logos are svg. we can add the png for now.

I have reservations about your requested links. Do you really want a channel with the name  `npo101` to show picon for `npo3xtra`?

**Comment by mcfly822** [comment]
@AbuBaniaz 

> I tried to make an svg out of this, got stuck.

If so, why don't you ask me? 😉 
I made the logos in svg.

[npothemenkanalen_mcfly822.zip](https://github.com/picons/picons-source/files/1847023/npothemenkanalen_mcfly822.zip)

**Comment by Lexzie** [comment]
You people are awesome!

**Comment by Lexzie** [comment]
> I have reservations about your requested links. Do you really want a channel with the name npo101 to show picon for npo3xtra?

Yes, you're right. It was because providers hadn't changed the names yet.
Right now two cable providers I am able to check changed the names, Canal Digitaal did not.
So, the name `npozappxtranpobest` is still in use while carrying the new station.

Fact is that the TV stations `npo101`, `npobest`, `npocultura` and `npohumortv` and all combinations with these stations don't exist anymore.

Another fact:
`npozappxtra` is now combined with `npo1extra`, so I made a combined logo:
[npozappxtra_npo1extra.zip](https://github.com/picons/picons-source/files/1849707/npozappxtra_npo1extra.zip)
Also, after scanning a cable provider found two extra srp-links which weren't present yet.

**Please delete from snp.index**
```
npo1extra=npo1extra
npozappxtranpobest=npozappxtra_npobest
```

**Please add to snp.index**
```
npo1extra=npozappxtra_npo1extra
npozappnpo1extra=npozappxtra_npo1extra
npozappxtranpobest=npozappxtra_npo1extra
```

**Please delete from srp.index**
```
1789_C82_3_EB0000=npo1extra
4B56_813_600_FFFF0000=npo1extra
4E50_803_600_FFFF0000=npo1extra
70D_12_25A8_FFFF0000=npo1extra
7D6_14_25A8_FFFF0000=npo1extra
```

**Please add to srp.index**
```
1789_C82_3_EB0000=npozappxtra_npo1extra
386_9_10EF_FFFF0000=npozappxtra_npo1extra
4B56_813_600_FFFF0000=npozappxtra_npo1extra
4E50_803_600_FFFF0000=npozappxtra_npo1extra
70D_12_25A8_FFFF0000=npozappxtra_npo1extra
7D6_14_25A8_FFFF0000=npozappxtra_npo1extra
2B04_B_10EF_FFFF0000=npo2extra
2B05_B_10EF_FFFF0000=npo3extra
```

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
Not too convinced of this, added anyway

**Comment by Lexzie** [comment]
> Not too convinced of this, added anyway

Why not? I live in the Netherlands, on all media this is a combination of NPO Zapp Xtra and NPO 1 Extra.
Unfortunately Ziggo names the channel just `NPO 1 Extra`, but right now (see logo in upper-right corner):
![image](https://user-images.githubusercontent.com/14023349/38768489-eb3033c4-3ff4-11e8-8f47-01887dafc940.png)

**Comment by Lexzie** [comment]
Yes (I guess you mean the npo1**e**xtra logo), just like a lot of other logos, like:
```
npo101
npodoc
npobest
nporadio6
npocultura
npohumortv
npopolitiek_npobest
npozappxtra_npobest
npozappxtra_npohumortv
```
