### ISSUE TITLE
RTS HD and BNT1 logos

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#353]
Please add these logos and links.

[RTS_HD+BNT1.zip](https://github.com/picons/picons-source/files/1861078/RTS_HD.BNT1.zip)

**Please add to snp.index:**
```
bnt1=bnt1
rtshd=rtshd
```

**Please add to srp.index:**
```
12D_7_3_130000=bnt1
385_C670_16E_A00000=bnt1
6EE_C544_16E_A00000=rtshd
```

`donkey monkey got issued`

**Comment by TheLegoBatman** [comment]
I added these and created a pull request. If accepted this issue can be closed.

**Comment by Lexzie** [comment]
Looking good, thanks!
