### ISSUE TITLE
Help for making RTS and BNT logos

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#354]
I try to find good logos for these stations but fail to find any.
Maybe someone can find them or make them? (@mcfly822 ?)

_RTS_
[RTS TV.zip](https://github.com/picons/picons-source/files/1861111/RTS.TV.zip)

_BNT_
[BNT.zip](https://github.com/picons/picons-source/files/1861120/BNT.zip)

The radio logos are even worse:
[RTS Radio.zip](https://github.com/picons/picons-source/files/1861153/RTS.Radio.zip)
(The logos of Radio Beograd 2 and Treci Program must be combined to one combined logo)

**Comment by mcfly822** [comment]
I'll do this sometimes in weekend.

**Comment by Lexzie** [comment]
Great, if it's impossible (RTS Radio) or too much work just don't bother.

**Comment by mcfly822** [comment]
Sorry guys, I have no time this week to make the logos.
If somebody can make them, let's go :)

**Comment by Lexzie** [comment]
There's no hurry for me. I only hope that it's allowed to leave the issue open.

**Comment by Lexzie** [comment]
Great! Only ... they are both the `BNT2` logo.\

When you have time is making SVG's for the RTS logos possible?
The TV logos could be made with f.e. the `RTS1` logo as default, but for me two problems:
- Determing which font is used 
- How to write Cyrilic characters?

If it can be done: Take your time.
If it can't be done: No problem, maybe we can add them as png, otherwise they won't be added.

**Comment by mcfly822** [comment]
@Lexzie Oh, sh*t, I overwrited the bnt hd logo while saved... And I deleted the svgs after upload.
I try to draw again, but not this time. Sorry :(

RTS: This is also the problem for me, to determine the font. Unfortunately the font recognizer cannot recognize cyrillic fonts... So I'll search for this font.

**Comment by mcfly822** [comment]
Bingo 😀 I found the font: Intro Bold.
I made the RTS tv logos. (One question: RTS SVET has a different style, but I drawed in the style that the other channels has. Is this good? Or may I make as we can see in RTS_SVET.png, which differs from the other RTS tv logo style?)
[rts_TV_mcfly822.zip](https://github.com/picons/picons-source/files/1911166/rts_TV_mcfly822.zip)

And cannot go to sleep before I draw again BNT HD... 🐵 
[bnt_TV_mcfly822.zip](https://github.com/picons/picons-source/files/1911167/bnt_TV_mcfly822.zip)

But I cannot undertake the RTS Radio logos. They are more complicated. If someone do them, lets do. But complex logos like them are better in png.

**Comment by Lexzie** [comment]
Yes, RTS Svet has a slightly different logo (font in 'CBET' is thinner).
![image](https://user-images.githubusercontent.com/14023349/38782969-13a55c3c-40fc-11e8-9ab7-cdfa9c752ec3.png)
But you can keep it the same colour as the other RTS logos you made.

Nevertheless, they are great! Also the BNT logos.
If you can make the 'CBET` letters thinner I can add the snp- and srp-links.

I will see what to do with the radio-logos, I guess not commit them, too low resolution.

**Comment by mcfly822** [comment]
> If you can make the 'CBET` letters thinner I can add the snp- and srp-links.

Yes, I can :)
[rtssvet.default.svg.zip](https://github.com/picons/picons-source/files/1914219/rtssvet.default.svg.zip)

> I will see what to do with the radio-logos, I guess not commit them, too low resolution.

Agree. I think, we should forget these radio logos. Complex images and very low resolution,

**Comment by mcfly822** [comment]
@Lexzie can you please provide snp- and srp-links?

**Comment by Lexzie** [comment]
Yes, I have to make some time.

**Comment by AbuBaniaz** [comment]
What is remaining please?

**Comment by Lexzie** [comment]
Checking if the logos are okay.
