### ISSUE TITLE
Nova International, Nova Sport 2 HD new in SkyLink Czech (23,5)

### ISSUE THREAD

**Issue by janky69** [picons/picons-source#36]
Hi this is new in SkyLink Czech

Nova International
1_0_16_339B_C89_3_EB0000
Nova Sport 2 HD
1_0_1_334E_C93_3_EB0000

Thank you very much.

PS: When you type me the safety way (nothing to destroy :-)) , how can i add logo to git (here i am absolutely new) i will be very happy to help you.

**Comment by mocram** [comment]
https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

**Comment by charlesduco** [comment]
Please edit your issue following the contributing rules. If you don't know how to use Github, look your problem up at https://help.github.com/
For example: https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

**Comment by mprajsler** [comment]
339B_C89_3_EB0000=novainternational
![](http://www.lyngsat-logo.com/hires/nn/nova_cz_international.png)

**Comment by mprajsler** [comment]
334E_C93_3_EB0000=novasport2hd

![](http://www.lyngsat-logo.com/logo/tv/nn/nova_cz_sport_2_hd.png)

**Comment by mprajsler** [comment]
141F_C85_3_EB0000=mnamtv

![](http://www.lyngsat-logo.com/hires/mm/mnam_tv_cz.png)

**Comment by mprajsler** [comment]
Thank you!

**Comment by mocram** [comment]
https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

**Comment by mprajsler** [comment]
Srp refference as code with backsticks and logos renamed inside archive?

**Comment by mocram** [comment]
Indeed, and I think they can even be converted to an svg using inkscape bitmap tracing...

**Comment by mprajsler** [comment]
Thanks and sorry used Pixelmator there is no SVG export.

**Comment by mocram** [comment]
Don't put everything seperate, the end goal is to easily copy/paste and extract 1 archive

```
339B_C89_3_EB0000=novainternational
334E_C93_3_EB0000=novasport2hd
141F_C85_3_EB0000=mnamtv
```

Also remove the MAC(crap) from the archives, when editing images, make sure that there are no leftover white pixels in the background.

**Comment by mprajsler** [comment]
```
339B_C89_3_EB0000=novainternational
334E_C93_3_EB0000=novasport2hd
141F_C85_3_EB0000=mnamtv
```
[logos.zip](https://github.com/picons/picons-source/files/120725/logos.zip)

**Comment by mprajsler** [comment]
it's more difficult than I thought :-)

**Comment by mocram** [comment]
Final issue, not taking into account the quality of the logos...

From contributing.md:
`A default version of a logo should get the identifier .default at the end of the filename, additional types are possible, by using for example .light, .dark, .black or .white as an identifier.`

**Comment by mocram** [comment]
And here is the correct svg version, created from a found png image using inkscape

**Comment by mocram** [comment]
Mnam is added, with proper svg created from found png using inkscape

**Comment by charlesduco** [comment]
You don't have to use inkscape bitmap tracing when you find a pdf with a vector logo on the first page of the Nnam website: http://www.mnam.tv/cz/
http://mnam.tv/files/1914/2685/0447/mnam_jak_naladit_2.pdf

Just import the pdf in inkscape copy, edit and save the logo as a new optimized svg file.

For this issue, you don't have to use inkscape bitmap tracing at all!
You can find vector logos in the brochures of czech and slovak tv providers: http://www.upc.cz/televize/tarify/komplet/ ==> http://www.upc.cz/pdf/Cenik_Digital.pdf
https://www.swan.sk/domacnosti/pomoc-a-podpora/dokumenty ==> https://www.swan.sk/media/content/Ponuka_sluzieb_SWAN_MULTIMEDIA_01-02-2016.pdf

http://pressweb.nova.cz/tiskovematerialy/ ==> http://img.cz.prg.cmestatic.com/media/documents/1beb68oY2U5YTkyMT.pdf

**Comment by mprajsler** [comment]
@charlesduco big big thanks!

**Comment by mocram** [comment]
muchas gracias
