### ISSUE TITLE
20 Mediaset

### ISSUE THREAD

**Issue by secuflag** [picons/picons-source#360]
Add to snp.index:

```20mediaset=20mediaset```

Please double check the logo but should be ok.
I can't find anywhere a bigger image nor a .svg version for now.

[20mediaset.default.png.tar.gz](https://github.com/picons/picons-source/files/1871858/20mediaset.default.png.tar.gz)

**Comment by TheLegoBatman** [comment]
I had to cleanup the logo and then added it. I just made a pull request so should be added soon.

**Comment by AbuBaniaz** [comment]
Pull request merged, I'll add to srp.index on a future commit
