### ISSUE TITLE
More Hispasat logos

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#363]
**Please add these logos:**
[Hispasat.20180405.zip](https://github.com/picons/picons-source/files/1877539/Hispasat.20180405.zip)

Unfortunately I couldn't find any decent logo for [Cinemundo](http://www.cinemundo.pt/), [80's RFM](https://rfm.sapo.pt/emissao80spub), [RFM Dancefloor](https://rfm.sapo.pt/emissaorfmdancefloorpub), [Oceano Pacifico](https://rfm.sapo.pt/emissaooceanopacificopub), [Sim](http://radiosim.sapo.pt/) and [Super FM](https://www.superfm.com/).

**Delete from snp.index**
```
tsf=tsfjazz
```

**Add to snp.index**
```
radioamalia=amalia
bftveu=babyfirsttv
bom=bom
cidadefm=cidade
geniusplus=geniusplustv
logostv=logostv
canaldeteste=nos
radioregional=radioregional
recordnews=recordnews
radiorenascenca=renascenca
sbsr=sbsrfm
sick=sick
smoothfm=smoothfm
12284hsid0x1f7=sporttv4k
tsf=tsfradionoticias
tvfatima=tvfatima
globopremium=tvglobopremium
tvi24=tvi24
tvificcao=tvificcao
tviinternacional=tviinternacional
tvireality=tvireality
```

**Add to srp.index**
```
51F_30_36_CE40000=amalia
1_1_1_CE4AAAA=bom
1_1_1_CE42CEF=bom
10D_66_53_CE40000=cidade
51E_30_36_CE40000=cidade
8_3138_FF01_CE4AAA5=logostv
1_24_36_CE40000=nos
6F_24_36_CE40000=nos
52E_30_36_CE40000=radioregional
A8C_6_6_CE40000=recordnews
530_30_36_CE40000=renascenca
52A_30_36_CE40000=sbsrfm
7F_65_53_CE40000=sick
103_66_53_CE40000=smoothfm
527_30_36_CE40000=smoothfm
64_24_36_CE40000=tsfradionoticias
68_65_53_CE40000=tvfatima
526_67_53_CE40000=tvglobopremium
170_67_53_CE40000=tvglobopremium
131_26_36_CE40000=tvi24
85_65_53_CE40000=tvi24
E6_66_53_CE40000=tvificcao
7D0_6_6_CE40000=tviinternacional
E6_30_36_CE40000=tvireality
```

`donkey monkey got issued`

**Comment by TheLegoBatman** [comment]
I wlll do these but will probably take me a couple of days as some have already been added and I have better sources for some. Meanwhile  if you could work on these two logos from tvi inside the zip as they are better sources I would appreciate whilst I work on the rest. :)
[tvi.zip](https://github.com/picons/picons-source/files/1876286/tvi.zip)

**Comment by Lexzie** [comment]
Sorry, I have been working on this for three days, when I started some of the logos were not in the source yet.
F.e. for some only the `default` version were in source, so I just added the `light` version, now I see they are added in the meantime (one day ago).
And I see I accedentally added a few logos double, sorry.

I have edited my first post leaving out the logos and links who are present right now.

If you have a better source, that's always good. I will have a look al the tvi.zip later this week.

**Comment by TheLegoBatman** [comment]
I had a bit of time and did the tvi logos. I am posting so you don't go through the trouble of doing them as well. Is the RFM dancefloor radio the same as RFM Clubbing? I can't find rfm dancefloor on the channel list.

**Comment by Lexzie** [comment]
Well, it's even more confusing:
The one scanned (on 12169 H) with the name `80s RFM` is `RFM Dancefloor` and the one with the name `RFM Clubbing` is `80's RFM`. Just compare them with the online streams:
https://rfm.sapo.pt/emissao80spub
https://rfm.sapo.pt/emissaorfmdancefloorpub

If you can find logos of enough quality could you also submit one for `RFM On the Rock`? (Stream only, so just snp-link is enough).

These are the logos I could find (unedited) and `light` versions I made from them (for own use):
[RFMonline.zip](https://github.com/picons/picons-source/files/1884546/RFMonline.zip)

Would you mind sharing the source if you have one with better logos?

**Comment by TheLegoBatman** [comment]
I will make sure I will add the right logos. I will update my channel list later on. I already have all of those logos as svg. I forgot to add them on my pull request yesterday. I extracted the svg from https://rfm.sapo.pt/ at the bottom and then edited them. I will also add the rfm on the rock.

**Comment by Lexzie** [comment]
Great work! A lot logos of these Hispasat stations were still missing.


> Edit: Is the rfm on the rock to be added to the snp index as rfmontherock?

```
rfmontherock=rfmontherock
```
is okay.

Notice how I colored the `light` versions of the `RFM` logos. I found them the best visible in this way.

I could not extract the logos at the botom of https://rfm.sapo.pt/ (could not find it with F12)
I'm curious how you got hold of them.

**Comment by TheLegoBatman** [comment]
To extract the svg you have two different solutions. First you can view page source or inspect element and copy all of the code inside the svg tag of the image you want. After that you paste it on a text editor and save as svg. Or when inspecting element edit as html in the svg you want and copy all including the tag and past and save as svg. The second option is to use the following https://nytimes.github.io/svg-crowbar/ .

**Comment by AbuBaniaz** [comment]
Can this be closed now?

**Comment by TheLegoBatman** [comment]
This issue can be closed.

**Comment by Lexzie** [comment]
Since the picon-packs on picons.eu are still from April the 6th, I have not been able to check if the picons are fine on my settopbox. Building the ipk myself is something I haven't mastered yet, besides that I don't have a Ubuntu PC and don't know what 'Bash on Ubuntu on Windows' is. Following the link doesn't help.
I have now installed the Ubuntu app (is the same as Bash on Ubuntu on Windows??) but all I get is:
![afbeelding](https://user-images.githubusercontent.com/14023349/38743105-83e5175e-3f3e-11e8-8e5f-29b531f674de.png)
Don't know how to go from there...so I'm stuck.

**Comment by TheLegoBatman** [comment]
I have built those. Can I email you a link to download them?

**Comment by Lexzie** [comment]
Eh, yes please. This is my email lexzie (at) msn (dot) com

**Comment by charlesduco** [comment]
> Don't know how to go from there...so I'm stuck.
You can easily learn things you don't understand watching Youtube: https://www.youtube.com/watch?v=tdzoX_M5dQU

**Comment by AbuBaniaz** [comment]
> This issue can be closed

Thanks. Done
