### ISSUE TITLE
Ads on picons.eu

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#364]
I download the ipk for the picons from picons.eu
I don't know if this is the right place for that site or that it is not maintained by you guys.

I understand the hosting is not for free, so I disabled my ad-blocker, like I do for a lot more sites I think deserve support.
Only this time I got a popup saying my PC is infected with ransomware!
How is this possible? Or am I doing something wrong?
So please isn't there any other way to make money there with ads?
And please also no porn ads.

**Comment by mcfly822** [comment]
Yesterday, when I downloaded a file, I also got a porn ad. Fortunately my child was not near me.
Is there any way to filter your ad partners, to block the porn advertisers (at server side)?
I can block ads, but then you don't get money...

**Comment by Lexzie** [comment]
With the ad blocker enabled I can't even download the ipk.

**Comment by mcfly822** [comment]
@Lexzie I use uBlock Origin, I can download the packs without popup ads.

**Comment by Lexzie** [comment]
@mcfly822 I use Adblock Plus on Firefox and Chrome. On Chrome I can (now) download the packs.
But the last one is of 2018-04-06, so I'm afraid the building process is stuck?
@mocram or any other owner: Can you look at that and answer this issue?

**Comment by charlesduco** [comment]
mocram is the one and only owner of the website https://www.picons.eu/

If you don't like the ads I would highly recommend to build the picon ipk package yourself: https://github.com/picons/picons-source#building-the-picons

**Comment by Lexzie** [comment]
No bad idea, that would have more benefits.
But I also recommend these picons to others and they are not able to build them their selves, so I direct them to picons.eu

**Comment by mcfly822** [comment]
@charlesduco no problem with the ads, only porn ads makes me angry.
My baby is 2.5 years old, I don't want her to see these things when I only download picons in daytime...
Besides, I know that the ads are necessary to get funds.

**Comment by mcfly822** [comment]
@Lexzie I think we cannot say more to this topic. We said everything, and got answers. I suggest to close this, but it's on you :)

**Comment by Lexzie** [comment]
The only one who can say something about it is @mocram 
He hasn't replied yet.

**Comment by mocram** [comment]
As much as I hate ads like you guys... As far as I know there is no way for me to "disable" porn ads on AdFly. In the past without these annoying ads there was a lot of abuse of the server.

Just don't go clicking on random ads and certainly never open any files if an ad would download something...except for the file you know you want.

Before I put the ads in place I tested the ad provider and everything worked ok at the time, otherwise I wouldn't have done it. FWIW I'm now able to download some stuff even with uBlock origin active on Chrome....

If anybody has an excellent adprovider that could replace AdFly... I'm open to suggestions.

**Comment by mocram** [comment]
Regarding the builds being outdated... That happened because of a script update that I was not aware of. The server does not execute code not authorized by me... so it refused to start the build. After @AbuBaniaz reverted the commit that caused this, all executed as planned again.

**Comment by Lexzie** [comment]
Thanks for the reply, so that is clarified.

And (probably said before) it's not that I (we) don't want ads (so we'd rather not use an adblocker), but I don't know how and what kind of popup I got, but it looked like my whole system was taken over by some ransomware, you must understand that frightens me.
Also not very pleased with the porn-ads of course.
I'm sure I did not c;lick or opened something, besides the desired picon-pack.

Fortunately it just happened once, so I hope it's was a one time only and it probably was just a hoax.

Well, anyhow, I shouldn't know an alternative but I hope you can find it.

Thanks again for clarifying.
