### ISSUE TITLE
Change BVN logo

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#368]
I saw that the logo for [BVN](https://www.bvn.tv/) has changed.
I could not find anything better than this:
https://www.bvn.tv/static/img/bvn-logo-wit.png
So unfortunately no svg-file and I could not make it better than 384x376 pixels.

**Comment by dalmore72** [comment]
Logo from facebook
[bvn tv.zip](https://github.com/picons/picons-source/files/1887121/bvn.tv.zip)

**Comment by Lexzie** [comment]
Much better indeed, still no svg where I was hoping for, but this one (1148x1123) is good enough.
Can someone merge that pull request? (I don't have the rights to do so).

**Comment by AbuBaniaz** [comment]
Issue closed as pull request has been merged
