### ISSUE TITLE
0 octets files

### ISSUE THREAD

**Issue by moose24** [picons/picons-source#37]
hi
i just want to ask why most of the picons are 0 octets files (corrupted files)
you can see that in the screenshot linked below
thanks for the good work
![capture](https://cloud.githubusercontent.com/assets/4118981/8139447/c7ddc524-114b-11e5-860d-fb11990f3dda.JPG)

**Comment by picons** [comment]
They are not corrupted files, they are hard links.

http://www.gnu.org/software/tar/manual/html_node/hard-links.html
