### ISSUE TITLE
Build server

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#377]
@mocram @charlesduco 
Is there an issue with the build server? Last ones are from 06/04/18. Manual builds are fine.

**Comment by AbuBaniaz** [comment]
There are no builds after this commit
https://github.com/picons/picons-source/commit/6026e46cd55a3338855242813526d2bc4105a3b1

I am not sure if the script mocram uses has been effected by it

**Comment by AbuBaniaz** [comment]
They built last night.

**Comment by mocram** [comment]
Please do not update scripts without me knowing about it! Before starting a build all scripts get hashed, if the hash changes, the build does not start.

**Comment by AbuBaniaz** [comment]
@mocram 
Can you re-apply this and make the necessary hash changes please?
https://github.com/picons/picons-source/commit/742ea3dc1733a67f18542ba78b51a43962468f91

**Comment by mocram** [comment]
done
