### ISSUE TITLE
New logos for some Mediaset channels

### ISSUE THREAD

**Issue by elton74** [picons/picons-source#378]
Hi all,

This is my first time writing and I am not very good on snp etc. However I can work with logos.
Attaching here the latest versions (light) of Mediaset HD channel logos and the 2018 canale 5 logo.

Thank You

![canale5-ita 2018](https://user-images.githubusercontent.com/38422936/38800240-0fba374e-4167-11e8-8e02-8504d4c1f9e7.png)

![canale5hd-ita 2018](https://user-images.githubusercontent.com/38422936/38800079-9b342f10-4166-11e8-9b9a-7ee02b944050.png)

![italiaunohd-2018](https://user-images.githubusercontent.com/38422936/38800108-aed66a06-4166-11e8-985c-68ee6a45731c.png)

![rete4hd-ita 2018](https://user-images.githubusercontent.com/38422936/38800120-b78619f8-4166-11e8-8c78-94049ce75324.png)

![20mediasethd 2018](https://user-images.githubusercontent.com/38422936/38800124-bd108c82-4166-11e8-9aa7-e7d7d19b3586.png)

**Comment by mcfly822** [comment]
@elton74 welcome here 😉 
Can you provide vector (.svg) version of these logos? If you can, please send here in attachment, every logos in one .zip file.

**Comment by elton74** [comment]
Hi,

Attached in svg format. Hoping they serve the purpose.

[20mediasethd 2018.zip](https://github.com/picons/picons-source/files/1915134/20mediasethd.2018.zip)
[Canale5_2018.zip](https://github.com/picons/picons-source/files/1915135/Canale5_2018.zip)
[Canale5hd-ita 2018.zip](https://github.com/picons/picons-source/files/1915136/Canale5hd-ita.2018.zip)
[italiaunohd-2018.zip](https://github.com/picons/picons-source/files/1915137/italiaunohd-2018.zip)
[rete4hd-ita 2018.zip](https://github.com/picons/picons-source/files/1915138/rete4hd-ita.2018.zip)

Regards

**Comment by AbuBaniaz** [comment]
Welcome.

We cannot add just a `.light` version of a logo. We need a `.default` ones too.  Pleaase have a look at the existing names of the logos we have.

Can you please redo and attach as one zip file please?

**Comment by mcfly822** [comment]
@elton74 Please consider what @AbuBaniaz wrote. Besides you provided .svg files with embedded images. It is not allowed here.
If you have real vector logos, you can upload here in svg. If you have raster images, you can send in transparent png. But simple logos like above should be in vector format.

> If it's possible to easily trace your png with Inkscape, only the svg is allowed. In most cases this is possible.

Here are the instructions:
https://github.com/picons/picons-source/blob/master/.github/CONTRIBUTING.md

**Comment by elton74** [comment]
sorry. this is all I have.
Best Regards

**Comment by Lexzie** [comment]
I have build the `20mediasethd` logo and more, see Pull Request 381

**Comment by AbuBaniaz** [comment]
These were added here
https://github.com/picons/picons-source/commit/5ef47342a9711c81407b2669b4c8eb5368e6d6ba

I'll close the issue now
