### ISSUE TITLE
Logo addition request

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#38]
Can the attached logos be added if they are good enough please?
We have a png for rtl5, I found a svg file

[20170526.zip](https://github.com/picons/picons-source/files/1032506/20170526.zip)

I will add the references later. Thanks in advance
```
donkey monkey got issued
```

**Comment by AbuBaniaz** [comment]
[20170526_v2.zip](https://github.com/picons/picons-source/files/1032543/20170526_v2.zip)

Forgot to add these

**Comment by charlesduco** [comment]
I didn't add two logos for the following reasons:
Omroep West is already in the repository.
RTL5 svg logo has no 3D light effect ==> https://twitter.com/rtl5

**Comment by AbuBaniaz** [comment]
Index changes added here
https://github.com/picons/picons-source/commit/222ce086f6c190fbb0ef551e62ec7b2b7bf0bb6e
