### ISSUE TITLE
How to fix the Bruzz logo?

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#388]
When opening the logo in Inkscape all looks normal:
![bruzz default](https://user-images.githubusercontent.com/14023349/39317445-e0d73b9e-497b-11e8-9599-47496d18e992.png)

But on screen there is something not right:
![bruzz](https://user-images.githubusercontent.com/14023349/39317743-a0b1f800-497c-11e8-9b1d-963167ba4958.png)

I've had this issue before and someone solved it for me, but I'd like to know if/how I can fix this myself?

Here are the svg's:
[bruzz.zip](https://github.com/picons/picons-source/files/1952097/bruzz.zip)

**Comment by TheLegoBatman** [comment]
I don't quite understand when exactly is that happening to you. I checked and they are fine for me even if converted to png. It looks like you moved the path of the first Z onto the second.

**Comment by AbuBaniaz** [comment]
The problem is evident when opening with GIMP instead of Inkscape. You have to clean it using the scour protocol. I don't know how to do it though.

**Comment by TheLegoBatman** [comment]
I have opened them with gimp as well and can't really see that happening. Could it maybe be a windows thing?

**Comment by AbuBaniaz** [comment]
Not a windows thing because the picons are built faulty

Scour should be the default cleanup in inkscape. I have tried uninstalling/reinstalling inkscape on windows, still not working.

**Comment by AbuBaniaz** [comment]
After several attempts, using a Virtual machine and actual Ubuntu installation, no  luck with inkscape.
Finally fixed it with
File > Document Properties > Resize page to content > Resize page to drawing or selection

Then saving as optimised svg worked

**Comment by charlesduco** [comment]
This is how I would cleanup this svg in Inkscape:

- Select All ==> Path ==> Break Apart
- Fill and Stroke ==> Stroke Paint ==> No Paint
- Fill and Stroke ==> Fill ==> Black
- Select BRUZ ==> Path ==> Exclusion
- Select All ==> Transform ==> Scale ==> Width 600 px, Scale proportionally ==> Apply
- File ==> Document Properties ==> Page ==> Display Units px, Units px ==> Resize page to content ==> Resize page to drawing or selection
- Select All ==> Edit ==> Cut
- Layers ==> Create a new layer
- Edit ==> Paste In Place
- File ==> Save As ==> Optimized SVG ==> Save
- Options ==> Shorten color values, Convert CSS attributes to XML attributes, Collapse groups, Create groups for similar attributes, Work around renderer bugs
- SVG Output ==> Remove the XML declaration, Remove metadata, Remove comments, Enable viewboxing, Format output with line-breaks and indentation
- IDs ==> Remove unused IDs, Shorten IDs
- ==> OK

Then you get this nice and clean SVG code:

`<svg class="logo" version="1.1" viewBox="0 0 600 140.63" xmlns="http://www.w3.org/2000/svg">
 <g>
  <path d="m0-4.7412e-6v31.421h15.198v76.218h-15.198v31.201h76.63c31.72 0 53.165-13.814 53.165-41.006 0-16.936-10.499-26.745-25.241-30.533v-0.43945c10.945-3.1219 20.773-12.709 20.773-31.21 0-1.4438-0.10144-2.8469-0.2655-4.2297h10.446v107.42h41.116v-49.695h10.776l18.539 29.187c12.506 19.838 23.004 22.293 39.532 22.293 4.4672 0 8.7145-0.88938 12.286-2.005v-29.196c-1.3406 0.225-2.8997 0.21972-3.7903 0.21972-4.2422 0-8.2698-1.3349-12.067-6.6833l-14.392-21.13c12.497-7.5938 19.244-20.715 19.244-37.482 0-4.5984-0.56199-8.9054-1.5839-12.927h11.7v53.265c0 40.566 24.346 55.939 62.54 55.939 38.198 0 60.086-15.378 60.086-55.939v-51.031h61.542l-58.127 71.31c-4.5656 6.6562-6.72 12.331-6.72 33.875h99.921c0-21.548 2.1635-27.223 6.7291-33.875h-54.172l57.614-71.31h9e-3c3.6984-5.4562 5.896-12.941 5.896-33.655h-151.34v84.467c0 13.594-6.4745 22.504-21.442 22.504s-21.442-8.9099-21.442-22.504v-84.467h-56.296v22.137c-7.3359-13.842-22.385-22.137-43.845-22.137h-77.408v18.347c-7.3125-11.358-22.6-18.347-44.467-18.347zm56.25 32.812h13.834c9.975 0 14.291 4.1307 14.291 11.481 0 7.5891-4.0859 11.957-14.52 11.957h-13.605zm121.88 0h13.733c10.031 0 14.392 6.4704 14.392 14.191 0 7.9312-4.5765 13.934-14.392 13.934h-13.733zm-121.88 46.875h13.632c9.0844 0 14.493 4.7232 14.493 13.943 0 9.2156-5.4084 14.182-14.493 14.182h-13.632z"/>
  <path d="m600 106.31h-64.162l58.2-72.234c3.7312-5.5172 5.9531-13.097 5.9531-34.078h-100.94c0 20.981-2.2219 28.561-5.9531 34.078v0.0047h55.223l-58.716 72.234c-4.6078 6.7312-6.7922 12.478-6.7922 34.308h117.19z"/>
 </g>
</svg>`

**Comment by Lexzie** [comment]
Great info guys!
I did not had the time to look at this until now.
I tried both your instructions, of course AbuBaniaz' one was simpler and worked also under Windows (10).
charlesduco methode is also clear now, besides 'Create groups for similar attributes' I had the same options for saving an optimized svg.

Logos are okay now (also in GIMP), I'll use them in a separate Pull Request.

Thank you all!

> My confusion came from building them in my machine. They built fine yesterday and that logo was fine. I should have checked the logos from picons.eu.

I always check them again when the picons are available in the ipk from picons.eu.

**Comment by mocram** [comment]
Just try building them with RSVG instead of Inkscape. The server uses RSVG. This has been told multiple times already.

**Comment by Lexzie** [comment]
> Just try building them with RSVG instead of Inkscape. The server uses RSVG. This has been told multiple times already.

I know, but learning stuff takes time (a lot!) and perhaps I'm not as smart as you all.
I am already happy I learnt a lot in Inkscape how to make/change logos (so we can get rid of (bad) png's).

Also, I believe you have to have Linux for RSVG. Also a thing I am not (yet) able to use.
