### ISSUE TITLE
Logo addition request 20170604

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#39]
Can the following logos be considered please? (Sorry they are jpeg files.) I will added both type of references later.
I got them from ```http://www.quran-hidayah.com/hidayah-live.html```

Thanks in advance

[20170604.zip](https://github.com/picons/picons-source/files/1050595/20170604.zip)

`donkey monkey got issued`

**Comment by charlesduco** [comment]
Can be considered when someone has time to clean up the logos: the background should be transparent. I'll look into it next weekend.

Are these channels broadcasted on satellite? Maybe I can find a better source.

**Comment by AbuBaniaz** [comment]
They are on 13.0 east on 12379 V 27500

```
BBC_20D0_13E_820000=hidayah-english
BD2_20D0_13E_820000=hidayah-albanaian
BD1_20D0_13E_820000=hidayah-bosnian
BBF_20D0_13E_820000=hidayah-french
BCA_20D0_13E_820000=hidayah-german
BD4_20D0_13E_820000=hidayah-persian
BCB_20D0_13E_820000=hidayah-russian
BC0_20D0_13E_820000=hidayah-spanish
```

```
hidayahenglish=hidayah-english
hidayahalbanaian=hidayah-albanaian
hidayahbosnian=hidayah-bosnian
hidayahfrench=hidayah-french
hidayahgerman=hidayah-german
hidayahpersian=hidayah-persian
hidayahrussian=hidayah-russian
hidayahspanish=hidayah-spanish
```
