### ISSUE TITLE
Missed logos 13° east

### ISSUE THREAD

**Issue by dax79** [picons/picons-source#39]
Hi, on hotbird there are missing logos
2FC4_2DB4_13E_820000_0_0_0
http://www.lyngsat-logo.com/logo/tv/gg/gambero_rosso.png
FF1_2C24_FBFF_820000_0_0_0
http://www.lyngsat-logo.com/logo/tv/rr/radio_radio_it_tv.png
10A8_2008_FBFF_820000_0_0_0
http://www.lyngsat-logo.com/hires/rr/roma_tv_it.png
4238_3DB8_13E_820000_0_0_0
http://www.lyngsat-logo.com/logo/tv/tt/tele_radio_padre_pio_tv.png

For these xxx channels is used the same wrong logo. These are the "real" logos
A_1388_13E_820000_0_0_0
http://www.lyngsat-logo.com/logo/tv/ss/sct_it_hd.png
35C0_1388_13E_820000_0_0_0
http://www.lyngsat-logo.com/logo/tv/tt/t_girls_tv_it.png
35C6_1388_13E_820000_0_0_0
http://www.lyngsat-logo.com/logo/tv/cc/cento_x_cento_tv_it.png
35C7_1388_13E_820000_0_0_0
http://www.lyngsat-logo.com/logo/tv/ss/sexto_senso_it.png
35C8_1388_13E_820000_0_0_0
http://www.lyngsat-logo.com/logo/tv/pp/passion_xxx_it.png
5D8_1388_13E_820000_0_0_0
http://www.lyngsat-logo.com/logo/tv/pp/pink_o_tv_it.png
Thanks in advance

**Comment by mocram** [comment]
https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

**Comment by dax79** [comment]
Now i'm right?
If i run ./1-build-servicelist.sh creating a 0 byte file..
I use vhannibal settings and archlinux os (maybe os is the problem)
[logos.zip](https://github.com/picons/picons-source/files/120753/logos.zip)

**Comment by mocram** [comment]
No, please read CONTRIBUTING.md!

1-build-servicelist.sh should not create a 0 byte file, is the system locale of your server properly setup?

**Comment by dax79** [comment]
Hi mocram, i really appreciate your work and would like to collaborate but it is quite complicated.
I think that first step is make a service list as i read in CONTRIBUTING.md
`./1-build-servicelist.sh

Log file located at: /tmp/tmp.iulasR3S8b.servicelist.log

Which style are you going to build?
1) Service Reference
2) Service Name
#? 1
Enigma2: Exported to /home/davide/Scrivania/pic/build-output/servicelist-enigma2-srp
TvHeadend (file-mode): /home/davide/Scrivania/pic/build-input/tvheadend not found
TvHeadend (server-mode): /home/davide/Scrivania/pic/build-input/tvheadend.serverconf not found
VDR: /home/davide/Scrivania/pic/build-input/channels.conf not found`
Both files, log and servicelist, are empty. I check my server and all packages are installed ( sed grep column cat sort find rm wc iconv awk printf )
See my enigma2 dir, i never did a scan just use vhannibal settings
Many thanks
[enigma2.zip](https://github.com/picons/picons-source/files/121288/enigma2.zip)

**Comment by mocram** [comment]
When the script is busy and you can see the counter 10/2000 or something like that, try looking for a temporary file in /tmp, called similar to tmp.ffd5654dg.servicelist (without log at the end)

If that file is found and it contains channel data, the script is most probably failing at 
```
sort -t $'\t' -k 2,2 "$tempfile" | sed -e 's/\t/§|/g' | column -t -s $'§' | sed -e 's/|/  |  /g' > $file
```

Probably the column command fails if the locales aren't setup properly.

**Comment by dax79** [comment]
I can't see the counter because the script terminate immediately!
If you try with my enigma2 dir which kind of result do you get?

> locale
> LANG=it_IT.UTF-8
> LC_CTYPE="it_IT.UTF-8"
> LC_NUMERIC="it_IT.UTF-8"
> LC_TIME="it_IT.UTF-8"
> LC_COLLATE="it_IT.UTF-8"
> LC_MONETARY="it_IT.UTF-8"
> LC_MESSAGES="it_IT.UTF-8"
> LC_PAPER="it_IT.UTF-8"
> LC_NAME="it_IT.UTF-8"
> LC_ADDRESS="it_IT.UTF-8"
> LC_TELEPHONE="it_IT.UTF-8"
> LC_MEASUREMENT="it_IT.UTF-8"
> LC_IDENTIFICATION="it_IT.UTF-8"
> LC_ALL=

**Comment by mocram** [comment]
I found the problem, it was indeed caused by the channellist, vhannibal uses `#SERVICE:` instead of `#SERVICE` without `:`

**Comment by mocram** [comment]
Ok, some more explanation:

The script expects the following input:
`#SERVICE 1:0:1:6dca:44d:1:c00000:0:0:0:`

Your vhannibal channellist contains the following:
`#SERVICE: 1:0:19:0D49:1450:013E:00820000:0:0:0:`

So two problems with this list
1) Semicolon
2) Trailing zero's

Is this list compatible with OpenVix? Can you import it with Dreamset and export it again?

**Comment by dax79** [comment]
Ok, first little step! But it's not better to fix the script?
Yes, i used openvix in the past and the list was compatible. Now i'm using openpli.
If i import-export with dreamset the script work

**Comment by dax79** [comment]
Well related to missing picons the output script
gambero rosso hd
`1_0_1_2FC4_2DB4_13E_820000_0_0_0      |  Gambero Rosso HD                                               |  2FC4_2DB4_13E_820000=--------`
radio radio it
`1_0_1_FF1_2C24_FBFF_820000_0_0_0      |  Radio Radio TV                                                 |  FF1_2C24_FBFF_820000=--------`
roma tv
`1_0_1_1FAA_189C_FBFF_820000_0_0_0     |  Roma TV                                                        |  1FAA_189C_FBFF_820000=romatv
1_0_19_10A8_2008_FBFF_820000_0_0_0    |  Roma TV                                                        |  10A8_2008_FBFF_820000=--------`
tele radio padre pio
`1_0_1_4238_3DB8_13E_820000_0_0_0      |  Padre Pio Tv                                                   |  4238_3DB8_13E_820000=--------`
I'm little bit confused... Some picons are present in logos directory.
Where is the issue? Provider or script side?

**Comment by dax79** [comment]
Again for xxx channel
sct hd
`1_0_1_A_1388_13E_820000_0_0_0         |  SCT HD                                                         |  A_1388_13E_820000=sct
1_0_1_35CA_1388_13E_820000_0_0_0      |  SCT PROMO b                                                    |  35CA_1388_13E_820000=sct`
tgirls
`1_0_1_35C0_1388_13E_820000_0_0_0      |  TGirlstv                                                       |  35C0_1388_13E_820000=redlighttv`
centoxcento
`1_0_1_35C6_1388_13E_820000_0_0_0      |  CENTOXCENTO TV                                                 |  35C6_1388_13E_820000=sct`
sexto senso
`1_0_1_35C7_1388_13E_820000_0_0_0      |  SESTO SENSO TV                                                 |  35C7_1388_13E_820000=sct`
passion xxx
`1_0_1_35C8_1388_13E_820000_0_0_0      |  PASSIONXXX                                                     |  35C8_1388_13E_820000=sct`
pinko
`1_0_1_35D8_1388_13E_820000_0_0_0      |  PINK O TV                                                      |  35D8_1388_13E_820000=--------`

**Comment by mocram** [comment]
First I should find out, why vhannibal his channel list is slighty different...if it's a more common thing I should probably fix the script, but if it's only with vhannibal his list....

Not sure what you are trying to say with your last 2 posts.

**Comment by dax79** [comment]
With my two last post i'm try to say (example for Gambero Rosso HD):
Why the script output is
`1_0_1_2FC4_2DB4_13E_820000_0_0_0 | Gambero Rosso HD | 2FC4_2DB4_13E_820000=--------`
what does it means -----? If i clone the git the gamberorossohd.default.png is present but when i run the script ./2-build-picons.sh the picon is not created. Which is the problem? Also for other channel of my first post.
I hope I'm making myself clear

**Comment by mocram** [comment]
`2FC4_2DB4_13E_820000` has not been added to srp-index yet, that's why the logo doesn't get linked.

**Comment by dax79** [comment]
Ok, so could you add? I think the problem is the same for other channels that i indicated.

**Comment by mocram** [comment]
Indeed, it's most probably the same problem...

But there are 3 possibilities one can take to fix mistakes:

1) Create a proper pull request, after reading CONTRIBUTING.md, very fast to resolve issues
2) Create a proper issue, after reading CONTRIBUTING.md, still fast to resolve issues
3) Create an issue similar to yours, totally neglecting everything that's been said in CONTRIBUTING.md, thus relying on the goodwill of others, for such issues to get resolved, can take days, months, perhaps never, who knows...

I myself don't watch those channels, so priority is low for me, you chose for option 3), so I'm guessing priority is also low for you.

Please remember that this is not a forum where people can scream "It doesn't work, PLEASE HELP".
The intention is that people who are not able to grasp the meaning of git/pull requests/etc, to have another way of submitting corrections, delivered in such a way, that it's possible for us to just copy/paste the stuff in, all that is required to achive that, is a bit of reading on their end.

**Comment by mocram** [comment]
Concerning the issue with the script, I just checked on vhannibal his site http://www.vhannibal.net/enigma2.php and his channellists are correct, so I'm not going to adjust the script, seems to be an issue with your personal setup/image only.

**Comment by dax79** [comment]
Ok, sorry i known that is not a forum and i' m person not skilled about bash, git, etc. But i don't want you waste your time.
So, if you want to investigate with me which is the problem i will apreciate so much, otherwise if you consider my issue bullshit and not a problem, please close the ticket.
First, if i run ./1-build-servicelist.sh i obtain this output (romatv,padrepio and gambero rosso hd)
`1_0_1_132E_33F4_13E_820000_0_0_0       |  TELEPADREPIO                      |  132E_33F4_13E_820000=teleradiopadrepiotv
1_0_1_4238_3DB8_13E_820000_0_0_0       |  Padre Pio Tv                      |  4238_3DB8_13E_820000=--------
1_0_1_1C18_384_110_EEEE0000_0_0_0      |  PADRE PIO TV                      |  1C18_384_110_EEEE0000=--------
1_0_1_1FAA_189C_FBFF_820000_0_0_0      |  Roma TV                           |  1FAA_189C_FBFF_820000=romatv
1_0_19_10A8_2008_FBFF_0_0_0_0          |  Roma TV                           |  10A8_2008_FBFF_0=--------
1_0_19_10A8_2008_FBFF_820000_0_0_0     |  Roma TV                           |  10A8_2008_FBFF_820000=--------
1_0_1_2FC4_2DB4_13E_0_0_0_0            |  Gambero Rosso HD                  |  2FC4_2DB4_13E_0=--------
1_0_1_2FC4_2DB4_13E_820000_0_0_0       |  Gambero Rosso HD                  |  2FC4_2DB4_13E_820000=--------`
Why the --------??? Script, provider or settings problem?
If i modify the last column by myself with
`10A8_2008_FBFF_820000=romatv
2FC4_2DB4_13E_820000=gamberorossohd
4238_3DB8_13E_820000=teleradiopadrepiotv`
The scritp build correct picons, otherwise no!
Again for xxx channel
`35D8_1388_13E_820000=pinkotv
35C8_1388_13E_820000=passionxxx
35C6_1388_13E_820000=centopercentotv
35C0_1388_13E_820000=tgirlstv`
In my opinion this is not the right way but probably i'm wrong.
If you want you can try also, my enigma2 dir is attached

I read again (and again) the CONTRIBUTING.md
If you want you can try also by yourself, my enigma2 dir is attached

Concerning vhannibal setting i investigated too: the "problem" is the settings editor that i use, enigmedit.
[enigma2.zip](https://github.com/picons/picons-source/files/123235/enigma2.zip)

**Comment by mocram** [comment]
When running the script `1-build-servicelist.sh`, the scripts takes your enigma2 folder and starts looking at all the channels that are present, when it sees the channel `1_0_1_132E_33F4_13E_820000_0_0_0` it goes looking in the file `srp-index`, if it finds the part `132E_33F4_13E_820000`, you'll get `132E_33F4_13E_820000=teleradiopadrepiotv`, if it doesn't find a link, you'll get `132E_33F4_13E_820000=--------`.

Afterwards when running the script `2-build-picons.sh`, the output from the first script is used and it starts linking and creating picons based on the file `servicelist-enigma2-srp`. Obviously when you manually edit this, it will build according to that. You can even "not" use the first script and create a file from scratch.

Now...if you add the following to srp-index
```
4238_3DB8_13E_820000=imaginarylogo1
1C18_384_110_EEEE0000=imaginarylogo2
2FC4_2DB4_13E_820000=imaginarylogo3
```
and then run `1-build-servicelist.sh`, you'll see it no longer puts `-------` after the serviceref.

____

If people create an issue, that they would like to get fixed ASAP, I expect them to create something like:

add to srp-index:
```
4238_3DB8_13E_820000=imaginarylogo1
1C18_384_110_EEEE0000=imaginarylogo2
2FC4_2DB4_13E_820000=imaginarylogo3
```
add to snp-index:
```
imaginarytvchannel1=imaginarylogo1
imaginarytvchannel2=imaginarylogo2
imaginarytvchannel3=imaginarylogo3
```

ZIP-file containing:
```
imaginarylogo1.default.svg
imaginarylogo2.default.png
imaginarylogo2.light.png
imaginarylogo3.default.svg
```

**Comment by dax79** [comment]
Ok, thanks a lot for great and clear explanation.
Please add to srp-index
```
2FC4_2DB4_13E_820000=gamberorossohd
10A8_2008_FBFF_820000=romatv
4238_3DB8_13E_820000=teleradiopadrepiotv
35C0_1388_13E_820000=tgirlstv
35C6_1388_13E_820000=centopercentotv
35C8_1388_13E_820000=passionxxx
35D8_1388_13E_820000=pinkotv
```
Snp-index is ok
Maybe the goal? :)
Thanks a lot mocram. In the next day i will study about the missing logos (svg, png, etc).

**Comment by dax79** [comment]
For other channels
srp-index
```
35C7_1388_13E_820000=sextosenso
A_1388_13E_820000=satisfactionhd
E12_708_C8_820000=rai4hd
```
snp-index
```
sextosenso=sextosensotv 
satisfactionhd=satisfactionhd
rai4hd=rai4hd
```
For radioradio tv i can't find a logo
`FF1_2C24_FBFF_820000=radioradiotv`
[logos.zip](https://github.com/picons/picons-source/files/126559/logos.zip)

**Comment by dax79** [comment]
more logos
srp-index
```
A_2BC_13E_820000=rtpi
425C_3DB8_13E_820000=tvavicenza
29D8_3CF0_13E_820000=ukrainetoday
[logos.zip](https://github.com/picons/picons-source/files/127718/logos.zip)

```
snp-index
```
rtpi=rtpi
tvavicenza=tvavicenza
ukrainetoday=ukrainetoday
```
For itv italia i can't find a logo
```
425F_3DB8_13E_820000=itvitalia
itvitalia=itvitalia
`
