### ISSUE TITLE
Very big png's

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#401]
Question: Do I have to downsize a png of almost 5 MB (3690x3754 px)?
If so, to which size?

**Comment by mcfly822** [comment]
If I have a big png like this, I resize it to 1600 wide. I think it is more than enough, and results a much smaller filesize.

**Comment by Lexzie** [comment]
Thanks, I will do that.
By the way, this is the logo: https://upload.wikimedia.org/wikipedia/commons/3/3f/Tv3_logo_rgb_transparent.png
