### ISSUE TITLE
New picon request

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons-source#41]
61_101_2114_EEEE0000=mdr
286E_431_1_FFFF0000=rbbhd
6E2D_431_1_FFFF0000=rbb
6E2D_431_1_FFFF0000=srfernsehen
CF6F_2721_F001_FFFF0000=zeeone
CB3D_2710_F001_FFFF0000=deutschewelle
CB97_2710_F001_FFFF0000=potsdamtv
CB49_2710_F001_FFFF0000=parlamentsfernsehen
CB71_2710_F001_FFFF0000=alexberlin
CB73_2710_F001_FFFF0000=tvberlin
D04E_2712_F001_FFFF0000=toggoplus
C763_2725_F001_FFFF0000=weltderwunder
CF1A_2721_F001_FFFF0000=drf1
C39E_2727_F001_FFFF0000=123tvhd
CF17_2726_F001_FFFF0000=vodafoneinfochannel
C3CA_2725_F001_FFFF0000=kabeleinsdoku
C75D_2725_F001_FFFF0000=n24doku
D04F_2714_F001_FFFF0000=rtlplus-mathecraki
7D4_203_2114_EEEE0000=3sathd
302_F101_2114_EEEE0000=artehd
4248_4061_2114_EEEE0000=bibeltvhd
321_F101_2114_EEEE0000=brhd
301_103_2114_EEEE0000=daserstehd
341_F101_2114_EEEE0000=hrfernsehenhd
4247_4061_2114_EEEE0000=hse24hd
7D5_203_2114_EEEE0000=kikahd
361_103_2114_EEEE0000=mdrhd
381_103_2114_EEEE0000=ndrhd
305_F101_2114_EEEE0000=onehd
303_F101_2114_EEEE0000=phoenixhd
4246_4061_2114_EEEE0000=qvchd
3B1_103_2114_EEEE0000=rbbhd
3B2_103_2114_EEEE0000=rbbhd
3E1_103_2114_EEEE0000=swrhd
304_103_2114_EEEE0000=tagesschau24hd
406_F101_2114_EEEE0000=wdrhd
7D1_203_2114_EEEE0000=zdfhd
7D2_203_2114_EEEE0000=zdfinfohd
7D3_203_2114_EEEE0000=zdfneohd

**Comment by charlesduco** [comment]
Please read the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md).

**Comment by AbuBaniaz** [comment]
You have two identical references pointing to two different logos.
```
6E2D_431_1_FFFF0000=rbb
6E2D_431_1_FFFF0000=srfernsehen
```
We do not have a logo called `alexberlin`

I did not check for any more issues after that. can you please double check your request. 

Don't be put off, just try again.

Thanks.

**Comment by AbuBaniaz** [comment]
> We do not have a logo called `alexberlin`

Oops, it's in your other request.

**Comment by AbuBaniaz** [comment]
I have added the references for existing logos.
I will post references for new logos in the other request.

Please respond about the duplication I commented about earlier.

**Comment by AbuBaniaz** [comment]
Apart from duplicate entry (still waiting fro response from you), everything has been added. OK to close?
