### ISSUE TITLE
Update ref & logos - M+ Spain.

### ISSUE THREAD

**Issue by Jglez3** [picons/picons-source#411]
```
772D_416_1_C00000=blaze
7600_408_1_C00000=bemad
18F0_3F4_1_C00000=canalextremadura
```

Logos
Canal extremadura: https://vignette.wikia.nocookie.net/logopedia/images/0/03/Canal_Extremadura_.jpg/revision/latest?cb=20160908170803

Be Mad:
https://vignette.wikia.nocookie.net/logopedia/images/2/26/BeMad.svg/revision/latest?cb=20171228172553

Thank you!

`donkey monkey got issued`

**Comment by Lexzie** [comment]
Please also add the snp-links (assuming these are the srp-links?)
And are you able to supply the logos as optimized svg's and with correct naming?
And, if necessary, light and dark version.

**Comment by TheLegoBatman** [comment]
@Jglez3 Please check if the issue has been sorted and close it if it has. Thanks

**Comment by Jglez3** [comment]
Everything is fine, thank you.
