### ISSUE TITLE
New picons white

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons-source#42]
i build some new white Logos and replace some outdated Logos in your source. most of them are svg's

here the files
[new logos.zip](https://github.com/picons/picons-source/files/1060904/new.logos.zip)

Is there a way to add it to you source ;)

**Comment by charlesduco** [comment]
Please read the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md).

**Comment by AbuBaniaz** [comment]
Some references to be added with this request
```
CB71_2710_F001_FFFF0000=alexberlin
CB97_2710_F001_FFFF0000=potsdamtv
CB73_2710_F001_FFFF0000=tvberlin
CF1A_2721_F001_FFFF0000=drf1
CF17_2726_F001_FFFF0000=vodafoneinfochannel
```

**Comment by mocram** [comment]
Don't include macos junk in your zip files please.

**Comment by AbuBaniaz** [comment]
OK to close?

**Comment by AbuBaniaz** [comment]
Please re-open if required.
