### ISSUE TITLE
Request : 400x170 picons 

### ISSUE THREAD

**Issue by moose24** [picons/picons-source#42]
hi
can you please make 400x170 resolution picons
Arctic skin support that resolution
thanks in advance

**Comment by picons** [comment]
Support has been added, you can build them on your own or wait until they come online here, which can take a little while.

**Comment by picons** [comment]
@moose24 

I forgot something in the script, so it didn't build the 400x170 packages, have fixed it now and will upload a 400x170 package in the next half hour.
