### ISSUE TITLE
DVB-T Italy

### ISSUE THREAD

**Issue by dax79** [picons/picons-source#42]
Hi, my idea is to add all services for italian dvb-t channels. Just for test
srp-index
`C43_3A2_110_EEEE0000=mediasetpremiumsport2hd`
snp-index
`mediasetpremiumsport2hd=mediasetpremiumsport2hd`
Is it possible to leave this ticket open for contribute?
File svg is ok for commit directly or need modifications?
Thanks
[logo.zip](https://github.com/picons/picons-source/files/128754/logo.zip)

**Comment by charlesduco** [comment]
No, the svg file is totally not ok. It only contains a base64 encoded png file, this violates the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md)
Svg files should only contain vector data. So, you have to find a source that provides that vector data, like pdf, eps files or svg files.
If you don't understand the difference between pixel and vector data, please[ learn](https://www.google.com/webhp#q=vector+vs+pixel).
For Mediaset Premium Sport2 HD, I found an svg logo online:
http://www.mediasetpremium.it/guidatv/
http://www.mediasetpremium.it/assets/images/channels/KC.svg
Most of the time, svg files you find online need small modifications like color correction, scaling and removing white space around the logo.
It's recommended you optimize every logo you add to this repository and doublecheck the appearance of the logo in an image viewer and a web browser.

**Comment by mocram** [comment]
What he said.

Oh, and even if the svg was ok, it still wasn't good, the red/orange border spoiled it.
