### ISSUE TITLE
New team members

### ISSUE THREAD

**Issue by mocram** [picons/picons-source#428]
@charlesduco @AbuBaniaz 

How do you guys feel about adding @TheLegoBatman @Lexzie @mcfly822 to the team? After a quick look, it seems @Lexzie is quite dedicated to help get everything up2date, although I see more issues (perhaps 50/50) created than pull requests.... Regarding @TheLegoBatman , haven't really dealt with him yet, but it seems he jumped right on the pull requests without as far as I can tell any mistakes (= me like).

Special recommendation for @mcfly822, sorry I overlooked you :-)

The persons themselves, feel free to express your thoughts about this or leave a `Thanks, but no thanks.` if not interested.

@AbuBaniaz I think you are most qualified at the moment to form an opinion, seeing as you've been most active lately...

Just throwing it out there.

**Comment by mcfly822** [comment]
In the past, I think I worked a lot to make this picon project better. Countless hours editing the logos.
https://github.com/picons/picons-source/graphs/contributors
Seems that this was not enough to be a member. Maybe my work was not enough good, sometimes I failed. Sorry for that.
So I leave this project now.
The best all for you.

**Comment by Lexzie** [comment]
It would be a great loss to loose mcfly822. His svg-skills are great and for as far as I have seen, his commits were always correct.

About myself: I would be honored if I could join the team.
I have seen a lot picon packs/projects and this one is far better and complete than others, so I'm committed to keep it that way and to improve/expand it.
I know I made a lot issues in the past, but lately I commit with pull requests and only make issues if I have a question or are in doubt or I need help.
Although I am member of Github from 2015, I just started to use it in August 2017 for this project.
I think I've learnt a lot from knowing nothing to where I am today in only 10 months.

**Comment by mocram** [comment]
hold on people, I only looked at the first page of pull requests.......don't anybody take offense

**Comment by mocram** [comment]
Yep, you are right @mcfly822 , don't be offended so fast, consider yourself added to the list.

**Comment by mocram** [comment]
Seriously, I don't understand how I could forget @mcfly822 and his svg skills....that's why I needed @AbuBaniaz his help. I feel ashamed now.

**Comment by mocram** [comment]
OK back to the original question, @mcfly822 you are invited already, the job is yours. And please don't make anything more out of it than it is, as you know I've not been around lately and I actually just indeed looked no further then the first page of the pull requests.

PS: GitHub has also private conversations for teams, why did I not see this 2 hours ago, would have saved me from the unlucky situation.

**Comment by mocram** [comment]
It seems I did not even make it al the way down the first page.....what a PR nightmare. :-)

👎 for me

**Comment by mocram** [comment]
@AbuBaniaz ping ping ping

I've invited @Lexzie , if I've made a terrible mistake @AbuBaniaz (don't think so :-)), please let me know.
Just waiting now on your opinion about @TheLegoBatman , the ball is in your court.

PS: If somehow I've forgotten somebody else, don't be offended.

**Comment by AbuBaniaz** [comment]
Sorry, been at work and not had a chance to reply.

Yes, @mcfly822 has been contributing quite a lot. I hope he accepts and overlooks the minor oversight.

@TheLegoBatman pull requests have been correct and straight forward to merge.

**Comment by mocram** [comment]
Invite sent to @TheLegoBatman . Yes I hope @mcfly822 accepts. I could have known I would screw this up. I checked in a couple of times the last week, saw a lot of commits from abubaniaz/lexzie/thelegobatman. Later I thought "Hey why not let them join, so that abubaniza doesn't have to do all the work". But since mcfly hasn't been real active the last week and my lack of attention, I completely forgot about him.

Forgotten, not less loved.

**Comment by mcfly822** [comment]
Okay @mocram , no problem 😉 
I thought that my work is not enough good in spite of my big effort in the past.
Yes, in the last month(s) I was more on 'read-only' state because I have a lot of challenge in my private life.
I will try to make my best in the future.

**Comment by mcfly822** [comment]
And I forgot to write the most important: I feel honored for this, and ```Thanks``` 😺

**Comment by mocram** [comment]
Somebody with svg skills gets a golden star from me.
Just an oversight, I hop in, merge a pull request at best, make a snarky comment :-) and I'm out. By the time my PC is in sleep mode I already have forgotten all the names that popped up.

Actually looking at https://github.com/picons/picons-source/graphs/contributors is a far better metric than relying on my memories.

**Comment by TheLegoBatman** [comment]
Thanks for the invite. :)
