### ISSUE TITLE
script doesn't generate icons for IPTV network

### ISSUE THREAD

**Issue by SmoothMC** [picons/picons-source#43]
for me the use of the script  ./1-build-servicelist.sh only generate index for dvb-c and dvb-t2
the iptv network services are ignored or non recognized.

**Comment by mocram** [comment]
???

VDR?? Enigma?? TvHeadend?? How do the service references look like?

**Comment by AbuBaniaz** [comment]
I would suggest that you use the complete SNP set instead.

If you use the SRP set, you need to  ensure the service reference attributed to each stream matches an actual service.

**Comment by mocram** [comment]
I'm going to close this due to lack of input.

**Comment by Woraspvm** [comment]
Hello, I have same issue, started using tvheadend and using it only for IPTV.
Trying server mode.  ./1-build-servicelist.sh script can see all my channels "TvHeadend (server-mode): Converting channel: 45/395" but after that I can see only empty file "servicelist-tvheadend-servermode-snp" in output folder.
