### ISSUE TITLE
microsoft-github-acquisition-rumors

### ISSUE THREAD

**Issue by mocram** [picons/picons-source#433]
https://www.theverge.com/2018/6/3/17422752/microsoft-github-acquisition-rumors
Should we move?

**Comment by mocram** [comment]
https://twitter.com/gitlab/status/1003409836170547200

**Comment by TheLegoBatman** [comment]
Definitely.

**Comment by mocram** [comment]
To be fair I wanna stick it to MS and hope that just about everybody leaves so that they paid 7.5 billion in shares for just the lolz.

I've created a gitlab user+group (I'm going to consolidate some of my github usernames, so don't freak out if I'm no longer called mocram), please create a gitlab user name and report it here, I'll send invites when I've got time and gitlab is a bit more responsive, I think they are overwhelmed by signups.

**Comment by TheLegoBatman** [comment]
I have never been keen on closed source stuff unless really needed. I created an account with the same username but took a while to get the confirmation email. They are going to take a few days to settle down from all of the migrating projects.

**Comment by mocram** [comment]
This will also be a nice opportunity to start using git LFS, if the free bandwith requirements allow it, this was unworkable on GitHub

**Comment by TheLegoBatman** [comment]
Maybe we can even self host it in the future.

**Comment by mocram** [comment]
Yeah       maybe, for now we'll let somebody else pay the bill :-)

**Comment by mocram** [comment]
@AbuBaniaz @Lexzie @mcfly822 @charlesduco @vpont Read the above and take appropiate action. Thanks

**Comment by Lexzie** [comment]
Just done, same username.

**Comment by mcfly822** [comment]
+1, same username

**Comment by AbuBaniaz** [comment]
Same username for me

**Comment by mcfly822** [comment]
Is there any advantages to move to GitLab (or any disadvantages to stay here)?

**Comment by mocram** [comment]
Well, one big advantage I think is that we'll actually be able to use git lfs. Their docker support is also neat and I think on the long run if I can figure it out their ci/do might be able to build the picons to...

**Comment by anthonykelly** [comment]
My gitlab username is antoineoc.

**Comment by Lexzie** [comment]
Can/must we still make commits here?

**Comment by AbuBaniaz** [comment]
How do you use Gitlab without your e-mail being seen to one and all?

**Comment by mocram** [comment]
You use an email adress that you don't care anybody knows, github its usage of a no-reply is bad practice, also one of the reasons the Linux kernel isn't developed using github

**Comment by AbuBaniaz** [comment]
I don't have a disposable e-mail address. Not having any joy with the ssh key either. I've gone through two accounts now.

Thanks for having me.

**Comment by mocram** [comment]
Use protonmail if you need a disposable email.

What's that with the ssh key? Not sure what you mean with "I've gone through two accounts now."

**Comment by mocram** [comment]
What do you mean with `Thanks for having me.`?

**Comment by AbuBaniaz** [comment]
I have tried two different accounts on Gitlab. The SSH key is not accepted. It is saying it is already taken. Second account was only created because first one failed to authenticate even though I can log on. I am not going to spend more time on it.
