### ISSUE TITLE
New logo Nick Jr. Too

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#438]
Nick Jr. 2 is rebranded to Nick Jr. Too, I found this logo:
![afbeelding](https://user-images.githubusercontent.com/14023349/40977305-dc6f38ee-68d0-11e8-9a7d-05325b95ffd3.png)

Right now we have better svg-logos for Nickelodeon etc.
Can anyone find or make a svg for this channel too?

The changes to the links are:
**Delete from snp.index**
```
nickjrtoo=nickjr2
```

**Add to snp.index**
```
nickjrtoo=nickjrtoo
```

**Delete from srp.index**
```
C791_81F_2_11A0000=nickjr2
C794_81F_2_11A0000=nickjr2
83A_15_F020_FFFF0000=nickjr2
C791_815_2_11A0000=nickjr2
C794_815_2_11A0000=nickjr2
```

**Add to srp.index**
```
83A_15_F020_FFFF0000=nickjrtoo
C791_815_2_11A0000=nickjrtoo
C794_815_2_11A0000=nickjrtoo
```

`donkey monkey got issued`

**Comment by mcfly822** [comment]
Hi guys, my first own commit in this repo 😸 hope everything is okay.

**Comment by Lexzie** [comment]
Amazing how quick you did that, and no idea how you made the logo.
Looks like all is okay, I will change the links.

**Comment by mcfly822** [comment]
Not my business, just partially :-) 
I found the svg, just minor corrections and cleaning was needed.
