### ISSUE TITLE
MTV Rocks

### ISSUE THREAD

**Issue by Jglez3** [picons/picons-source#44]
MTV Rocks has a new image from few weeks ago.

Logo: https://vignette1.wikia.nocookie.net/logopedia/images/e/ea/MTV_Rocks_%282017%29.png

Thanks in advance.

`donkey monkey got issued`

**Comment by mocram** [comment]
https://vignette1.wikia.nocookie.net/logopedia/images/e/ea/MTV_Rocks_%282017%29.png/revision/latest?cb=20170417094151
