### ISSUE TITLE
New german TELE 5 (HD) Logo

### ISSUE THREAD

**Issue by tunip** [picons/picons-source#45]
TELE 5
https://de.wikipedia.org/wiki/Datei:TELE_5_Logo.png

TELE 5 HD
https://upload.wikimedia.org/wikipedia/commons/e/e2/TELE_5_HD_Germany_Logo_2017.png

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
I am closing this issue owing to the commit above.
