### ISSUE TITLE
Channel logo requests (Sweden)

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#47]
Can we please add following logos (if they are acceptable/useable) when you have some spare time from this site please?
```
https://www.comhem.se/tv/tv-kanaler
```

```
axess TV
canal-de-las-estrellas
yletv1hd
yletv2hd
pink plus
rtk
C More golf
fueltv
rai uno
rai due
```

Thanks in advance

```
donkey monkey got issued
```

**Comment by charlesduco** [comment]
Which logos should be added? Please check first if they are already in the repository and provide a clear list with proper naming.

**Comment by AbuBaniaz** [comment]
Links to requested logos

```
https://www.comhem.se/asset/rqq4gefrk8ol/6N4xxtyxgsQIMqiEUQKYSY/ef1e82d203f5873ea8decb2e2e0db791/axess-tv-logo-data.png
https://www.comhem.se/asset/rqq4gefrk8ol/1PR5Ii58FW0G0OOa8SsUie/fd8102f3903b5c676907942ba0694091/canaldelasestrellas-data.png
https://www.comhem.se/asset/2zxwgcm7u48q/4gYF43ML56m0IGy0Uwgie8/5efdfc456b9e1f50723dbbaa44a950a6/logo-yle1.png
https://www.comhem.se/asset/2zxwgcm7u48q/5k1QWeqUeWEwI66WyYwIuO/1c1bb4e4e0cf2aaf1bf2d28f43452532/logo-yle2.png
https://www.comhem.se/asset/rqq4gefrk8ol/2hJ7UktrducSC0I4oWg4QM/d423fd29f3c65b4cf213a3dbd5c6a06a/pinkplus-data.png
https://www.comhem.se/asset/rqq4gefrk8ol/Bh7nZBGD7i0oSieaO6aA8/ea1b364d5ecc6e54689a9c67b5565061/cmoregolf-data.png
https://www.comhem.se/asset/rqq4gefrk8ol/5WvlAL5kZ22YyUEASyKQuY/ea4556eb47b479f82468030fe4a2e872/tvfinland-data.png
https://www.comhem.se/asset/rqq4gefrk8ol/3TEjevUbTOYg8Emm846UeE/062095c894230ddbec4fe00d1e07cc0c/raiuno-data.png
https://www.comhem.se/asset/rqq4gefrk8ol/55R8gDAEnewYeQ6OMWkYKc/7cfdd6f916afb1d9bf70704409d76d70/raidue-data.png
```
Names

```
axesstv.default
canaldelasestrellas.default
yletv1hd.default
yletv2hd.default
pinkplus.default
cmoregolf.default
tvfinland.default
raiuno.default
raidue.default
```

**Comment by AbuBaniaz** [comment]
Some more.
```
http://film.viasat.se/themes/simple/images/viasat_film_premiere_neg.png
http://film.viasat.se/themes/simple/images/viasat_film_hits.png
http://film.viasat.se/themes/simple/images/viasat_series_neg.png
```
Names
```
viasatfilmpremiere.default
viasatfilmhits.default
viasatseries.default
```

Thanks in advance

**Comment by McLalala** [comment]
I have the logos to almost all the channels you are requesting. It's going
up this weekend if I'm not working too much. :)

Also I'm done with all logos for Swedish providers Viasat and Canal
Digital.

Den 3 juli 2017 19:43 skrev "AbuBaniaz" <notifications@github.com>:

**Comment by charlesduco** [comment]
I don't understand why very old logos for `raiuno.default` and `raidue.default` should be added while `rai1.default` and `rai2.default` are already in this repository.

Or am I living in the future?
https://twitter.com/raiuno
https://twitter.com/raidue

**Comment by McLalala** [comment]
True, the logos on comhem.se are old. I'll take care of this case this weekend probably. 👍

**Comment by AbuBaniaz** [comment]
The story is as follows...
We added ComHem cable to AutoBuquetsMaker. I asked the person send me his lamedb and noticed the  missing picons. I looked at the provider's website and saw the missing logos and raised the request.

You'd think that the provider would have the most recent logos for the services. I am in a different country and cannot receive his DVB-C braodcast. Nobody is going to knowingly add old logos.

I attach a lamedb file and total list of picons for the provider if it helps.  The Green SNP ones are already added.
[sweden cable lamedb.zip](https://github.com/picons/picons-source/files/1122649/sweden.cable.lamedb.zip)
[sweden-picons.zip](https://github.com/picons/picons-source/files/1122650/sweden-picons.zip)

**Comment by AbuBaniaz** [comment]
If you get time, can you add this too please?
```http://tv.sky.com/logo/0/0/skychb5070.png```
Name to be stv2

srp
```
C6CE_82A_2_11A0000=stv2
```

snp
```
stv2=stv2
```

**Comment by AbuBaniaz** [comment]
Can you add these well please? Thanks in advance.

```
http://tv.sky.com/logo/0/0/skychb401515.png
http://tv.sky.com/logo/0/0/skychb1815.png
http://tv.sky.com/logo/0/0/skychb1844.png
http://tv.sky.com/logo/0/0/skychb1087.png
http://tv.sky.com/logo/0/0/skychb3753.png
```

SRP
``
1612_7DC_2_11A0000`=skycinemabrits
EE7_7E8_2_11A0000=skycinemabritshd
FB8_7EA_2_11A0000=mtvbeats
CB8A_83B_2_11A0000=kanshitv
2390_7DB_2_11A0000=marvelspiderman
```
SNP
```
skybritshd=skycinemabritshd
skybrits=skycinemabrits
mtvbeats=mtvbeats
kanshitv=kanshitv
spiderman=marvelspiderman
```

**Comment by AbuBaniaz** [comment]
Can we also update `sonymoviechannel.default.png`  and `sonymoviechannelplus1.default.png` please?

```
http://tv.sky.com/logo/0/0/skychb3709.png
https://www.sonymoviechannel.co.uk/sites/all/themes/responsive/responsive_smc_uk_2/logo.png
http://tv.sky.com/logo/0/0/skychb3771.png
```
Freeview pdf attached for inkscape extraction if it helps
[Freeview-Channel-Guide-2017.pdf](https://github.com/picons/picons-source/files/1137576/Freeview-Channel-Guide-2017.pdf)

Thanks in advance

**Comment by charlesduco** [comment]
At least the following channel logos are added to the repository now:
```axesstv
lasestrellas
yletv1hd
yletv2hd
rtvpinkplus
cmoregolf
tvfinland
rai1
rai2
viasatfilmpremiere
viasatseries
viasatfilmhits
```

**Comment by mocram** [comment]
This funny business of constantly feeding charlesduco the wrong/old logos has got to stop. Besides it being the wrong/old logo, it doesn't even remotely comes close to following the rules.

This is not a "add all the junk you can find" repository. Plenty of that elsewhere...

**Comment by AbuBaniaz** [comment]
You are absolutely correct. However, you have to bear in mind that the broadcasters sometimes have the wrong logos. Is it not a logical to assume that the broadcaster is using the latest logo? This has proven not to be the case.

Also, you have to give yourself and Charles some credit. You guys are aware of subtle differences that the untrained person is not. For example, I can't see the difference between `skyatlantichd-wispelutri.default.svg` and `skyatlantichd-clivebesle.default.png` apart from the file extension. As another example, I submitted some svg files as these are preferred, but they were rejected because of a subtle difference. The existing png files were used.

The person who has been e-mailing me these was "shouted" at. Yes it is frustrating, but we need to be more tolerant with others without lowering the standards of this project.

Charles has been giving feedback as to why the logos are rejected. This helps educate others so they can improve their contributions.

**Comment by charlesduco** [comment]
Com Hem is not a broadcaster, Com Hem is a cable operator. That's a huge difference.

**Comment by charlesduco** [comment]
@AbuBaniaz The logo on wikipedia was almost okay, but the transparancy of the word 'pink' is wrong, it should be white as on their website: http://www.rtvpink.com/pinkplus/

**Comment by AbuBaniaz** [comment]
Many thanks

**Comment by mocram** [comment]
When you see `.svg.png` in the URL... NO that logo will not be OK, because there's a 99% gurantee that you will be able to find a SVG instead of the PNG.

Regarding skyatlantichd-................, you are absolutely right, that is not correct, somebody messed up. The both svg images are indentical and the png could be dropped if you ask me.

I'm guessing somebody was to fast to click merge pull request...perhaps we should be more stricter? :-)
