### ISSUE TITLE
C+ESTRENOSHD

### ISSUE THREAD

**Issue by Jglez3** [picons/picons-source#48]
C+ESTRENOSHD is in this frecuency too.
```
74D5_3F8_1_C00000=tv/canal+estrenos-esp
```

Also one of the frequencies you add for C+Estrenos is a SD channel (76C0_40E_1_C00000=tv/canal+estrenos-esp) and there's no logo atm, maybe this but I think it's too small (http://www1.plus.es/recorte/?id=MV1&v=NEO&r=canal&t=m)

The same case is C+SeriesXtra, there is a logo but I think it's too small too (http://www1.plus.es/recorte/?id=MV2&v=NEO&r=canal&t=m).

**Comment by vpont** [comment]
Yes, it's on that freq too but that's a secondary (temporary I guess) location, as shown here: http://es.kingofsat.net/pack-digitalplusa.php

We need to find better logos for both Canal+ Estrenos and Series Xtra ((SD/HD).

**Comment by Jglez3** [comment]
Other channels like C+ LIGA or C+ XTRA have logos on all refs (3 and 4 respectively), why not this?

I think not all of us have the same reference channel in the channel list.

**Comment by vpont** [comment]
Ok, added.
