### ISSUE TITLE
Bein Sports Spain snp

### ISSUE THREAD

**Issue by franory** [picons/picons-source#48]
I think that it is needed to include:
beinmax1=beinsportsmax1hd
beinmax2=beinsportsmax2hd
beinmax3=beinsportsmax3hd
beinmax4=beinsportsmax4
beinmax5=beinsportsmax5
beinmax6=beinsportsmax6
beinmax7=beinsportsmax7
beinmax8=beinsportsmax8
SD & HD channels have the same name.

Beins sports HD is finnally named Bein sports so I think that it is necessary to update this line:
beinsportshd=beinsportshd
into
beinsports=beinsportshd
Can you check if it is right?
Thanks and regards

**Comment by mocram** [comment]
https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

**Comment by franory** [comment]
I think that this is what you mean.
If that is not the case, sorry, but i don't get the point:
`beinmax1=beinsportsmax1hd`
`beinmax2=beinsportsmax2hd`
`beinmax3=beinsportsmax3hd`
`beinmax4=beinsportsmax4`
`beinmax5=beinsportsmax5`
`beinmax6=beinsportsmax6`
`beinmax7=beinsportsmax7`
`beinmax8=beinsportsmax8`
`beinsports=beinsportshd`

**Comment by mocram** [comment]
```
beinmax1=beinsportsmax1hd
beinmax2=beinsportsmax2hd
beinmax3=beinsportsmax3hd
beinmax4=beinsportsmax4
beinmax5=beinsportsmax5
beinmax6=beinsportsmax6
beinmax7=beinsportsmax7
beinmax8=beinsportsmax8
beinsports=beinsportshd
```
