### ISSUE TITLE
Script doesn't generate icons for IPTV network

### ISSUE THREAD

**Issue by Woraspvm** [picons/picons-source#48]
Hello,
I have started using tvheadend and using it only for IPTV.
When trying to use Your script to generate picons in server mode, it returns empty output file "servicelist-tvheadend-servermode-snp".
Script can see all my channels "TvHeadend (server-mode): Converting channel: 45/395" but nothing is generated.

**Comment by mocram** [comment]
snp isn't for tvheadend

**Comment by Woraspvm** [comment]
SRP same situation...
