### ISSUE TITLE
Log addition request 20170406

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#5]
Please consider the attached logos someone passed to me. One is a gif file, maybe something can be done with it.

Can we also combine BBC Four and Cbeebies into a new logo?

[logos_20170406.zip](https://github.com/picons/picons-source/files/901114/logos_20170406.zip)

Thanks in advance 

`donkey monkey got issued`

**Comment by charlesduco** [comment]
There is already a combined logo for Cbeebies and BBC Four in the repository:  cbeebies_bbcfour

**Comment by AbuBaniaz** [comment]
Many thanks once again
