### ISSUE TITLE
Logo naming explanation

### ISSUE THREAD

**Issue by zag2me** [picons/picons-source#50]
Can someone explain the file naming a little better? I had a look at the enigma code and can get a few things but still trying to work out the rest.

Are all spaces deleted?
Where do the hyphens come from?
Where does the string ".default" come from?

**Comment by charlesduco** [comment]
Logo naming is explained in the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md)
Service names are simplified as explained here: https://github.com/picons/picons-source#snp---service-name-picons

**Comment by mocram** [comment]
```
snpname=$(sed -e 's/&/and/g' -e 's/*/star/g' -e 's/+/plus/g' -e 's/\(.*\)/\L\1/g' -e 's/[^a-z0-9]//g' <<< "$channelname")
```

**Comment by AbuBaniaz** [comment]
Just to explain the SNP code in slightly different terms.

- lowercase only
- letters  (a to z)  and numbers (0 to 9) only apart from following exceptions
- replace "&" with "and"
- replace "+" with "plus"
- replace "*" with "star"
- spaces or other characters skipped

As examples...
`5*` will use `5star.png` "*" replaced with "star"
`Sony Chnl +1` will use `sonychnlplus1.png` All lower case, space is skipped, "+" replaced with "plus"
`BT Sport//ESPN` will use `btsportespn.png` All lower case, space is skipped, "/" skipped as it is not a-z, 0-9 or the three accepted/replaced characters. 

Additionally if a channel name ends in "hd" and there is no matching picon, the sd version will be used 

You can use both the service reference picons and service name picons. Priority is 
Service reference
Service name
HD workaround

Majority of images have the SNP code. There are some skins which use different picon renderers, so they won't work with SNP.

**Comment by AbuBaniaz** [comment]
I have added the SNP explanation to contribution guide.
