### ISSUE TITLE
Script doesn't generate icons for IPTV network

### ISSUE THREAD

**Issue by Woraspvm** [picons/picons-source#51]
https://github.com/picons/picons-source/issues/48

>Woraspvm 
Hello,
I have started using tvheadend and using it only for IPTV.
When trying to use Your script to generate picons in server mode, it returns empty output file "servicelist-tvheadend-servermode-snp".
Script can see all my channels "TvHeadend (server-mode): Converting channel: 45/395" but nothing is generated.

>mocram 
 snp isn't for tvheadend

> Woraspvm
SRP same situation...

So it goes that I can't use picons for IPTV on tvheadend? Just like "channel icon" and set icon's names manually?

**Comment by AbuBaniaz** [comment]
This project is for picon creation.

If you want tvheadend to use SNPicons, ask them.

**Comment by Woraspvm** [comment]
As I said, with SRP is same situation, it won't create anything for me. 
It doesn't matter what to use SRP or SNP, I just want to have icons generated for me if it is possible without setting icons on each of ~2000 channels manually.
So I just want to know is it possible to generate picons for IPTV networks on tvheadend?

**Comment by AbuBaniaz** [comment]
Do you have valid tvheadend *DVB* services? Not interested in IPTV at the moment, don't confuse issue by mentioning this.

**Comment by Woraspvm** [comment]
Yes, I have valid working DVB input services.

**Comment by AbuBaniaz** [comment]
Does it work for those?

**Comment by Woraspvm** [comment]
Ahh, I thought You talking about about DVB services in general...
NO, I don't have neither DVB-T nor DVB-S or DVB-C, only network services.

**Comment by mocram** [comment]
Try using file mode instead... if that works, server mode will be removed, just like I said to the original author of that feature.

**Comment by mocram** [comment]
Also next time, don't create such confusing issues...

You start by stating you are creating SNP, which is not even a thing on tvheadend, you also claim that it doesn't work for IPTV, giving us the illusion it does work for DVB-S/C/T.

And on top of that, none of the files you are refering to are included... where's servicelist-tvheadend-servermode-snp? Where's the log? Where's your channellist?

**Comment by Woraspvm** [comment]
Sorry for that, I haven't read CONTRIBUTING, it's first time I am on github...

Please give me few more days and I will test everything and will give You all required information.

Also about this part: "_PS: Don't even try running the script if picon serviceref generation isn't enabled._" 
I can't see such option in tvheadend, maybe You can say where I should search for that? 
My tvheadend version: "HTS Tvheadend 4.3-240~gd7a848caa"

**Comment by mocram** [comment]
Not sure exactly where that option resides, it's something to enable picon support. After enabling it, it should generate something in your channellist files like "picon://..........................................................".

If that is enabled and the script turns up empty, it's highly likely that the servicerefs are simply just not added to this project.

**Comment by mocram** [comment]
Closed due to lack of user input
