### ISSUE TITLE
"/dev/shm/picons-tmp/newbuildsource/logos": No files or folders of this type

### ISSUE THREAD

**Issue by wada3n** [picons/picons-source#52]
When I try to execute the command   ./2-build-picons.sh , i get this error 
![Image ](http://i.imgur.com/tQChFg6.png)
Please help me .

**Comment by picons** [comment]
Could you try running it from /tmp... Do you have /dev/shm on your system?

**Comment by wada3n** [comment]
No I do not have  /dev/shm on my system ,I tried it in Mint and Fedora also ,
I still find the same error : find: ‘/dev/shm/picons-tmp/newbuildsource/logos’: No such file or directory
can you help me with my servicelist_tvheadend file ? 
Thank you very much to help my brother and I apologize for the delay.

**Comment by picons** [comment]
Did the first script run succesfully? 1-build-... Because if there's no servicelist file, it will not work.

If /dev/shm doesn't exist it should use /tmp instead.

**Comment by wada3n** [comment]
Yes it ran successfully and i got the servicelist_tvheadend file on my home folder.
I tried to run the file  from /tmp folder and i got the same error.
Do I have to modify the 2-build script?
Here is my servicelist file 
https://www.dropbox.com/s/3e61s7pvlrxconj/servicelist_tvheadend.tar.gz?dl=0

**Comment by picons** [comment]
Something seems to be going wrong with the first script. The servicelist_tvheadend file should look more like https://gist.github.com/picons/c301a97d070797eb64b9

Try running the second script with the following file first (https://gist.github.com/picons/c301a97d070797eb64b9) at least we'll know if that works OK.

**Comment by wada3n** [comment]
with this servicelist_enigma2 it works like a charm !, It's weird .

**Comment by picons** [comment]
Doesn't matter where it's located, you should copy it to build-input either way.
Is it a recent github build or some old version?

**Comment by wada3n** [comment]
Yes ,I did that With the latest version.

**Comment by picons** [comment]
What is your tvheadend version? If it's an older version from before the DVB-rewrite, it will not work. If it's a recent version, perhaps something changed which breaks the script.

**Comment by wada3n** [comment]
Aha ,I use the HTS Tvheadend 4.0.5 version ! the latest stable version , I think. 
Do I have to upload the tvheadend folder to see it ?

**Comment by picons** [comment]
Yes, that would help a lot.
Only the folder `tvheadend/channel/config` should be enough.

**Comment by wada3n** [comment]
Here is my Tvheadend folder (https://www.dropbox.com/s/0b7nfgrfrzybcuv/tvheadend.tar.gz?dl=0)
by the way Thank you very much for your attention.

**Comment by picons** [comment]
I know now what the problem is. You should enable picons within TvHeadend, so that TvHeadend generates the picon servicerefs image url's, as seen in this image http://i.imgur.com/wlX30Jc.png

**Comment by wada3n** [comment]
yes yes ...I don't know how to thank you enough,You saved me.
My appreciation and respect my brother.
