### ISSUE TITLE
Movistar Disney·Pixar

### ISSUE THREAD

**Issue by Jglez3** [picons/picons-source#52]
New channel on Movistar+, the best quality logo I found is this one:
http://www.movistarplus.es/recorte/m-NEO/canal/MPIXAR.png

Thanks for your work.

```
76C4_40E_1_C00000=movistardisneypixar
```
`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
@Jglez3 
Is it OK to close this issue?

**Comment by charlesduco** [comment]
Yes.

**Comment by charlesduco** [comment]
I definitely fixed this issue.
