### ISSUE TITLE
Channel logo addition request

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#53]
Can these logos be added please? I'll add the references later. Thanks in advance

[Logos_to be_added.zip](https://github.com/picons/picons-source/files/1142476/Logos_to.be_added.zip)
`donkey monkey got issued`

**Comment by charlesduco** [comment]
Some logos are already in this repository and please double-check the contributing rules before submitting.

**Comment by AbuBaniaz** [comment]
Many thanks.
I could not find the logos you said already exist. What names are they please?

I am afraid that the logo/graphics terminology goes above my head. If I knew/understood, I would have added the logos I got from the broadcasters site myself if they met the criteria.

**Comment by charlesduco** [comment]
Bad naming:
`ziggologo.default.svg` ==> utterly no reason to add "logo" to a logo name.

Already in the repository:
```
openrotterdam.default.svg
openrotterdam.light.svg
rtvdordrecht.default.svg
rtvdordrecht.light.svg
ziggo.default.svg
```
