### ISSUE TITLE
Logo request mainly French

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#56]
Another logo request when you get a moment please. Thanks in advance.

[additions.zip](https://github.com/picons/picons-source/files/1147127/additions.zip)
[replacement.zip](https://github.com/picons/picons-source/files/1147128/replacement.zip)

SNP
```
etb1=etb1
fransatinfo=fransat
fransatultrahddemo=fransatultrahd
entv=entv
programmenational=entv
265_2A94_0_DDE2B33=algerie4
4_2A94_55E_DCA0000=algerie4
tvtamazight=algerie4
264_2A94_0_DDE2B33=algerie5
5_2A94_55E_DCA0000=algerie5
tvcoran=algerie5
bfm=bfmbusinessradio
2397_44A_1_C00000=bfmbusinessradio
mfm=mfmradio
radioafrican01=african1libreville
52F_30_36_CE40000=rfm-portugal
104_66_53_CE40000=rfm-portugal
rmc=rmc
44C_2711_90_DDE0000=rtlradiofrance
23CD_44A_1_C00000=rtlradiofrance
4B0_2711_90_DDE0000=rtl2radio
23E2_44A_1_C00000=rtl2radio
virgin=virginradio
virginradio=virginradio
D02_C_1_E082E7C=virginradioromania
B8F_51A4_55F_DDE0000=franceinforadio
15E0_2711_90_DDE0000=franceinforadio
23C4_44A_1_C00000=franceinforadio
```
SRP
```
104_66_53_CE40000=rfm-portugal
15E0_2711_90_DDE0000=franceinforadio
2397_44A_1_C00000=bfmbusinessradio
23C4_44A_1_C00000=franceinforadio
23CD_44A_1_C00000=rtlradiofrance
23E2_44A_1_C00000=rtl2radio
264_2A94_0_DDE2B33=algerie5
265_2A94_0_DDE2B33=algerie4
44C_2711_90_DDE0000=rtlradiofrance
4B0_2711_90_DDE0000=rtl2radio
4_2A94_55E_DCA0000=algerie4
52F_30_36_CE40000=rfm-portugal
5_2A94_55E_DCA0000=algerie5
B8F_51A4_55F_DDE0000=franceinforadio
D02_C_1_E082E7C=virginradioromania
```

`donkey monkey got issued`

**Comment by charlesduco** [comment]
Again, you did not check the logos and naming. I had to correct a lot of mistakes:
`franceinforadio` ==> `franceinfo`
==> old logo and wrong name(`radio` is not part of the name) and the new logo is already in the repository
`rfm-portugal` ==> `rfm-dowrouusli`
==> wrong name(`portugal` is not part of the name), you should use a unique identifier if the logo name already exists as explained in the contributing rules
`bfmbusinessradio` ==> `bfmbusiness`
==> old logo and wrong name(`radio` is not part of the name)
`rtlradiofrance` ==> `rtl-frakuherow`
==> wrong name(`radio france` is not part of the name), you should use a unique identifier if the logo name already exists as explained in the contributing rules
`rtl2radio` ==> `rtl2-frakuherow`
==> wrong name(`radio` is not part of the name), you should use a unique identifier if the logo name already exists as explained in the contributing rules
`african1libreville` ==> `africanumero1`
==> wrong name(`libreville` is not part of the name and `N°1` is replaced with` numero1`)

**Comment by AbuBaniaz** [comment]
Many thanks for taking the trouble to correct the errors.

I shall pass the comments to the person who e-mailed me the request and endeavour not to make the same mistakes again.
