### ISSUE TITLE
Logo addition request, Bein sports

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#57]
Can the attached logos be added please? I'll add the references later.

I got them from the beinsports site. They don't have the reflective band in the middle that the existing png files have. Link to one file is `http://epg.beinsports.com/mena_sports/HD1.svg?2017` I couldn't download the others owing to geo-locking.

Thanks in advance

`donkey monkey got issue`

[beinsports.zip](https://github.com/picons/picons-source/files/1150397/beinsports.zip)

**Comment by AbuBaniaz** [comment]
Any verdict on these please?

**Comment by charlesduco** [comment]
The svg logos you provided don't render correct on my Linux system. (Linux Mint 18.1)
I think I have to edit the svg's in Inkscape and I have no time for this at the moment.

Feel free to create a private git branch on your Linux system and build a picons package with these logos yourself.
If you can provide me a self-built picons package and these logos seem to render totally okay, you can add these logos and I will investigate what's wrong with my Linux system. But now, I have no clue if these logos will render correct on other machines.

I also don't understand what `mena` means. Does BEIN use separate logo versions for every country?
It is always helpful to provide a little bit more information about the tv packages for which these logos are used.

**Comment by AbuBaniaz** [comment]
mena= middle east and north africa

They use slightly different logos for different countries. Taking account your previous reminder, they could be named `beinsportshd01-papriniwop.default ` I got `papriniwop` from the password generator.

The Bein svg files did not make useful picons. Jeemtv one did. I shall add it unless told otherwise.

What about the 4 png files? Are those OK?

**Comment by charlesduco** [comment]
There were no naming conflicts, so there is no need to add an identifier.

**Comment by AbuBaniaz** [comment]
Many thanks
