### ISSUE TITLE
missing icons

### ISSUE THREAD

**Issue by bastard79** [picons/picons-source#57]
hi all, thanx for your hard work, if you will have some time i give you list o missing icons from polish channels polsat & nc+

paramount channel hd
tvn fabula hd
bbc brit hd
bbc earth hd
4funTV - new logo
4fun fit and dance
4fun hits
tvn meteo activ
and maybe upcomming
polsat food hd
elevensports sd i hd

thanx

**Comment by picons** [comment]
When creating your issue, you might have missed the following link https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

![contrib](https://cloud.githubusercontent.com/assets/11367004/9037631/885d66fa-39ed-11e5-8ed7-290707b20a59.png)

If you have some time, perhaps use it to read the above mentioned link.
