### ISSUE TITLE
28.2 sky sports rename

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#58]
I got these off the sky website, sorry only png files for time being. One or two have same name as some existing svg files. However, the font they use is slightly different, so may be a good idea to replace them anyway. I have also added `craftmarket.default` and `heartsummer.default`

I'll add the references later.
[20170718.zip](https://github.com/picons/picons-source/files/1157260/20170718.zip)

Thanks in advance again.

`donkey monkey got issue`

**Comment by AbuBaniaz** [comment]
Some svg files thanks to Jasmeet
[20170718_v2.zip](https://github.com/picons/picons-source/files/1160789/20170718_v2.zip)

**Comment by AbuBaniaz** [comment]
I can add them myself once someone confirms they are OK

**Comment by charlesduco** [comment]
Logos are okay, it seems they are the original ones from http://www.skysports.com/watch

I think the unique identifier `clivebesle` is not needed anymore, there are no naming conflicts with sky sport germany or sky sport italy.

**Comment by AbuBaniaz** [comment]
Hopefully I didn't break anything. 

Not sure if you want to delete the following logos
```
skysportsboxoffice-clivebesle
skysportsboxofficehd-clivebesle
skysportsf1-clivebesle
skysportsf1hd-clivebesle
skysportsnews-clivebesle
skysportsnewshd-clivebesle
skysportsnewshq-clivebesle
skysportsnewshqhd-clivebesle
```
