### ISSUE TITLE
1-build-servicelist.sh returns wrong logo in some cases

### ISSUE THREAD

**Issue by charlesduco** [picons/picons-source#59]
When there are two service references where only the first digit is different, the script returns a wrong logo reference when using an Enigma2 channel list.

For example, the service reference for Viva Polska in the Polish Cyfrowy Polsat package gets a wrong logo reference:

wrong output in servicelist_enigma2 file:

```
1_0_1_5_3200_13E_820000_0_0_0       tv/mtvlivehd                       VIVA Polska
1_0_19_15_3200_13E_820000_0_0_0     tv/mtvlivehd                       MTV Live HD
```

correct entries in srindex file:

```
15_3200_13E_820000=tv/mtvlivehd
5_3200_13E_820000=tv/viva
```

**Comment by picons** [comment]
Good spot, will look into it.

**Comment by picons** [comment]
Should be fixed now
