### ISSUE TITLE
Logo Sources

### ISSUE THREAD

**Issue by brettser** [picons/picons-source#59]
Hi

A lot of the png's are 0 kb ?
![image](https://cloud.githubusercontent.com/assets/17860112/13791579/ba573240-eae5-11e5-9f78-70e4aaa74ace.png)

rgds
Brettser

**Comment by mocram** [comment]
Which program are you using to extract them? 7-zip has proer support to extract hardlinks inside a tar archive, your program doesn't it seems.

**Comment by brettser** [comment]
Hi
I was using 7-zip on Windows 10 PC- every file created mostly 0kb pngs. for srp only.
I have retried it in work now on another Windows 10 PC and it works fine. Strange one.
Rgds
Brettser

**Comment by mocram** [comment]
If you dowloaded a symlink version, 0kb files are outputted, need to make sure you pick hardlink from the list.
