### ISSUE TITLE
several picons missings 

### ISSUE THREAD

**Issue by leec32** [picons/picons-source#59]
hi

i have several picons missing from 
enigma2-plugin-picons-srp-full.220x132-220x132.light.on.transparent_2017-07-20--23-10-22_all

sky living
lifetime hd 
none of the new sky sports 

are these just not added yet or is it something my end ?

thanks

**Comment by charlesduco** [comment]
The service references of these channels has changed and are not updated yet. Feel free to provide the new service references.

**Comment by leec32** [comment]
1_0_19_F57_7D5_2_11A0000_0_0_0 sky sports premiere league hd 

i am not sure if this is correct, if it is the new or old ?

if correct i will send the rest

thanks

**Comment by AbuBaniaz** [comment]
I have added them.
What you have posted is not correct

Before the "=" sign, You must have the service references but trimmed down.  
Only the part `296_5_85_C00000` is used, the parts `1_0_1_` and `_0_0_0` must be removed.

After the "=" sign: You must have the logo name, without filetype or type of logo. 

More details in the contributing guide: 
https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

See here as an example:
https://github.com/picons/picons-source/blob/master/build-source/srp-index#L48

**Comment by leec32** [comment]
ah great, sorry i didn't quite understand how it worked, i am a bit of a novice haha

if i re download the new apk will they be available from there 

thanks

**Comment by AbuBaniaz** [comment]
I'll close the issue now

**Comment by charlesduco** [comment]
@leec32 The .ipk is automatically built on the server every morning. But you don't have to wait, you can always build an ipk package yourself: https://github.com/picons/picons-source#building-the-picons

**Comment by leec32** [comment]
great thank you for your help, i have the .ipk now but will know for the future
