### ISSUE TITLE
ESP Channels

### ISSUE THREAD

**Issue by franory** [picons/picons-source#6]
Good morning, 
First of all, I don´t know if this is the right place to post it (sorri if it is not).
I have missed these SNP picons which I saw on SRP picons:
Channel is 1_0_1_785F_41A_1_C00000_0_0_0 aka C+ Partidazo.
1_0_1_746A_3F0_1_C00000_0_0_0 aka Iberalia
Thanks and regards. Good job!

**Comment by mocram** [comment]
so if I convert the names to SNP, I'll get this:

```
cpluspartidazo=tv/canalpluspartidazo-esp.black.svg
iberalia=tv/iberalia.black.svg
```

Correct?

**Comment by franory** [comment]
Yes, I think that is right!

2015-12-29 19:58 GMT+01:00 mocram <notifications@github.com>:

> so if I convert the names to SNP, I'll get this:
>
> cpluspartidazo=tv/canalpluspartidazo-esp.black.svg
> iberalia=tv/iberalia.black.svg
>
> Correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/picons/picons-source/issues/6#issuecomment-167853309>.
>



-- 
Francisco de Ory
