### ISSUE TITLE
Channel Logo Requests (Ireland)

### ISSUE THREAD

**Issue by anthonykelly** [picons/picons-source#61]
First off, this is great software than thanks for creating it!

The following two channels available in Ireland are missing:
1. Saorview Information
2. Tithe an Oireachtais

I have prepared logo PNGs than can be used:
https://www.dropbox.com/s/74agollbqluof2u/saorviewinformation.default.png?dl=0
﻿https://www.dropbox.com/s/pdfdjkapraubqvg/titheanoireachtais.default.png?dl=0

I tested manually by copying these logos to the ./picons-source/build-source/logos folder and updating the following two lines to the generated servicelist-enigma2-srp file. The picons were created successfully.

1_0_16_453_3E9_2174_EEEE0000_0_0_0    |  Saorview Information        |  453_3E9_2174_EEEE0000=saorviewinformation

1_0_16_44D_3E9_2174_EEEE0000_0_0_0    |  Tithe an Oireachtais        |  44D_3E9_2174_EEEE0000=titheanoireachtais 

Let me know if there's any other information you need. 

Thanks.

**Comment by charlesduco** [comment]
Welcome, please follow the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md) when submitting an issue.

**Comment by anthonykelly** [comment]
**srp-index:**
```
453_3E9_2174_EEEE0000=saorviewinformation
44D_3E9_2174_EEEE0000=titheanoireachtais
```

**snp-index:**
```
saorviewinformation=saorviewinformation
titheanoireachtais=titheanoireachtais
```

**Logos:**
[Archive.zip](https://github.com/picons/picons-source/files/1180499/Archive.zip)

**Comment by charlesduco** [comment]
Thanks. Is `titheanoireachtais` the same as [Oireachtas TV ](http://www.oireachtas.ie/parliament/watchlisten/watchoireachtastv/#d.en.2731)? Channel 22 on Saorview?

**Comment by anthonykelly** [comment]
Yes, it's the same channel. It's called Tithe an Oireachtais (Houses of Parliament) on the Saorview EPG.

**Comment by AbuBaniaz** [comment]
What is wrong with the existing logos `oireachtastv` in the repository?

**Comment by charlesduco** [comment]
Okay, I added the following to comply with the naming rules:
**srp-index:**
```
453_3E9_2174_EEEE0000=saorview
44D_3E9_2174_EEEE0000=oireachtastv
```
**snp-index:**
```
saorviewinformation=saorview
titheanoireachtais=oireachtastv
```

**Comment by anthonykelly** [comment]
Thanks, those picons are generating now. But it seems the RTE News Now picon is now missing. The SRP seems to have changed. Can you update the srp-index as follows.

**srp-index:**
```
451_3E9_2174_EEEE0000=rtenewsnow
```

**Comment by anthonykelly** [comment]
Perfect! Closing issue.
