### ISSUE TITLE
skyatlantichd-.......... needs a cleanup, duplicate logos found

### ISSUE THREAD

**Issue by mocram** [picons/picons-source#62]
We messed up. [sad smiley face]

**Comment by AbuBaniaz** [comment]
Can we make a `skyatlanticplus1` svg file from `skyatlanticplus1hd` instead of using the png file?

**Comment by AbuBaniaz** [comment]
Thanks @charlesduco 

Ok to close @mocram ?

**Comment by mocram** [comment]
Shouldn't this logo be grouped togheter with other sky channels? You removed all unique identifiers....

**Comment by AbuBaniaz** [comment]
We only use the unique identifiers when there are duplicates.

**Comment by charlesduco** [comment]
In this case, I think grouping together logos complicates things. Sky Atlantic is available in the UK, Ireland, Germany, Austria and Italy on many different satellite and cable networks.
