### ISSUE TITLE
logo request for belgian cable

### ISSUE THREAD

**Issue by leper-messiah** [picons/picons-source#63]
hello 
i would like to ask if its possible to add those channel:
be1
voo sport world 1
voo sport world 2
voo sport world 3
telemaroc
i dont have reference because they are on cable i have a zip with logo
thank in advance
[http://www39.zippyshare.com/v/kYfmMGvY/file.html](url)

**Comment by AbuBaniaz** [comment]
Cable services also have service references. We can't add them to the SRP index unless you provide them.  In the attached example/picture, we would use `259_6_F020_FFFF0000`

![cable service webif](https://user-images.githubusercontent.com/6644489/29050731-c606c9c0-7bd5-11e7-96c6-1abd053c0904.png)

Please attach the zip file to the comment, the link you provided does not work.

**Comment by leper-messiah** [comment]
hello thank for reply
the probleme is that channel are from cable but i m using iptv box so i would be thankful if you can add them to snp index
[logorequest.zip](https://github.com/picons/picons-source/files/1208249/logorequest.zip)

**Comment by AbuBaniaz** [comment]
Those logos are not of a good quality.

**Comment by AbuBaniaz** [comment]
Maybe this website has better logos. You will need to adapt default selection to include all channels. I can only find .gif files. 

`http://www.betv.be/fr/programme-tv/`

**Comment by leper-messiah** [comment]
hello sorry  i have found new ones hope they are good
snp index
betv=betv
telemaroc=telemaroc
voosport=voosport
[logo.zip](https://github.com/picons/picons-source/files/1208717/logo.zip)

**Comment by mocram** [comment]
https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

**Comment by leper-messiah** [comment]
Sorry but i dont understand where is the probleme and why clossing i didnt understand the rules

**Comment by mocram** [comment]
This is a small part from the above mentioned page concerning the guidelines to which the logos should adhere.

```
The resolution doesn't matter for svg, for png try to get it > 800px.
Quality should be as high as possible with transparancy.
```

Please read the following articles, perhaps you'll understand then what the lingo means.
https://en.wikipedia.org/wiki/Image_resolution
https://en.wikipedia.org/wiki/Transparency_(graphic)

Not understanding the rules, does not mean you are exempt from them. In that case you should educate yourself until you do understand them. But don't worry, they are simple, it basically al comes down to:

`Don't give us shitty images`
