### ISSUE TITLE
1-build-servicelist.sh outputs empty servicelist-enigma2-srp file

### ISSUE THREAD

**Issue by charlesduco** [picons/picons-source#66]
I get an empty servicelist-enigma2-srp file when I execute the 1-build-servicelist.sh script on my Linux Mint 17 system.
I investigated the script and it seems the column -o option (output-separator) is not suppported in Debian Linux.
When I manually execute "column -o" I get the following output:
```
column: invalid option -- 'o'
usage: column [-tx] [-c columns] [-s sep] [file ...]
```
So for the moment, I cannot build the picons. Any idea how to solve this?

**Comment by picons** [comment]
I'll investigate, I have been testing on cygwin....my ubuntu also doesn't seem to support it.

**Comment by picons** [comment]
Fix is on it's way, just doing a final test to make sure it's the same output.

**Comment by picons** [comment]
Can you confirm it fixes the issue on your system?

**Comment by charlesduco** [comment]
Yes, it fixes this issue. But there's apparently another issue with the 2-build-picons script. 
I think the selection of the build style has a bug.

**Comment by picons** [comment]
what does it do?

**Comment by picons** [comment]
I'm not able to detect anything strange on Cygwin or Ubuntu.

**Comment by picons** [comment]
Should be good now, atleast on my setup I'm able to build succefull, don't forget to recreate servicelist.

**Comment by charlesduco** [comment]
Build is successful now. Thanks for solving this.
