### ISSUE TITLE
Changes in SNP Index

### ISSUE THREAD

**Issue by Silverscape** [picons/picons-source#66]
To change in SNP Index:
skyatlanticplus1hd=skyatlanticplus1hd-phibruspel
eurosporthd=eurosport1hd

To remove in SNP Index:
eurosportdanmarkhd=eurosport1 (Double entry in snp-index. The next line is the correct one)
eurosportdanmarkhd=eurosport1hd
eurosporthddut=eurosport1 (Double entry in snp-index. The next line is the correct one)
eurosporthddut=eurosport1hd
eurosporthdpl=eurosport1 (Double entry in snp-index. The next line is the correct one)
eurosporthdpl=eurosport1hd

To add in SNP Index:
idxtra=idxtra (New Logo: http://www.lyngsat-logo.com/tvchannel/bg/Investigation-Discovery-Xtra.html)
zutv=zutv (New Logo: http://www.lyngsat-logo.com/tvchannel/ro/ZU-TV.html)

**Comment by mocram** [comment]
snp-index and srp-index may contain double entries, only the first one found (the one that's the most at the top of the document) is used, so it's only necessary to list the ones that should be added to the top.

So in your case it should be something like:

Add to snp-index
```
skyatlanticplus1hd=skyatlanticplus1hd-phibruspel
eurosporthd=eurosport1hd
eurosportdanmarkhd=eurosport1hd
eurosporthddut=eurosport1hd
eurosporthdpl=eurosport1hd
```

**Comment by Silverscape** [comment]
Thanks mocram for the clarification and thanks charlesduco for the very fast implementation of the changes and new logos! :-)
