### ISSUE TITLE
Movistar James Bond

### ISSUE THREAD

**Issue by Jglez3** [picons/picons-source#67]
New channel on Movistar+ from 25th August to 10th September, the best quality logo I found is this one:
http://www.movistarplus.es/recorte/m-NEO/canal/MBOND.png

Thanks for your work.

```
76C4_40E_1_C00000=movistarjamesbond
```
`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
That logo's size is 270x66 and looks very poor. Maybe we can manipulate `movistardcine.default.svg` & `movistardcine.light.svg`?

**Comment by AbuBaniaz** [comment]
@jglez3, please close this issue. Logo has been added by Charlesduco.
