### ISSUE TITLE
Radio SRP picons not working

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#70]
It seems we have a problem with radio picons. They are not showing.

As an example, for absolute radio on 28.2, we have this ` CB40_839_2_11A0000=absoluteradio` in the index file.
The link that is created is `1_0_1_CB40_839_2_11A0000_0_0_0.png`
The actual reference is `1_0_2_CB40_839_2_11A0000_0_0_0.png`

The difference is the service type.  There are no links beginning with `1_0_2`

`Donkey monkey got issue`

**Comment by mocram** [comment]
That is a kown problem, which I even mentioned months ago. When building against a channel list the correct 102 prefix for radio will be used. When building them all without a channellist, there is no way to know if it's a radio channel.

**Comment by AbuBaniaz** [comment]
Worked around it with this
https://github.com/OpenViX/enigma2/commit/1a2185e2392893f78e6449819622b5dc596363b9

Lets see if other images accept it too.
