### ISSUE TITLE
New (svg) logos

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#71]
I found these logos, they already exist but these are svg images and/or are the current logos used by the television stations.
But I'm not good in editing svg-files, so I hope they are okay?
[logos_to_replace.zip](https://github.com/picons/picons-source/files/1246880/logos_to_replace.zip)

`Donkey monkey got issue`

**Comment by AbuBaniaz** [comment]
![1plus1](https://user-images.githubusercontent.com/6644489/29642354-391bd0e0-8860-11e7-88f5-82f92a925415.jpg)

1+1 is still using the current logo

**Comment by Lexzie** [comment]
First of all, this is a screenshot of 1+1 which is using the logo of 1+1 international (wrong link in snp-index).
I am going to issue missing logos (like 1+1) and additions to snp-index later when I completed my search for all Ukrainian channels.

This issue is about replacing png for svg and replacing the 2+2 and Tet logo without the current ones.

**Comment by Lexzie** [comment]
I meant 'with the current ones'.

**Comment by AbuBaniaz** [comment]
I can't clear the other one, so can't check.

**Comment by AbuBaniaz** [comment]
Best to add to both SNP-index and SRP-index if you can please.

**Comment by dalmore72** [comment]
Here you can find the correct logo 1 + 1 international + some more all svg files                                              https://media.1plus1.ua/en/media/channels

**Comment by Lexzie** [comment]
Found that site too, but the logos there are inversed. Found the right svg-logos on other sites of this media-group.

**Comment by Lexzie** [comment]
Thanks for adding the logos!
