### ISSUE TITLE
Movistar+ (19.2) new channels Picons

### ISSUE THREAD

**Issue by gnze796** [picons/picons-source#75]
Add the following to srp-index

```
757C_412_1_C00000=tv/canal+liga2-eso
757D_412_1_C00000=tv/canal+liga2-esp
769D_41E_1_C00000=tv/canal+liga2-esp
769E_41E_1_C00000=tv/canal+liga2-esp
```

**Comment by gnze796** [comment]
Mostly are the new football channels

C+Partidazo
C+Liga Multi
C+Liga 2 abcd

Also some multideporte channels use the wrong picon even if Multideporte picons exist. I'll get the ref numbers of the wrong or missing picons that I see and try to update it here.

**Comment by gnze796** [comment]
C+Partidazo Picon is wrong Sref: 1_0_19_785F_41A_1_C00000_0_0_0	 	 
C+Liga Multi Picon is wrong Sref: 1_0_19_7853_41A_1_C00000_0_0_0	 	 
C+Liga 2 HD picon doesnt exist, but there is a C+Liga 2 HD picon in the pack Sref: 1_0_19_750F_420_1_C00000_0_0_0	 	 
Multideporte 4 and 5 picons are wrong, the rest of them are OK
Sref: 1_0_1_7575_412_1_C00000_0_0_0	 	 
Sref: 1_0_1_757A_412_1_C00000_0_0_0	 	 
All Multifutbol picons are missing or wrong, guess their picons are still not created.
Multifut 1 HD: Sref: 1_0_19_7864_41A_1_C00000_0_0_0	 	 
Multifut 2 HD: Sref: 1_0_19_7861_41A_1_C00000_0_0_0	 	 
Multifut 3 HD: Sref: 1_0_19_750E_420_1_C00000_0_0_0	 	 
Multifut 4: Sref: 1_0_1_7579_412_1_C00000_0_0_0	 	 
Multifut 5: Sref: 1_0_1_757E_412_1_C00000_0_0_0	 	 
Multifut 6: Sref: 1_0_1_757F_412_1_C00000_0_0_0	 	 
Multifut 7: Sref: 1_0_1_769B_41E_1_C00000_0_0_0

**Comment by picons** [comment]
https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

**Comment by picons** [comment]
Don't take this the wrong way, but if you wanna help, read the link above and give us something like

```
785F_41A_1_C00000=tv/canal+corectlogo-esp
```

If the logos are missing, find the logo, correctly name the logo and put them in a zip file.

You can watch the channel and knows how it looks, me/we have to first figure out what multifut is, search the history of the channel, to try and guess what the correct logo is.

We also don't need an entire story about what is wrong, what is correct, just facts, to the point, this is how it should be.

Now you are wasting all this time, typing pointless info, capital letters for your channels, spaces, etc...which looks good if it was a story book. And I will have to retype everything again, because I can't do a simple copy/paste.

So if you read the link above and did all that, it would have been fixed a couple of minutes ago, now it might take weeks...

FYI, just some positive critique.

**Comment by gnze796** [comment]
I'm sorry, I didnt know how to help, now after reading I understand that and I also saw which logos are missing. I'll try to get the missing icons soon or build them. Right now I can start saying the channels that actually have a picon but they're not linked or they are wrong.

750F_420_1_C00000=tv/canal+liga2hd-esp
7575_412_1_C00000=tv/canal+multideporte-esp.png
757A_412_1_C00000=tv/canal+multideporte-esp.png

**Comment by picons** [comment]
No need for the extension.

**Comment by gnze796** [comment]
Okay. I created the C+Partidazo HD picon as I see it on TV.
![canal partidazohd-esp](https://cloud.githubusercontent.com/assets/559639/9451177/5a71541a-4aad-11e5-84ce-7776fc404039.png)

```
785F_41A_1_C00000=tv/canal+partidazohd-esp
```

Still I need to check how other channels looks and draw them

**Comment by charlesduco** [comment]
I updated the sport channel logos for movistar+ in the last commit. The green tint in the currently used logos is slightly different, I think. So I adjusted that for all logos.

I didn't find good quality logos for the other new channels and I didn't look up the new service references.
So there's some work left for you. It would be great if you can give an overview of all changed service references in the correct format in the next message.

**Comment by picons** [comment]
I've got to ask, all those svg's, are you finding those? Or creating them from scratch/tracing over from png?

Great work either way.

**Comment by gnze796** [comment]
great work charles.
I updated the first post adding the picon for C+Partidazo(& HD) with their refs. I don't know if you will do or the remaining channels or you know how they look. The icons that are left to create are:

* C+Liga Multi (&HD)
* C+Liga 2 A/B/C/D
* Multifutbol

Let's see what can we get done this weekend

**Comment by charlesduco** [comment]
All logos I add are found on the internet. I search very thoroughly for vectorial logos with all kinds of search terms and operators. Most of the time I limit the results with `filetype:pdf` or `filetype:svg`
In general there are three kinds of sources:
- brochures, magazines and folders from tv providers, broadcasters, logo design studios and such in pdf format. 
- websites that use SVG images online, for example http://www.skysports.com/watch and http://www.mtv.co.uk/mtv
- websites that collect svg files like https://en.wikipedia.org or http://logos.wikia.com/

With the vector graphics software "Inkscape" I convert every vectorial logo I've found to a clean svg-file with the "optimized svg" export option.

@gnze796 If you can find the missing icons, please add them in this issue. I don't know what they look like. Maybe later I can find vectorial versions of the logos, but I haven't found anything yet.

**Comment by picons** [comment]
I see you guys are both on top of this, feel free to close the issue as soon it's resolved to your liking....

**Comment by gnze796** [comment]
@charlesduco I found C+Liga Multi (SD version) on Wikipedia

![c _liga_multi-2](https://cloud.githubusercontent.com/assets/559639/9490823/e5c3d608-4bea-11e5-9c98-b95738dff308.png)

**Comment by charlesduco** [comment]
Ok, I managed to compose vector logos for C+Liga Multi SD&HD from some other logo elements.

**Comment by gnze796** [comment]
@charlesduco awesome, I updated the first post with their refs so you can add them. And here is how Multifutbol looks like, it's the pretty much the same as multideporte.

![canal multifutbol-esp](https://cloud.githubusercontent.com/assets/559639/9518460/250d3e7c-4cb7-11e5-8aba-abf59f0a1366.png)

But we need also a white version of it.

**Comment by charlesduco** [comment]
Ok, I added the service references and I composed black and white vector logos for the following channels:
```
canal+multideporte-esp
canal+multifotbal-esp
canal+taquilla-esp
```
I found a channel listing at http://plus.es/dial/ but it seems the new channels are not listed.

**Comment by gnze796** [comment]
@charlesduco updated first post with srefs.

**Comment by picons** [comment]
Just because you guys are so active...

I'm gonna tell the two of you a secret: https://picons.xyz/downloads/

**Comment by charlesduco** [comment]
@picons Nice job and a great domain name!

**Comment by gnze796** [comment]
Great! I tested the icons and I found 1 sref I missed for Multifutbol 5. 1st post updated.

**Comment by vpont** [comment]
Great work with these, guys.
Props.

**Comment by gnze796** [comment]
OK. So right now the A B C D channels are on emission and they look like this.
![1_0_1_757c_412_1_c00000_0_0_0](https://cloud.githubusercontent.com/assets/559639/9568389/3f200cfc-4f48-11e5-9663-e11831942f67.jpg)

As you can see there is no official icon and while they are on HT break they only show the C+Liga icon with music. So I think that the most correct option is to use the C+Liga 2 picon (SD  version, not HD). So I updated the first post with the srefs for those 4 channels. In the next days I'll use a different satellite list so I can see both SD&HD picons are right for Movistar+, and then we can close this issue.

**Comment by gnze796** [comment]
Everything OK. Closed
