### ISSUE TITLE
Rendering of german tv / radio stations not really well - cuts on right and bottom

### ISSUE THREAD

**Issue by connaisseur** [picons/picons-source#76]
noticed that zooming / rendering of german TV / radio stations is not really well. There were cuts on right and bottom. It affects

3sathd
ntvhd
deutschlandfunk
orfsportplus
orf3
orf3hd
atvhd
atv2
zdfkultur
superrtlhd

Used dark.on.blue in different resolutions; with same results.

**Comment by mocram** [comment]
Did you download these, or did you build them yourself?

If you build them yourself, please see https://github.com/picons/picons-source/issues/1
You can also use Inkscape instead of rsvg, slower, but less problems.

**Comment by connaisseur** [comment]
I pulled all from github repository. No own logos in use.

Any special version of toolchain for rendering required? Used Arch Linux for building w/ latest software pulled from their repositories.

**Comment by mocram** [comment]
So you did not download the picons from https://picons.xyz/downloads/, but build them yourself...

See https://bugzilla.gnome.org/show_bug.cgi?id=756340

So either use a different version of rsvg (without the bug) or use inkscape (see https://github.com/picons/picons-source/blob/master/build-source/config/svgconverter.conf)

**Comment by connaisseur** [comment]
No, I did not download anything from [https://picons.xyz/downloads/](https://picons.xyz/downloads/), All pulled and build by myself.

Checked your link on GNOME bugzilla. In there's said, that librsvg version 2.40.11 has a bug. I have librsvg 2.40.15 installed. Is this still affected?

**Comment by charlesduco** [comment]
The bug is fixed last month: https://bugzilla.gnome.org/show_bug.cgi?id=760262
But librsvg 2.40.15 was released before this fix and so is still affected. Next release 2.40.16 should include this fix.

**Comment by mocram** [comment]
@connaisseur 
If it looks like a duck, swims like a duck, and quacks like a duck, then it probably is a duck.

Do you think it's still affected?

**Comment by connaisseur** [comment]
It was affected. Applied the referenced fix / recompiled library and the rsvg-convert.

Rebuild my set of picons. Et volià! The mentioned error/flaw is gone!

Thanks for pointing this out!
