### ISSUE TITLE
Canvas (HD) new logo, een (HD) in few days

### ISSUE THREAD

**Issue by Clemens12345** [picons/picons-source#76]
Here links to lyngsat logo, svg pictures are not available yet (but they are high res pngs) and don't know if there will be some in short.

een
http://www.lyngsat-logo.com/tvchannel/be/Een.html
Canvas
http://www.lyngsat-logo.com/tvchannel/be/Canvas.html

The SD/HD version have the same logo now (before there was an HD and non HD logo), because I guess 99% of Flanders use them in HD.
The één logo is not in use yet, but it will be in few days.
The Canvas Logo is in use from today on.

No problems if this issue stays opened until svg sources are available in the www, I will keep my eyes opened.

Kind regards and my compliments for this great great picon pack,
Clemens12345

**Comment by charlesduco** [comment]
An SVG version of the new Canvas logo is already in the repository since last Sunday: https://github.com/picons/picons-source/blob/6753abf83b1204ef9ef8a8e6dc125f36034b48d1/build-source/tv/canvas.svg

I have an SVG version of the new Eén logo already on my hard disk and I will add this later this week.

**Comment by Clemens12345** [comment]
Great. May I ask where you find those?

**Comment by charlesduco** [comment]
Yes, I've found an svg version of the new Eén logo on the website http://najaar2015.een.be
And the new canvas logo on http://www.canvasvernieuwt.be
You'll find the svg file in the html source.

But there is also an easier way to get the logos: http://pers.vrt.be

**Comment by Clemens12345** [comment]
Thanks a lot.
Will close the issue :)
