### ISSUE TITLE
Please add "Family TV" channel to inventory

### ISSUE THREAD

**Issue by connaisseur** [picons/picons-source#77]
A non-svg logo could be found on [https://de.wikipedia.org/wiki/Family_TV](url)

**Comment by mocram** [comment]
![familytv](https://cloud.githubusercontent.com/assets/16463960/15426446/0a7d9c64-1e8f-11e6-8604-d7546ef24726.png)

This is a high res version, if I had the needed info, it could have been added.

**Comment by charlesduco** [comment]
This channel is already in the repository, but the service reference wasn't up to date.
