### ISSUE TITLE
New TV Station at Astra 19.2°C: RTLplus

### ISSUE THREAD

**Issue by connaisseur** [picons/picons-source#78]
No real issue - more a notification - a new TV station on the Astra satellite system is to go live: RTLplus. Logo already on wikipedia avalable: [https://de.wikipedia.org/wiki/RTLplus#/media/File:RTLplus_Logo_2016.png](url)

**Comment by charlesduco** [comment]
Please check the repository first. RTLplus was already added last week. Only open issues when you've checked the last version and you've found a missing channel or other problem.
