### ISSUE TITLE
New logo Nitro (former RTL Nitro)

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#79]
RTL Nitro is renamed to Nitro and changed logo.
The logo nitro.default.svg/nitro.light.svg is not used in both snp-index and srp-index, so this logo can be replaced?
nitro.light.svg, rtlnitro.default.svg, rtlnitro.white.svg and rtlnitrohd.default.svg can be deleted.

![nitro default](https://user-images.githubusercontent.com/14023349/29719762-c1959b7e-89b7-11e7-9891-9f30197a7c75.png)
![nitrohd default](https://user-images.githubusercontent.com/14023349/29720811-5d26533c-89bb-11e7-85d2-fc97c63c5a9a.png)

After this logo is added I will add the changes to snp-index and srp-index.

**Comment by AbuBaniaz** [comment]
What are the index additions? Whoever commits this can add in one go.

**Comment by Lexzie** [comment]
I'm sorry, I thought first the logo must exist in picons-source/build-source/logos/ before a change to snp-index and srp-index is allowed.
(Because you may not link to a logo that does not exist).

Besides that I don't know how, I go to picons-source/build-source/, edit the snp-index and srp-index files and after that as far as I can see I can only make a pull-request of each file separately.
Please explain to me how it's is wanted and how I must do that (privat of course, you have my e-mail address).
For now I've already changed the snp-index (commit 6c937fc97140eaeded3f02a23cd5ae77dc913f1c ?)
But I'm stuck there, don't know how to add that here.

**Comment by AbuBaniaz** [comment]
Swapped the logo
https://github.com/picons/picons-source/commit/c7b4aa4740c227dde814b42f0593a28c58fd2816

**Comment by Lexzie** [comment]
Thanks for swapping the logo.

Please add to snp-index:
```
nitro=nitro
nitrohd=nitrohd
```

srp-index is fine.

**Comment by AbuBaniaz** [comment]
What you are asking is impossible. There is no logo called `nitro` or `nitrohd`.  You cannot link to what does not exist.

I shall create links to the logos that exist instead.

**Comment by Lexzie** [comment]
Sorry, copy-paste error...
Off course it should be
nitro=rtlnitro
nitrohd=rtlnitrohd

**Comment by dalmore72** [comment]
nitro hd looks home made.

svg file here.

https://de.wikipedia.org/wiki/Datei:Nitro_Logo-HD.svg
