### ISSUE TITLE
Iberalia TV

### ISSUE THREAD

**Issue by Jglez3** [picons/picons-source#80]
To add on srp-index
````
7A46_410_1_C00000=tv/iberalia
````

Logo's here: http://37.187.192.85/~gonzalez/picon/iberalia.png

**Comment by picons** [comment]
logo isn't transparent

**Comment by Jglez3** [comment]
My bad!

It's transparent now, same link.

**Comment by picons** [comment]
Try watching that again on a black background...

**Comment by Jglez3** [comment]
Ok, what about now?
It's smaller than the other one but it's 100% transparent. I think it can work until we found a big one.

**Comment by picons** [comment]
done
