### ISSUE TITLE
add Eurosport 2 HD Xtra (german)

### ISSUE THREAD

**Issue by CWempe** [picons/picons-source#81]
There is a new channel that exclusively broadcasts some Bundesliga-Games.

https://de.wikipedia.org/wiki/Eurosport#Eurosport_2_HD_Xtra

I cannot find the new logo anywhere, yet.
There is a spanish version which misses the "HD" part.
https://en.wikipedia.org/wiki/File:Eurosport_2_xtra_logo.png

**Comment by CWempe** [comment]
Thanks for adding the logos.

I guess you need this next to make it work. :)

![image](https://user-images.githubusercontent.com/1270359/29754901-2fc70686-8b8f-11e7-956e-20c51811d7c3.png)

```
Eurosport 2 HD Xtra
picon://1_0_19_30D7_413_1_C00000_0_0_0.png
```

**Comment by AbuBaniaz** [comment]
Added
`30D7_413_1_C00000=eurosport2hdxtra`

**Comment by CWempe** [comment]
It works.
Thank. 👍
