### ISSUE TITLE
AXN and AXN White new logos

### ISSUE THREAD

**Issue by Jglez3** [picons/picons-source#84]
Hi, AXN and AXN white changed logos few days ago (on Movistar+ Spain, I don't know if also changed logos on other platforms, I guess yes). There are new ones.

http://37.187.192.85/~gonzalez/picon/axn.png
http://37.187.192.85/~gonzalez/picon/axnwhite.png

I know they're small size but I can't find bigger logos, same case for HD channels (can't find logos).

Thanks!

**Comment by Jglez3** [comment]
I found AXN HD new logo.
http://37.187.192.85/~gonzalez/picon/axnhd.png

**Comment by charlesduco** [comment]
So for now, I have updated the following logos already in black and white versions:
```
axn
axnhd
axnwhite
axnwhitehd
axnblack
axnblackhd
```
I renamed the old logos to `axn-old`, etc. for compatibility with platforms that still uses the old logos. In that case, the service references should also be updated, but that is a task for people who are watching axn channels on these platforms.
