### ISSUE TITLE
Question about new Sky Cinema logos

### ISSUE THREAD

**Issue by secuflag** [picons/picons-source#84]
Sky Cinema (Italy) has updates all _Cinema_ logos once again, see here: http://guidatv.sky.it/guidatv/grid.html?category=cinema&day=0
but I can't find the new logos in svg nor in png bigger than this: http://guidatv.sky.it/app/guidatv/images/epgimages/channels/home/101_home.png

Maybe someone have other sources where to search?

Thanks.

**Comment by dalmore72** [comment]
Maybe this helps :)
[SKY.pdf](https://github.com/picons/picons-source/files/1260361/SKY.pdf)

**Comment by secuflag** [comment]
That pdf seems to be outdated, one channel is missing (Sky Cinema Max Collection HD) and others are slightly different.
Logos on the Sky website are the most updated.

**Comment by dalmore72** [comment]
The Sky Cinema logos come in 3 different variants

Transparent - 3D and those in the PDF file

So the pdf file is not outdated just not updated

**Comment by charlesduco** [comment]
Managed to create all the logos from the pdf.
More sources at: https://www.google.com/search?q="ogni+giorno"+filetype:pdf+site:sky.it

**Comment by secuflag** [comment]
Awesome, thanks @charlesduco for your work!
