### ISSUE TITLE
built picon filenames prefixes are fixed prepended with "1_0_1_"

### ISSUE THREAD

**Issue by bpgregson** [picons/picons-source#87]
SRP icons were built using picons-source tools on Ubuntu 14.04, for use in tvheadend v4.0.9.  README.md was followed.  After building servicelist by running 1-build-servicelist.sh using the tvheadend server method, service reference (full) icons were built using 2-build-icons.sh. Icon package archives were generated, as expected.  When the packages were unzipped, all picon files within were prepended with "1_0_1_".  
Example: 1_0_1_5226_812_2_11A0000_0_0_0.png

For my tvheadend instance, the assigned picon filenames are prepended with "1_0_0_".  See the attached screenshot of my tvheadend channel listing, with filenames visible.
![image](https://cloud.githubusercontent.com/assets/17072941/16431632/6fa8f9e2-3d4f-11e6-985e-4cfb01758a2d.png)

I noticed in create-symlinks.sh that srp files are named according to the following:
` echo "ln -s -f logos/$logo_srp.png $temp/package/picon/1_0_1_"$unique_id"_0_0_0.png" >> $temp/create-symlinks.sh
`
with the first 3 and last 3 digits static.

Can you address making the pre and post digits dynamic?

Thank you,
Brian

**Comment by mocram** [comment]
What's the output of 1-build-servicelist.sh? Did you correctly build against the servicelist or did you just use "srp-full"?

It should already do what you are asking for...

**Comment by bpgregson** [comment]
Thanks for your reply.

The attached was generated by 1-build-servicelist.sh.

When running 2-build-picons.sh I selected option 2, Service Reference
(Full).  I was unclear as to the correct usage.  Is there documentation
that clarifies the usage of the different options?

Thank you.

Brian

**Comment by mocram** [comment]
just use service reference without "full"

**Comment by bpgregson** [comment]
Thanks. That did work when I re-ran without "full." Icons were not
generated for the ATSC terrestrial stations.

Brian

**Comment by mocram** [comment]
Because they are not added/included in this project at the moment (look at: srp-index), most probably.

**Comment by bpgregson** [comment]
yes, I realized that after browsing through the repo.  I may contribute
some of the icons specific to my region.
Thanks

Brian
