### ISSUE TITLE
name similarities

### ISSUE THREAD

**Issue by sunder67** [picons/picons-source#87]
Some channels with a similar name
for example:
http://www.lyngsat-logo.com/tvchannel/at/ATV-HD.html
http://www.lyngsat-logo.com/tv/a_36.html

42.0e-atv.png (http://en.wikipedia.org/wiki/ATV_%28Turkey%29)
38.0e-atv.png (http://en.wikipedia.org/wiki/ATV_%28Pakistan%29)
19.2e-atv.png (http://en.wikipedia.org/wiki/ATV_%28Austria%29)

1-build-servicelist.sh output for Turksat-42E
1_0_1_3908_A21D_42E_1A40000_0_0_0     |  POWER TV                     |  3908_A21D_42E_1A40000=--------    |  powertv=tv/powertv-pol  

powertv-pol  (Poland is not channel )  http://www.lyngsat.com/tvchannels/tr/Power-TV.html

**Comment by picons** [comment]
It's correctly naming according to the SNP rules(snp-index) your channel to tv/powertv-pol.
For this particular problem you are experiencing, you can overrule the snp lookup by adding the correct link based on serviceref.
This is one of the limitations of SNP.

PS: Try to ask an actual question next time you create an issue.
