### ISSUE TITLE
New logos

### ISSUE THREAD

**Issue by secuflag** [picons/picons-source#89]
Rename in snp-index: ```milanchannel=milanchannel``` to ```milantv=milantv```

Add to snp-index:
```
redbulltv=redbulltv
topcalcio24=topcalcio24
wwenetwork=wwenetwork
```
[logos.tar.gz](https://github.com/picons/picons-source/files/1272124/logos.tar.gz)
(Please check all the images as I'm not good at all with graphics)

`donkey monkey got issued`

**Comment by mocram** [comment]
only redbulltv is ok

**Comment by secuflag** [comment]
Someone can kindly edit the images please?

**Comment by AbuBaniaz** [comment]
Is this OK?

`
https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/Future/Red%20Bull%20TV.svg
`

**Comment by mocram** [comment]
@AbuBaniaz yes nothing wrong with that svg as far I can see

**Comment by Stevie-v** [comment]
![img_0291](https://user-images.githubusercontent.com/25457350/30079247-dc1b0404-927f-11e7-8447-244b8a6ef430.PNG)
![img_0290](https://user-images.githubusercontent.com/25457350/30079246-dc0df11a-927f-11e7-9d96-17520af4269c.PNG)
![img_0293](https://user-images.githubusercontent.com/25457350/30079248-dc210c64-927f-11e7-94a6-9eacc2a43d74.PNG)

New logos for rtl5 and rtl7 and rtl8

**Comment by AbuBaniaz** [comment]
I added the redbulltv logo here
https://github.com/picons/picons-source/commit/5985cbf9550a7a910ba9e53308c5f9848498adaf

**Comment by AbuBaniaz** [comment]
@Stevie-v
Do you have light editions of those rtl logos

**Comment by Stevie-v** [comment]
![rtl7](https://user-images.githubusercontent.com/25457350/30130574-eb57b5c8-9349-11e7-8b1b-d7e7b4a2a810.png)
light RTL7

**Comment by secuflag** [comment]
Thanks @charlesduco
