### ISSUE TITLE
ESP multifutbol & multideporte

### ISSUE THREAD

**Issue by franory** [picons/picons-source#9]
Good afternoon
I think several multifutbol ad multideporte channels picons for spanish platform are wrong.
C+ liga de camponeones channels don't exist anymore.
I have found these picons which should work.
I hope it helps.

![multifutbol3hd_220x132](https://cloud.githubusercontent.com/assets/11354517/12071925/74887a5c-b0c6-11e5-9cab-c31109138f47.png)
![f1_220x132](https://cloud.githubusercontent.com/assets/11354517/12071926/749e8324-b0c6-11e5-9449-1d0ff485200d.png)
![f2_220x132](https://cloud.githubusercontent.com/assets/11354517/12071928/74be814c-b0c6-11e5-804b-cf38f61e6490.png)
![f3_220x132](https://cloud.githubusercontent.com/assets/11354517/12071927/74b5a626-b0c6-11e5-8b52-002d937f399e.png)
![f4_220x132](https://cloud.githubusercontent.com/assets/11354517/12071934/74d825e8-b0c6-11e5-9b17-d0873217e3eb.png)
![f5_220x132](https://cloud.githubusercontent.com/assets/11354517/12071932/74d7a898-b0c6-11e5-9f5c-398355a3285b.png)
![f6_220x132](https://cloud.githubusercontent.com/assets/11354517/12071930/74d47dda-b0c6-11e5-9608-681b4ac32fe2.png)
![f7_220x132](https://cloud.githubusercontent.com/assets/11354517/12071933/74d8301a-b0c6-11e5-8431-44860c9ebbf3.png)
![multifutbol1hd_220x132](https://cloud.githubusercontent.com/assets/11354517/12071929/74ca3258-b0c6-11e5-9fd8-03af241814de.png)
![multifutbol2hd_220x132](https://cloud.githubusercontent.com/assets/11354517/12071931/74d63bfc-b0c6-11e5-88f9-e3a99181fcce.png)

**Comment by charlesduco** [comment]
I have no access to Spanish Movistar+ package. So please provide some more information about these "wrong" channels:
```
-service references of the channels
-service names of the channels
-the source of the logos or some visual confirmation like a screenshot
```

And please follow the rules when submitting an issue: https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

**Comment by franory** [comment]
This is the info I have:
Channel SR SN multifutbol1 HD 7864_41A_1_C00000 MULTIFUT. 1 HD multifutbol2
HD 7861_41A_1_C00000 MULTIFUT. 2 HD multifutbol3 HD 750E_420_1_C00000
MULTIFUT. 3 HD multifutbol1  756E_412_1_C00000 MULTIFUT. 1 multifutbol2
7577_412_1_C00000 MULTIFUT. 2 multifutbol3 7578_412_1_C00000 MULTIFUT. 3
multifutbol4 7579_412_1_C00000 MULTIFUT. 4 multifutbol5 757E_412_1_C00000
MULTIFUT. 5 multifutbol6 757F_412_1_C00000 MULTIFUT. 6 multifutbol7
769B_41E_1_C00000 MULTIFUT. 7 multifutbol8 7690_41E_1_C00000 MULTIFUT. 8
multifutbol9 76A6_41E_1_C00000 MULTIFUT. 9 Multideporte1 756C_412_1_C00000
MULTIDEP. 1 Multideporte2 756D_412_1_C00000 MULTIDEP. 2 Multideporte3
7573_412_1_C00000 MULTIDEP. 3 Multideporte4 7575_412_1_C00000 MULTIDEP. 4
Multideporte5 757A_412_1_C00000 MULTIDEP. 5 Multideporte6 7574_412_1_C00000
MULTIDEP. 6 Multideporte7 7576_412_1_C00000 MULTIDEP. 7 Multideporte8
7693_41E_1_C00000 MULTIDEP. 8 Multideporte9 76A7_41E_1_C00000 MULTIDEP. 9

2016-01-03 8:43 GMT+01:00 charlesduco <notifications@github.com>:

> I have no access to Spanish Movistar+ package. So please provide some more
> information about these "wrong" channels:
>
> -service references of the channels
> -service names of the channels
> -the source of the logos or some visual confirmation like a screenshot
>
> And please follow the rules when submitting an issue:
> https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/picons/picons-source/issues/9#issuecomment-168474866>.
>



-- 
Francisco de Ory

**Comment by Jglez3** [comment]
All multideporte and multifutbol channels have their correct picon.

Maybe you see the same ref on more than one line, but the script only takes the first it found.

Take this example (all refs on srp-index):
Line 461: 756E_412_1_C00000=canalplusmultifutbol-phochasluu
Line 5848: 756E_412_1_C00000=canalplusligadecampeones-phochasluu

The script only takes line 461 and you get multifutbol picon.

**Comment by franory** [comment]
What I mean is that multifutbol channels dont have correct picon. They have
canalplusligadecampones and that channel does not exist anymore.

Thanks and regards.

2016-01-04 13:26 GMT+01:00 Jglez3 <notifications@github.com>:

> All multideporte and multifutbol channels have their correct picon.
>
> Maybe you see the same ref on more than one line, but the script only
> takes the first it found.
>
> Take this example (all refs on srp-index):
> Line 461: 756E_412_1_C00000=canalplusmultifutbol-phochasluu
> Line 5848: 756E_412_1_C00000=canalplusligadecampeones-phochasluu
>
> The script only takes line 461 and you get multifutbol picon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/picons/picons-source/issues/9#issuecomment-168665957>.
>



-- 
Francisco de Ory

**Comment by mocram** [comment]
Please let us know which version you are using... I presume you have installed version 2016-01-03--14-20-05 when making those claims?

**Comment by charlesduco** [comment]
@franory Please let me know if my commit solves this issue.
If not, please provide some more information and don't forget to follow the contributing rules.

**Comment by franory** [comment]
I have seen changes you have made. I suppose it should solve it. I will
wait until picons are rebuilt and reload them and confirm.

Thanks and regards.


2016-01-04 18:08 GMT+01:00 charlesduco <notifications@github.com>:

> @franory <https://github.com/franory> Please let me know if my commit
> solves this issue.
> If not, please provide some more information and don't forget to follow
> the contributing rules.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/picons/picons-source/issues/9#issuecomment-168737817>.
>



-- 
Francisco de Ory

**Comment by franory** [comment]
They seem OK. I think it can be closed.
Thanks!
