### ISSUE TITLE
Sky Cinema UK

### ISSUE THREAD

**Issue by DaMacFunkin** [picons/picons-source#90]
Hello, your latest don't seem to have Sky Hits HD, Sky Greats HD or Sky Select HD for the new Sky Cinema rebrand in the UK in either snp or srp, you have the SD variants of Hits and Select.
![skyselect](https://cloud.githubusercontent.com/assets/19837162/17269552/4bdb7c12-5643-11e6-9f01-aae69cd214b4.png)

**Comment by charlesduco** [comment]
Please read https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md and provide the necessary service references or service names.

Meanwhile I updated some channels, so you should build the picons again to see what is exactly missing.

**Comment by mocram** [comment]
Doesn't seem to be very important to the OP...
