### ISSUE TITLE
New logo - Discovery science in .svg

### ISSUE THREAD

**Issue by MarhyCZ** [picons/picons-source#91]
Hi,
I've found logo of Discovery science in EPS format!! (from Discovery logo manual).
I have converted it into .svg and submitting it in archive below. I hope the .zip is ok.
[discoveryscience.zip](https://github.com/picons/picons-source/files/1273173/discoveryscience.zip)

**Comment by mocram** [comment]
Please read the rules next time!

```
It's not allowed for svg files to contain base64 encoded images.
```

Also we prefer not to have all that macos junk in the zip files, only the required files is enough.

But, thanks anyway for your effort.

**Comment by MarhyCZ** [comment]
I've read the rules. Illustrator probably exported thumbnail view or something with that. Well I manually packaged it into tar without that junk, but .tar is apparently not allowed here. And I don't think that the .DS_Store is a huge problem.

At least, here is the link for the .eps if you want https://press.discovery.com/emea/sci/info/

**Comment by mocram** [comment]
The zip contents is just a small annoyance....but not the real issue
