### ISSUE TITLE
New Icon Style Movistar Spain

### ISSUE THREAD

**Issue by TSCNEO** [picons/picons-source#92]
Movistar Spain has changed the style. ¿Is possible make the new one? I have it in PNG, dont know how to make SVG.

![estrenos](https://cloud.githubusercontent.com/assets/452066/17512244/27c9fc72-5e27-11e6-9b22-589beb81c95e.png)
![formula1](https://cloud.githubusercontent.com/assets/452066/17512245/27ed59ec-5e27-11e6-9002-05c6e954f911.png)
![futbol](https://cloud.githubusercontent.com/assets/452066/17512246/27f82fde-5e27-11e6-8ad4-d9a975953344.png)
![golf](https://cloud.githubusercontent.com/assets/452066/17512247/27fa3e64-5e27-11e6-8502-1e5632a8d31b.png)
![motogp](https://cloud.githubusercontent.com/assets/452066/17512248/27fe2aec-5e27-11e6-9933-4ba25a987ebe.png)
![partidazo](https://cloud.githubusercontent.com/assets/452066/17512249/2804feb2-5e27-11e6-8c12-ef4dd7d3b31d.png)
![series](https://cloud.githubusercontent.com/assets/452066/17512250/2810eaec-5e27-11e6-9905-9a9f5e2c89d1.png)
![seriesxtra](https://cloud.githubusercontent.com/assets/452066/17512251/2812a832-5e27-11e6-938a-428ba5967254.png)
![xtra](https://cloud.githubusercontent.com/assets/452066/17512255/28320fa6-5e27-11e6-9266-edcf38977934.png)
![accion](https://cloud.githubusercontent.com/assets/452066/17512252/28202912-5e27-11e6-8a33-03831f4367f9.png)
![cine espanol](https://cloud.githubusercontent.com/assets/452066/17512253/2822915c-5e27-11e6-92b2-5f59a4c62892.png)
![comedia](https://cloud.githubusercontent.com/assets/452066/17512254/282b52ec-5e27-11e6-90dd-45d14d1c5a89.png)
![dcine](https://cloud.githubusercontent.com/assets/452066/17512256/28351c5a-5e27-11e6-8f5f-95b7f97c003f.png)
![deportes1](https://cloud.githubusercontent.com/assets/452066/17512257/2839b6de-5e27-11e6-8369-d959f1d001f0.png)
![1_0_19_750f_420_1_c00000_0_0_0](https://cloud.githubusercontent.com/assets/452066/17512275/3756f2c6-5e27-11e6-909a-63e68f3a7fc5.png)

Picon Credit to LUCIFERspa (https://github.com/LUCIFERspa/Picon_Movistar)

**Comment by manuelin94** [comment]
Yes, Movistar has changed all logos of this platform.
Here you can find the logos with better quality: http://logos.wikia.com/wiki/Movistar%2B

For example, Canal+ Estrenos (now it called: Movistar Estrenos): http://logos.wikia.com/wiki/Movistar_Estrenos

http://vignette4.wikia.nocookie.net/logopedia/images/6/61/MEstrenos.png/revision/latest?cb=20160707185129
![GitHub Logo](http://vignette4.wikia.nocookie.net/logopedia/images/6/61/MEstrenos.png/revision/latest?cb=20160707185129)

Thank you very much!
Regards ;)

**Comment by TSCNEO** [comment]
Thanks for your answer. I was wondering, if is possible to upload in SVG in the repository, and build it in all sizes and types.

thanks again ;)

**Comment by charlesduco** [comment]
Please read https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md to know how to provide images.
I'll add a commit with the new logos. Please check if everything is updated correctly because I have no access to the movistar+ package myself.

**Comment by manuelin94** [comment]
Thank you very much charlesduco!
Everything is perfect, but missing some of the new logos.
Here are all the logos have changed: http://www.movistarplus.es/nuevaimagen

Then, missing logos from that list:
- Canal+ Partidazo (now it called: Movistar Partidazo)
- Canal+ Toros (now it called: Toros TV)
- Caza y Pesca (It appears not to have changed, so this logo is already correct)
- #0 (It appears not to have changed, so this logo is already correct. But in the repository the [cero.light.svg](https://github.com/picons/picons-source/blob/master/build-source/logos/cero.light.svg) logo is yellow and white, but [on TV they are using full white logo] (https://i.imgur.com/2k0A2DU.jpg) (without yellow), so the opposite of this: http://vignette2.wikia.nocookie.net/logopedia/images/d/d9/Cero3.png/revision/latest?cb=20160313142148)
- Canal+ Yomvi now it called Yomvi (without "Canal+"), so [canalplusyomvi.default.svg](https://github.com/picons/picons-source/blob/master/build-source/logos/canalplusyomvi.default.svg) should be replaced by yomvi.default.svg, and in the logo image eliminate part of "Canal+" and leave only the part of "Yomvi".
- Now Canal+ is Movistar+, so all Canal+ logos should be replaced by Movistar+ logos: [canalplus.default.svg] (https://github.com/picons/picons-source/blob/master/build-source/logos/canalplus.default.svg) > movistarplus.default.svg
Movistar+ logo can get here (removing the blue background and letting it transparent): https://scontent.fmad3-1.fna.fbcdn.net/v/t1.0-9/13901601_10153803898701149_2061592568321422184_n.png?oh=699cba272e1e410ab867743446198ee2&oe=5855A767

And for this last, if I'm not mistaken, should be eliminated:
`75A9_422_1_C00000=canalplus`
And add:
```
75A9_422_1_C00000=canalplus
75C6_422_1_C00000=canalplus
```

Thank you very much again and sorry for my bad English!
Regards ;)

**Comment by TSCNEO** [comment]
Thanks for your commit charlesdusco!
I have to add those changes too:

- 750F_420_1_C00000=BeinLaLiga HD ![1_0_1_7692_41e_1_c00000_0_0_0](https://cloud.githubusercontent.com/assets/452066/17581357/9547a266-5fa5-11e6-9f00-182bc2c8285d.png)
- 7797_424_1_C00000=BeinLaLiga SD (same logo)
- Old Canal+ Multicine and Canal+ Multideporte, now are Movistar+ Multicine and Movistar+ Multideporte, with same style (attached PNG Logo)
![1_0_1_7694_41e_1_c00000_0_0_0](https://cloud.githubusercontent.com/assets/452066/17581358/954e8fea-5fa5-11e6-8415-bad65189e15f.png)
![1_0_1_7797_424_1_c00000_0_0_0](https://cloud.githubusercontent.com/assets/452066/17581359/9553d004-5fa5-11e6-8309-c20ce650d191.png)

- #0 default its blue, but correct its all black, like Manuelin94 show before (http://vignette2.wikia.nocookie.net/logopedia/images/d/d9/Cero3.png/revision/latest?cb=20160313142148)

Thanks in advance for your hard work... and sorry if i have a bad english...

**Comment by TSCNEO** [comment]
Thanks! Now are perfect

**Comment by manuelin94** [comment]
Yes, now are perfect, thanks again charlesduco!
As much, the only thing missing would change the color of channel #0 as we mentioned above.
[cero.light.svg] (https://github.com/picons/picons-source/blob/master/build-source/logos/cero.light.svg) -> Really is all white, not yellow and white.
[cero.default.svg] (https://github.com/picons/picons-source/blob/master/build-source/logos/cero.default.svg) -> Really is all black, not blue and black.

Thanks again for everything charlesduco!
Regards ;)

**Comment by manuelin94** [comment]
Perfect! Thank you very much charlesduco!
Regards and thanks again ;)
