### ISSUE TITLE
Discovery science in .svg

### ISSUE THREAD

**Issue by MarhyCZ** [picons/picons-source#92]
I've read the rules before my first try of posting something here and I am sorry, Illustrator just probably exported thumbnail view or something with that when I tried last time

At least, I can give you a link to Discovery science logo in .eps format, so someone can convert it to .svg. Because when I tried to remove the my so called Illustrator junk, I actually removed the black "liquid" in that logo. So probably mask cannot be exported in something else than base64?

https://cf.press.discovery.com/ugc/logos/2012/05/30/Discovery-science.eps

**Comment by charlesduco** [comment]
The logo contains a gradient mesh and this is only fully supported in the SVG 2.0 standard which is still being developed.
For now, we can only support SVG 1.1, so if a vector logo has a gradient mesh, you should export the image as a > 800px png image.
