### ISSUE TITLE
Update M+ SRP - Bein LaLiga 1-6 Logos - LaLiga TV

### ISSUE THREAD

**Issue by TSCNEO** [picons/picons-source#93]
Hello,
I made a new srp-index with all M+ channels updated, and made new SVG Logo por BeinLaliga 1-6
LaLiga TV only made in PNG.

¿How can i upload it? I made my own fork with some changes, maybe can help: https://github.com/TSCNEO/picons-source/tree/master/build-source

Thanks in advance

**Comment by charlesduco** [comment]
You can open a pull request and I''ll look if your changes comply with [our contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md).
But first you should make sure your fork is synced with the latest version of the original repository.

Please take some time to learn how git works:
https://help.github.com/categories/bootcamp/
https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/using-pull-requests/

If you don't have time to learn git, you can always upload an archive with the new logos to a cloud service and share the link here as explained in the contributing rules: https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

**Comment by TSCNEO** [comment]
Thanks for your comment.
I tried to make a  good fork and sync it, but have some problems. I will read more and learn. 
Meantime, i already iploaded the new logos.
https://mega.nz/#!N40XxTzI!Yfzk1OvDhXBwPnO3YxR9WLxE6kc3JDw_URntlNPRRn0

And in srp-index, have to change:
`756E_412_1_C00000=beinsportslaliga7
7579_412_1_C00000=beinsportslaliga5
757E_412_1_C00000=beinsportslaliga6
769B_41E_1_C00000=beinsportslaliga4
7690_41E_1_C00000=beinsportslaliga3
750F_420_1_C00000=beinsportslaliga
7797_424_1_C00000=beinsportslaliga
7853_41A_1_C00000=beinsportslaliga1
756B_412_1_C00000=beinsportslaliga1
7580_412_1_C00000=beinsportslaliga2
756B_412_1_C00000=beinsportslaliga1
756E_412_1_C00000=beinsportslaliga7
7579_412_1_C00000=beinsportslaliga5
757E_412_1_C00000=beinsportslaliga6
7690_41E_1_C00000=beinsportslaliga3
7797_424_1_C00000=beinsportslaliga
7853_41A_1_C00000=beinsportslaliga1
7855_41A_1_C00000=beinsportslaliga2
Line 6654: 74A3_41C_1_C00000=gol
7793_424_1_C00000=laligatv
769A_41E_1_C00000=laligatv
`
With this changes, now the picons are 100% OK like M+.

Thanks again, and sorry for my bad english,

**Comment by charlesduco** [comment]
I merged your pull request with some small changes. (wrong transparancy on bein sports laliga logos).
Please close this issue if everything is okay. Otherwise, let me know what is wrong or make the changes yourself and open a new pull request.

**Comment by TSCNEO** [comment]
Thanks, its OK now.
I will close this issue.
