### ISSUE TITLE
SYFY rebranding

### ISSUE THREAD

**Issue by Jglez3** [picons/picons-source#93]
SYFY, to commemorate its 25th birthday, has a new logo.

SVG: https://vignette.wikia.nocookie.net/logopedia/images/2/2d/Syfy_2017_horizontal.svg/revision/latest?cb=20170806160731

In the spanish channels I can see this image (different than the svg): http://www.movistarplus.es/recorte/m-NEO/canal/SCI-FI.png

SVG: https://vignette.wikia.nocookie.net/logopedia/images/0/09/Syfy_2017_vertical.svg/revision/latest?cb=20170801161816

Light versions: https://vignette.wikia.nocookie.net/logopedia/images/c/c2/Syfy_2017_horizontal_logo_2.svg/revision/latest?cb=20170619120021
https://vignette.wikia.nocookie.net/logopedia/images/4/47/Syfy_2017_vertical_logo_2.svg/revision/latest?cb=20170619120040

Same for SD and HD channels. So, we could change every single 'syfyhd' reference to the 'syfy' one.

Thanks for all!

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
The UK ones are still using the existing one.

**Comment by Jglez3** [comment]
That's probably because the change is going to take full effect on the 1st of October.
I don't know why some providers changed the logos on September.

**Comment by charlesduco** [comment]
I added these new variants while retaining the uk versions:
**Horizontal variant:**
```
syfy-stiswekuch
```
**Vertical variant:**
```
syfy-spatupriho
```
Please provide the necessary entries for snp- or srp-index.

**Comment by Jglez3** [comment]
Thank you @charlesduco.

These are the entries for the srp-index.

```
74CD_3F8_1_C00000=syfy-spatupriho
7796_424_1_C00000=syfy-spatupriho
```

**Comment by AbuBaniaz** [comment]
I have added to SNP index too. Looks like there is a another logo with "HD" text.

![1_0_19_7e_c_85_c00000_0_0_0](https://user-images.githubusercontent.com/6644489/30140962-1578ee3c-9370-11e7-9a34-9d19c7cfc237.jpg)

**Comment by AbuBaniaz** [comment]
I am closing this issue as the logos and references have been added. Would be a good idea for reporters/requesters to do this themselves.
