### ISSUE TITLE
Updated RAI logos

### ISSUE THREAD

**Issue by secuflag** [picons/picons-source#94]
RAI updated some logos, attached the svg files.
Please someone could make the HD version of _raistoria_ and the standard version of _raigulp_.

[RAI_logos.tar.gz](https://github.com/picons/picons-source/files/1284693/RAI_logos.tar.gz)

Thanks!

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
I'll close the issue as the logos have been added.

**Comment by secuflag** [comment]
Thanks!
