### ISSUE TITLE
Movistar+ Star Wars

### ISSUE THREAD

**Issue by Jglez3** [picons/picons-source#94]
Hello! 

Movistar+ release a new channel to promote Star Wars saga from 1st to 15th of December and there's the picon (same on both SD and HD channels) and references.

```
78B4_3EC_1_C00000=tv/movistarstarwars
757B_412_1_C00000=tv/movistarstarwars
```

http://37.187.192.85/~gonzalez/picon/white/movistarstarwars.png
http://37.187.192.85/~gonzalez/picon/black/movistarstarwars.png

**Comment by charlesduco** [comment]
If everything is oké, you can close this issue.

**Comment by Jglez3** [comment]
Everything is okay, thanks for all.
